Repository akeneo/pim-community-dev, pull requests merged in 2018-12, with the labels that each got.

#9217 Update jQuery event object typehinting
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
Labels: to review

#9220 PIM-7908: fix variant family creation if an attribute doesn't have a translation for the current locale
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-fields-container.js
Labels: to review

#9202 PIM-7720: add variant axis basics
  src/Akeneo/Pim/Enrichment/Bundle/Resources/public/js/product/field/reference-multi-select-field.js
  src/Akeneo/Pim/Enrichment/Bundle/Resources/public/js/product/field/reference-simple-select-field.js
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/add_child.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/values/reference-entity.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/creation/variant.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#9228 Merge 1.7 into 2.0
  CHANGELOG-1.7.md
  src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php
Labels: to review

#9223 Add `yarn.lock` to VCS
  .gitignore
  yarn.lock
Labels: tech-improvement

#9185 PIM-7866: do not show delete icon on import/export profile
  CHANGELOG-2.3.md
  src/Pim/Bundle/ImportExportBundle/Resources/config/datagrid/job_profile.yml
Labels: bug

#9205 PIM-7892: allow to filter on active catalog locale when adding an attribute to the product export filters
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
Labels: to review

#9257 PIM-7930: use remover to delete user group
  src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/removers.yml
Labels: tech-improvement

#9167 PIM-7660: get images of product models in the datagrid
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
Labels: to review

#9181 PIM-7660: apply permissions on the product datagrid
  src/Oro/Bundle/PimDataGridBundle/Datasource/ProductAndProductModelDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/ProductAndProductModelDatasourceSpec.php
Labels: to review

#9242 PIM-7920: Remove options values label from versioning
  CHANGELOG-2.0.md
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/AttributeNormalizer.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php
Labels: to review

#9218 APAI-448: Style fixes
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
Labels: to review

#9254 PIM-7910: parent filter is now case insensitive
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/ParentFilterIntegration.php
Labels: to review

#9278 APAI-383: Implement InMemoryLocaleRepository "getActivatedLocales"
  tests/back/Acceptance/Locale/InMemoryLocaleRepository.php
Labels: to review

#9224 PIM-7899: Norm RGPD - Hide the field "Date of Birth"
  CHANGELOG-2.3.md
  src/Pim/Bundle/UserBundle/Entity/UserInterface.php
  src/Pim/Bundle/UserBundle/Form/Type/UserType.php
  src/Pim/Bundle/UserBundle/Resources/views/User/Tab/general.html.twig
  src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
Labels: to review

#9299 CircleCI - Run static front tests
  .circleci/config.yml
Labels: to review

#9301 CircleCI - Run acceptance back tests
  .circleci/config.yml
Labels: to review
