Repository akeneo/pim-community-dev, pull requests merged in 2018-07, with the labels that each got.

#8427 Merge 20 into 22
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js
  src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php
  src/Pim/Component/Catalog/spec/Job/ComputeProductModelsDescendantsTaskletSpec.php
Labels: to review

#8430 PIM-7373 Fixes versioning guesser when deleting family
  src/Pim/Bundle/VersioningBundle/UpdateGuesser/FamilyAttributeRequirementUpdateGuesser.php
  src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/FamilyAttributeRequirementUpdateGuesserSpec.php
Labels: to review

#8431 Merge 22 into 23
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.2.md
  src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
  src/Akeneo/Component/Localization/Localizer/NumberLocalizer.php
  src/Akeneo/Component/Localization/spec/Localizer/NumberLocalizerSpec.php
  src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
  src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongValuesOnVariantProductCleaner.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsBatchCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsCommand.php
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FindAttributesForFamily.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/CatalogBundle/spec/Command/Cleaner/WrongValuesOnVariantProductCleanerSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
  src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductModelReader.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductReader.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/GroupController.php
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/CountImpactedProducts.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductModelReaderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductReaderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Query/CountImpactedProductsSpec.php
  src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/ORM/Query/CountImpactedProductsIntegration.php
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv
  src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml
  src/Pim/Bundle/UserBundle/Resources/views/layout.html.twig
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
  src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php
  src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/Normalizer/Standard/Product/MetricNormalizer.php
  src/Pim/Component/Catalog/spec/Job/ComputeProductModelsDescendantsTaskletSpec.php
  src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/MetricNormalizerSpec.php
  tests/legacy/features/attribute-group/create_attribute_group.feature
  tests/legacy/features/export/convert_metric_values_during_product_export.feature
  tests/legacy/features/product/create_product_and_save_added_attributes.feature
  tests/legacy/features/update/set_metric.feature
Labels: to review

#8410 PIM-7462: Fix step execution read count
  CHANGELOG-2.0.md
  features/export/export_products.feature
  features/export/xlsx/export_products.feature
  src/Pim/Component/Connector/Reader/Database/ProductReader.php
Labels: to merge

#8437 PIM-7478: Fix memory leak on quick export
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductModelReader.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductReader.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductModelReaderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductReaderSpec.php
Labels: to review

#8436 TIP-842: Move group type classes to Structure
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/GroupTypeController.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/GroupTypeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/array_converters.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Repository/GroupTypeRepositorySpec.php
  src/Akeneo/Pim/Structure/Component/ArrayConverter/FlatToStandard/GroupType.php
  src/Akeneo/Pim/Structure/Component/ArrayConverter/StandardToFlat/GroupType.php
  src/Akeneo/Pim/Structure/Component/Repository/GroupTypeRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/spec/ArrayConverter/FlatToStandard/GroupTypeSpec.php
  src/Akeneo/Pim/Structure/Component/spec/ArrayConverter/StandardToFlat/GroupTypeSpec.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
  src/Pim/Bundle/EnrichBundle/Controller/GroupController.php
  src/Pim/Bundle/EnrichBundle/Controller/GroupTypeController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Component/Catalog/Factory/GroupFactory.php
  src/Pim/Component/Catalog/Updater/GroupUpdater.php
  src/Pim/Component/Catalog/spec/Factory/GroupFactorySpec.php
  src/Pim/Component/Catalog/spec/Updater/GroupUpdaterSpec.php
  src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/FieldConverter.php
  src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/FieldConverterSpec.php
  tests/back/Acceptance/Catalog/InMemoryGroupTypeRepository.php
  tests/back/Acceptance/spec/Catalog/InMemoryGroupTypeRepositorySpec.php
Labels: to review

#8440 PIM-7455: Fix indexation issue after a product model import
  tests/Integration/catalog/technical/jobs.yml
Labels: to review

#8433 PIM-7464: Add CacheClearer to clear UOW and cached repo
  src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Clearer/CacheClearer.php
  src/Akeneo/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
  src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Clearer/CacheClearerSpec.php
Labels: to review

#8445 PIM-7466: do not escape quotes for translation
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/views/AttributeGroup/_js-handler.html.twig
Labels: bug, to review

#8449 PIM-7381 : Add the flash message container for the acceptance test
  tests/front/common/templates/index.html
Labels: to review

#8441 TIP-842: Move attritbute option classes to Structure
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Pim/Structure/Bundle/EventListener/AttributeOptionRemovalSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionCreateType.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionValueType.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/FamilyType.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Structure/Bundle/spec/EventListener/AttributeOptionRemovalSubscriberSpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionCreateTypeSpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionTypeSpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionValueTypeSpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/FamilyTypeSpec.php
  src/Akeneo/Pim/Structure/Component/tests/Integration/ExternalApi/AttributeOptionIntegration.php
  src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/AttributeOptionIntegration.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml
Labels: to review

#8446 Bounded context definitions
  ARCHITECTURE.md
Labels: to review

#8452 PIM-7488: use catalog locale for attributes list in attribute groups
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Normalizer/LocaleNormalizer.php
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-group/tab/attribute.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attribute-list.html
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/LocaleNormalizerSpec.php
Labels: bug, to review

#8461 Update eslint to fix step-definition files
  .eslintrc
Labels: to review

#8466 PIM7466: fix attribute group translation again
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/views/AttributeGroup/_js-handler.html.twig
Labels: to review

#8454 Reference documentation
  internal_doc/ARCHITECTURE.md
  internal_doc/STANDARD_FORMAT.md
Labels: to review

#8480 PIM-7482: fix sequential edit with sort
  src/Pim/Bundle/EnrichBundle/Controller/Rest/SequentialEditController.php
  tests/legacy/features/mass-action/edit_common_attributes_scopable_localizable.feature
Labels: to review

#8420 PIM-7475: Add family to Families edit history
  .ci/Jenkinsfile
  CHANGELOG-1.7.md
  features/navigation/navigation_title.feature
  src/Oro/Bundle/NavigationBundle/Entity/Builder/AbstractBuilder.php
  src/Oro/Bundle/NavigationBundle/Entity/Builder/HistoryItemBuilder.php
  src/Oro/Bundle/NavigationBundle/Entity/NavigationHistoryItem.php
  src/Oro/Bundle/NavigationBundle/Event/ResponseHistoryListener.php
  src/Oro/Bundle/NavigationBundle/Provider/TitleService.php
  src/Oro/Bundle/NavigationBundle/Resources/config/services.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.ca.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.da.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.es.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fi.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.hr.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.it.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.ja.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.nl.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pl.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pt.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pt_BR.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pt_PT.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.ru.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.sv.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.zh.yml
  src/Pim/Bundle/EnrichBundle/Resources/views/Family/edit.html.twig
Labels: to review

#8478 PIM-7429: fix category tab in product edit form
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
Labels: to review

#8479 PIM-7512: add migration scripts for the category tree in the product grid
  upgrades/2.2-2.3/Version_2_3_20180418094859_add_job_instances.php
  upgrades/2.2-2.3/Version_2_3_20180423092444_add_table_aggregated_volume.php
  upgrades/2.2-2.3/Version_2_3_20180522151757_batch_jobs_migration.php
  upgrades/2.2-2.3/Version_2_3_20180620102817_add_table_product_model_associations.php
  upgrades/2.2-2.3/Version_2_3_20180620134351_add_table_structure_version_last_update.php
  upgrades/2.2-2.3/Version_2_3_20180621121925_index_products_and_product_models.php
  upgrades/schema/Version_3_0_20180716083150_add_index_category.php
Labels: to review

#8486 PIM-7517: fix the product models export filter on identifier
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  tests/legacy/features/export/product_model/csv/export_product_models.feature
  upgrades/schema/Version_2_3_20180716135306_update_job_instances.php
Labels: to review

#8490 Update requirement for Mysql 5.7.22
  app/PimRequirements.php
Labels: to review

#8488 PIM-7452: Fix memory leak when reinitializing family completeness
  CHANGELOG-2.0.md
  features/locale/detach_locale_from_channel.feature
  src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Component/Catalog/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  src/Pim/Component/Catalog/spec/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
Labels: to review

#8402 PIM-7456: Security vulnerabilities in dependencies
  .ci/Jenkinsfile
  CHANGELOG-1.7.md
  app/AppKernel.php
  app/config/config.yml
  app/config/routing.yml
  composer.json
  features/Pim/Behat/Context/NavigationContext.php
  src/Pim/Bundle/EnrichBundle/Controller/AttributeController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/bundles/apy_js_form_validation.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
  src/Pim/Bundle/EnrichBundle/Resources/views/AssociationType/create.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/form_options.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/AttributeGroup/form.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/Family/create.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/Group/create.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/GroupType/create.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/GroupType/edit.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure.html.twig
  src/Pim/Bundle/EnrichBundle/Resources/views/VariantGroup/create.html.twig
  src/Pim/Bundle/JsFormValidationBundle/DependencyInjection/PimJsFormValidationExtension.php
  src/Pim/Bundle/JsFormValidationBundle/Generator/FormValidationScriptGenerator.php
  src/Pim/Bundle/JsFormValidationBundle/PimJsFormValidationBundle.php
  src/Pim/Bundle/JsFormValidationBundle/Resources/config/jsfv.yml
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/DateValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/EmailValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/NotBlankPropertiesValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/RangeValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/TypeValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/UniqueValueValidator.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Resources/views/JsFormValidation.js.twig
  src/Pim/Bundle/JsFormValidationBundle/Twig/Extension/JsFormValidationTwigExtension.php
  src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig
  src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
Labels: tech-improvement, to review

#8498 PIM-7443: Fix behat, since PIM-7518 the completeness is compute againafter locales of a channel are deleted
  tests/legacy/features/product/completeness/remove_completeness.feature
Labels: to review

#8497 PIM-7476: fix family select2 to have the right limit
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/metric.html
  tests/legacy/features/product/create_product_and_save_added_attributes.feature
Labels: to review

#8411 PIM-7473 - Enable cache for validation mapping
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
Labels: to review

#8503 Add AppKernel to the composer autoload (non dev)
  composer.json
Labels: to review

#8502 PIM-7528: Do not use User timezone for product/product model versionning normalization
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Controller/Rest/VersioningController.php
  tests/legacy/features/product/date.feature
Labels: to review

#8500 Fix the CI "java.io.IOException"
  .ci/Dockerfile
  .ci/Jenkinsfile
Labels: to review

#8495 PIM-7525: add loading mask on upload clic
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/launch.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/upload-launch.js
Labels: to review

#8521 iterate on reference data configuration only if iterable
  src/Pim/Bundle/ReferenceDataBundle/DependencyInjection/Compiler/RegisterConfigurationsPass.php
Labels: to review

#8523 PIM-7519 : Fix Infinite scroll on the reference-data-simple-select
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/simple-select-async.js
Labels: to review

#8531 PIM-7540: Fix translations of boolean attributes
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html
Labels: to review

#8533 PIM-7529: Fix method with missing parameter when a tree is removed
  .ci/Jenkinsfile
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Controller/CategoryTreeController.php
  src/Pim/Bundle/UserBundle/EventSubscriber/UserPreferencesSubscriber.php
  src/Pim/Bundle/UserBundle/spec/EventSubscriber/UserPreferencesSubscriberSpec.php
Labels: to review

#8541 Merge 2 2 into 2 3
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php
  src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/simple-select-async.js
  tests/legacy/features/Pim/Behat/Context/NavigationContext.php
Labels: to review

#8519 PIM-7532: improve the standard format for products associated to avoid performance impact
  CHANGELOG-1.7.md
  features/update/add_association.feature
  src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Query/GetAssociatedProductCodesByProductFromDB.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/GetAssociatedProductCodesByProductFromDB.php
  src/Pim/Bundle/CatalogBundle/Resources/config/serializers_standard.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/GetAssociatedProductCodesByProductIntegration.php
  src/Pim/Component/Catalog/Normalizer/Standard/Product/AssociationsNormalizer.php
  src/Pim/Component/Catalog/Query/AssociatedProduct/GetAssociatedProductCodesByProduct.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/AssociationsNormalizerSpec.php
Labels: to review

#8518 APAI-2 identifiers mapping front
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/field.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/field.html
  src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#8555 PIM-7546: fix the batch size of the cursor for the datagrid
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
Labels: to review

#8560 Add documentation about how to run the tests
  README.md
  composer.lock
  internal_doc/RUNNING_THE_TESTS.md
Labels: to review

#8557 PIM-7536: Fix tool-tip error
  CHANGELOG-2.3.md
  src/Pim/Bundle/UserBundle/Resources/views/layout.html.twig
Labels: to review

#8574 Fix front unit tests
  composer.lock
  tests/front/common/base.jest.json
Labels: to review

#8563 PIM-7453: forbid to remove a role if user won't have role after deletion
  CHANGELOG-1.7.md
  src/Oro/Bundle/UserBundle/Controller/RoleController.php
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Pim/Bundle/UserBundle/DependencyInjection/PimUserExtension.php
  src/Pim/Bundle/UserBundle/Doctrine/ORM/Query/IsThereUserWithoutRole.php
  src/Pim/Bundle/UserBundle/EventSubscriber/RemoveRoleSubscriber.php
  src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/UserBundle/Resources/config/queries.yml
  src/Pim/Bundle/UserBundle/Resources/config/removers.yml
  src/Pim/Bundle/UserBundle/tests/integration/RemoveRoleIntegration.php
  src/Pim/Component/User/Exception/ForbiddenToRemoveRoleException.php
Labels: to review

#8554 GH-8550: Exclude more folders to improve build time
  CHANGELOG-2.3.md
  tsconfig.json
Labels: to merge

#8556 TIP-872: Move the last classes fron API bundle/component to the right BC
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Channel/Bundle/Controller/ExternalApi/CurrencyController.php
  src/Akeneo/Channel/Bundle/Resources/config/controllers.yml
  src/Akeneo/Channel/Bundle/Resources/config/routing.yml
  src/Akeneo/Channel/Bundle/Resources/config/routing/external_api/currency.yml
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CategoryController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/ProductRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/category.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product_model.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
  src/Akeneo/Pim/Enrichment/Component/Category/Normalizer/ExternalApi/CategoryNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ProductNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ExternalApi/ProductRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ExternalApi/ProductModelUpdater.php
  src/Akeneo/Pim/Enrichment/Component/spec/Category/Normalizer/ExternalApi/CategoryNormalizerSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/ExternalApi/ProductNormalizerSpec.php
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/controllers.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/normalizers.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/repositories.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/routing.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/updaters.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Media/CreateProductMediaFileIntegration.php
Labels: to review

#8576 [SLA] PIM-7538: Reset datagrid state correctly
  CHANGELOG-1.7.md
  features/product/filtering/filter_products.feature
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/reset-collection-action.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js
Labels: to review

#8552 APAI-117: Merge "suggest_data" into "master"
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/field.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save-form.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/router.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/field.html
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en_US.yml
  src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#8561 Handle todo after merge 2.3 -> master
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Bundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Component/Catalog/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php
  src/Pim/Component/Catalog/spec/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
  src/Pim/Component/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Pim/Component/Connector/Job/ComputeDataRelatedToFamilyVariantsTasklet.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyVariantsTaskletSpec.php
Labels: to merge

#8584 GITHUB-8578 - Fixed wrong labels displayed in the 'active/inactive' filters in user grid
  CHANGELOG-2.3.md
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/user.yml
Labels: contribution, to merge

#8575 [SLA] PIM-7531: improve indexation time for "compute product models descendants" step
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
Labels: to review

#8582 Adds InMemoryProductRepository features
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
Labels: to review

#8586 Backport of PIM-7531
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
Labels: to review
