Repository akeneo/pim-community-dev, pull requests merged in 2018-06, with the labels that each got.

#8224 Fix integration tests that were not executed
  .ci/Jenkinsfile
  Dockerfile
  app/config/config_test.yml
Labels: to review

#8222 PIM-7391: Fix offset pagination when listing product models with the API
  CHANGELOG-2.0.md
  src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
  src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml
  src/Pim/Component/Api/Normalizer/ProductModelNormalizer.php
  src/Pim/Component/Api/spec/Normalizer/ProductModelNormalizerSpec.php
Labels: to review

#8204 TIP-861: Remove ImageExtension
  CHANGELOG-3.0.md
  src/Pim/Bundle/PdfGeneratorBundle/DependencyInjection/PimPdfGeneratorExtension.php
  src/Pim/Bundle/PdfGeneratorBundle/Resources/config/twig.yml
  src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php
Labels: to review

#8158 TIP-860: Create empty directories for PIM structure
  CHANGELOG-3.0.md
  STANDARD_FORMAT.md
  app/AppKernel.php
  src/Akeneo/Pim/Enrichment/Bundle/AkeneoPimEnrichmentBundle.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimChannelExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Enrichment/Component/Category/.gitkeep
  src/Akeneo/Pim/Enrichment/Component/Comment/.gitkeep
  src/Akeneo/Pim/Enrichment/Component/PdfGeneration/.gitkeep
  src/Akeneo/Pim/Enrichment/Component/Product/.gitkeep
  src/Akeneo/Pim/Structure/Bundle/AkeneoPimStructureBundle.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Structure/Component/.gitkeep
  src/Pim/Bundle/PdfGeneratorBundle/DependencyInjection/PimPdfGeneratorExtension.php
  src/Pim/Bundle/PdfGeneratorBundle/Resources/config/twig.yml
  src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php
Labels: to review

#8217 CI for 1.7 : be Back
  .ci/Jenkinsfile
  .ci/k8s/pubsub_consumer_job.yaml
Labels: to review

#8256 TIP-842: Extract attribute group
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Component/Model/AbstractAttribute.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeGroup.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeGroupInterface.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeGroupTranslation.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeGroupTranslationInterface.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeInterface.php
  src/Akeneo/Tool/Bundle/ApiBundle/Controller/AttributeGroupController.php
  src/Akeneo/Tool/Bundle/ApiBundle/spec/Checker/QueryParametersCheckerSpec.php
  src/Akeneo/Tool/Component/Api/Normalizer/AttributeGroupNormalizer.php
  src/Akeneo/Tool/Component/Api/spec/Normalizer/AttributeGroupNormalizerSpec.php
  src/Akeneo/Tool/Component/Localization/spec/Factory/TranslationFactorySpec.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeGroupRepository.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
  src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Attribute.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeGroup.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeGroupTranslation.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/models.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/attributegroup.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Validation/AttributeGroupValidationIntegration.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php
  src/Pim/Bundle/EnrichBundle/Normalizer/AttributeGroupNormalizer.php
  src/Pim/Bundle/PdfGeneratorBundle/spec/Renderer/ProductPdfRendererSpec.php
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/AttributeGroupNormalizer.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeGroupNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeGroupUpdateGuesserSpec.php
  src/Pim/Component/Catalog/Model/AbstractProduct.php
  src/Pim/Component/Catalog/Normalizer/Standard/AttributeGroupNormalizer.php
  src/Pim/Component/Catalog/Repository/AttributeGroupRepositoryInterface.php
  src/Pim/Component/Catalog/Repository/AttributeRepositoryInterface.php
  src/Pim/Component/Catalog/Updater/AttributeGroupUpdater.php
  src/Pim/Component/Catalog/Updater/AttributeUpdater.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/AttributeGroupNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/AttributeNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Updater/AttributeGroupUpdaterSpec.php
  src/Pim/Component/Catalog/spec/Updater/AttributeUpdaterSpec.php
  src/Pim/Component/Catalog/tests/integration/Updater/AttributeGroupUpdaterIntegration.php
  src/Pim/Component/Connector/spec/Writer/Database/AttributeGroupWriterSpec.php
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/AttributeGroup/InMemoryAttributeGroupRepository.php
  tests/back/Acceptance/spec/AttributeGroup/InMemoryAttributeGroupRepositorySpec.php
Labels: to review

#8258 PIM-7394: add slash as an allowed character for the identifier of a product in the API
  CHANGELOG-1.7.md
  src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml
Labels: to review

#8262 TIP-842: Extract variant attribute set interface to Akeneo\Pim\Structure
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Model/VariantAttributeSet.php
  src/Akeneo/Pim/Structure/Component/Model/VariantAttributeSetInterface.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AttributeOptionSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AttributeSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/FamilyVariantSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/VariantAttributeSetSpec.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxis.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/AddBooleanValuesToNewProductSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/FamilyVariant.orm.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxisSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AddBooleanValuesToNewProductSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/RemoveAttributesFromFamilyVariantsOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/VariantNavigationNormalizerSpec.php
  src/Pim/Component/Catalog/Normalizer/Standard/FamilyVariantNormalizer.php
  src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php
  src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValidator.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/AddParentSpec.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/CheckAttributeEditableSpec.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/KeepOnlyValuesForVariationSpec.php
  src/Pim/Component/Catalog/spec/FamilyVariant/AddUniqueAttributesSpec.php
  src/Pim/Component/Catalog/spec/Manager/EntityWithFamilyVariantAttributesProviderSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/FamilyVariantNormalizerSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductAttributeFilterSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductModelAttributeFilterSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/ImageAsLabelSpec.php
  src/Pim/Component/Catalog/spec/Updater/FamilyVariantUpdaterSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyVariantValidatorSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableVariantAxesValidatorSpec.php
Labels: to review

#8261 Extract attribute translation
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Component/Model/AbstractAttribute.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeTranslation.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeTranslationInterface.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Model/VariantAttributeSet.php
  src/Akeneo/Pim/Structure/Component/Model/VariantAttributeSetInterface.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AttributeOptionSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AttributeSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/FamilyVariantSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Model/VariantAttributeSetSpec.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxis.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/AddBooleanValuesToNewProductSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Attribute.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/FamilyVariant.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/models.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxisSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AddBooleanValuesToNewProductSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/RemoveAttributesFromFamilyVariantsOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/CompletenessCollectionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/IncompleteValuesNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/VariantNavigationNormalizerSpec.php
  src/Pim/Component/Catalog/Normalizer/Standard/FamilyVariantNormalizer.php
  src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php
  src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValidator.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/AddParentSpec.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/CheckAttributeEditableSpec.php
  src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/KeepOnlyValuesForVariationSpec.php
  src/Pim/Component/Catalog/spec/FamilyVariant/AddUniqueAttributesSpec.php
  src/Pim/Component/Catalog/spec/Manager/EntityWithFamilyVariantAttributesProviderSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/FamilyVariantNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/TranslationNormalizerSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductAttributeFilterSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductModelAttributeFilterSpec.php
  src/Pim/Component/Catalog/spec/ProductModel/ImageAsLabelSpec.php
  src/Pim/Component/Catalog/spec/Updater/AttributeUpdaterSpec.php
  src/Pim/Component/Catalog/spec/Updater/FamilyVariantUpdaterSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyVariantValidatorSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableVariantAxesValidatorSpec.php
Labels: to review

#8246 ASI-1: Add some new front elements for the PIM.ai connection screen
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/common/title-with-subtitle.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/title-with-subtitle.html
  src/Pim/Bundle/UIBundle/Resources/config/assets.yml
  src/Pim/Bundle/UIBundle/Resources/public/images/illustrations/Helpcenter-settings.svg
  src/Pim/Bundle/UIBundle/Resources/public/less/components/SubTitleContainer.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/button/Button.less
Labels: to review

#8269 Extract catalog doctrine models configuration
  src/Akeneo/Pim/Structure/Bundle/AkeneoPimStructureBundle.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Attribute.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeGroup.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeGroupTranslation.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOption.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeRequirement.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeTranslation.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Family.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/FamilyTranslation.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/FamilyVariant.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/FamilyVariantTranslation.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/VariantAttributeSet.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attributegroup.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/family.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/familyvariant.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/variantattributeset.yml
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/CreateAttributeRequirementSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/attributeoptionvalue.yml
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/CreateAttributeRequirementSubscriberSpec.php
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml
  tests/legacy/features/Context/FixturesContext.php
  tests/legacy/features/Pim/Behat/Context/FixturesContext.php
  tests/legacy/features/versioning/purge_entites.feature
Labels: to review

#8278 PIM-7411: [SLA] Use json post for selected categories in product export
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/category.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
Labels: to review

#8281 PIM-7381 : Add modifier for specific input style on enriched entity
  src/Pim/Bundle/UIBundle/Resources/public/less/components/Subsection.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
Labels: to review

#8277 PIM-7405: Extract ordering in ProductValueNormalizer
  behat.yml.dist
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js
  src/Pim/Component/Catalog/Normalizer/Standard/Product/ProductValueNormalizer.php
  tests/legacy/features/Context/FeatureContext.php
  tests/legacy/features/Pim/Behat/Context/Domain/Enrich/ProductContext.php
  tests/legacy/features/Pim/Behat/Context/ImportExportFileContext.php
Labels: to review

#8282 PIM-7363: add family filter
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongBooleanValuesOnVariantProductCleaner.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsBatchCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsCommand.php
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/CatalogBundle/spec/Command/Cleaner/WrongValuesOnVariantProductCleanerSpec.php
Labels: to review

#8283 [SLA] PIM-7327: Fix completeness calculation memory leak
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
Labels: to review

#8263 PIM-7308: bulk associate to product models
  CHANGELOG-2.3.md
  src/Akeneo/Component/Versioning/Model/VersionableInterface.php
  src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/associate.js
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  tests/legacy/features/Context/Page/Batch/Operation.php
  tests/legacy/features/mass-action/mass_associate.feature
Labels: to review

#8016 Transform end to end validation tests into acceptance tests
  behat.yml.dist
  phpspec.yml.dist
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/product.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/productmodel.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Validation/ProductIdentifierValidationIntegration.php
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php
  src/Pim/Component/Api/Normalizer/Exception/ViolationNormalizer.php
  src/Pim/Component/Catalog/Validator/ConstraintGuesser/UniqueValueGuesser.php
  src/Pim/Component/Catalog/Validator/Constraints/Product/UniqueProductEntity.php
  src/Pim/Component/Catalog/Validator/Constraints/Product/UniqueProductEntityValidator.php
  src/Pim/Component/Catalog/Validator/Constraints/Product/UniqueProductModelEntity.php
  src/Pim/Component/Catalog/Validator/Constraints/Product/UniqueProductModelEntityValidator.php
  src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/UniqueValueGuesserSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/Product/UniqueProductEntitySpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/Product/UniqueProductEntityValidatorSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/Product/UniqueProductModelEntitySpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/Product/UniqueProductModelEntityValidatorSpec.php
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/Catalog/Context/ProductCreation.php
  tests/back/Acceptance/Catalog/Context/ProductValidation.php
  tests/back/Acceptance/Channel/ChannelContext.php
  tests/back/Acceptance/Locale/LocaleContext.php
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Acceptance/Resources/config/pim/repositories.yml
  tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
  tests/back/Common/EntityBuilder.php
  tests/back/Common/EntityWithValue/Association.php
  tests/back/Common/EntityWithValue/Builder/Product.php
  tests/back/Common/EntityWithValue/Builder/ProductModel.php
  tests/back/Common/EntityWithValue/Code.php
  tests/back/Common/EntityWithValue/ListOfCodes.php
  tests/back/Common/EntityWithValue/ListOfValues.php
  tests/back/Common/EntityWithValue/Status.php
  tests/back/Common/EntityWithValue/Value.php
  tests/back/Common/Structure/Attribute/Builder.php
  tests/back/Common/Structure/Attribute/Type.php
  tests/back/Common/spec/Structure/Attribute/BuilderSpec.php
  tests/back/Common/spec/Structure/Attribute/TypeSpec.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
  tests/features/catalog/product/value/product_identifier.feature
  tests/legacy/features/import/product/import_products_with_invalid_data.feature
  tests/legacy/features/product/validation/validate_identifier_attribute.feature
Labels: to review

#8285 PIM-7400: ensureIndexes uses a retry loop
  CHANGELOG-1.7.md
  src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreator.php
Labels: bug

#8299 PIM-7390: In the Product Edit Form, we now keep the context of attributes filter (missing, all, level specific...)
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js
Labels: to review

#8303 PIM-7345 : Remove the is_empty operator on the SKU filter
  CHANGELOG-2.3.md
  src/Oro/Bundle/FilterBundle/Form/Type/Filter/TextFilterType.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/IdentifierFilterIntegration.php
Labels: to review

#8306 [BUGFIX] Fix product model integration by adding missing associations
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/GetProductModelIntegration.php
Labels: to review

#8302 Use & track composer.lock to speed up install time
  .ci/Jenkinsfile
  .ci/builder.yaml
  .gitignore
  Dockerfile
  composer.lock
Labels: to review

#8304 PIM-7420: Keep item ordering in item picker
  src/Pim/Bundle/EnrichBundle/Resources/public/js/common/item-picker.js
  src/Pim/Bundle/EnrichBundle/spec/Provider/StructureVersion/StructureVersionProviderSpec.php
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
Labels: to review

#8295 Merge 1.7 into 2.0
  CHANGELOG-1.7.md
  features/export/convert_metric_values_during_product_export.feature
  features/product/create_product_and_save_added_attributes.feature
  features/update/set_metric.feature
  src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
  src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
  src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongValuesOnVariantProductCleaner.php
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml
  src/Pim/Component/Catalog/Normalizer/Standard/Product/MetricNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/MetricNormalizerSpec.php
Labels: to review

#8317 PIM-7381: add jest cache
  tests/front/common/base.jest.json
  tests/front/integration/jest/setup.js
Labels: to review

#8319 Merge 2.0 into 2.2
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  features/export/convert_metric_values_during_product_export.feature
  features/product/create_product_and_save_added_attributes.feature
  features/update/set_metric.feature
  src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
  src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
  src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongValuesOnVariantProductCleaner.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsBatchCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsCommand.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FindAttributesForFamily.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/CatalogBundle/spec/Command/Cleaner/WrongValuesOnVariantProductCleanerSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
  src/Pim/Bundle/EnrichBundle/Controller/Rest/GroupController.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml
  src/Pim/Component/Catalog/Normalizer/Standard/Product/MetricNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/MetricNormalizerSpec.php
Labels: to review

#8315 PIM-7438: fix usage of identifier attribute on association grid
  CHANGELOG-2.2.md
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
Labels: to review

#8265 PIM-7397: Asset preview
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/configure-columns-action.js
  src/Pim/Bundle/DataGridBundle/Resources/public/templates/configure-columns-action.html
  src/Pim/Bundle/EnrichBundle/Resources/public/js/job/product/edit/content/structure/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/item-picker.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attributes-selector.html
  src/Pim/Bundle/UIBundle/Resources/config/assets.yml
  src/Pim/Bundle/UIBundle/Resources/public/images/Default-picture.svg
  src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/ColumnConfigurator.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetPreview.less
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less
  src/Pim/Bundle/UIBundle/Resources/public/less/pages/FullPage.less
  tests/legacy/features/Context/AssertionContext.php
  tests/legacy/features/product/history/display_removed_value_history.feature
Labels: to review

#8320 Extract missing savers/repositories to Akeneo\Pim\Structure
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeOptionRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeRequirementRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Saver/AttributeSaver.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Saver/FamilySaver.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOption.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/repositories.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Saver/AttributeSaverSpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Saver/FamilySaverSpec.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/FamilyNormalizer.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeOptionRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeRequirementRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  src/Akeneo/Pim/Structure/Component/spec/Normalizer/Standard/FamilyNormalizerSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Updater/FamilyUpdaterSpec.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/OptionFilter.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Attribute/OptionFilterSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/UIBundle/Form/Transformer/AjaxEntityTransformer.php
  src/Pim/Bundle/UIBundle/Tests/Unit/Form/Transformer/AjaxEntityTransformerFactoryTest.php
  src/Pim/Bundle/UIBundle/Tests/Unit/Form/Transformer/AjaxEntityTransformerTest.php
  src/Pim/Bundle/UIBundle/spec/Controller/AjaxOptionControllerSpec.php
  src/Pim/Component/Catalog/spec/Factory/Value/OptionValueFactorySpec.php
  src/Pim/Component/Catalog/spec/Factory/Value/OptionsValueFactorySpec.php
  src/Pim/Component/Connector/Reader/Database/AttributeOptionReader.php
  tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
  tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
Labels: to review

#8326 PIM-7430: association versioning
  CHANGELOG-2.3.md
  src/Pim/Bundle/VersioningBundle/Resources/config/guessers.yml
  src/Pim/Bundle/VersioningBundle/UpdateGuesser/AssociationsUpdateGuesser.php
  src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AssociationsUpdateGuesserSpec.php
  tests/legacy/features/mass-action/mass_associate.feature
Labels: to review

#8346 PIM-7450: Add styles for remove asset confirmation
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetPreview.less
Labels: to merge

#8349 Ignore composer.lock file for now
  .gitignore
  composer.lock
Labels: to review

#8347 Correct the deletion of the query_parameters in CE
  src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml
Labels: to review

#8344 PIM-7442: Bulk actions ALL - count not taking into account variants
  CHANGELOG-2.2.md
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/CountImpactedProducts.php
  src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Query/CountImpactedProductsSpec.php
  src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/ORM/Query/CountImpactedProductsIntegration.php
Labels: to review

#8357 TIP-863: Move Completeness to Enrichment
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/Completeness.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/Product.orm.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractCompleteness.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/Completeness.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/CompletenessInterface.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/models.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessTestCase.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/PriceCollectionAttributeTypeCompletenessIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForLocalisableAttributeIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForScopableAndLocalisableAttributeIntegration.php
  src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductAssociationNormalizerSpec.php
  src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessNormalizer.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/CompletenessCollectionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/CompletenessNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
  src/Pim/Component/Catalog/Completeness/CompletenessCalculator.php
  src/Pim/Component/Catalog/Completeness/CompletenessCalculatorInterface.php
  src/Pim/Component/Catalog/Normalizer/Indexing/CompletenessCollectionNormalizer.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessCalculatorSpec.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/CompletenessCollectionNormalizerSpec.php
Labels: to review

#8361 PIM-7342: Implement findOneBy in InMemoryUserRepository
  tests/back/Acceptance/User/InMemoryUserRepository.php
  tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
Labels: to review

#8365 TIP-863: Move Associations to Enrichment
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/Product.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/ProductAssociation.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/ProductModel.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/model/doctrine/ProductModelAssociation.orm.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AssociationInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductAssociationInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelAssociationInterface.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Model/ProductSpec.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/models.yml
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php
  src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
  src/Pim/Bundle/EnrichBundle/Form/Subscriber/BindAssociationTargetsSubscriber.php
  src/Pim/Bundle/EnrichBundle/spec/Form/Type/AssociationTypeSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
  src/Pim/Bundle/FilterBundle/spec/Filter/Product/IsAssociatedFilterSpec.php
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductModelNormalizer.php
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductNormalizer.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductModelNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/Association/MissingAssociationAdder.php
  src/Pim/Component/Catalog/Model/EntityWithAssociationsInterface.php
  src/Pim/Component/Catalog/Normalizer/Standard/Product/ParentsAssociationsNormalizer.php
  src/Pim/Component/Catalog/Repository/AssociationRepositoryInterface.php
  src/Pim/Component/Catalog/Updater/Adder/AssociationFieldAdder.php
  src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
  src/Pim/Component/Catalog/spec/Association/AssociationClassResolverSpec.php
  src/Pim/Component/Catalog/spec/Association/MissingAssociationAdderSpec.php
  src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/AssociationsNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/ParentsAssociationsNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Updater/Adder/AssociationFieldAdderSpec.php
  src/Pim/Component/Catalog/spec/Updater/Setter/AssociationFieldSetterSpec.php
  src/Pim/Component/Connector/spec/Processor/Denormalization/ProductAssociationProcessorSpec.php
  src/Pim/Component/Connector/spec/Processor/Denormalization/ProductModelAssociationProcessorSpec.php
  src/Pim/Component/Connector/spec/Writer/Database/ProductAssociationWriterSpec.php
  tests/legacy/features/Context/FixturesContext.php
Labels: to review

#8364 TIP-842: Move the last classes/resources to the sub context structure
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Bundle/AkeneoPimStructureBundle.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Compiler/RegisterAttributeTypePass.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/entities.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/managers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/family.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/variantattributeset.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Bundle/spec/DependencyInjection/Compiler/RegisterAttributeTypePassSpec.php
  src/Akeneo/Pim/Structure/Component/Manager/AttributeOptionsSorter.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeAsImage.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeAsImageValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeAsLabel.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeAsLabelValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeUsedAsAxis.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyAttributeUsedAsAxisValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirements.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/ImmutableVariantAxes.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/ImmutableVariantAxesValidator.php
  src/Akeneo/Pim/Structure/Component/spec/Validator/Constraints/FamilyAttributeAsLabelValidatorSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Validator/Constraints/FamilyAttributeUsedAsAxisValidatorSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Validator/Constraints/FamilyRequirementsValidatorSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Validator/Constraints/ImmutableVariantAxesSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Validator/Constraints/ImmutableVariantAxesValidatorSpec.php
  src/Pim/Bundle/CatalogBundle/PimCatalogBundle.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/managers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Family/UpdateFamilyIntegration.php
  src/Pim/Component/Catalog/Model/AttributeTypeTranslationInterface.php
  src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValuesValidator.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableVariantAxesValuesValidatorSpec.php
Labels: to review

#8375 TIP-842: Move attribute option value model to structure sub context
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/entities.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOption.orm.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOptionValue.orm.yml
  src/Akeneo/Pim/Structure/Component/Model/AttributeOption.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeOptionValue.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeOptionValueInterface.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AttributeOptionSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Normalizer/Standard/AttributeOptionNormalizerSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Normalizer/Versionning/AttributeNormalizerSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Normalizer/Versionning/AttributeOptionNormalizerSpec.php
  src/Akeneo/Pim/Structure/Component/spec/Updater/AttributeOptionUpdaterSpec.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/models.yml
  src/Pim/Bundle/DataGridBundle/spec/Normalizer/Product/OptionNormalizerSpec.php
  src/Pim/Bundle/DataGridBundle/spec/Normalizer/Product/OptionsNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/Normalizer/AttributeOptionValueCollectionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/AttributeOptionValueNormalizer.php
  src/Pim/Bundle/EnrichBundle/spec/Form/Type/AttributeOptionValueTypeSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/UpdateGuesser/AttributeOptionUpdateGuesser.php
  src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php
  src/Pim/Component/Catalog/spec/Value/OptionValueSpec.php
  src/Pim/Component/Catalog/spec/Value/OptionsValueSpec.php
Labels: to review

#8377 Add missing changelogs for the release 2.3
  CHANGELOG-2.3.md
Labels: to review

#8384 Remove version from package.json
  package.json
Labels: tech-improvement

#8366 PIM-7432: fix the base URl
  tests/front/acceptance/cucumber/tools.js
  tests/front/acceptance/cucumber/world.js
  tests/front/common/templates/index.js
Labels: to review

#8382 PIM-7411: Fix Request-URI Too Large issue on category selection for p…
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/category.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
Labels: to review

#8387 merge 1.7 into 2.0
  CHANGELOG-1.7.md
Labels: to review

#8339 PIM-7396: Improve performances on Compute Model Descendants
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php
  src/Pim/Component/Catalog/spec/Job/ComputeProductModelsDescendantsTaskletSpec.php
Labels: to review

#8396 Fix typo on the changelog
  CHANGELOG-2.3.md
Labels: to review

#8395 Improve usage of docker-compose
  .gitignore
  docker-compose.override.yml.dist
  docker-compose.yml
Labels: to review

#8393 PIM-7465: Set front-end entity into field context
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
Labels: to review

#8403 Fix typo in docker-compose.yml
  docker-compose.override.yml.dist
  docker-compose.yml
Labels: to review

#8166 PIM-7366 Use CHILDREN operators instead of redoing it
  CHANGELOG-1.7.md
  src/Pim/Bundle/FilterBundle/Filter/CategoryFilter.php
  src/Pim/Bundle/FilterBundle/spec/Filter/CategoryFilterSpec.php
Labels: to review

#8398 Add composer.lock and use it
  .gitignore
  composer.lock
Labels: to review

#8397 Fix memory attribute repository to support array values as filter
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
Labels: to review

#8407 add acceptance tests path in CS fixer configuration
  .php_cs.php
  tests/back/Acceptance/Catalog/Context/ProductCreation.php
  tests/back/Acceptance/Catalog/Context/ProductValidation.php
  tests/back/Acceptance/Catalog/InMemoryGroupRepository.php
  tests/back/Acceptance/Catalog/InMemoryGroupTypeRepository.php
  tests/back/Acceptance/Common/ListOfCodes.php
  tests/back/Acceptance/Common/NotImplementedException.php
  tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php
  tests/back/Acceptance/User/InMemoryGroupRepository.php
  tests/back/Acceptance/User/InMemoryRoleRepository.php
  tests/back/Acceptance/User/InMemoryUserRepository.php
Labels: to review

#8345 Add constraint on products to check expected attributes
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/product.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Validation/OnlyExpectedAttributesValidationIntegration.php
  src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributes.php
Labels: to review

#8413 PIM-7474: Show job profile label instead of code in the headers
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/common/edit/meta.html
Labels: to merge

#8414 PIM-7460: Fix locale flag for locales with two underscores.
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js
Labels: bug, to review

#8333 [SLA] PIM-7413: Newly created attribute group is correctly sorted after existing ones
  CHANGELOG-2.2.md
  features/attribute-group/create_attribute_group.feature
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv
Labels: to review
