Repository akeneo/pim-community-dev, pull requests merged in 2018-09, with the labels that each got.

#8786 [SLA] PIM-7610: Add a command to create users
  CHANGELOG-2.3.md
  src/Pim/Bundle/UserBundle/Command/CreateUserCommand.php
Labels: to review

#8789 PIM-7631: Fix API filter product and product model on date with between operator
  CHANGELOG-2.3.md
  src/Pim/Bundle/ApiBundle/Controller/ProductController.php
  src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php
Labels: to review

#8785 PIM-7609: Handle 'empty' and 'not empty' filter types in string filter
  CHANGELOG-2.3.md
  src/Oro/Bundle/FilterBundle/Filter/StringFilter.php
  src/Oro/Bundle/FilterBundle/spec/Filter/ChoiceFilterSpec.php
  src/Oro/Bundle/FilterBundle/spec/Filter/StringFilterSpec.php
Labels: to review

#8804 Fix wrong namespace in integration tests
  .ci/Jenkinsfile
  composer.lock
  src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
  src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
  src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php
  src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Standard/ProductStandardIntegration.php
  src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Storage/EntityWithValuesStorageIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/GetProductModelIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListOffsetProductModelIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
  src/Akeneo/Tool/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
Labels: to review

#8806 TIP-878: Move Image to the right folder
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-lock2.svg
Labels: to review

#8808 PIM-7628: Fix identifier filter initialization
  CHANGELOG-2.3.md
  composer.lock
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
Labels: to review

#8799 PIM-7612 allow scalable frontend architecture for media content delivery
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Controller/FileController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/media.yml
Labels: to review

#8814 Fix integration test too long to execute
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListOffsetProductModelIntegration.php
Labels: to review

#8743 PIM-7594: Put cursor back instead of doctrine Paginator who load all data and memory leak occurs
  CHANGELOG-2.3.md
  src/Pim/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
  src/Pim/Bundle/VersioningBundle/Purger/VersionPurger.php
  src/Pim/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php
  src/Pim/Bundle/VersioningBundle/Resources/config/repositories.yml
Labels: to review

#8818 Merge branch '2.0' into branch '2.3'
  .ci/Dockerfile
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  composer.lock
  src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/mass-edit/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-switcher.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/mass-edit/attributes.html
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionNormalizerSpec.php
  src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
  src/Pim/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistry.php
  src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistryInterface.php
  src/Pim/Component/Enrich/Converter/StandardToEnrich/ValueConverter.php
  src/Pim/Component/Enrich/spec/Converter/StandardToEnrich/ValueConverterSpec.php
Labels: to review

#8813 PIM-7265: Fix attributes groups order on the PEF
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv
Labels: to review

#8763 PIM-7601: Update Symfony to 3.4.4
  CHANGELOG-2.3.md
  composer.json
  composer.lock
Labels: to review

#8750 Use a dedicated system user token instead of UsernamePasswordToken for commands
  src/Pim/Bundle/UserBundle/EventListener/CreateSystemUserForCommandsListener.php
  src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/UserBundle/Security/SystemUserToken.php
Labels: to review

#8628 PIM-7506: Cache default column/views requests on the datagrid
  CHANGELOG-3.0.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/fetcher/datagrid-view-fetcher.js
Labels: to merge

#8812 TIP-878: Improve version display
  src/Akeneo/Platform/VersionProvider.php
  src/Akeneo/Platform/spec/VersionProviderSpec.php
Labels: to review

#8834 Implements findBy method for in memory user repo
  tests/back/Acceptance/User/InMemoryUserRepository.php
  tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
Labels: to review

#8863 Implement InMemoryAttributeRepository::getAttributeTypeByCodes()
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
Labels: to review

#8862 APAI-287 - Style for EE
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Labels: to review

#8765 PIM-7621 - add new axes on System Information
  app/config/pim_parameters.yml
  behat.yml.dist
  src/Pim/Bundle/AnalyticsBundle/DataCollector/AttributeDataCollector.php
  src/Pim/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
  src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Pim/Bundle/AnalyticsBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/AnalyticsBundle/spec/DataCollector/AttributeDataCollectorSpec.php
  src/Pim/Bundle/AnalyticsBundle/spec/DataCollector/DBDataCollectorSpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/AverageMaxLocalizableAndScopableAttributesPerFamily.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/AverageMaxLocalizableAttributesPerFamily.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/AverageMaxProductValuesPerFamily.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/AverageMaxScopableAttributesPerFamily.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/CountUseableAsGridFilterAttributes.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/spec/Persistence/Query/Sql/AverageMaxLocalizableAndScopableAttributesPerFamilySpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/spec/Persistence/Query/Sql/AverageMaxLocalizableAttributesPerFamilySpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/spec/Persistence/Query/Sql/AverageMaxProductValuesPerFamilySpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/spec/Persistence/Query/Sql/AverageMaxScopableAttributesPerFamilySpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/spec/Persistence/Query/Sql/CountUseableAsGridFilterAttributesSpec.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/LocalizableAndScopableAttributePerFamilyContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/LocalizableAttributePerFamilyContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/ProductValuePerFamilyContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/ScopableAttributePerFamilyContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/SystemInfoAttributeContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/SystemInfoContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Context/UseableAsGridFilterAttributeContext.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Persistence/Query/InMemory/InMemoryAverageMaxQuery.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Resources/config/behat/services.yml
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Acceptance/Resources/config/pim/queries.yml
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/AverageMaxLocalizableAndScopableAttributesPerFamilyIntegration.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/AverageMaxLocalizableAttributesPerFamilyIntegration.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/AverageMaxScopableAttributesPerFamilyIntegration.php
  src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/CountUseableAsGridFilterAttributesIntegration.php
  tests/features/volume-monitoring/volume_customer_statistics.feature
Labels: to review

#7905 Update to PHP 7.2
  .ci/Dockerfile
  .ci/php.ini
  .ci/vhost.conf
  CHANGELOG-3.0.md
  app/PimRequirements.php
  composer.json
  composer.lock
  docker-compose.yml
  src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/Family/RemoveFamilyVariantIntegration.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductAssociationWriter.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductModelCsvExportSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Writer/Database/ProductAssociationWriterSpec.php
  src/Akeneo/UserManagement/Component/Model/User.php
  src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/NavigateAction.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/SequentialEditController.php
Labels: to review

#8864 TIP-860: Fix review comment
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Channel/Bundle/Doctrine/Repository/InternalApi/ChannelRepository.php
  src/Akeneo/Channel/Bundle/Doctrine/Repository/InternalApi/CurrencyRepository.php
  src/Akeneo/Channel/Bundle/Doctrine/Repository/InternalApi/LocaleRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/form_types.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/spec/Elasticsearch/Sorter/InGroupSorterSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/spec/Form/Type/SelectFamilyTypeSpec.php
  src/Akeneo/Pim/Enrichment/Component/Category/Normalizer/InternalApi/CategoryNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/FileNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ImageNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/InternalApi/FileNormalizerSpec.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/SelectFamilyType.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/file_storage.yml
Labels: to review

#8801 Add ProgressBar component in indexer commands
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/spec/Command/IndexProductCommandSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/spec/Command/IndexProductModelCommandSpec.php
Labels: contribution, to review

#8884 Merge branch 2.0 into branch 2.3
  composer.lock
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Command/PublishJobToQueueCommandIntegration.php
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Queue/DatabaseJobExecutionQueueIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/legacy/features/Pim/Behat/Context/DBALPurger.php
Labels: to review

#8871 TIP-873: remove EE datagrid bundle
  bin/check-pullup
  src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/extensions.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/pagers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/mass-edit.js
Labels: to review

#8874 PIM-7652: Fix concurrent edition with the parent of a product or a product model in the UI
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/filters.yml
Labels: to review

#8894 PIM-7659: Fix search on the families to get one result by label
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php
  src/Pim/Bundle/EnrichBundle/tests/integration/Repository/FamilySearchableRepositoryIntegration.php
Labels: to review

#8752 TIP-879 Uses utf8mb4 instead of MySQL flawed utf8
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/EventListener/InstallDatabase.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/CommunityRequirements.php
  src/Akeneo/Platform/Requirement.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/tests/integration/Utf8mb4SupportIntegrationTest.php
  src/Pim/Bundle/EnrichBundle/Resources/config/bundles/doctrine.yml
  src/Pim/Bundle/EnrichBundle/StructureVersion/EventListener/TableCreator.php
  upgrades/schema/Version_3_0_20180823184342_switch_to_utf8mb4.php
Labels: to review

#8875 PIM-7629: Refactor the way we aggregate ES search results for datagrid
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactory.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelSearchAggregator.php
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactorySpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelSearchAggregatorSpec.php
Labels: to review

#8899 PIM-7619: Fix search on groups for the variant products
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
Labels: to review

#8900 PIM-7671 : Fix display associated products even if the product limit is reached before to display the product models on the page.
  CHANGELOG-2.3.md
  src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
Labels: to review

#8903 PIM-7668: Always display datetime according to current user timezone
  CHANGELOG-2.3.md
  composer.lock
  src/Pim/Bundle/EnrichBundle/Controller/Rest/JobExecutionController.php
  src/Pim/Bundle/EnrichBundle/Normalizer/JobExecutionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/last_executions.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/JobExecutionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
  src/Pim/Bundle/NotificationBundle/Controller/NotificationController.php
  src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
  src/Pim/Bundle/NotificationBundle/spec/Controller/NotificationControllerSpec.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
Labels: to review

#8905 PIM-7656: Fix link insertion in wysiwyg mass edit field
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js
Labels: to review
