Repository akeneo/pim-community-dev, pull requests merged in 2018-05, with the labels that each got.

#8023 PIM-7323: rework unique value data synchronizer
  CHANGELOG-2.0.md
  features/Context/AssertionContext.php
  features/product/validation/validate_unique_attribute.feature
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizer.php
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/AbstractProduct.orm.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductUniqueDataSynchronizerSpec.php
Labels: to review

#8098 TIP-856: Move Pim\Buffer Component and Bundle to Akeneo\Tool
  CHANGELOG-3.0.md
  UPGRADE.md
  app/AppKernel.php
  src/Akeneo/Tool/Bundle/BufferBundle/AkeneoBufferBundle.php
  src/Akeneo/Tool/Bundle/BufferBundle/DependencyInjection/AkeneoBufferExtension.php
  src/Akeneo/Tool/Bundle/BufferBundle/Resources/config/factories.yml
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/validation/fileInfo.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/README.md
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/phpspec.yml
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ChannelNormalizerSpec.php
  tests/legacy/features/Pim/Behat/Context/FixturesContext.php
Labels: to review

#8078 PIM-7338: Attribute groups label used catalog locale (not UI locale) in grid
  CHANGELOG-2.0.md
  features/attribute-group/list_attribute_groups.feature
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js
Labels: to review

#8144 TIP-840/839/841: Move currency/locale/channel jobs to Akeneo\Channel
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Channel/Bundle/DependencyInjection/AkeneoChannelExtension.php
  src/Akeneo/Channel/Bundle/Resources/config/array_converters.yml
  src/Akeneo/Channel/Bundle/Resources/config/jobs.yml
  src/Akeneo/Channel/Bundle/Resources/config/processors.yml
  src/Akeneo/Channel/Bundle/Resources/config/readers.yml
  src/Akeneo/Channel/Bundle/Resources/config/steps.yml
  src/Akeneo/Channel/Bundle/Resources/config/translations/jsmessages.en_US.yml
  src/Akeneo/Channel/Bundle/Resources/config/writers.yml
  src/Akeneo/Channel/Component/ArrayConverter/FlatToStandard/Channel.php
  src/Akeneo/Channel/Component/ArrayConverter/FlatToStandard/Currency.php
  src/Akeneo/Channel/Component/ArrayConverter/FlatToStandard/Locale.php
  src/Akeneo/Channel/Component/ArrayConverter/StandardToFlat/Channel.php
  src/Akeneo/Channel/Component/ArrayConverter/StandardToFlat/Currency.php
  src/Akeneo/Channel/Component/ArrayConverter/StandardToFlat/Locale.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/FlatToStandard/ChannelSpec.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/FlatToStandard/CurrencySpec.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/FlatToStandard/LocaleSpec.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/StandardToFlat/ChannelSpec.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/StandardToFlat/CurrencySpec.php
  src/Akeneo/Channel/Component/spec/ArrayConverter/StandardToFlat/LocaleSpec.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
  src/Pim/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
Labels: to review

#8109 PIM-7348: Prevent completeness calculation for products without a family
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessManagerSpec.php
  src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
  src/Pim/Component/Connector/Reader/Database/ProductReader.php
  src/Pim/Component/Connector/spec/Reader/Database/ProductReaderSpec.php
Labels: to merge

#8060 Fix measure family converter
  CHANGELOG-2.0.md
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/GetMeasureFamilyIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/ListMeasureFamilyIntegration.php
  src/Pim/Component/Api/Converter/MeasureFamilyConverter.php
Labels: contribution, to review

#8080 PIM-7330: Better validation message on sibling duplicate
  .ci/Jenkinsfile
  .ci/bin/start-elasticsearch
  CHANGELOG-2.3.md
  Dockerfile
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListVariantProductIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entity_with_family_variant.yml
  src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateProductModelIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
  src/Pim/Component/Catalog/Exception/AlreadyExistingAxisValueCombinationException.php
  src/Pim/Component/Catalog/Model/ProductModel.php
  src/Pim/Component/Catalog/Repository/EntityWithFamilyVariantRepositoryInterface.php
  src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxis.php
  src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Pim/Component/Catalog/Validator/UniqueAxesCombinationSet.php
  src/Pim/Component/Catalog/Value/OptionValue.php
  src/Pim/Component/Catalog/spec/Exception/AlreadyExistingAxisValueCombinationExceptionSpec.php
  src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  src/Pim/Component/Catalog/spec/Validator/UniqueAxesCombinationSetSpec.php
  tests/legacy/features/import/product_model/import_with_invalid_data.feature
  tests/legacy/features/product-model/add_product_model_children.feature
Labels: to review

#8157 PIM-7363: fix rename of cursor factory
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
Labels: to review

#8038 PIM-7298: As Julia, I would like to change the parent of a sub product model
  behat.yml.dist
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateProductModelIntegration.php
  src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
  src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
  tests/legacy/features/Pim/Behat/Context/Domain/Enrich/ProductModelContext.php
  tests/legacy/features/import/product_model/import_with_invalid_data.feature
  tests/legacy/features/product-model/change_parent.feature
Labels: to review

#8159 Merge 2.0 into 2.2
  CHANGELOG-2.0.md
  features/attribute-group/list_attribute_groups.feature
  features/family/remove_attribute_from_a_family.feature
  features/product/filtering/filter_products.feature
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/GetMeasureFamilyIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/ListMeasureFamilyIntegration.php
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/TextFilter.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/IdentifierFilterSpec.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/product-completeness.html
  src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig
  src/Pim/Component/Api/Converter/MeasureFamilyConverter.php
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/Query/Escaper/QueryString.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessManagerSpec.php
  src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
  src/Pim/Component/Connector/Reader/Database/ProductReader.php
  src/Pim/Component/Connector/spec/Reader/Database/ProductReaderSpec.php
Labels: remontada

#8168 PIM-7363: fix commands to clean products
  src/Pim/Bundle/CatalogBundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RefreshProductCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
Labels: to review

#8177 Fix CI build
  Dockerfile
Labels: to review

#8180 Fix CI build
  Dockerfile
Labels: to review

#8179 Fix CI build
  Dockerfile
Labels: to review

#8117 PIM-7326: Create a version when the parent of a variant product or a sub product model is changed
  .ci/bin/start-elasticsearch
  CHANGELOG-2.3.md
  behat.yml.dist
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductModelNormalizer.php
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductNormalizer.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductModelNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductNormalizerSpec.php
  tests/legacy/features/Pim/Behat/Context/Domain/Enrich/ProductModelContext.php
  tests/legacy/features/Pim/Behat/Context/Domain/Enrich/VariantProductContext.php
  tests/legacy/features/mass-action/add_products_and_variant_products_to_groups.feature
  tests/legacy/features/product-model/change_parent.feature
  tests/legacy/features/product/variant/change_parent.feature
Labels: to review

#8186 Fix tests on product model export with association
  tests/legacy/features/Context/FixturesContext.php
  tests/legacy/features/export/product_model/csv/export_product_models.feature
  tests/legacy/features/export/product_model/xlsx/export_product_models.feature
Labels: to review

#8181 PIM-7380: make bundle structure more flexible
  package.json
  src/Pim/Bundle/EnrichBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts
  src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php
  src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  tests/front/unit/pimenrich/js/i18n.unit.ts
  tsconfig.json
  webpack.config.js
  webpack/requirejs-utils.js
Labels: to review

#8165 TIP-858: Enable php coupling detector for user management BC
  .ci/Jenkinsfile
  CHANGELOG-3.0.md
  UPGRADE.md
  composer.json
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Channel/Bundle/EventListener/CurrencyDisablingSubscriber.php
  src/Akeneo/Channel/Bundle/Resources/config/services.yml
  src/Akeneo/Channel/Bundle/Resources/config/validation/currency.yml
  src/Akeneo/Channel/Bundle/Resources/config/validation/locale.yml
  src/Akeneo/Channel/Bundle/spec/EventListener/CurrencyDisablingSubscriberSpec.php
  src/Akeneo/Channel/Component/Exception/LinkedChannelException.php
  src/Akeneo/Channel/Component/Model/Channel.php
  src/Akeneo/Channel/Component/Model/ChannelInterface.php
  src/Akeneo/Channel/Component/Model/Currency.php
  src/Akeneo/Channel/Component/Model/CurrencyInterface.php
  src/Akeneo/Channel/Component/Model/Locale.php
  src/Akeneo/Channel/Component/Model/LocaleInterface.php
  src/Akeneo/Channel/Component/Normalizer/InternalApi/ChannelNormalizer.php
  src/Akeneo/Channel/Component/Updater/ChannelUpdater.php
  src/Akeneo/Channel/Component/spec/Normalizer/InternalApi/ChannelNormalizerSpec.php
  src/Akeneo/Channel/Component/spec/Updater/ChannelUpdaterSpec.php
  src/Akeneo/Tool/Component/StorageUtils/Model/ReferableInterface.php
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Context/UserContext.php
  src/Akeneo/UserManagement/Bundle/EventListener/UserPreferencesSubscriber.php
  src/Akeneo/UserManagement/Bundle/Form/Subscriber/UserPreferencesSubscriber.php
  src/Akeneo/UserManagement/Bundle/Resources/config/context.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
  src/Akeneo/UserManagement/Bundle/spec/Context/UserContextSpec.php
  src/Akeneo/UserManagement/Component/Model/User.php
  src/Akeneo/UserManagement/Component/Model/UserInterface.php
  src/Pim/Bundle/CatalogBundle/Builder/ChoicesBuilder.php
  src/Pim/Bundle/CatalogBundle/Builder/ChoicesBuilderInterface.php
  src/Pim/Bundle/CatalogBundle/Command/ValidateObjectsCommand.php
  src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
  src/Pim/Bundle/CatalogBundle/spec/Builder/ChoicesBuilderSpec.php
  src/Pim/Bundle/EnrichBundle/Controller/CurrencyController.php
  src/Pim/Component/Catalog/Model/AssociationInterface.php
  src/Pim/Component/Catalog/Model/AssociationTypeInterface.php
  src/Pim/Component/Catalog/Model/AttributeGroupInterface.php
  src/Pim/Component/Catalog/Model/AttributeInterface.php
  src/Pim/Component/Catalog/Model/AttributeOptionInterface.php
  src/Pim/Component/Catalog/Model/CategoryInterface.php
  src/Pim/Component/Catalog/Model/FamilyInterface.php
  src/Pim/Component/Catalog/Model/GroupInterface.php
  src/Pim/Component/Catalog/Model/GroupTypeInterface.php
  src/Pim/Component/Catalog/Model/ProductInterface.php
Labels: to review

#8161 PIM-6350: As Julia, I would like to change the parent of a variant product/sub product model from the UI
  CHANGELOG-2.3.md
  behat.yml.dist
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelRepository.php
  src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/ChangeParentProcessor.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/change_parent_product.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/product.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_constraints.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_defaults.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/jobs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/product_model.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/update-entity-with-family-variant-parent.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/product/update-entity-with-family-variant-parent.html
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/MassEdit/Product/ChangeParentProcessorSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/ProductAndProductModelReaderSpec.php
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Pim/Component/Catalog/Repository/ProductModelRepositoryInterface.php
  tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php
  tests/back/Integration/catalog/technical/jobs.yml
  tests/legacy/features/Context/catalog/apparel/jobs.yml
  tests/legacy/features/Context/catalog/catalog_modeling/jobs.yml
  tests/legacy/features/Context/catalog/default/jobs.yml
  tests/legacy/features/Context/catalog/footwear/jobs.yml
  tests/legacy/features/Pim/Behat/Context/MassEditJobContext.php
  tests/legacy/features/mass-action/change_product_parent.feature
  upgrades/schema/Version_2_3_20180522151757_batch_jobs_migration.php
Labels: to review

#8199 Merge 1 7 into 2 0
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.de.yml
  src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php
Labels: to review

#8082 PIM-7302: delete an attribute option is forbiden if it is a variant axis
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FamilyVariantsByAttributeAxes.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyVariantRepository.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/FamilyVariantFilter.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/AttributeOption/AttributeOptionRemovalSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Query/FamilyVariantsByAttributeAxesSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/FamilyVariantFilterSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AttributeOption/AttributeOptionRemovalSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/PimCatalogFamilyVariantIntegration.php
  src/Pim/Component/Catalog/FamilyVariant/Query/FamilyVariantsByAttributeAxesInterface.php
  src/Pim/Component/Catalog/tests/integration/Updater/Remover/AttributeOptionRemoverIntegration.php
  tests/legacy/features/Pim/Behat/Context/NavigationContext.php
  tests/legacy/features/attribute/option/delete_attribute_options.feature
  tests/legacy/features/mass-action/add_products_to_groups.feature
Labels: to review

#8048 Test fest decorators
  .eslintrc
  package.json
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/number.html
  tests/front/acceptance/cucumber/decorators/catalog-volume/report.js
  tests/front/acceptance/cucumber/decorators/catalog-volume/volume.js
  tests/front/acceptance/cucumber/decorators/common/create-element-decorator.js
  tests/front/acceptance/cucumber/decorators/common/header.js
  tests/front/acceptance/cucumber/step-definitions/structure/locales.js
  tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
  tests/front/acceptance/cucumber/tools.js
  tests/front/acceptance/cucumber/world.js
  tests/front/acceptance/test-helpers.js
  webpack/test/acceptance/generate-html-report.js
Labels: to review

#8203 PIM-7380: fix form extension listing
  src/Pim/Bundle/EnrichBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
  tsconfig.json
  webpack.config.js
Labels: to review

#8200 PIM-7385: Fix memory leak on purge job command
  CHANGELOG-1.7.md
  src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
Labels: to merge

#8202 Merge 2 0 into 2 2
  .ci/Jenkinsfile
  .ci/bin/start-elasticsearch
  .ci/bin/start-mysql
  .ci/bin/start-selenium
  .ci/bin/start-webserver
  .ci/builder.yaml
  .ci/php.ini
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  Dockerfile
  app/config/config_behat.yml
  composer.json
  features/import/check_encoding_before_import.feature
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.de.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.de.yml
  src/Pim/Component/Catalog/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php
Labels: to review

#8084 PIM-7315 : 500 on "IS EMPTY" operator for the SKU filter
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/IdentifierFilterSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/IdentifierFilterIntegration.php
Labels: to review

#8215 PIM-7388: [SLA] Completeness filter on product grid for models does not work as expected
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
Labels: to review
