Repository akeneo/pim-community-dev, pull requests merged in 2018-03, with the labels that each got.

#7748 PIM-7217: [SLA] Fix missing and disabled fields in product model import
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
Labels: to review

#7761 Fix #7760 wrong HTTP status on response
  src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
Labels: to review

#7766 Add amansilla contrib on changelog
  CHANGELOG-1.6.md
Labels: to review

#7757 Fix #7752 wrong position of warning icon
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Labels: to review

#7746 PIM-7167 Slowness when going back to the Product grid when a family is used in the filter
  CHANGELOG-2.0.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
Labels: to review

#7768 Merge 1.6 into 1.7
  CHANGELOG-1.6.md
  src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
Labels: to review

#7776 PIM-7214: Select products and families on multiple grid pages
  CHANGELOG-2.0.md
  features/Context/FixturesContext.php
  features/family/multiple_page_selection.feature
  features/product/multiple_page_selection.feature
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/header-cell/select-all-header-cell.js
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/row.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/mass-actions.js
Labels: to review

#7784 Merge 2.0 into 2.1
  CHANGELOG-1.6.md
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  bin/docker/pim-front.sh
  bin/docker/pim-initialize.sh
  composer.json
  features/Context/Page/Base/Grid.php
  features/attribute/delete_attribute.feature
  src/Akeneo/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php
  src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
  src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/FromSizeCursorSpec.php
  src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php
  src/Oro/Bundle/UserBundle/Controller/ResetController.php
  src/Oro/Bundle/UserBundle/Resources/config/navigation.yml
  src/Oro/Bundle/UserBundle/Resources/config/oro/routing.yml
  src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
  src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/UserBundle/Resources/views/Reset/request.html.twig
  src/Pim/Bundle/UserBundle/Resources/views/Reset/sendEmail.html.twig
  src/Pim/Bundle/VersioningBundle/Purger/VersionPurger.php
  src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
  src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
  src/Pim/Component/Connector/Reader/Database/ProductReader.php
Labels: to review

#7793 [SLA] PIM-7220: Fix filter is empty
  CHANGELOG-2.0.md
  features/Context/FixturesContext.php
  features/import/import_families.feature
  features/product/filtering/filter_products_per_media.feature
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Family/UpdateFamilyIntegration.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
  src/Pim/Component/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
Labels: to review

#7790 PIM-7187: Fix product and product model reader
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php
Labels: to review

#7751 PIM-7143: Mass delete products and product models with job
  CHANGELOG-2.2.md
  features/Context/catalog/apparel/jobs.yml
  features/Context/catalog/catalog_modeling/jobs.yml
  features/Context/catalog/default/jobs.yml
  features/Context/catalog/footwear/jobs.yml
  features/family/delete_family.feature
  features/mass-action/mass_delete.feature
  features/mass-action/mass_delete_products_and_product_models.feature
  src/Pim/Bundle/DashboardBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/DashboardBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/DataGridBundle/Extension/MassAction/Actions/Ajax/DeleteMassAction.php
  src/Pim/Bundle/DataGridBundle/Resources/config/mass_actions.yml
  src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/mass-delete-action.js
  src/Pim/Bundle/DataGridBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/Actions/Ajax/DeleteMassActionSpec.php
  src/Pim/Bundle/EnrichBundle/Connector/Job/JobParameters/DefaultValuesProvider/ProductAndProductModelMassDelete.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
  src/Pim/Bundle/EnrichBundle/MassEditAction/OperationJobLauncher.php
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/factories.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_constraints.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_defaults.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/jobs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/MediaField.less
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
  src/Pim/Component/Enrich/Job/DeleteProductsAndProductModelsTasklet.php
  src/Pim/Component/Enrich/spec/Job/DeleteProductsAndProductModelsTaskletSpec.php
Labels: to review

#7742 PIM-6389: Add attribute value for collections in bulk actions
  CHANGELOG-2.2.md
  features/Context/Page/Batch/Operation.php
  features/Context/catalog/apparel/jobs.yml
  features/Context/catalog/catalog_modeling/jobs.yml
  features/Context/catalog/default/jobs.yml
  features/Context/catalog/footwear/jobs.yml
  features/attribute/use_unique_attribute.feature
  features/export/export_products_with_media.feature
  features/job-tracker/display_jobs_execution_in_job_tracker.feature
  features/mass-action/add_attribute_value.feature
  features/mass-action/edit_common_attributes.feature
  features/mass-action/edit_common_attributes_channel.feature
  features/mass-action/edit_common_attributes_groups.feature
  features/mass-action/edit_common_attributes_images.feature
  features/mass-action/edit_common_attributes_locale_specific.feature
  features/mass-action/edit_common_attributes_metric.feature
  features/mass-action/edit_common_attributes_per_families.feature
  features/mass-action/edit_common_attributes_product_model.feature
  features/mass-action/edit_common_attributes_scopable_localizable.feature
  features/mass-action/mass_action_count_impacted_products_and_variant_products.feature
  features/mass-action/mass_actions_on_all_entities.feature
  features/mass-action/mass_edit_and_update_attribute_history.feature
  features/mass-action/mass_edit_products_and_product_models.feature
  features/mass-action/validate/edit_common_attributes_permissions.feature
  features/mass-action/validate/validate_editing_common_boolean_attributes.feature
  features/mass-action/validate/validate_editing_common_date_attributes.feature
  features/mass-action/validate/validate_editing_common_file_attributes.feature
  features/mass-action/validate/validate_editing_common_image_attributes.feature
  features/mass-action/validate/validate_editing_common_numeric_attributes.feature
  features/mass-action/validate/validate_editing_common_select_attributes.feature
  features/mass-action/validate/validate_editing_common_text_attributes.feature
  features/navigation/navigate_using_hash_navigation.feature
  features/reference-data/mass-action/edit_common_attributes.feature
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddAttributeValueProcessor.php
  src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_add_attributes_values.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/product.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_constraints.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/job_defaults.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/jobs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/MassEdit/Product/AddAttributeValueProcessorSpec.php
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Pim/Bundle/UIBundle/Resources/public/images/bulk/icon-add-attribute-values.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/bulk/icon-add-attribute-values_selected.svg
  src/Pim/Bundle/UIBundle/Resources/public/less/components/SquareList.less
  tests/Integration/catalog/technical/jobs.yml
  upgrades/schema/Version_2_2_20180228120422.php
Labels: to review

#7814 PIM-7152: Fix errors due to deletion of attributes
  CHANGELOG-2.0.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/edit.yml
Labels: to review

#7819 PIM-7106: fix repo to return children of given entity instead of its parent
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/VariantProductRepository.php
Labels: to review

#7821 PIM-7255: Reduce slowness on product grid
  CHANGELOG-2.0.md
  src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php
  src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CategoryFilter.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CategoryFilterSpec.php
Labels: to review

#7810 PIM-7237: fix integrity constraint violation during import
  .ci/behat.community.yml
  .ci/behat.enterprise.yml
  CHANGELOG-2.0.md
  behat.yml.dist
  features/Context/FeatureContext.php
  features/Pim/Behat/Context/Storage/AttributeOptionStorage.php
  features/attribute/option/import_attribute_options.feature
  src/Akeneo/Component/Batch/Event/EventInterface.php
  src/Akeneo/Component/Batch/Step/ItemStep.php
  src/Akeneo/Component/Batch/spec/Step/ItemStepSpec.php
  src/Pim/Bundle/ConnectorBundle/DependencyInjection/PimConnectorExtension.php
  src/Pim/Bundle/ConnectorBundle/EventListener/ResetProcessedItemsBatchSubscriber.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
  src/Pim/Bundle/ConnectorBundle/spec/EventListener/ResetProcessedItemsBatchSubscriberSpec.php
  src/Pim/Component/Connector/Processor/Denormalization/AbstractProcessor.php
  src/Pim/Component/Connector/Processor/Denormalization/Processor.php
  src/Pim/Component/Connector/spec/Processor/Denormalization/ProcessorSpec.php
Labels: to review

#7841 Fix PEB filter validator
  src/Pim/Component/Connector/Validator/Constraints/FilterDataValidator.php
Labels: to review

#7847 Migration: Add missing job instance in migration
  upgrades/schema/Version_2_2_20180228120422.php
  upgrades/schema/Version_2_2_20180321103340_index_products_and_product_models.php
Labels: to review

#7851 Migration: Add migration of job parameters
  upgrades/schema/Version_2_2_20180321135455_product_model_export_job_parameters.php
Labels: to review

#7854 Migration: index as the last step
  upgrades/schema/Version_2_2_20180321135455_product_model_export_job_parameters.php
  upgrades/schema/Version_2_2_20180321164023_index_products_and_product_models.php
Labels: to review

#7831 PIM-7243: [SLA] issue on currencies in CSV and XLSX product imports
  CHANGELOG-2.0.md
  src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/FieldSplitter.php
  src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/FieldSplitterSpec.php
Labels: to merge

#7858 Update changelog
  CHANGELOG-2.2.md
Labels: to review

#7813 PIM-6919: Fix show boolean label for boolean-status-cell
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/boolean-status-cell.js
Labels: to review

#7781 [PIM-7203] Fix : bulk action mass edit attibute to edit all the product selection.
  CHANGELOG-2.0.md
  features/Context/FixturesContext.php
  features/mass-action/mass_edit_many_products_at_once.feature
  src/Pim/Bundle/CatalogBundle/Entity/Family.php
  src/Pim/Bundle/CatalogBundle/spec/Entity/FamilySpec.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/ProductAndProductModelReaderSpec.php
Labels: to review

#7815 PIM-7240: Add subscriber to clear the cache between each job step batch
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ResetUniqueValidationSubscriberSpec.php
  src/Pim/Bundle/ConnectorBundle/EventListener/ClearBatchCacheSubscriber.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
  src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredFamilyReader.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredFamilyReaderSpec.php
  src/Pim/Component/Connector/Writer/Database/ProductModelDescendantsWriter.php
  src/Pim/Component/Connector/Writer/Database/ProductModelWriter.php
  src/Pim/Component/Connector/Writer/Database/ProductWriter.php
  src/Pim/Component/Connector/spec/Writer/Database/ProductModelDescendantsWriterSpec.php
  src/Pim/Component/Connector/spec/Writer/Database/ProductModelWriterSpec.php
  src/Pim/Component/Connector/spec/Writer/Database/ProductWriterSpec.php
Labels: to review

#7868 Add duration into the junit report of the behat
  features/Pim/Behat/Extension/PimFormatter/Output/Node/EventListener/JUnitDurationListener.php
  features/Pim/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php
  features/Pim/Behat/Extension/PimFormatter/ServiceContainer/Formatter/PimFormatterFactory.php
Labels: to review

#7877 PIM-7256: Add missing filters on product group grid
  CHANGELOG-2.0.md
  features/product-group/add_products.feature
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group/edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/grid.html
Labels: to merge

#7888 PIM-6945: Fix missing header elements on identifier attribute edit form
  CHANGELOG-2.0.md
  features/attribute/edit_identifier_attribute.feature
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/identifier/edit.yml
Labels: to review

#7881 PIM-7119: Fix missing translation on filters
  CHANGELOG-1.7.md
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.en.yml
Labels: to review

#7866 PIM-7264: Add validation on import decimal number greater than limit in MySQL
  CHANGELOG-1.7.md
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Component/Catalog/Validator/ConstraintGuesser/DecimalGuesser.php
  src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/DecimalGuesserSpec.php
Labels: to review

#7876 PIM-7257: Add missing translations in product grid
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
Labels: to review

#7879 PIM-7259: Remove only attribute's option removed for multi select attribute
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/LoadEntityWithValuesSubscriberIntegration.php
  src/Pim/Component/Catalog/Exception/InvalidOptionsException.php
  src/Pim/Component/Catalog/Factory/Value/OptionsValueFactory.php
  src/Pim/Component/Catalog/Factory/ValueCollectionFactory.php
  src/Pim/Component/Catalog/spec/Factory/Value/OptionsValueFactorySpec.php
  src/Pim/Component/Catalog/spec/Factory/ValueCollectionFactorySpec.php
Labels: to review

#7887 Merge 2.1 into 2.2
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.1.md
  CHANGELOG-2.2.md
  features/Context/FixturesContext.php
  features/Context/Page/Batch/Operation.php
  features/import/import_families.feature
  features/localization/mass-action/edit_common_attributes.feature
  features/product/filtering/filter_products_per_media.feature
  features/user/edit_user.feature
  src/Akeneo/Bundle/BatchBundle/spec/Launcher/SimpleJobLauncherSpec.php
  src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php
  src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CategoryFilter.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/translations/messages.pt_PT.yml
  src/Pim/Bundle/CatalogBundle/Version.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CategoryFilterSpec.php
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Family/UpdateFamilyIntegration.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/ConnectorBundle/tests/integration/Export/Writer/YamlWriterIntegration.php
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Pim/Bundle/DataGridBundle/spec/Extension/Formatter/Property/DateTimeWithUserTimezonePropertySpec.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
  src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.da.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.es.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fr.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.pl.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pl.yml
  src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.pl.yml
  src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Pim/Bundle/UIBundle/Resources/translations/messages.sv.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.pl.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.pt_BR.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.pt_PT.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.sv.yml
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
  src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Channel.php
  src/Pim/Component/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Pim/Component/Connector/Writer/File/Yaml/Writer.php
  src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ChannelSpec.php
  src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
Labels: to review

#7893 PIM-7263: Purging command for boolean values on variant products
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/spec/Command/RemoveWrongBooleanValuesOnVariantProductsCommandSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
Labels: to review

#7203 Fix comparators not ordered by priority
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/RegisterComparatorsPass.php
Labels: contribution, to review

#7910 Update CHANGELOG-1.7.md
  CHANGELOG-1.7.md
Labels: to review
