Repository akeneo/pim-community-dev, pull requests merged in 2018-10, with the labels that each got.

#8887 TIP-860: Fix the CI build
  CHANGELOG-3.0.md
  src/Akeneo/Channel/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/product_model.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/Tab/property.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/_scripts.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/children-tree.json.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/children.json.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/edit.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/form.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/index.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/listTree.json.twig
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/ProductModel/listCategories.json.twig
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/repositories.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/view_elements/category.yml
Labels: to review

#8918 PIM-7664: an exception is not thrown anymore when the asset cannot be loaded
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/LoadEntityWithValuesSubscriberIntegration.php
  src/Pim/Component/Catalog/Factory/Value/ValueFactoryInterface.php
  src/Pim/Component/Catalog/Factory/ValueCollectionFactory.php
  src/Pim/Component/Catalog/Factory/ValueFactory.php
  src/Pim/Component/Catalog/spec/Factory/ValueCollectionFactorySpec.php
  src/Pim/Component/Catalog/spec/Factory/ValueFactorySpec.php
  src/Pim/Component/ReferenceData/Factory/Value/ReferenceDataCollectionValueFactory.php
  src/Pim/Component/ReferenceData/spec/Factory/Value/ReferenceDataCollectionValueFactorySpec.php
Labels: to review

#8931 TIP-860: Move classes from enrich bundle to the right BC
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/File/DefaultImageProvider.php
  src/Akeneo/Pim/Enrichment/Bundle/File/DefaultImageProviderInterface.php
  src/Akeneo/Pim/Enrichment/Bundle/File/FileTypeGuesser.php
  src/Akeneo/Pim/Enrichment/Bundle/File/FileTypeGuesserInterface.php
  src/Akeneo/Pim/Enrichment/Bundle/File/FileTypes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/files.yml
  src/Akeneo/Pim/Enrichment/Bundle/spec/File/DefaultImageProviderSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/spec/File/FileTypeGuesserSpec.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Event/AttributeGroupEvents.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/SelectFamilyTypeSpec.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/JobProfileController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Event/JobInstanceEvents.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Factory/MassEditNotificationFactory.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/mail_recorder.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Test/MailRecorder.php
  src/Akeneo/Platform/Bundle/UIBundle/Flash/Message.php
  src/Akeneo/Platform/spec/Bundle/ImportExportBundle/Factory/MassEditNotificationFactorySpec.php
  src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
  src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
  src/Pim/Bundle/EnrichBundle/Event/CategoryEvents.php
  src/Pim/Bundle/EnrichBundle/EventListener/TranslateFlashMessagesSubscriber.php
  src/Pim/Bundle/EnrichBundle/spec/EventListener/TranslateFlashMessagesSubscriberSpec.php
  tests/legacy/features/Context/FeatureContext.php
Labels: to review

#8933 Merge 2.3 into master
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  src/Akeneo/Channel/Bundle/Controller/InternalApi/ChannelController.php
  src/Akeneo/Channel/Component/Normalizer/InternalApi/ChannelNormalizer.php
  src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/EventSubscriber/LoadEntityWithValuesSubscriberIntegration.php
  src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataCollectionValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ValueFactoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Factory/Value/ReferenceDataCollectionValueFactorySpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Factory/ValueCollectionFactorySpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Factory/ValueFactorySpec.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/FamilySearchableRepository.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Controller/NotificationController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Platform/spec/Bundle/NotificationBundle/Controller/NotificationControllerSpec.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/JobExecutionController.php
  src/Pim/Bundle/EnrichBundle/Normalizer/JobExecutionNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactory.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelSearchAggregator.php
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/attribute.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/last_executions.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/general/locales.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/channel/edit.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.hr_HR.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.nl_NL.yml
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/JobExecutionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactorySpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelSearchAggregatorSpec.php
  src/Pim/Bundle/EnrichBundle/tests/integration/Repository/FamilySearchableRepositoryIntegration.php
  tests/back/Channel/Specification/Component/Normalizer/InternalApi/ChannelNormalizerSpec.php
  tests/legacy/features/pim/structure/attribute/browse/filter.feature
  tests/legacy/features/pim/structure/family/browse_families.feature
Labels: to review

#8950 TIP-860: Move enrich component classes to the right BC
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/MassEditController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ValuesController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/AscendantCategories.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/InternalApi/CategoryRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/InternalApi/GroupRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/converters.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Enrichment/Bundle/spec/Doctrine/ORM/Repository/InternalApi/CategoryRepositorySpec.php
  src/Akeneo/Pim/Enrichment/Bundle/spec/Doctrine/ORM/Repository/InternalApi/GroupRepositorySpec.php
  src/Akeneo/Pim/Enrichment/Component/Category/Query/AscendantCategoriesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Converter/ConverterInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Converter/InternalApiToStandard/ValueConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Converter/MassOperationConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Converter/StandardToInternalApi/ValueConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/DeleteProductsAndProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Converter/InternalApiToStandard/ValueConverterSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Converter/StandardToInternalApi/ValueConverterSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Job/DeleteProductsAndProductModelsTaskletSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/InternalApi/ProductModelNormalizerSpec.php
  src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeGroupRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/FamilyRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/GroupTypeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AvailableAttributesType.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/entities.yml
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Repository/InternalApi/AttributeGroupRepositorySpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Repository/InternalApi/AttributeRepositorySpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Repository/InternalApi/FamilyRepositorySpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Doctrine/ORM/Repository/InternalApi/GroupTypeRepositorySpec.php
  src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AvailableAttributesTypeSpec.php
  src/Akeneo/Pim/Structure/Component/Model/AvailableAttributes.php
  src/Akeneo/Pim/Structure/Component/spec/Model/AvailableAttributesSpec.php
  src/Akeneo/Platform/Bundle/UIBundle/Form/Type/LightEntityType.php
  src/Akeneo/Platform/Bundle/UIBundle/Form/Type/ProductGridFilterChoiceType.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/TranslatedLabelsProviderInterface.php
  src/Akeneo/Platform/spec/Bundle/UIBundle/Form/Type/ProductGridFilterChoiceTypeSpec.php
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Form/Subscriber/UserPreferencesSubscriber.php
  src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
  src/Pim/Bundle/EnrichBundle/Resources/config/converters.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/entities.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Component/Enrich/Model/ChosableInterface.php
Labels: to review

#8951 PIM-7718: Fix update of family requirements for existing and non-requ…
  CHANGELOG-1.7.md
  features/family/define_the_attribute_requirement.feature
  src/Pim/Component/Catalog/Updater/FamilyUpdater.php
  src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php
Labels: to review

#8955 TIP-860: Move compiler pas to the right BC
  src/Akeneo/Pim/Enrichment/Bundle/AkeneoPimEnrichmentBundle.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/RegisterCategoryItemCounterPass.php
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterGenericProvidersPass.php
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterViewElementsPass.php
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Reference/ReferenceFactory.php
  src/Akeneo/Platform/Bundle/UIBundle/PimUIBundle.php
  src/Pim/Bundle/EnrichBundle/PimEnrichBundle.php
Labels: to review

#8956 Tip 860 enrich bundle controllers
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/MeasuresController.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Bundle/Controller/ApiClientController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/routing.yml
  src/Akeneo/UserManagement/Bundle/Resources/routing/api_connection.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/measures.yml
Labels: to review

#8962 Extra docs nanou
  .ci/Jenkinsfile
  internal_doc/REPRODUCE_CI_BUILD.md
Labels: to review

#8959 PIM-7655: Fix issue with Attribute Groups order
  .ci/Dockerfile
  .ci/Jenkinsfile
  CHANGELOG-2.0.md
  features/Context/Page/AttributeGroup/Index.php
  features/Context/WebUser.php
  features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php
  features/Pim/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
  features/attribute-group/list_attribute_groups.feature
  features/import/import_attribute_group.feature
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FindAttributeGroupOrdersEqualOrSuperiorTo.php
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-group-fetcher.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv
  src/Pim/Component/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php
  src/Pim/Component/Connector/spec/Job/EnsureConsistentAttributeGroupOrderTaskletSpec.php
Labels: to review

#8971 Merge 2.0 to 2.3
  .ci/Dockerfile
  .ci/Jenkinsfile
  CHANGELOG-2.0.md
  src/Akeneo/Bundle/MeasureBundle/Resources/translations/jsmessages.ru.yml
  src/Akeneo/Bundle/MeasureBundle/Resources/translations/messages.ru.yml
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FindAttributeGroupOrdersEqualOrSuperiorTo.php
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-group-fetcher.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv
  src/Pim/Component/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php
  src/Pim/Component/Connector/spec/Job/EnsureConsistentAttributeGroupOrderTaskletSpec.php
  tests/legacy/features/Context/Page/AttributeGroup/Index.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php
  tests/legacy/features/Pim/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
  tests/legacy/features/attribute-group/list_attribute_groups.feature
  tests/legacy/features/import/import_attribute_group.feature
Labels: to review

#8980 PIM-7694: fix null options values string casting
  CHANGELOG-2.3.md
  src/Pim/Component/Catalog/Value/OptionValue.php
  src/Pim/Component/Catalog/spec/Value/OptionValueSpec.php
Labels: bug

#8982 PIM-7731: check for attribute as label not null
  CHANGELOG-2.3.md
  src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizer.php
  src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabelValidator.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyAttributeAsLabelValidatorSpec.php
Labels: bug

#8986 PIM-7740: bump summernote version to fix scroll glitches
  CHANGELOG-2.3.md
  package.json
  tests/legacy/features/Context/Page/Base/ProductEditForm.php
Labels: bug

#8987 PIM-7727: parent filter search case insensitive
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
Labels: tech-improvement

#8878 PIM:7527 - Improve performance loading filters on the product grid
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeRepository.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
  src/Oro/Bundle/PimDataGridBundle/Controller/ProductGridController.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/ConfiguratorInterface.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/AllAttributesUseableInGridConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/SelectedAttributesConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/DependencyInjection/PimDataGridExtension.php
  src/Oro/Bundle/PimDataGridBundle/EventListener/ConfigureProductGridListener.php
  src/Oro/Bundle/PimDataGridBundle/Query/ListAttributesUseableAsColumnInProductGrid.php
  src/Oro/Bundle/PimDataGridBundle/Query/ListAttributesUseableInProductGrid.php
  src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListAttributesUseableAsColumnInProductGrid.php
  src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListAttributesUseableInProductGrid.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/configurators.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/queries.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/routing/datagrid.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/date-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_category-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-selector.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/configure-columns-action.js
  src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/AllAttributesUseableInGridConfiguratorSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/ContextConfiguratorSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/SelectedAttributesConfiguratorSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Query/Sql/ListAttributesUseableInProductGridSpec.php
  src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListAttributesUsableInProductGridIntegration.php
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_listeners.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_and_product_models.feature
Labels: to merge

#8993 PIM-7751: Fix filters "Type" and "Status" in the process tracker
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml
Labels: bug, to review

#9000 Fix clear attributes selector decorator in export builder
  features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php
Labels: tech-improvement

#8997 TIP-860: move Enrich tests
  .ci/Jenkinsfile
  app/phpunit.xml.dist
  src/Akeneo/Pim/Enrichment/Bundle/spec/Form/Subscriber/FilterLocaleValueSubscriberSpec.php
  src/Pim/Bundle/EnrichBundle/tests/Unit/Form/Subscriber/FilterLocaleValueSubscriberTest.php
  tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Counter/CountProductsPerCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/CountImpactedProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Filter/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/SearchOnAttributesAndCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Sorter/InGroupSorterIntegration.php
  tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/InternalApi/FamilySearchableRepositoryIntegration.php
  tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/InternalApi/FamilyVariantSearchableRepositoryIntegration.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/JobExecutionRepositoryIntegration.php
Labels: to review

#9006 Add docker-setup
  .gitignore
  bin/docker/pim-setup.sh
Labels: to review

#9005 Set explicit white background for light inputs
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
Labels: to review

#9002 [APAI-320] Add custom CSS for EE
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-value-purple.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-value.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/bootstrap.dropdown.less
Labels: to review

#8985 TIP-860: move general configuration outside of EnrichBundle
  app/AppKernel.php
  app/config/config.yml
  src/Akeneo/Platform/config/bundles/akeneo_api.yml
  src/Akeneo/Platform/config/bundles/akeneo_batch.yml
  src/Akeneo/Platform/config/bundles/assetic.yml
  src/Akeneo/Platform/config/bundles/doctrine.yml
  src/Akeneo/Platform/config/bundles/escape_wsse_authentication.yml
  src/Akeneo/Platform/config/bundles/fos_auth_server.yml
  src/Akeneo/Platform/config/bundles/fos_js_routing.yml
  src/Akeneo/Platform/config/bundles/fos_rest.yml
  src/Akeneo/Platform/config/bundles/gedmo_doctrine_extensions.yml
  src/Akeneo/Platform/config/bundles/liip_imagine.yml
  src/Akeneo/Platform/config/bundles/oneup_flysystem.yml
  src/Akeneo/Platform/config/bundles/oro_filter.yml
  src/Akeneo/Platform/config/bundles/oro_translation.yml
  src/Akeneo/Platform/config/bundles/pim_user.yml
  src/Akeneo/Platform/config/bundles/twig.yml
  src/Akeneo/Platform/config/pim.yml
Labels: to review

#8963 PIM-7527: Add paginated column selector
  composer.lock
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less
  src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListAttributesUseableInProductGrid.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml
  tests/legacy/features/Context/Page/Element/ConfigurationPopin.php
Labels: to review

#9004 Fix forgotten bc-break to manage
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MediaValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ScalarValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ValueFactoryInterface.php
Labels: to review

#9028 TIP-860: remove enrich bundle
  CHANGELOG-3.0.md
  app/AppKernel.php
  bin/check-pullup
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/twig.yml
  src/Akeneo/Platform/config/bundles/assetic.yml
  src/Akeneo/Platform/config/pim.yml
  src/Pim/Bundle/EnrichBundle/DependencyInjection/Configuration.php
  src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
  src/Pim/Bundle/EnrichBundle/PimEnrichBundle.php
  src/Pim/Bundle/EnrichBundle/Resources/config/colors.yml
Labels: to review

#9007 APAI-318: add validation error BEM element for dropdown
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/red_arrow.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less
Labels: to review

#9044 APAI-306: Fix robot icon position in list
  composer.lock
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#9050 APAI-303: Allow next button to hide on mass edit
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/MessageBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
Labels: to review

#9054 APAI-306: Add family attribute mapping status container
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Labels: to review
