Repository akeneo/pim-community-dev, pull requests merged in 2018-04, with the labels that each got.

#7922 Master branch is future 3.0
  composer.json
Labels: to review

#7923 Prepare 2.3 branch
  .ci/Jenkinsfile
  CHANGELOG-2.3.md
  README.md
  composer.json
  src/Pim/Bundle/CatalogBundle/Version.php
  upgrades/2.1-2.2/Version_2_2_20180201155905_add_phone_on_user.php
  upgrades/2.1-2.2/Version_2_2_20180228120422.php
  upgrades/2.1-2.2/Version_2_2_20180308081108_add_user_timezone.php
  upgrades/2.1-2.2/Version_2_2_20180320093100_remove_product_type.php
  upgrades/2.1-2.2/Version_2_2_20180321135455_product_model_export_job_parameters.php
  upgrades/2.1-2.2/Version_2_2_20180321164023_index_products_and_product_models.php
Labels: to review

#7926 Merge branch '1.6' into branch '1.7'
  CHANGELOG-1.6.md
Labels: to merge

#7903 PIM-6962 : Fix breadcrumb links after the save on edit page.
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/common/breadcrumbs.js
Labels: to review

#7907 TIP-850: Define coupling detector rules
  .php_cd_v3.php
  composer.json
Labels: to review

#7895 Use native docker .env and override feature instead of docker-compose.yml.dist
  .env.dist
  .gitignore
  docker-compose.yml
Labels: POC, tech-improvement, wip

#7920 Merge 1.7 into 2.0
  CHANGELOG-1.7.md
  features/mass-action/mass_delete_products_and_product_models.feature
  features/mass-action/mass_edit_many_products_at_once.feature
  features/mass-action/quick_export_products_and_product_models.feature
  features/product-model/remove.feature
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/LargeAndOrderedListProductModelIntegration.php
  src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/RegisterComparatorsPass.php
  src/Pim/Bundle/CatalogBundle/Resources/config/cursors.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ChannelController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/GroupController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/MediaController.php
  src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductCommentController.php
  src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.pl.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.ca.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.da.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.de.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.es.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.hr.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.it.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.ja.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.nl.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.pt_BR.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.pt_PT.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.ru.yml
  src/Pim/Bundle/FilterBundle/Resources/translations/messages.zh.yml
  src/Pim/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml
  src/Pim/Bundle/UserBundle/Resources/translations/messages.fr.yml
  src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
  src/Pim/Component/Catalog/Validator/ConstraintGuesser/DecimalGuesser.php
  src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/DecimalGuesserSpec.php
Labels: core-team

#7787 TIP-835: Introduce acceptance tests with cucumber, puppeteer and gherkin
  .ci/Jenkinsfile
  .eslintrc
  .gitignore
  docker-compose.yml.dist
  package.json
  src/Pim/Bundle/EnrichBundle/Controller/Rest/FormExtensionController.php
  src/Pim/Bundle/EnrichBundle/Provider/FormExtensionProvider.php
  src/Pim/Bundle/InstallerBundle/Command/DumpExtensionsCommand.php
  tests/features/volume-monitoring/monitor_attribute_per_family_volume.feature
  tests/front/WRITING-FRONT-TESTS.md
  tests/front/acceptance/cucumber/factory/association-type.js
  tests/front/acceptance/cucumber/factory/channel.js
  tests/front/acceptance/cucumber/factory/locale.js
  tests/front/acceptance/cucumber/factory/product.js
  tests/front/acceptance/cucumber/factory/user.js
  tests/front/acceptance/cucumber/step-definitions/page.js
  tests/front/acceptance/cucumber/step-definitions/structure/locales.js
  tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
  tests/front/acceptance/cucumber/tools.js
  tests/front/acceptance/cucumber/world.js
  webpack-test.config.js
  webpack/test/acceptance/generate-report.js
  webpack/test/acceptance/run-steps.js
  webpack/test/templates/index.html
  webpack/test/templates/index.js
Labels: to merge

#7908 Add typescript
  package.json
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.ts
  tsconfig.json
  webpack.config.js
Labels: to review

#7911 PIM-7260: Add validation in the 'configure' step of mass edits
  CHANGELOG-2.0.md
  features/mass-action/edit_common_attributes.feature
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/add-to-existing-product-model.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/add-to-group.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/category.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/product/category.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/EnrichBundle/Twig/CategoryExtension.php
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less
Labels: to review

#7928 PIM-7263: extract command's logic into a dedicated service
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongBooleanValuesOnVariantProductCleaner.php
  src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/CatalogBundle/spec/Command/Cleaner/WrongBooleanValuesOnVariantProductCleanerSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Command/RemoveWrongBooleanValuesOnVariantProductsCommandSpec.php
Labels: to review

#7913 PIM-6999: Fix flash message on edit user
  CHANGELOG-2.0.md
  src/Oro/Bundle/UserBundle/Controller/UserController.php
  src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
Labels: to review

#7912 PIM-6993: Fix to add pagination in list of users in group and roles
  CHANGELOG-2.0.md
  features/Context/FixturesContext.php
  features/Pim/Behat/Context/Domain/Enrich/GridPaginationContext.php
  features/Pim/Behat/Decorator/Grid/PaginationDecorator.php
  features/user/edit_user_group_and_role_assignations.feature
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
  src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml
Labels: to review

#7949 Poc baseform
  CHANGELOG-2.3.md
  package.json
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/copy.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/complete-variant-product.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/sequential-edit.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base-interface.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base.ts
  tsconfig.json
  webpack.config.js
Labels: to review

#7848 GITHUB-7750: Mass edit family : Fix warning message instead of fatal errors when we have violations
  CHANGELOG-1.7.md
  src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/MassEdit/Family/SetAttributeRequirementsSpec.php
Labels: to review

#7959 Add symlink support for typescript
  .prettierrc.json
  src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base.ts
  webpack.config.js
Labels: to review

#7962 PIM-7282 : Add validator on the code attribute value
  CHANGELOG-2.0.md
  features/attribute/create_text_attribute.feature
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
Labels: to review

#7853 Less UI in Behat imports
  .ci/behat.enterprise.yml
  features/Pim/Behat/Context/ImportFileContext.php
  features/family/remove_attribute_from_a_family.feature
  features/import/attribute/import_attributes.feature
  features/import/family_variant/csv/create_family_variant.feature
  features/import/family_variant/xlsx/create_family_variant.feature
  features/import/import_association_types.feature
  features/import/import_attribute_group.feature
  features/import/import_categories.feature
  features/import/import_channels.feature
  features/import/import_families.feature
  features/import/import_group_types.feature
  features/import/import_locales.feature
  features/import/import_options.feature
  features/import/product/import_partial_products.feature
  features/import/product/import_products_with_associations.feature
  features/import/product/import_products_with_media.feature
  features/import/product/import_products_with_optional_values.feature
  features/import/product/import_products_with_product_model_associations.feature
  features/import/product/xlsx/import_products.feature
  features/import/product_model/csv/create_product_model.feature
  features/import/product_model/xlsx/create_product_model.feature
  features/import/variant_product/convert_product_to_variant_product_by_import.feature
  features/import/variant_product/csv/import_variant_products.feature
  features/import/variant_product/import_business_rules.feature
  features/import/variant_product/xlsx/import_variant_products.feature
  features/import/xlsx/import_attribute_group.feature
  features/import/xlsx/import_channels.feature
  features/import/xlsx/import_currencies.feature
  features/import/xlsx/import_group_types.feature
  features/import/xlsx/import_locales.feature
Labels: to review

#7978 PIM-7282 : Fix changelog
  CHANGELOG-2.0.md
Labels: to review

#7977 Use native docker .env and override feature instead of docker-compose.yml.dist
  .env.dist
  .gitignore
  docker-compose.yml
Labels: to review

#7976 PIM-7043 : Fix to add the last page into the pagination only if the total records is under 10000.
  .ci/Jenkinsfile
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/pagination-input.js
Labels: to review

#7740 PIM-7211: Add catalog volume monitoring screen
  .ci/Jenkinsfile
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/catalog_volume/index.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/catalog_volume.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/catalog-volume.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base-interface.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/average-max.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/header.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/number.html
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/section.html
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
  src/Pim/Bundle/UIBundle/Resources/config/assets.yml
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-add-attribute.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-attribute.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-info.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-locale.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-shop.svg
  src/Pim/Bundle/UIBundle/Resources/public/images/icon-tag.svg
  src/Pim/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
  src/Pim/Bundle/UIBundle/Resources/public/less/components/Widget.less
  tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
  tests/front/acceptance/cucumber/tools.js
  tests/front/acceptance/cucumber/world.js
  webpack.config.js
Labels: to merge

#7988 PIM-7211: Fix typescript issues
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/catalog-volume.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base-interface.ts
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/section.html
  src/Pim/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
  webpack-test.config.js
Labels: to merge

#7986 Introduce the AssociationAwareInterface
  CHANGELOG-2.3.md
  features/Context/FixturesContext.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AssociationTypeRepository.php
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductAssociation.orm.yml
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductNormalizerSpec.php
  src/Pim/Component/Catalog/Builder/ProductBuilder.php
  src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
  src/Pim/Component/Catalog/Model/AbstractAssociation.php
  src/Pim/Component/Catalog/Model/AssociationAwareInterface.php
  src/Pim/Component/Catalog/Model/AssociationInterface.php
  src/Pim/Component/Catalog/Model/ProductAssociation.php
  src/Pim/Component/Catalog/Model/ProductAssociationInterface.php
  src/Pim/Component/Catalog/Model/ProductInterface.php
  src/Pim/Component/Catalog/Repository/AssociationTypeRepositoryInterface.php
  src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
  src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
  src/Pim/Component/Catalog/spec/Model/ProductSpec.php
  src/Pim/Component/Connector/spec/Writer/Database/ProductAssociationWriterSpec.php
Labels: core-team

#7679 PIM-7216: Resolve target discriminator map for products
  CHANGELOG-2.0.md
  src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/MappingsOverrideConfigurator.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ResolveTargetDiscriminatorMapForProductSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/AbstractProduct.orm.yml
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/ResolveTargetDiscriminatorMapForProductSubscriberSpec.php
Labels: to review

#7982 PIM-7299: Add pagination for family variants on several screens
  CHANGELOG-2.0.md
  features/Context/Page/Base/Form.php
  features/Context/WebUser.php
  features/category/display_category_history.feature
  features/family/list_family_variant.feature
  features/family/remove_attribute_from_a_family.feature
  features/product-model/create_product_model.feature
  src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyVariantController.php
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilyVariantSearchableRepository.php
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/add_to_existing_product_model.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/create.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/routing/family_variant.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/creation/variant.js
Labels: bug

#8000 Add phpspec suite for acceptance tests
  phpspec.yml.dist
Labels: to review

#8001 In memory repos about family and family variant and product and product models
  tests/back/Acceptance/Family/InMemoryFamilyRepository.php
  tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantRepository.php
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php
  tests/back/Acceptance/Resources/config/pim/repositories.yml
  tests/back/Acceptance/spec/Family/InMemoryFamilyRepositorySpec.php
  tests/back/Acceptance/spec/FamilyVariant/InMemoryFamilyVariantRepositorySpec.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
  tests/back/Acceptance/spec/ProductModel/InMemoryProductModelRepositorySpec.php
Labels: to review

#8003 Add an in memory attribute related repository
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/AttributeGroup/InMemoryAttributeGroupRepository.php
  tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
  tests/back/Acceptance/Resources/config/pim/repositories.yml
  tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
  tests/back/Acceptance/spec/AttributeGroup/InMemoryAttributeGroupRepositorySpec.php
  tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
Labels: to review

#7968 PIM-7284: be able to mass edit status of product models
  CHANGELOG-2.3.md
  features/mass-action/mass_edit_products_and_product_models.feature
  features/mass-action/mass_update_product_models_status.feature
  src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
Labels: to review

#7999 PIM-7043
  CHANGELOG-2.0.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/pagination-input.js
Labels: to review

#7990 PIM-7304 : Fix the SKU filter to be able to be scrollable
  CHANGELOG-2.0.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#7998 [SLA] PIM-7313: prevent the same job to be executed by two different daemons due to race condition
  CHANGELOG-2.0.md
  src/Akeneo/Bundle/BatchQueueBundle/Queue/DatabaseJobExecutionQueue.php
  src/Akeneo/Bundle/BatchQueueBundle/Queue/JobExecutionMessageRepository.php
  src/Akeneo/Bundle/BatchQueueBundle/spec/Queue/DatabaseJobExecutionQueueSpec.php
Labels: to review

#8010 Mutualize builders for integration and acceptance tests
  composer.json
  tests/back/Acceptance/Channel/ChannelContext.php
  tests/back/Acceptance/Locale/LocaleContext.php
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Common/Builder/EntityBuilder.php
  tests/back/Common/Builder/EntityWithValue/Association.php
  tests/back/Common/Builder/EntityWithValue/Builder/Product.php
  tests/back/Common/Builder/EntityWithValue/Builder/ProductModel.php
  tests/back/Common/Builder/EntityWithValue/Code.php
  tests/back/Common/Builder/EntityWithValue/ListOfCodes.php
  tests/back/Common/Builder/EntityWithValue/ListOfValues.php
  tests/back/Common/Builder/EntityWithValue/Status.php
  tests/back/Common/Builder/EntityWithValue/Value.php
  tests/back/Integration/AppKernelTest.php
  tests/back/Integration/IntegrationTestsBundle/Fixture/EntityBuilder.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
Labels: to review

#8007 Run legacy & acceptance tests on CI
  .ci/Jenkinsfile
  .ci/behat.community.yml
  .ci/behat.enterprise.yml
  behat.yml.dist
Labels: to review

#7179 Add index_hosts to the incenteev parameters.
  composer.json
Labels: contribution, to review

#8034 Update CHANGELOG-2.0.md
  CHANGELOG-2.0.md
Labels: to review

#7989 PIM-7296: Allow to change the parent of a variant product
  .ci/behat.community.yml
  .ci/behat.enterprise.yml
  CHANGELOG-2.3.md
  behat.yml.dist
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateVariantProductIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateVariantProductIntegration.php
  src/Pim/Component/Catalog/Updater/Setter/ParentFieldSetter.php
  src/Pim/Component/Catalog/spec/Updater/Setter/ParentFieldSetterSpec.php
  tests/legacy/features/Pim/Behat/Context/Domain/Enrich/VariantProductContext.php
  tests/legacy/features/Pim/Behat/Context/Storage/ProductModelStorage.php
  tests/legacy/features/Pim/Behat/Context/Storage/ProductStorage.php
  tests/legacy/features/product/variant/change_parent.feature
Labels: to review

#8043 PIM-7329: Revert "PIM-7264"
  features/import/product_model/import_business_rules.feature
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Component/Catalog/Validator/ConstraintGuesser/DecimalGuesser.php
  src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/DecimalGuesserSpec.php
Labels: to review

#8046 Merge branch '2.0' into branch '2.2'
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
  src/Pim/Component/Catalog/Validator/ConstraintGuesser/DecimalGuesser.php
  src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/DecimalGuesserSpec.php
Labels: to review

#8041 Documentation: Broken links on README.md
  README.md
Labels: contribution, to review

#7994 Add associations to product models
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
  src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php
  src/Pim/Bundle/CatalogBundle/Resources/config/associations.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductModel.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductModelAssociation.orm.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
  src/Pim/Component/Catalog/Association/AssociationClassResolver.php
  src/Pim/Component/Catalog/Association/MissingAssociationAdder.php
  src/Pim/Component/Catalog/Builder/ProductBuilder.php
  src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
  src/Pim/Component/Catalog/Model/AbstractProduct.php
  src/Pim/Component/Catalog/Model/AssociationAwareInterface.php
  src/Pim/Component/Catalog/Model/ProductModel.php
  src/Pim/Component/Catalog/Model/ProductModelAssociation.php
  src/Pim/Component/Catalog/Model/ProductModelAssociationInterface.php
  src/Pim/Component/Catalog/Model/ProductModelInterface.php
  src/Pim/Component/Catalog/Normalizer/Standard/Product/AssociationsNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Standard/ProductModelNormalizer.php
  src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
  src/Pim/Component/Catalog/spec/Association/AssociationClassResolverSpec.php
  src/Pim/Component/Catalog/spec/Association/MissingAssociationAdderSpec.php
  src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
  src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModel.php
  src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModelAssociation.php
  src/Pim/Component/Connector/Processor/Denormalization/ProductModelAssociationProcessor.php
  src/Pim/Component/Connector/Processor/Denormalization/ProductModelProcessor.php
  src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductModelAssociationSpec.php
  src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductModelSpec.php
  src/Pim/Component/Connector/spec/Processor/Denormalization/ProductModelAssociationProcessorSpec.php
  tests/legacy/features/Context/FixturesContext.php
  tests/legacy/features/import/product_model/import_with_associations.feature
Labels: to review

#8035 PIM-7310 : Fix completeness in rule's conditions
  .ci/behat.enterprise.yml
  CHANGELOG-2.2.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CompletenessFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CompletenessFilterSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/CompletenessFilterIntegration.php
Labels: to review

#8045 PIM-7328: Fix indexation of very large texts
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php
  src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Attribute/TextAreaFilterSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/PimCatalogTextAreaIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/TestData/VeryLongText.php
Labels: to review

#7579 Partially revert 1b22956abf7bb8b79b5e24510f6824c7a83938b3.
  src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
Labels: contribution, to review

#8055 Make puppeteer in frontend acceptance tests more stable
  tests/front/acceptance/cucumber/world.js
Labels: to review

#8056 PIM-7331: Simplify getRawFilters method to avoid calling useless stuff
  src/Pim/Bundle/DataGridBundle/Extension/MassAction/MassActionDispatcher.php
  src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
Labels: to review

#7981 TIP-838: Move user classes to security bundle or the right bundle
  CHANGELOG-3.0.md
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/RemoveProductModelIntegration.php
  src/Pim/Bundle/UserBundle/Form/Type/UserType.php
  src/Pim/Bundle/UserBundle/Resources/config/form_types.yml
  src/Pim/Component/User/Model/User.php
  src/Pim/Component/User/Model/UserInterface.php
  src/Pim/Component/User/Updater/UserUpdater.php
Labels: to review
