Repository akeneo/pim-community-dev, pull requests merged in 2018-11, with the labels that each got.

#9047 TIP-860: Move the last enrichment integration tests to test folder
  .ci/Jenkinsfile
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/LargeAndOrderedListProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Structure/Integration/AttributeGroup/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
Labels: to review

#9063 Merge 1.7 into 2.0
  CHANGELOG-1.7.md
  features/family/define_the_attribute_requirement.feature
  src/Pim/Bundle/ApiBundle/Resources/translations/messages.ru.yml
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.ru.yml
Labels: to review

#9076 TIP-892: Fix Typo
  UPGRADE.md
Labels: to review

#9031 PIM-7757: Reduce a lot the risk of inserting duplicate completenesses.
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductSaverSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessCommandIntegration.php
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
  src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/Model/AbstractCompleteness.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php
Labels: to review

#9078 Merge 2.0 into 2.3
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  composer.lock
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php
  src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductSaverSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessCommandIntegration.php
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
  src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
  src/Pim/Component/Catalog/Manager/CompletenessManager.php
  src/Pim/Component/Catalog/Model/AbstractCompleteness.php
  src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php
  tests/legacy/features/family/define_the_attribute_requirement.feature
Labels: to review

#9081 Remove deprecation notice on CompletenessRemover
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
Labels: to review

#9083 Merge 2.0 into 2.3
  src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
Labels: to merge

#9079 Merge 2.3 into master
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  composer.lock
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGenerator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGeneratorInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Manager/CompletenessManager.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractCompleteness.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/AttributeDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/catalog_volume/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/header.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/section.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/catalog-volume/average-max.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/catalog-volume/number.html
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
  tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/CompletenessGeneratorSpec.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/AttributeDataCollectorSpec.php
  tests/legacy/features/pim/structure/family/define_the_attribute_requirement.feature
Labels: to review

#9087 Fix drag'n'drop of huge attribute group in family variant
  CHANGELOG-2.3.md
  composer.lock
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js
Labels: to review

#9080 PIM-7767: Remove options values label from versioning
  CHANGELOG-2.3.md
  src/Pim/Bundle/VersioningBundle/Normalizer/Flat/AttributeNormalizer.php
  src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeNormalizerSpec.php
  src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php
Labels: to review

#9086 Remove deprecated methods from completeness manager and generator
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/managers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/readers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGenerator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGeneratorInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Manager/CompletenessManager.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/CompletenessGeneratorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/ProductReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Manager/CompletenessManagerSpec.php
Labels: to review

#9091 PIM-7783: Fix constraint on attribute name
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Validation/Attribute/GlobalConstraintsIntegration.php
Labels: to review

#9103 Merge 17 into 20
  CHANGELOG-1.7.md
Labels: to review

#9094 PIM-7823: Fix product gap between product grid and sequential edit when selecting `All` option
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builder.yml
  src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
Labels: to review

#9082 TIP-892: Fix changelog
  CHANGELOG-3.0.md
  UPGRADE.md
Labels: to review

#9090 PIM-7824: Fix the option filter
  CHANGELOG-2.3.md
  src/Pim/Bundle/FilterBundle/Filter/ProductValue/ChoiceFilter.php
  src/Pim/Bundle/FilterBundle/Resources/config/filters.yml
  src/Pim/Bundle/FilterBundle/spec/Filter/ProductValue/ChoiceFilterSpec.php
  src/Pim/Bundle/ReferenceDataBundle/DataGrid/Filter/ReferenceDataFilter.php
  src/Pim/Bundle/ReferenceDataBundle/Resources/config/datagrid/filters.yml
Labels: to review

#9115 Merge 2.3 into master
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/product.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  src/Akeneo/Pim/Structure/Component/Normalizer/Versioning/AttributeNormalizer.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/SystemInfoController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/datagrid/action/toggle-product-action.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/date-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/date-filter.html
  tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/Versioning/AttributeNormalizerSpec.php
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_channel.feature
Labels: to review

#9136 Do not generate an id if the product already has one in InMemoryProductRepository::save()
  tests/back/Acceptance/Product/InMemoryProductRepository.php
Labels: to review

#9093 TIP-897: Enable coupling php detector for structure bounded context
  .ci/Jenkinsfile
  CHANGELOG-3.0.md
  UPGRADE.md
  src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamilyVariant/KeepOnlyValuesForVariation.php
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Saver/FamilySaver.php
  src/Akeneo/Pim/Structure/Bundle/EventListener/AttributeOptionRemovalSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Structure/Component/Model/AttributeRequirement.php
  src/Akeneo/Pim/Structure/Component/Model/CommonAttributeCollection.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/AttributeGroupNormalizer.php
  src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/GroupTypeNormalizer.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AssociationTypeNormalizer.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeGroupNormalizer.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeNormalizer.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/GroupTypeNormalizer.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/ImmutableVariantAxesValidator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/CheckAttributeEditableSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/EntityWithFamilyVariantAttributesProviderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/KeepOnlyValuesForVariationSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductModelAttributeFilterSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Doctrine/ORM/Saver/FamilySaverSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/CommonAttributeCollectionSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php
Labels: to review

#9128 TIP-888: fix order of upgrade information
  UPGRADE.md
Labels: to review

#9145 PIM-7865: Improve performances on Product model export
  CHANGELOG-2.3.md
  src/Pim/Component/Catalog/Model/AbstractProduct.php
  src/Pim/Component/Catalog/Model/ProductModel.php
  src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
Labels: to review

#9143 TIP-888: Prepare standard for 3.0
  UPGRADE.md
  src/Akeneo/UserManagement/Bundle/Form/Handler/ResetHandler.php
Labels: to review

#9135 TIP-897: Redesign user model to allow extension
  CHANGELOG-3.0.md
  bin/check-pullup
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
  src/Akeneo/UserManagement/Bundle/Context/UserContext.php
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml
  src/Akeneo/UserManagement/Component/Factory/DefaultProperty.php
  src/Akeneo/UserManagement/Component/Factory/SimpleDefaultProperty.php
  src/Akeneo/UserManagement/Component/Factory/UserFactory.php
  src/Akeneo/UserManagement/Component/Model/User.php
  src/Akeneo/UserManagement/Component/Model/UserInterface.php
  src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  tests/back/UserManagement/Specification/Component/Factory/SimpleDefaultPropertySpec.php
  tests/back/UserManagement/Specification/Component/Factory/UserFactorySpec.php
  tests/back/UserManagement/Specification/Component/Model/UserSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Updater/UserUpdaterSpec.php
Labels: to review

#9150 Change `filterOnlyExistingOptions` visibility
  src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/ChoiceFilter.php
Labels: tech-improvement

#9163 TIP-896: coupling rules for enrichment
  Makefile
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Form/Type/GroupType.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php
Labels: to review

#9166 PIM-7885: Allow "0" for non decimal metric value
  CHANGELOG-2.3.md
  src/Pim/Component/Catalog/Normalizer/Standard/Product/MetricNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/MetricNormalizerSpec.php
Labels: bug, to review

#9168 Sort form extensions pass
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
Labels: to review

#9170 Migrate users
  upgrades/schema/Version_3_0_20181128084612_migrate_users.php
Labels: to review

#9140 PIM-7855: Optional attributes are added when family column is not in the imported product file
  CHANGELOG-2.0.md
  features/Context/FixturesContext.php
  features/export/export_products.feature
  features/import/product/import_products_with_optional_values.feature
  features/localization/export/export_products_with_date.feature
  features/localization/export/export_products_with_decimal.feature
  features/mass-action/edit_common_attributes_channel.feature
  features/product/remove_attributes_from_product.feature
  features/reference-data/export/export_products_with_reference_data.feature
  features/reference-data/product/display_reference_data_in_the_grid.feature
  features/reference-data/product/sorting/sort_products_per_reference_data.feature
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/RemoveOptionalAttributeIntegration.php
  src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
  src/Pim/Component/Connector/spec/Processor/Denormalization/ProductProcessorSpec.php
Labels: to review

#9165 Add illustration for reference entities
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/Records.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/Reference-entities.svg
Labels: to review
