Repository akeneo/pim-community-dev, pull requests merged in 2019-07, with the labels that each got.

#10303 PIM-8480: Remove the job execution message orphans after a job execution purge
  CHANGELOG-2.3.md
  src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
  src/Akeneo/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
  src/Akeneo/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php
Labels: to review

#10313 PULLUP: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
  src/Akeneo/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
Labels: PULLUP

#10315 PULLUP: Merge 3.0 into 3.1
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  src/Akeneo/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
  src/Akeneo/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/upload-launch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterChoice.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/summernote.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/FullPage.less
  src/Akeneo/Tool/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/metric-filter.html
Labels: PULLUP

#10091 Add required extensions to composer.json
  composer.json
  src/Akeneo/Platform/CommunityRequirements.php
Labels: tech-improvement

#10323 PIM-7935: Close variant select dropdowns on page navigation
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
Labels: to merge

#10331 PIM-8441: Fix badge positioning on PM dropdowns
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
Labels: to merge

#10335 DAPI-333: Add separated suffix to AknButton
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
Labels: to review

#10353 PULLUP: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.da_DK.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.es_ES.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.it_IT.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/init-layout.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/translations/messages.da_DK.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/messages.pt_BR.yml
  src/Oro/Bundle/PimFilterBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Oro/Bundle/PimFilterBundle/Resources/translations/messages.fr_FR.yml
  src/Oro/Bundle/UserBundle/Controller/UserController.php
  src/Oro/Bundle/UserBundle/Exception/UserCannotBeDeletedException.php
Labels: PULLUP

#10363 Simplify behat configuration
  behat.yml.dist
Labels: to review

#10376 PIM-8556: remove single asset link attribute type
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
Labels: to review

#10340 PIM-8484: Show flash message instead of deprecated modal on deletion
  CHANGELOG-2.3.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  tests/legacy/features/family/delete_family.feature
Labels: to review

#10414 PIM-8570: Fix category tree display
  CHANGELOG-2.3.md
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
Labels: to review

#10366 Extract push job to queue logic into a dedicated service
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Command/PublishJobToQueueCommandSpec.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
Labels: to review

#10410 TIP-1192 Clean Community edition
  app/config/config_behat.yml
  app/config/config_test.yml
  app/config/pim_parameters.yml
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
Labels: to review

#10432 TIP-901: update dependencies
  app/AppKernel.php
  app/config/routing.yml
  composer.json
  composer.lock
  src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
  src/Akeneo/UserManagement/Bundle/Controller/RoleController.php
Labels: towards SF4

#10420 PULLUP: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/ListMeasureFamilyEndToEnd.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  tests/legacy/features/pim/structure/family/delete_family.feature
Labels: PULLUP

#10440 PULLUP: Merge 3.0 into 3.1
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/ListMeasureFamilyEndToEnd.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php
  tests/legacy/features/pim/structure/family/delete_family.feature
Labels: PULLUP

#10443 TIP-901: Remove duplicated keys in YAML files
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_group.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
Labels: to review, towards SF4

#10459 TIP-901: make controllers public
  src/Akeneo/Channel/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Oro/Bundle/ConfigBundle/Resources/config/controllers.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
Labels: to review, towards SF4

#10455 Add logs to orphan archives removal
  upgrades/schema/remove_orphan_archives.php
Labels: to review

#10460 TIP-1193 Use the latest 'symfony' way to load env vars
  .circleci/config.yml
  .env.behat
  .env.dist
  app/bootstrap.php
  bin/console
  docker-compose.yml
  docker/akeneo-behat.conf
  docker/akeneo.conf
  web/app.php
  web/app_behat.php
  web/app_dev.php
  web/app_test.php
  web/install.php
Labels: to review

#10465 TIP-901: Small fixes to ease SF4 support
  app/config/security.yml
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php
  src/Akeneo/Channel/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/ProductModelNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/JobProfileController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/EventListener/TranslateFlashMessagesSubscriber.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml
  src/Oro/Bundle/FilterBundle/Form/Type/Filter/FilterType.php
  src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/ProductModelNormalizerSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/EventListener/TranslateFlashMessagesSubscriberSpec.php
Labels: to review, towards SF4

#10471 Merge feature branch raccoon into 3.2
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Command/PublishJobToQueueCommandSpec.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
Labels: to review

#10431 TIP-901: no direct access to container
  CHANGELOG-4.0.md
  UPGRADE.md
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/LoadEntityWithValuesSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/fixture_loader.yml
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/TableNameBuilder.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/AddVersionListener.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/event_subscribers.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/EventSubscriber/AddVersionListenerSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/EventSubscriber/AddVersionSubscriberSpec.php
  src/Akeneo/UserManagement/Bundle/EventListener/UserPreferencesListener.php
  src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
  src/Oro/Bundle/DataGridBundle/Datagrid/Manager.php
  src/Oro/Bundle/DataGridBundle/Datagrid/MetadataParser.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/Actions/Ajax/DeleteMassAction.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/Actions/Widget/WindowMassAction.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/DeleteMassActionHandler.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionDispatcher.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionHandlerInterface.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionMediator.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionMediatorInterface.php
  src/Oro/Bundle/DataGridBundle/Resources/config/mass_actions.yml
  src/Oro/Bundle/DataGridBundle/Resources/config/services.yml
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/Handler/DeleteProductsMassActionHandler.php
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/Handler/ExportMassActionHandler.php
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/Handler/SequentialEditActionHandler.php
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/Util/ProductFieldsBuilder.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/twig.yml
  src/Oro/Bundle/PimDataGridBundle/Twig/FilterExtension.php
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/Handler/DeleteProductsMassActionHandlerSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/Handler/ExportMassActionHandlerSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/Util/ProductFieldsBuilderSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Twig/FilterExtensionSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/LoadEntityWithValuesSubscriberSpec.php
  tests/back/UserManagement/Specification/Bundle/EventListener/UserPreferencesListenerSpec.php
Labels: towards SF4

#10497 TIP-1193 Run behat on the right env using makefile
  .circleci/config.yml
  Makefile
Labels: to review

#10483 TIP-1192 Make the symfony kernel compatible with SF4
  app/AppKernel.php
  app/bundles.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/routing_dev.yml
  composer.json
  composer.lock
  tests/back/Integration/AppKernelTest.php
Labels: to review, towards SF4

#10491 TIP-1192 Remove useless files
  .php_cd.php
  app/AppCache.php
  app/autoload.php
  composer.json
Labels: to review
