Repository akeneo/pim-community-dev, pull requests merged in 2019-03, with the labels that each got.

#9646 DAPI-22: Add sticky Modifier and Element on HorizontalNavtab style
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/HorizontalNavtab.less
Labels: to review

#9560 TIP-1048: Upgrade all Doctrine packages
  composer.json
  composer.lock
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeOptionSearchableRepository.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeGroupUpdateGuesserSpec.php
  tests/back/UserManagement/Specification/Bundle/EventListener/UserPreferencesSubscriberSpec.php
Labels: to review

#9685 Move migration scripts for 2.3 to 3.0
  upgrades/2.3-3.0/Version_3_0_20180131154710_add_role_user_if_needed.php
  upgrades/2.3-3.0/Version_3_0_20180716083150_add_index_category.php
  upgrades/2.3-3.0/Version_3_0_20180717082451_add_file_info_to_user.php
  upgrades/2.3-3.0/Version_3_0_20180717082452_migrate_avatars.php
  upgrades/2.3-3.0/Version_3_0_20180823184342_switch_to_utf8mb4.php
  upgrades/2.3-3.0/Version_3_0_20181030150153_update_versioning_entities.php
  upgrades/2.3-3.0/Version_3_0_20181128084612_migrate_users.php
  upgrades/2.3-3.0/Version_3_0_20181205151719_add_configuration_table.php
  upgrades/2.3-3.0/Version_3_0_20181227141616_remove_birthdate.php
  upgrades/2.3-3.0/es_20190128110000_ce_update_document_type_product_and_product_model.php
Labels: to review

#9679 DAPI-61: Improve proposals datagrid performances
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Structure/Bundle/Twig/AttributeExtension.php
  tests/back/Pim/Structure/Specification/Bundle/Twig/AttributeExtensionSpec.php
Labels: to review

#9705 Merge 2.3 into 3.0
  .circleci/config.yml
  .circleci/docker-compose.override.yml.dist
  .circleci/find_phpunit.sh
  .circleci/run_behat.sh
  .circleci/run_phpunit.sh
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  Makefile
  bin/docker/pim-dependencies.sh
  bin/docker/pim-front.sh
  bin/docker/pim-initialize.sh
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AssociationTypeController.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content/structure/attributes-selector.html
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Command/ResetIndexesCommandSpec.php
  tests/legacy/features/Behat/Extension/PimFormatter/Output/Node/EventListener/PimFeatureElementListener.php
  tests/legacy/features/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php
Labels: PULLUP

#9707 PIM-8189: Fix display of new patch availability on dashboard
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig
Labels: to review

#9711 PIM-8195: Fix JS error on catalog volume monitoring screen
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/header.ts
Labels: to review

#9710 TIP-1071: Upgrade webpack, TS, jest, babel
  .eslintignore
  frontend/build/check-dependencies.js
  frontend/webpack/config-loader.js
  package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-dialog.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  tests/front/unit/jest/unit.jest.js
  webpack-test.config.js
  webpack.config.js
  yarn.lock
Labels: to merge

#9701 DAPI-29: Add loadingMask Element to ProjectWidget styles
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less
Labels: to review

#9677 Improve makefile
  .circleci/docker-compose.override.yml.dist
  Makefile
  docker-compose.override.yml.dist
  docker-compose.yml
  make-file/channel.mk
  make-file/enrichment.mk
  make-file/structure.mk
  make-file/user-management.mk
Labels: to review

#9690 Use the power of makefile to install the pim assets
  Makefile
Labels: to review

#9773 PIM-8136: Fix display order of datepicker
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/dropdown.less
Labels: to merge

#9764 PIM-8128: Fix the display of reset password confirmation message
  CHANGELOG-3.0.md
  src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
Labels: to review

#9786 PIM-8227: Get columns by code/name in selector
  CHANGELOG-3.0.md
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
Labels: to review

#9792 PIM-8196: Fix long channel labels on completeness widget
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less
Labels: to review

#9783 Update the context map of the PIM
  internal_doc/architecture/context_map.md
  internal_doc/architecture/domain.md
  internal_doc/architecture/images/context_map/all_teams.svg
  internal_doc/architecture/images/context_map/chipmunk.svg
  internal_doc/architecture/images/context_map/raccoon.svg
  internal_doc/architecture/images/context_map/relation.svg
  internal_doc/architecture/images/context_map/weasel.svg
  internal_doc/architecture/images/domain/domain.svg
  internal_doc/architecture/images/domain/subdomains.svg
  internal_doc/index.md
Labels: to review

#9798 PIM-8237: Fix the query params on search attributes
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SearchAttributeEndToEnd.php
Labels: to review

#9817 Improve the context map (squad point of vue) to make it clearer
  internal_doc/architecture/images/context_map/all_teams.svg
Labels: to review

#9815 Upgrade Phpstan to install Symfony's extension
  composer.json
  composer.lock
  phpstan.neon
  src/Akeneo/Pim/Enrichment/Bundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php
Labels: to review

#9823 DAPI-151: Fix InMemory repository to support findBy syntax
  tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
  tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
Labels: to review

#9838 Merge 2.3 into 3.0
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/DescendantProductIdsQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/DescendantProductModelIdsQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product_model.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/mass_edit.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/product_model.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Query/DescendantProductIdsQueryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/DescendantProductModelIdsQueryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/OnlyExpectedAttributesValidator.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute_option.yml
  src/Akeneo/Pim/Structure/Component/Repository/FamilyRepositoryInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/mass-edit.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-buttons.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/multi-select-field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/text.html
  src/Akeneo/Tool/Bundle/ApiBundle/Doctrine/ORM/Repository/ProductModelRepository.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/repositories.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/mass-delete-action.js
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/DescendantProductIdsIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/DescendantProductModelIdsIntegration.php
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/user-management/group/edit_user_group_assignations.feature
Labels: PULLUP

#9844 PIM-8253: Fix unique attributes excluded in attributes search
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml
  src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js
  tests/legacy/features/attribute/use_unique_attribute.feature
Labels: to review
