Repository akeneo/pim-community-dev, pull requests merged in 2019-11, with the labels that each got.

#10984 TIP-1327: Introduce new targets to run our tests (locally and on the CI)
  .circleci/config.yml
  Makefile
  docker-compose.yml
  make-file/apps.mk
  make-file/channel.mk
  make-file/dev.mk
  make-file/enrichment.mk
  make-file/structure.mk
  make-file/test.mk
  make-file/user-management.mk
  src/Akeneo/Apps/back/tests/Acceptance/behat.yml
Labels: to review

#11013 TIP-1327: Introduce new targets to run our tests (locally and on the CI)
  .circleci/config.yml
  .circleci/run_phpunit.sh
  make-file/apps.mk
  make-file/dev.mk
  make-file/test.mk
Labels: to review

#10965 DAPI-545: add 2 official green variations
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
Labels: weasels

#11021 TIP-1327: Use make to run behat legacy tests
  .circleci/config.yml
  .circleci/run_behat.sh
  make-file/apps.mk
  make-file/channel.mk
  make-file/dev.mk
  make-file/enrichment.mk
  make-file/structure.mk
  make-file/test.mk
  make-file/user-management.mk
Labels: to review

#11051 PIM-8966: Merge 3.0 into 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child/fields-container.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html
Labels: PULLUP

#11072 TIP-1290 Fix CI to avoid "^@^@" character
  make-file/test.mk
Labels: to review

#11049 Yarn workspaces & cleanup js dependencies
  Makefile
  frontend/build/check-dependencies.js
  frontend/webpack/requirejs-utils.js
  internal_doc/index.md
  package.json
  src/Akeneo/Apps/front/package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/translator.js
  yarn.lock
Labels: to review

#11088 AST-11: Use imagick as liip_imagine driver
  config/packages/liip_imagine.yml
Labels: to review

#11091 Use relative paths instead of absolute ones in require-paths.js
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
Labels: to review

#11099 TIP-1264 Upgrade Doctrine
  composer.json
  composer.lock
Labels: to review

#11109 API 659: Delete an unused App
  src/Akeneo/Apps/back/Application/Command/DeleteAppCommand.php
  src/Akeneo/Apps/back/Application/Command/DeleteAppHandler.php
  src/Akeneo/Apps/back/Application/Service/DeleteClientInterface.php
  src/Akeneo/Apps/back/Application/Service/DeleteUserInterface.php
  src/Akeneo/Apps/back/Domain/Persistence/Repository/AppRepository.php
  src/Akeneo/Apps/back/Infrastructure/Cli/DeleteAppCommand.php
  src/Akeneo/Apps/back/Infrastructure/Client/Fake/DeleteClient.php
  src/Akeneo/Apps/back/Infrastructure/Client/Fos/DeleteClient.php
  src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
  src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
  src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/cli.yml
  src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Apps/back/Infrastructure/User/Fake/DeleteUser.php
  src/Akeneo/Apps/back/Infrastructure/User/Internal/DeleteUser.php
  src/Akeneo/Apps/back/tests/.php_cd.php
  src/Akeneo/Apps/back/tests/Acceptance/Context/AppContext.php
  src/Akeneo/Apps/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Apps/back/tests/Acceptance/behat.yml
  src/Akeneo/Apps/back/tests/Acceptance/features/create_an_app.feature
  src/Akeneo/Apps/back/tests/Acceptance/features/delete_an_app.feature
  src/Akeneo/Apps/back/tests/Acceptance/features/update_an_app.feature
  src/Akeneo/Apps/back/tests/EndToEnd/App/DeleteAppEndToEnd.php
  src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/DeleteAppCommandSpec.php
  src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/DeleteAppHandlerSpec.php
  src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/Client/Fos/DeleteClientSpec.php
  src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/User/Internal/DeleteUserSpec.php
Labels: to review

#11123 PIM-8974: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-completeness.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/job-execution/summary-table.html
  tests/legacy/features/pim/structure/attribute-group/display_attribute_group_history.feature
Labels: PULLUP
