Repository akeneo/pim-community-dev, pull requests merged in 2019-08, with the labels that each got.

#10449 TIP-901: command not container aware - Part 1
  src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeProductsCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/DependencyInjection/PimInstallerExtension.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
Labels: towards SF4

#10512 PIM-8614: Fix empty variant axes validation
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotEmptyVariantAxesValidator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php
Labels: to review

#10482 TIP-1185: Remove unused indexing normalizers
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_indexing.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/DateTimeNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Product/ProductNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Product/PropertiesNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductCompletenessCollectionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductModel/ProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/BooleanNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/DateNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/DummyNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/MediaNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/MetricNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/NumberNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/OptionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/OptionsNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/PriceCollectionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/ReferenceDataCollectionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/ReferenceDataNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/TextAreaNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/TextNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/ValueCollectionNormalizer.php
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Indexing/FamilyNormalizer.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Indexing/ProductIndexingIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/DateTimeNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Product/ProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductCompletenessCollectionNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/BooleanNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/DateNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/MediaNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/MetricNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/NumberNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/OptionNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/OptionsNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/PriceCollectionNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/ReferenceDataCollectionNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/ReferenceDataNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/TextAreaNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/TextNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/ValueCollectionNormalizerSpec.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/Indexing/FamilyNormalizerSpec.php
Labels: to merge

#10508 PIM-8611: Fix filters applied when a product model is excluded from a product-grid selection
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductMassActionRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorFilter.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ProductMassActionRepositorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorFilterSpec.php
Labels: to review

#10505 TIP-901: Small fixes towards SF4
  app/bundles.php
  app/config/pim_parameters.yml
  app/config/security.yml
  app/phpunit.xml.dist
  behat.yml.dist
  bin/check-services-instantiability
  bin/console
  composer.json
  composer.lock
  phpstan.neon
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/config/pim.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/Configuration.php
  src/Akeneo/UserManagement/Bundle/DependencyInjection/Configuration.php
  src/Kernel.php
  tests/back/Integration/AppKernelTest.php
  web/app.php
Labels: to review, towards SF4

#10525 TIP-1185: Add migration script
  upgrades/3.2-4.0/es_delete_unused_indexes.php
Labels: to review

#10527 TIP-901: fix SF4 deprecations
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/product_grid_category_tree.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/EventListener/InstallDatabase.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
  src/Akeneo/Platform/config/bundles/doctrine.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/DBAL/Types/JsonType.php
  src/Oro/Bundle/FilterBundle/Form/Type/Filter/AbstractChoiceType.php
  src/Oro/Bundle/PimFilterBundle/PimFilterBundle.php
  upgrades/3.1-3.2/LocalLogToObjectStorage.php
  upgrades/3.1-3.2/LocaleArchivesToObjectStorage.php
  upgrades/3.1-3.2/RelocateException.php
  upgrades/3.1-3.2/Version_3_2_20190624081152_update_comment_foreign_key.php
  upgrades/3.1-3.2/archived_files_local_filesystem_to_object_storage.php
  upgrades/3.1-3.2/archived_logs_local_filesystem_to_object_storage.php
Labels: to review, towards SF4

#10542 Fix check pull up
  bin/check-pullup
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php
Labels: to review

#10569 PIM-8583: Add missing translations on role deletion
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: to review

#10554 TIP-901: use SF4 config directory
  .circleci/config.yml
  .circleci/local-object-storage-setup.sh
  .gitignore
  app/config/config_behat.yml
  app/config/config_test_fake.yml
  app/phpunit.xml.dist
  behat.yml.dist
  bin/check-services-instantiability
  bin/console
  config/bootstrap.php
  config/bundles.php
  config/packages/behat/config.yml
  config/packages/config.yml
  config/packages/dev/config.yml
  config/packages/prod/config.yml
  config/packages/security.yml
  config/packages/test/config.yml
  config/packages/test/security/security.yml
  config/packages/test_fake/config.yml
  config/routes/dev/routes.yml
  config/routes/routes.yml
  config/services/behat/parameters.yml
  config/services/pim_parameters.yml
  config/services/services.yml
  config/services/test/parameters.yml
  config/services/test_fake/parameters.yml
  config/services/test_fake/services.yml
  src/Kernel.php
  web/app.php
Labels: to review, towards SF4

#10585 PIM-8629: Allow import profile actions to be filtered by allowed property
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher-item.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher.js
Labels: to merge

#10599 TIP-901: database migration for native_json type removal
  upgrades/schema/Version_4_0_20190801084247_remove_native_json_type.php
Labels: to review

#10601 TIP-1210 Make Makefile simpler
  Makefile
  docker-compose.yml
  make-file/dev.mk
Labels: to review

#10602 PIM-8661: Fix merging values from a variant product when one of its ancestors has empty values
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiers.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiersIntegration.php
Labels: to review

#10603 TIP-1207 Commit .env to the repository
  .circleci/config.yml
  .env
  .gitignore
  Makefile
Labels: to review

#10606 TIP-1202: remove the old app/ directory
  .circleci/config.yml
  .circleci/find_phpunit.sh
  .env
  .gitignore
  app/.htaccess
  config/packages/behat/config.yml
  config/packages/config.yml
  config/packages/dev/config.yml
  config/packages/test/config.yml
  config/packages/test_fake/config.yml
  config/services/pim_parameters.yml
  internal_doc/tests/running_the_tests.md
  make-file/dev.mk
  phpunit.xml.dist
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/Default/pim_uservoice.js.twig
  src/Akeneo/Platform/config/pim.yml
  tests/back/Integration/AppKernelTest.php
  var/PimRequirements.php
  var/SymfonyRequirements.php
Labels: to review, towards SF4

#10617 PIM-8615: Fix issue with boolean attribute used as variant axis
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ConfigureAxisValueLabelsNormalizerPass.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
Labels: to review

#10568 GITHUB-10247: Fix regex to compile the frontend assets
  CHANGELOG-4.0.md
  frontend/build/compile-less.js
  frontend/build/update-extensions.js
Labels: contribution, to merge

#10631 PIM-8701: Fix PDF rendering for scopable/localizable simple or multi select attributes
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
  tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
Labels: to review

#10632 TIP-1209 Install symfony flex
  bin/docker/pim-dependencies.sh
  composer.json
  composer.lock
  symfony.lock
Labels: to review

#10642 TIP-1087: Add .env.***.local file to .gitignore
  .gitignore
Labels: to review

#10639 TIP-1239: make the config/ directory explicit
  config/packages/akeneo_api.yml
  config/packages/akeneo_batch.yml
  config/packages/akeneo_elasticsearch.yml
  config/packages/akeneo_pim_enrichment.yml
  config/packages/akeneo_pim_user.yml
  config/packages/akeneo_storage_utils.yml
  config/packages/behat/akeneo_pim_structure.yml
  config/packages/behat/framework.yml
  config/packages/behat/monolog.yml
  config/packages/behat/pim_import_export.yml
  config/packages/dev/akeneo_pim_structure.yml
  config/packages/dev/config.yml
  config/packages/dev/framework.yml
  config/packages/dev/monolog.yml
  config/packages/dev/swiftmailer.yml
  config/packages/dev/web_profiler.yml
  config/packages/doctrine.yml
  config/packages/fos_auth_server.yml
  config/packages/fos_js_routing.yml
  config/packages/fos_rest.yml
  config/packages/framework.yml
  config/packages/liip_imagine.yml
  config/packages/oneup_flysystem.yml
  config/packages/oro_filter.yml
  config/packages/oro_translation.yml
  config/packages/prod/doctrine.yml
  config/packages/prod/monolog.yml
  config/packages/sensio_framework_extra.yml
  config/packages/swiftmailer.yml
  config/packages/test/akeneo_pim_structure.yml
  config/packages/test/config.yml
  config/packages/test/framework.yml
  config/packages/test/monolog.yml
  config/packages/test/security.yml
  config/packages/test/swiftmailer.yml
  config/packages/test_fake/akeneo_pim_structure.yml
  config/packages/test_fake/framework.yml
  config/packages/test_fake/monolog.yml
  config/packages/test_fake/swiftmailer.yml
  config/packages/twig.yml
  config/services/gedmo_doctrine_extensions.yml
  config/services/pim.yml
  src/Akeneo/Platform/config/bundles/twig.yml
  src/Akeneo/Platform/config/pim.yml
Labels: to review

#10643 TIP-1204 Rework docker-compose configuration
  .circleci/config.yml
  .circleci/docker-compose.override.yml.dist
  .env
  .env.behat
  .env.test
  .gitignore
  Dockerfile
  Makefile
  bin/benchmark_products_api.sh
  docker-compose.override.yml.dist
  docker-compose.yml
  docker/akeneo.conf
  docker/build/akeneo.ini
  docker/build/docker-php-entrypoint
  docker/build/nodesource_com.gpg
  docker/build/sury_org_php.gpg
  docker/build/xdebug.ini
  docker/build/yarnpkg_com.gpg
  docker/httpd.conf
  make-file/dev.mk
Labels: to review

#10649 PIM-8707: Merge 3.0 into 3.2
  CHANGELOG-3.0.md
  composer.lock
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ConfigureAxisValueLabelsNormalizerPass.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/form.html.twig
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/family.yml
  src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher-item.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-attributeoptionview.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/FiltersConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/SelectedAttributesConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/Extension/Filter/FilterExtension.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/FiltersConfiguratorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
  tests/legacy/features/pim/structure/attribute/option/delete_attribute_options.feature
Labels: PULLUP

#10616 TIP-1204 Rework docker-compose configuration
  .circleci/config.yml
  .circleci/docker-compose.override.yml.dist
  .circleci/run_behat.sh
  .circleci/run_phpunit.sh
  .circleci/wait_docker_up.sh
  .env
  .env.behat
  .env.test
  .gitignore
  Dockerfile
  Makefile
  bin/benchmark_products_api.sh
  composer.json
  composer.lock
  docker-compose.override.yml.dist
  docker-compose.yml
  docker/akeneo.conf
  docker/build/akeneo.ini
  docker/build/docker-php-entrypoint
  docker/build/nodesource_com.gpg
  docker/build/sury_org_php.gpg
  docker/build/xdebug.ini
  docker/build/yarnpkg_com.gpg
  docker/httpd.conf
  make-file/dev.mk
  src/Akeneo/Tool/Component/Console/CommandLauncher.php
Labels: to review

#10651 Fix integer as codes for required attributes masks
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetRequiredAttributesMasks.php
Labels: to merge

#10653 TIP-1204 Fix little glitches
  .circleci/config.yml
  make-file/dev.mk
Labels: to review

#10647 TIP-1213 Clean .env files
  .env.behat
  .env.test
  docker-compose.yml
Labels: to review

#10664 PIM-7127: Hide version from CSS call
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/VersionStrategy/CacheBusterVersionStrategy.php
  src/Pim/Bundle/EnrichBundle/spec/VersionStrategy/CacheBusterVersionStrategySpec.php
Labels: wip
