Repository akeneo/pim-community-dev, pull requests merged in 2019-05, with the labels that each got.

#9989 TIP-1162 Uses object storage on CI
  .circleci/config.yml
  .circleci/local-object-storage-setup.sh
  .gitignore
  composer.json
  composer.lock
  docker-compose.override.yml.dist
  docker-compose.yml
  docker/object_storage/.gitkeep
  docker/object_storage/catalog/.gitkeep
Labels: CI, to review

#9836 Add the last definitions of bounded context
  internal_doc/architecture/context_map.md
Labels: to review

#9968 Fix asset installation + add target to build frontend
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/unused/DefaultPicture.svg
Labels: to review

#9990 PIM-8323: Fix issue on attribute option removing
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
Labels: to review

#9960 #1092: Configure form extension for the cloud edition
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/unused/Default_picture.svg
Labels: to review

#9995 Clear Docker images cache
  .circleci/config.yml
  .gitignore
  yarn.lock
Labels: CI

#10012 Merge 3.0 into 3.1
  .circleci/config.yml
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.da_DK.yml
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizer.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.da_DK.yml
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/property.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/upload-launch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/flags.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js
  src/Akeneo/Tool/Bundle/VersioningBundle/Manager/VersionManager.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
  tests/back/Common/EntityBuilder.php
  tests/back/Common/Structure/Attribute/Builder.php
  tests/back/Common/spec/Structure/Attribute/BuilderSpec.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
  tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizerSpec.php
  tests/front/unit/jest/unit.jest.js
  tests/legacy/features/pim/enrichment/product/pef/edit_product.feature
  tests/legacy/features/pim/structure/attribute/display_localized_attribute_history.feature
  webpack.config.js
Labels: PULLUP

#10017 Merge 3.1 into master
  .circleci/config.yml
  frontend/build/compile-less.js
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizer.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/unused/DefaultPicture.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/unused/Default_picture.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/property.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/upload-launch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/flags.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js
  src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
  tests/back/Common/EntityBuilder.php
  tests/back/Common/Structure/Attribute/Builder.php
  tests/back/Common/spec/Structure/Attribute/BuilderSpec.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
  tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizerSpec.php
  tests/front/unit/jest/unit.jest.js
  tests/legacy/features/pim/enrichment/product/pef/edit_product.feature
  tests/legacy/features/pim/structure/attribute/display_localized_attribute_history.feature
  webpack.config.js
Labels: PULLUP

#10020 TIP-1157: Create real query for API List Product Models
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ORM/Connector/GetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ORM/Connector/GetMetadataForProductModel.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetMetadataInterface.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/AbstractProductModelTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListProductModelWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/ORM/Connector/GetConnectorProductModelsSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php
Labels: to review

#10036 Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/PimUIExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/translator.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/mass-edit/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Translator/TranslatorDecorator.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateMappingIndexCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/AkeneoElasticsearchExtension.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMapping.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexMappingIntegration.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/search-filter.html
  tests/back/Platform/Specification/Bundle/UIBundle/Translator/TranslatorDecoratorSpec.php
Labels: PULLUP

#10037 Fix sequential edit ui
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/SequentialEdit.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js
Labels: to review

#10038 PIM-8340: Allow to delete a user who authored or replied to a comment
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/RemoveUserSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Comment/Comment.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Comment/Normalizer/Standard/CommentNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/comments.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/comments.html
  tests/back/Pim/Enrichment/Integration/Comment/CommentWithDeletedAuthorIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Comment/Normalizer/Standard/CommentNormalizerSpec.php
Labels: to review

#9997 TIP-1158: Add filter for reference data options
  src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetExistingReferenceDataCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetExistingReferenceDataCodes.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeTypes/Sql/SqlGetAttributes.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php
Labels: to merge

#10048 PIM-8346: Fix product grid price filters
  CHANGELOG-2.3.md
  src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
  src/Pim/Bundle/FilterBundle/Filter/ProductValue/PriceFilter.php
  tests/legacy/features/Pim/Behat/Decorator/Grid/Filter/PriceDecorator.php
  tests/legacy/features/product/filtering/filter_products_per_price.feature
Labels: to review

#10018 DAPI-138: New event when starting sequential edit
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sequential-edit.js
Labels: to review

#10002 TIP-1126: Uploading a file in the PEF
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/MediaController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/MediaStorer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductModelProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/MediaAttributeSetter.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  src/Akeneo/Tool/Component/FileStorage/Exception/InvalidFile.php
  src/Akeneo/Tool/Component/FileStorage/File/FileStorer.php
  src/Akeneo/Tool/Component/FileStorage/File/FileStorerInterface.php
  src/Akeneo/Tool/Component/FileStorage/spec/File/FileStorerSpec.php
  tests/back/Integration/TestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Completeness/AttributeType/FileAttributeTypeCompletenessIntegration.php
  tests/back/Pim/Enrichment/Integration/Completeness/AttributeType/ImageAttributeTypeCompletenessIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/MediaFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/ScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByFilesIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByImagesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
  tests/back/Pim/Enrichment/Integration/Updater/Copier/MediaAttributeCopierIntegration.php
  tests/back/Pim/Enrichment/Integration/Updater/Setter/MediaAttributeSetterIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/MediaStorerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductModelProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/MediaAttributeSetterSpec.php
Labels: to review

#10025 TIP-1168: Use query and dedicated read model when getting a single pr…
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetCategoryCodesByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetConnectorProductModels.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListOffsetProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListSearchAfterProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
Labels: to review

#10081 PIM-8352: Add comment about trusted proxy and HTTPS
  web/app.php
Labels: to review

#10088 PIM-8308: Fix missing translation for import and export profiles
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
Labels: to review

#10086 PIM-8308: Fix broken translation keys for import and export profiles
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
Labels: to review

#10090 PIM-7772: Fix translation in roles ACL
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature
Labels: to review

#10089 PIM-7772: Fix translation in roles ACL
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  tests/legacy/features/mass-action/apply_permissions_on_mass_edit_actions.feature
Labels: to review

#10075 TIP-1117: Improve command to create new users
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/users.csv
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php
  tests/back/Integration/TestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountNotIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountNotIncludingSubCategoriesIntegration.php
  tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/CountUsersIntegration.php
  tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
Labels: to review

#10114 Merge 3.0 into 3.1
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/QueryBuilderUtility.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/AttributeTypeForOptionValidator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/locale-fetcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TabContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family-variant/attribute-set.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/variant-navigation/navigation.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/search-filter.html
  src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/PriceFilter.php
  tests/legacy/features/Behat/Decorator/Grid/Filter/PriceDecorator.php
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_price.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature
  web/app.php
Labels: PULLUP

#10115 Set phpstan to level 1
  .circleci/config.yml
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
Labels: to review

#10120 PIM-8385: Fix timeout when launching the clean attributes command
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
Labels: to review

#10130 PIM-7583: Prevent js error for locales without country
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts
Labels: to review

#10097 TIP-1144: Add the family into the API product model format
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ExternalApi/ProductModelUpdater.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/AbstractProductModelTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListProductModelWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelListSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ExternalApi/ProductModelUpdaterSpec.php
Labels: to review

#10157 PIM-8315: Fix undefined attribute groups in family mass edit
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/mass-edit/toolbar/add-select/attribute/select.js
Labels: to merge
