Repository akeneo/pim-community-dev, pull requests merged in 2019-04, with the labels that each got.

#9852 Add back code coverage report on jest unit tests
  tests/front/unit/jest/unit.jest.js
Labels: to review

#9861 Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/family/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/meta/family-variant.js
  tests/legacy/features/pim/enrichment/product/mass-edit/unique_attribute.feature
Labels: PULLUP

#9851 TIP-1059: ProductInterface does not extend LocalizableInterface nor ScopableInterface anymore
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/LocalizableSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ScopableSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/LocalizableSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ScopableSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Labels: to review

#9899 PIM-8286: Allow a user to edit his/her own account
  CHANGELOG-3.0.md
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/user_rest.yml
  src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
  tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
  tests/legacy/features/user-management/user/edit_my_account.feature
Labels: to review

#9912 Pull up 2.3 to 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php
  tests/legacy/features/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_optional_values.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_date_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_file_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_image_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_numeric_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_select_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_text_attributes.feature
  tests/legacy/features/pim/enrichment/product/pef/join_a_document_to_a_product.feature
  tests/legacy/features/pim/enrichment/product/pef/join_an_image_to_a_product.feature
  tests/legacy/features/pim/enrichment/product/pef/remove_attributes_from_product.feature
Labels: to review

#9919 Bump symfony version to 3.4.26
  composer.json
  composer.lock
Labels: to review

#9917 TIP-1134: Create a query to get product association of product models
  src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodesIntegration.php
Labels: to merge

#9885 #1062: Hide the file path property for cloud edition
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/field/allow-file-upload.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/field/file-path.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-edition.ts
  webpack.config.js
Labels: to review

#9920 TIP-1091: Hide the file path property for cloud edition
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
Labels: to review

#9926 Revert "Fix possibly undefined variables"
  .circleci/config.yml
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/MediaAttributeSetter.php
Labels: to review

#9941 Merge 2.0 into 2.3
  CHANGELOG-2.0.md
Labels: PULLUP

#9934 PIM-8287: Fix horizontal scroll on history panel
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
Labels: to merge

#9935 TIP-1149: Update the warning limits in the Catalog volume monitoring …
  CHANGELOG.md
  app/config/pim_parameters.yml
  tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/AverageMaxCategoryLevelsIntegration.php
Labels: to review

#9944 Merge 2.3 into 3.0
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/MetricConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractMetric.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/MetricConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/MetricFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/ValueNormalizerSpec.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_invalid_data.feature
Labels: PULLUP

#9951 Stop 2.0 nightly build
  .circleci/config.yml
Labels: CI

#9948 Set 3.1 version name
  src/Akeneo/Platform/CommunityVersion.php
Labels: to review

#9954 Allow empty form extension .ymls to be ignored during the build
  frontend/build/update-extensions.js
Labels: to review

#9945 Fix exclude folders to make them relative
  webpack.config.js
Labels: to merge

#9955 UPGRADE.md for 3.1
  UPGRADE.md
Labels: to review

#9950 Merge 3.0 into master
  composer.json
  src/Akeneo/Pim/Enrichment/Bundle/AkeneoPimEnrichmentBundle.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ConfigureAxisValueLabelsNormalizerPass.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Widget/CompletenessWidget.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/MetricConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractMetric.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/AxisValueLabelsNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/SimpleSelectOptionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/user_rest.yml
  src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  tests/back/Acceptance/User/InMemoryRoleRepository.php
  tests/back/Acceptance/spec/User/InMemoryRoleRepositorySpec.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Bundle/Widget/CompletenessWidgetSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/MetricConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/MetricFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/SimpleSelectOptionNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/ValueNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
  tests/legacy/features/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_invalid_data.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_optional_values.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_date_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_file_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_image_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_numeric_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_select_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_text_attributes.feature
  tests/legacy/features/pim/enrichment/product/pef/join_a_document_to_a_product.feature
  tests/legacy/features/pim/enrichment/product/pef/join_an_image_to_a_product.feature
  tests/legacy/features/pim/enrichment/product/pef/remove_attributes_from_product.feature
  tests/legacy/features/user-management/user/edit_my_account.feature
Labels: PULLUP

#9961 Alias master to 3.2
  composer.json
Labels: to review

#9962 Properly name changelog
  CHANGELOG-3.1.md
Labels: to review

#9967 Merge 3.1 into master
  CHANGELOG-3.2.md
  CHANGELOG.md
  composer.json
  src/Akeneo/Platform/CommunityVersion.php
Labels: to review

#9970 Fix version
  src/Akeneo/Platform/CommunityVersion.php
Labels: to review

#9966 PIM-8318: Fix CE 2.3 CI
  .circleci/config.yml
  CHANGELOG-2.3.md
  composer.json
  composer.lock
  src/Pim/Bundle/FilterBundle/Form/Type/Filter/AjaxChoiceFilterType.php
  src/Pim/Bundle/FilterBundle/Form/Type/UnstructuredType.php
Labels: CI, tech-improvement

#9977 Launch yarn run less during yarn run webpack
  webpack.config.js
Labels: to review

#9971 PIM-8289: Fix search on label or identifier for product variants ancestors
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
Labels: to review
