Repository akeneo/pim-community-dev, pull requests merged in 2019-02, with the labels that each got.

#9427 PIM-8008:Fix attribute sort order in PEF
  .gitignore
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/EventSubscriber/AttributeCreationSubscriber.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AttributeCreationSubscriberSpec.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
Labels: to review

#9406 PIM-8007: Content of sortable attribute options are now copyable
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-option/show.html
  src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
Labels: to review

#9490 PIM-8022: Fix the job status when using the batch command
  CHANGELOG-2.3.md
  composer.lock
  src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
  src/Akeneo/Bundle/BatchQueueBundle/Manager/JobExecutionManager.php
  src/Akeneo/Bundle/BatchQueueBundle/spec/Manager/JobExecutionManagerSpec.php
  src/Pim/Bundle/ImportExportBundle/Resources/config/routing/import_execution.yml
  src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/files/model-tshirt-divided-blue/.DS_Store
  tests/legacy/features/Context/catalog/catalog_modeling/files/model-tshirt-divided-blue/.DS_Store
Labels: to review

#9413 PIM-7943: Fix duplicate popin mask in family variant edit form
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/edit-in-modal-action.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/family-variant.js
  src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less
Labels: to review

#9488 Stabilize behat on 2.0
  bin/docker/pim-dependencies.sh
  features/Context/AssertionContext.php
  features/Context/DataGridContext.php
  features/Context/Page/Attribute/Creation.php
  features/Context/Page/Base/Form.php
  features/Context/Page/Base/Grid.php
  features/Context/WebUser.php
  features/Pim/Behat/Context/Domain/SecondaryActionsContext.php
  features/Pim/Behat/Context/Domain/Spread/ExportBuilderContext.php
  features/Pim/Behat/Context/NavigationContext.php
  features/Pim/Behat/Decorator/Grid/Filter/BaseDecorator.php
  features/acl/assert_acl.feature
  features/attribute/option/edit_attribute_options_02.feature
  features/category/list_categories.feature
  features/category/remove_a_category.feature
  features/datagrid/datagrid_views.feature
  features/datagrid/products_category_backtothegrid.feature
  features/export/execute_an_export.feature
  features/export/product-export-builder/export_products_by_multiselect.feature
  features/export/product-export-builder/export_products_by_simpleselect.feature
  features/family/set_the_attribute_used_as_image.feature
  features/import/product_group/import_groups.feature
  features/mass-action/apply_permissions_on_mass_edit_actions.feature
  features/mass-action/edit_common_attributes_per_families.feature
  features/mass-action/quick_export_grid_context.feature
  features/mass-action/quick_export_products_and_product_models.feature
  features/product/comments.feature
  features/product/completeness/remove_completeness.feature
  features/product/edit_product.feature
  features/product/ensure_tab_redirection.feature
  features/product/filtering/filter_products.feature
  features/product/join_a_document_to_a_product.feature
  features/user/create_and_delete_user.feature
  features/user/create_edit_and_delete_group.feature
  features/user/create_edit_and_delete_role.feature
  features/user/edit_user_group_and_role_assignations.feature
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/DocumentTypeIntegration.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/group-selector.js
Labels: CI

#9512 Fix 3.0 composer aliases
  composer.json
Labels: tech-improvement

#9521 Fix upgrade3
  UPGRADE.md
Labels: to review

#9520 GITHUB-9480: Stabilize test
  features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php
Labels: CI

#9526 Merge 1.7 into 2.0
  CHANGELOG-1.7.md
  src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
  src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
  src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Pim/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
Labels: to review

#9522 PIM-8020: Fix wrong count on missing required attributes in the completeness
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGenerator.php
  tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
  tests/back/Pim/Enrichment/Integration/Completeness/UpdateMissingAttributesIntegration.php
Labels: to review

#9443 PIM-8028: Fix labels for boolean values
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/boolean.html
Labels: to review

#9357 Add ticket number to coupling issues
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Structure/.php_cd.php
Labels: to review

#9537 Merge 2.0 into 2.3
  .gitignore
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  app/phpunit.xml.dist
  bin/docker/pim-dependencies.sh
  src/Akeneo/Bundle/ElasticsearchBundle/Client.php
  src/Pim/Bundle/CatalogBundle/EventSubscriber/Category/UpdateIndexesOnCategoryDeletion.php
  src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
  src/Pim/Bundle/CatalogBundle/tests/integration/Classification/UpdateIndexesOnCategoryDeletionIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogTestCase.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/group-selector.js
  src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
  src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
  src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Pim/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
  src/Pim/Component/Catalog/Category/GetDescendentCategoryCodes.php
  src/Pim/Component/Catalog/tests/integration/Category/CategoryTreeFixturesLoader.php
  src/Pim/Component/Catalog/tests/integration/Category/GetDescendentCategoryCodesIntegration.php
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/Pim/Behat/Context/Domain/SecondaryActionsContext.php
  tests/legacy/features/Pim/Behat/Context/Domain/Spread/ExportBuilderContext.php
  tests/legacy/features/Pim/Behat/Context/NavigationContext.php
  tests/legacy/features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php
  tests/legacy/features/Pim/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
  tests/legacy/features/acl/assert_acl.feature
  tests/legacy/features/product/filtering/filter_products.feature
Labels: to review

#9483 PIM-8026: Upgrade to jQuery 3.3.1
  package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-option/create.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/layout.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-dialogform.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child/fields-container.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-associate.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-manage.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-switch/bootstrap.switch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/less/bootstrap.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/basic.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone-amd-module.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/basic.min.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone-amd-module.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone.min.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/readme.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-form/jquery.form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-numeric/jquery.numeric.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-ui/jquery-ui-1.11.4.custom.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-ui/jquery-ui-1.12.1.custom.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/slimbox2/slimbox2.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/tab/attributes/copy.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/locale-switcher.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/scope-switcher.html
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/pagination-input.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.js
  tests/legacy/features/Behat/Decorator/ContextSwitcherDecorator.php
  tests/legacy/features/Behat/Decorator/Export/Filter/BaseDecorator.php
  tests/legacy/features/Context/Page/Product/Edit.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute-group/list_attribute_groups.feature
  webpack/requirejs-utils.js
  yarn.lock
Labels: to merge

#9551 PIM-8026: Upgrade to jQuery 3.3.1
  package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-option/create.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/jstree/jquery.jstree.tree_selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/layout.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-dialogform.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-fileinput.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-saveformstate.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child/fields-container.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-associate.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-manage.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-switch/bootstrap.switch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/less/bootstrap.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/basic.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone-amd-module.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/dropzone.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/basic.min.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone-amd-module.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone.min.css
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/min/dropzone.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/dropzonejs/dist/readme.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-form/jquery.form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-numeric/jquery.numeric.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-ui/jquery-ui-1.11.4.custom.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery-ui/jquery-ui-1.12.1.custom.min.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jquery/jquery-1.10.2.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/slimbox2/slimbox2.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/tab/attributes/copy.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/locale-switcher.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/scope-switcher.html
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/ajax-choice-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-manager.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/boolean-cell.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/pagination-input.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/widget/export-widget.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.js
  tests/legacy/features/Behat/Decorator/ContextSwitcherDecorator.php
  tests/legacy/features/Behat/Decorator/Export/Filter/BaseDecorator.php
  tests/legacy/features/Context/Page/Product/Edit.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute-group/list_attribute_groups.feature
  webpack/requirejs-utils.js
  yarn.lock
Labels: to merge

#9558 Upgrade Doctrine ORM to latest patch
  composer.json
  composer.lock
Labels: to review

#9564 Introduce makefile with basic target
  Makefile
Labels: to review

#9565 PIM-8057: [SLA] Fix 500 error when requesting "forgot password"
  CHANGELOG-3.0.md
  src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
Labels: to merge

#9550 Remove unused dependencies
  app/AppKernel.php
  composer.json
  composer.lock
  phpspec.yml.dist
  src/Akeneo/Platform/Bundle/UIBundle/Twig/Md5Extension.php
Labels: to review

#9571 Fix Build 3.0 by setting doctrine deps
  composer.json
  composer.lock
Labels: to review

#9416 Upgrade Symfony behat extension to 2.0
  Makefile
  app/AppKernel.php
  app/config/config_test_fake.yml
  behat.yml.dist
  composer.json
  composer.lock
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml
  tests/back/Platform/Acceptance/CatalogVolumeMonitoring/Resources/config/behat/services.yml
  var/SymfonyRequirements.php
Labels: to review

#9572 PIM-8019: Fix broken bulk product association modal
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
Labels: to merge

#9540 PIM-7939: Search on ancestors labels and codes
  CHANGELOG-2.3.md
  src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifier.php
  src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
  src/Pim/Bundle/CatalogBundle/Resources/config/serializers_indexing.yml
  src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierSpec.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierIntegration.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php
  src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php
  src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/CountImpactedProducts.php
  src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/ProductAndProductModelReaderSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Query/CountImpactedProductsSpec.php
  src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/ORM/Query/CountImpactedProductsIntegration.php
  src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
  src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
  src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
  src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
Labels: to review

#9426 APAI
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-confirm.ts
  tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
  tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
Labels: wip

#9580 PIM-8058: Backport PIM-8020 to update missing attributes
  CHANGELOG-2.0.md
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessTestCase.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/UpdateMissingAttributesIntegration.php
  src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
Labels: to merge

#9581 Reorganize/improve internal doc
  internal_doc/REPRODUCE_CI_BUILD.md
  internal_doc/architecture/context_map.md
  internal_doc/architecture/domain.md
  internal_doc/architecture/images/context_map/context_map.dia
  internal_doc/architecture/images/context_map/context_map.png
  internal_doc/architecture/images/context_map/context_map.svg
  internal_doc/architecture/images/domain/domain.svg
  internal_doc/architecture/images/domain/subdomains.svg
  internal_doc/enrichment/images/search/categories-for-this-level.png
  internal_doc/enrichment/images/search/data-set.png
  internal_doc/enrichment/images/search/expected-result-1.png
  internal_doc/enrichment/images/search/expected-result-2.png
  internal_doc/enrichment/images/search/expected-result-3.png
  internal_doc/enrichment/images/search/expected-result-4.png
  internal_doc/enrichment/images/search/filtering-on-categories-not-working.png
  internal_doc/enrichment/images/search/naive-filtering.png
  internal_doc/enrichment/images/search/smart-filtering-attribute.png
  internal_doc/enrichment/images/search/sumup-structure.png
  internal_doc/enrichment/images/search/testing-solution-1.png
  internal_doc/enrichment/images/search/testing-solution-2.png
  internal_doc/enrichment/images/search/testing-solution-3.png
  internal_doc/enrichment/product_aggregate.md
  internal_doc/enrichment/product_grid.md
  internal_doc/enrichment/search_of_products_and_product_models.md
  internal_doc/enrichment/search_specification_on_elasticsearch.rst
  internal_doc/index.md
  internal_doc/standard_format.md
  internal_doc/tests/running_the_tests.md
  web/bundles/.gitkeep
Labels: to review

#9561 Improve makefile
  Makefile
  make-file/channel.mk
  make-file/enrichment.mk
  make-file/structure.mk
  make-file/user-management.mk
Labels: to review

#9583 Clean stuff
  .gitignore
  .php_cs.php
  phpdoc.xml.dist
Labels: to review

#9621 PIM-8131 labels cannot be used for search in bulk action
  CHANGELOG-2.3.md
  Makefile
  src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
Labels: to merge

#9620 PIM-8130: add test decorator for reference entity attributes
  tests/legacy/features/Context/Page/Base/Grid.php
Labels: to review

#9626 Add restart fpm in UPGRADE
  UPGRADE.md
Labels: to review

#9584 Remove old changelog.md and update.md
  CHANGELOG-1.0.md
  CHANGELOG-1.1.md
  CHANGELOG-1.2.md
  CHANGELOG-1.3.md
  CHANGELOG-1.4.md
  CHANGELOG-1.5.md
  CHANGELOG-1.6.md
  CHANGELOG-1.7.md
  CHANGELOG-2.0.md
  CHANGELOG-2.1.md
  CHANGELOG-2.2.md
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  CHANGELOG.md
  UPGRADE.md
Labels: to review

#9641 CI-9640: Homogenize Behat job name
  .circleci/config.yml
Labels: to review

#9523 PIM-8018: Move the 'Confirm' button under the warning message in bulk…
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
Labels: to review

#9639 PIM-8155: Fix bad ACL set on xlsx product export edit form
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
Labels: to review

#9618 Merge 2.3 into 3.0
  .circleci/config.yml
  .circleci/unstable_behats.txt
  CHANGELOG-2.0.md
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/CountImpactedProducts.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/VariantProductRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifier.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_indexing.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Product/PropertiesNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/family/mass_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Acl.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family/tab/attributes/attributes.html
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/CountImpactedProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Query/CountImpactedProductsSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
Labels: wip

#9607 Compile form extensions with node
  frontend/build/check-requirements.js
  frontend/build/compile-less.js
  frontend/build/update-extensions.js
  frontend/webpack/requirejs-utils.js
  package.json
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpExtensionsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
  src/Akeneo/Platform/Bundle/UIBundle/Controller/InternalApi/FormExtensionController.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/FormExtensionProvider.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/file.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/image.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/providers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing/internal_api/form_extensions.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/config-provider.js
  tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
  tests/front/acceptance/cucumber/world.js
  webpack.config.js
  yarn.lock
Labels: to merge

#9672 Merge 2.0 into 2.3
  CHANGELOG-2.0.md
  src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
  tests/legacy/features/category/list_categories.feature
Labels: to review

#9680 GITHUB-9511: generate an error in Circle CI when there is a JS error in a behat and split by timing
  .circleci/config.yml
  tests/legacy/features/Pim/Behat/Extension/PimFormatter/Output/Node/EventListener/PimFeatureElementListener.php
  tests/legacy/features/Pim/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php
Labels: CI
