Repository akeneo/pim-community-dev, pull requests merged in 2019-09, with the labels that each got.

#10654 TIP-1235: upgrade to Debian Buster and PHP7.3
  .circleci/config.yml
  Dockerfile
  Makefile
  composer.json
  composer.lock
  docker-compose.yml
  docker/build/docker-php-entrypoint
  docker/build/nodesource_com.gpg
  docker/build/sury_org_php.gpg
  docker/build/yarnpkg_com.gpg
  src/Akeneo/Platform/CommunityRequirements.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Storage/EntityWithValuesStorageIntegration.php
Labels: to review

#10684 PIM-8722: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
  src/Akeneo/Platform/Bundle/UIBundle/VersionStrategy/CacheBusterVersionStrategy.php
  tests/back/Platform/Specification/Bundle/UIBundle/VersionStrategy/CacheBusterVersionStrategySpec.php
Labels: PULLUP

#10686 PIM-8723: Merge 3.0 into 3.2
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
  src/Akeneo/Platform/Bundle/UIBundle/VersionStrategy/CacheBusterVersionStrategy.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/array_converters.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/writers.yml
  src/Akeneo/Tool/Component/Connector/ArrayConverter/InvalidDataItemConverter.php
  src/Akeneo/Tool/Component/Connector/spec/ArrayConverter/InvalidDataItemConverterSpec.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
  tests/back/Platform/Specification/Bundle/UIBundle/VersionStrategy/CacheBusterVersionStrategySpec.php
Labels: PULLUP

#10663 TIP-1232 Handle Symfony requirements properly
  Makefile
  composer.json
  composer.lock
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/PimRequirements.php
  src/Akeneo/Platform/Requirement.php
  src/Akeneo/Platform/Requirements.php
  var/SymfonyRequirements.php
Labels: to review

#10661 TIP-1249: upgrade to MySQL 8
  config/packages/doctrine.yml
  docker-compose.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php
  src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
  src/Akeneo/Platform/PimRequirements.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
Labels: to review

#10665 Fix symfony deprecation
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
Labels: to review, towards SF4

#10715 PIM-8755: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
Labels: PULLUP

#10545 TIP-901: no direct access to container from old controllers
  docker-compose.yml
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
  src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
  src/Akeneo/UserManagement/Bundle/Controller/RoleController.php
  src/Akeneo/UserManagement/Bundle/Controller/SecurityController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/old_oro_routes.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/user.yml
  src/Oro/Bundle/DataGridBundle/Controller/GridController.php
  src/Oro/Bundle/DataGridBundle/Extension/MassAction/Actions/Ajax/AjaxMassAction.php
  src/Oro/Bundle/DataGridBundle/Resources/config/oro/routing.yml
  src/Oro/Bundle/DataGridBundle/Resources/config/services.yml
  src/Oro/Bundle/UserBundle/Controller/UserController.php
  tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SearchAttributeEndToEnd.php
Labels: to review, towards SF4

#10717 PIM-8755: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/GetAttributeOptionsMaxSortOrder.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Component/Model/AttributeOption.php
  src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php
  src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/GetAttributeOptionsMaxSortOrderIntegration.php
  tests/back/Pim/Enrichment/Integration/EventSubscriber/SetAttributeOptionSortOrderSubscriberIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriberSpec.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/CreateAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/PartialUpdateAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/PartialUpdateListAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/Specification/Component/Model/AttributeOptionSpec.php
Labels: PULLUP

#10723 PIM-8750: Fix wrong re-render on simple-select-async
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js
Labels: bug, to review

#10732 PIM-8738: fix memory leak on purge job execution
  CHANGELOG-2.3.md
  src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php
  src/Akeneo/Bundle/BatchBundle/Resources/config/removers.yml
  tests/back/Integration/integration/BatchBundle/Persistence/Sql/DeleteJobExecutionIntegration.php
Labels: to review

#10735 TIP-1262 Turn Platform commands into services (exit ContainerAwareCommand) Part 1
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/PrepareRequiredDirectoriesCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
Labels: to review

#10743 Fix EE installation
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
Labels: to review

#10737 PIM-8766: Change Dashboard Channel labels to Catalog locale
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/public/js/completeness-widget.js
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
  src/Akeneo/Pim/Enrichment/Component/FollowUp/ReadModel/ChannelCompleteness.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Widget/CompletenessWidgetSpec.php
  tests/back/Pim/Enrichment/Specification/Component/FollowUp/ReadModel/ChannelCompletenessSpec.php
  tests/back/Pim/Enrichment/Specification/Component/FollowUp/ReadModel/CompletenessWidgetSpec.php
Labels: to review

#10693 PIM-8689: Update some Acceptance context for test purpose
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  tests/back/Acceptance/Catalog/Context/ProductCreation.php
  tests/back/Acceptance/Catalog/Context/ProductValidation.php
  tests/back/Acceptance/Family/FamilyContext.php
  tests/back/Acceptance/Resources/config/behat/services.yml
Labels: to review

#10722 Fix permission during javascript file generation
  Makefile
  tests/legacy/features/pim/structure/attribute-group/display_attribute_group_history.feature
Labels: to review

#10751 TIP-1262 Turn some commands into services (exit ContainerAwareCommand)
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/QueryHelpProductCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/QueryHelpProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/RefreshProductCommand.php
  src/Akeneo/Pim/Structure/Bundle/ReferenceData/Command/CheckRequirementsCommand.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/commands.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Command/AggregateVolumesCommand.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
  src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php
  src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
  src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml
Labels: to review

#10754 PIM-8778: replace 500 error code by 422 in product API
  CHANGELOG-2.3.md
  src/Akeneo/Component/StorageUtils/Exception/InvalidObjectException.php
  src/Pim/Bundle/ApiBundle/Controller/ProductController.php
  src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
  src/Pim/Component/Catalog/Comparator/Filter/EntityWithValuesFilter.php
  src/Pim/Component/Catalog/Updater/EntityWithValuesUpdater.php
  src/Pim/Component/Catalog/spec/Comparator/Filter/EntityWithValuesFilterSpec.php
Labels: to review

#10748 TIP-1262 Turn Tool commands into services (exit ContainerAwareCommand)
  src/Akeneo/Tool/Bundle/ApiBundle/Command/CreateClientCommand.php
  src/Akeneo/Tool/Bundle/ApiBundle/Command/ListClientsCommand.php
  src/Akeneo/Tool/Bundle/ApiBundle/Command/RevokeClientCommand.php
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Command/CreateClientIntegration.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/CreateJobCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/ListJobsCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/DependencyInjection/AkeneoBatchExtension.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Command/PublishJobToQueueCommandSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Command/ResetIndexesCommandSpec.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/Command/StoreFileCommand.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/DependencyInjection/AkeneoFileStorageExtension.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/DependencyInjection/AkeneoVersioningExtension.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
Labels: to review

#10759 PULLUP: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Storage/RemoveCategoryFilterInJobInstanceSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Filter/EntityWithValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/EntityWithValuesUpdater.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
  src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidObjectException.php
  tests/back/Integration/integration/BatchBundle/Persistence/Sql/DeleteJobExecutionIntegration.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/EventSubscriber/RemoveCategoryFilterInJobInstanceSubscriberIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Storage/RemoveCategoryFilterInJobInstanceSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Filter/EntityWithValuesFilterSpec.php
Labels: PULLUP

#10775 TIP-1284: Create a service to compute completeness and index product models, children and ancestors
  src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductModelCompleteDataSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductModelsSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductsSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ComputeProductCompletenessAndIndexProductAndAncestors.php
  src/Akeneo/Pim/Enrichment/Component/Product/Storage/Indexer/ProductIndexerInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Storage/Indexer/ProductModelIndexerInterface.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductModelCompleteDataSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductModelsSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductsSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/ComputeProductCompletenessAndIndexProductAndAncestorsSpec.php
Labels: to review

#10777 TIP-1262 Make datagrid actions public
  src/Oro/Bundle/DataGridBundle/Resources/config/actions.yml
  src/Oro/Bundle/DataGridBundle/Resources/config/services.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
Labels: to review, towards SF4

#10783 TIP-1262 Use Inflector instead of StringUtils because it is deprecated
  src/Akeneo/Pim/Enrichment/Component/Product/ReferenceData/MethodNameGuesser.php
Labels: to review, towards SF4

#10779 TIP-1262: move web/ to public/
  .gitignore
  .scrutinizer.yml
  Dockerfile
  Makefile
  bin/pim-front.sh
  config/packages/liip_imagine.yml
  docker/akeneo.conf
  frontend/build/check-requirements.js
  frontend/build/compile-less.js
  frontend/build/update-extensions.js
  frontend/test/acceptance/generate-html-report.js
  frontend/webpack/requirejs-utils.js
  package.json
  public/.htaccess
  public/app.php
  public/favicon.ico
  public/robots.txt
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/files.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Twig/TranslationsExtension.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/UserManagement/Bundle/EventListener/UploadedImageSubscriber.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/less/index.less
  src/Oro/Bundle/TranslationBundle/Command/OroTranslationDumpCommand.php
  tests/front/WRITING-FRONT-TESTS.md
  tests/front/acceptance/cucumber/world.js
  tests/front/common/base.jest.json
  tests/front/integration/jest/environment.js
  tests/front/unit/jest/unit.jest.js
  tests/legacy/features/Behat/Context/PimContext.php
  tsconfig.json
  webpack-test.config.js
  webpack.config.js
Labels: to review, towards SF4

#10778 TIP-1262 Add strict mode to choice validation constraint
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
Labels: to review, towards SF4

#10786 TIP-1262 Make context services public to avoid failure in SF4.3
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml
  tests/back/Platform/Acceptance/CatalogVolumeMonitoring/Resources/config/behat/services.yml
Labels: to review, towards SF4

#10797 TIP-1262: proper dependency injection in the test services
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
  tests/back/Integration/IntegrationTestsBundle/Security/SystemUserAuthenticator.php
  tests/back/Integration/TestCase.php
  tests/back/Pim/Enrichment/Integration/Classification/ClassifyProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  tests/back/Pim/Enrichment/Integration/Fixture/EntityBuilder.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ParentFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetCategoryCodesByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetGroupAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductModelAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetCategoryCodesByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
Labels: to review, towards SF4

#10787 TIP-1263: fix check requirements
  Makefile
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/PimRequirements.php
Labels: to review

#10793 Clean Circle-CI configuration
  .circleci/config.yml
Labels: to review

#10798 TIP-1262 Make datagrid actions public
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid_actions.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/actions.yml
Labels: to review, towards SF4

#10791 Improve makefile
  .circleci/config.yml
  .gitignore
  Makefile
  behat.yml
  make-file/dev.mk
Labels: to review
