Repository akeneo/pim-community-dev, pull requests merged in 2019-01, with the labels that each got.

#9315 PIM-7915: Display a modal on deletion error
  src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
Labels: to review

#9331 PIM-7957: Fix dependencies for doctrine
  CHANGELOG-1.7.md
  composer.json
Labels: to review

#9339 Add icons & edit some CSS
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less
Labels: to review

#9330 Add ticket number to coupling issues
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/UserManagement/.php_cd.php
Labels: to review

#9354 Fix missing translations on catalog volume screen
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/section.ts
Labels: to review

#9344 PIM-7961: Fix localizable assets used as main image for family and added to product product model
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
  src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
  src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
  src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
Labels: to review

#9355 Add ticket number to coupling issues
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Structure/.php_cd.php
Labels: to review

#9333 Fix DSN to consider the port number on system information page
  CHANGELOG-3.0.md
  composer.lock
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/StorageDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  var/SymfonyRequirements.php
  yarn.lock
Labels: bug, contribution, to review

#9272 TIP-899: Improve product export performance by computing headers at the end
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/writers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromAttributeCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromFamilyCodes.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/FlatFileHeader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/GenerateFlatHeadersFromAttributeCodesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/GenerateFlatHeadersFromFamilyCodesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBuffer.php
  tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByPriceCollectionsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/AssertHeaders.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromAttributeCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromFamilyCodesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/FlatFileHeaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature
Labels: to review

#9346 PIM-7968: Fix users
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/user.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/error.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/modal.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/saver/entity-saver.js
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/datagrid/user.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/factories.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/create.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/user.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/user_rest.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/delete.js
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/UserManagement/Component/Factory/UserFactory.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/CountUsersIntegration.php
  tests/back/UserManagement/Integration/Component/Updater/UserUpdaterIntegration.php
  tests/back/UserManagement/Specification/Component/Factory/UserFactorySpec.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Context/Page/User/Edit.php
  tests/legacy/features/user-management/user/create_and_delete_user.feature
Labels: to review

#9361 TIP-1018: Removes SOAP and WSSE, cleanups Imagine and oro user
  CHANGELOG-3.0.md
  app/AppKernel.php
  bin/check-services-instantiability
  composer.json
  composer.lock
  src/Akeneo/Platform/CommunityRequirements.php
  src/Akeneo/Platform/config/bundles/escape_wsse_authentication.yml
  src/Akeneo/Platform/config/pim.yml
  src/Oro/Bundle/ConfigBundle/Resources/config/services.yml
Labels: to review

#9370 Fix edit: add parameters for redirectRoute
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/create.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
Labels: to review

#9372 Migrate nodeJS 8.x to 10.x
  .ci/Dockerfile
Labels: to review

#9382 Update front dependencies
  composer.lock
  package.json
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
  yarn.lock
Labels: wip

#9393 Use "akeneo/node" image in docker-compose
  composer.lock
  docker-compose.yml
  yarn.lock
Labels: to review

#9392 Use "akeneo/node" image in docker-compose
  composer.lock
  docker-compose.yml.dist
Labels: to review

#9411 Move upgrade file to 2.2-2.3
  upgrades/2.2-2.3/Version_2_3_20180716135306_update_job_instances.php
Labels: to review

#9260 CircleCI POC - Main branch
  .circleci/config.yml
  .circleci/docker-compose.override.yml.dist
  .circleci/run_behat.sh
  .circleci/run_phpunit.sh
  .circleci/unstable_behats.txt
  .gitignore
  app/config/.gitignore
  app/phpunit.xml.dist
  bin/docker/pim-dependencies.sh
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
  tests/back/Channel/EndToEnd/Channel/ExternalApi/PartialUpdateListChannelEndToEnd.php
  tests/back/Integration/TestCase.php
  tests/back/Integration/integration/BatchBundle/Command/BatchCommandIntegration.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/SuccessLargeAndOrderedListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/LargeAndOrderedListProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/FindActivatedCurrenciesIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModel.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/DocumentTypeIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/PimCatalogFamilyVariantIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/SearchAncestorsIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/SearchProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/SearchSelfAndAncestorsIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/RemoveProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Filter/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/SearchOnAttributesAndCategoriesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Builder/ProductBuilderSpec.php
  tests/legacy/features/Behat/Context/Domain/SecondaryActionsContext.php
  tests/legacy/features/Behat/Context/Domain/Spread/ExportBuilderContext.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Behat/Decorator/Grid/Filter/BaseDecorator.php
  tests/legacy/features/Context/AssertionContext.php
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/Context/Page/Base/Form.php
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/enrichment/product/completeness/remove_completeness.feature
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products.feature
  tests/legacy/features/pim/enrichment/product/export/export_products_by_multiselect.feature
  tests/legacy/features/pim/enrichment/product/export/export_products_by_simpleselect.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_per_families.feature
  tests/legacy/features/pim/enrichment/product/pef/association/associate_product.feature
  tests/legacy/features/pim/enrichment/product/pef/association/update_associations.feature
  tests/legacy/features/platform/acl/assert_acl.feature
  tests/legacy/features/user-management/group/edit_user_group_assignations.feature
  tests/legacy/features/user-management/role/edit_user_role_assignations.feature
  web/.gitignore
  web/bundles/.gitkeep
Labels: wip

#9409 Fix js dependencies
  CHANGELOG-2.3.md
  package.json
Labels: to review

#9398 APAI-471: Extract confirm dialog for datagrid entity deletion
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-confirm.ts
Labels: to review

#9433 PIM-8016: Fix duplicate filters in search
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
Labels: to merge

#9437 Update document type
  upgrades/schema/es_20190128110000_ce_update_document_type_product_and_product_model.php
Labels: to review

#9453 Fix smallint type for ORO tables like in 2.3
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
Labels: to review

#9404 Remove strict typehint on $image attribute as in EE it could be an Asset (ReferenceData)
  src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/Row.php
Labels: to review

#9478 #9468 Backport Circle CI configuration on 2.3
  .circleci/config.yml
  .circleci/docker-compose.override.yml.dist
  .circleci/run_behat.sh
  .circleci/run_phpunit.sh
  bin/docker/pim-setup.sh
  composer.json
Labels: CI, to review

#9480 Stabilize the phpunit on 2.0
  app/phpunit.xml.dist
  src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Launcher/QueueJobLauncherIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModel.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchAncestorsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchSelfAndAncestorsIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/RemoveOptionalAttributeIntegration.php
  src/Pim/Bundle/CatalogBundle/tests/integration/Product/RemoveProductModelIntegration.php
  tests/integration/BatchBundle/Command/BatchCommandIntegration.php
Labels: CI

#9492 Migration guide for CE
  UPGRADE.md
Labels: to review
