Repository akeneo/pim-community-dev, pull requests merged in 2019-10, with the labels that each got.

#10809 Improve makefile
  .circleci/config.yml
  Makefile
Labels: to review

#10825 TIP-1249: Update MySQL requirements
  src/Akeneo/Platform/PimRequirements.php
Labels: to review

#10824 PIM-8854: Merge 3.0 into 3.2
  CHANGELOG-3.0.md
Labels: PULLUP

#10842 PIM-8866: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Channel/Bundle/Doctrine/Query/GetChannelActiveLocaleCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/GetAttributeOptionsMaxSortOrderIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/GetChannelActiveLocaleCodesIntegration.php
Labels: PULLUP

#10820 TIP-1262 Do not use getenv because it returns false in SF 4.3
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
Labels: to review

#10853 PIM-8773: Add missing delegateEvents() in the render of the user-navigation dropdown
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
Labels: to review

#10868 PIM-7691: Users were able to edit their own roles
  CHANGELOG-2.3.md
  src/Pim/Bundle/UserBundle/Form/Type/UserType.php
  src/Pim/Bundle/UserBundle/Resources/config/form_types.yml
  tests/legacy/features/user/edit_user.feature
Labels: to review

#10815 TIP-1262: remove AppKernelTest
  composer.json
  config/services/test/test_services.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Manager/EntityWithVariantVersionIntegration.php
  tests/back/Integration/AppKernelTest.php
  tests/back/Integration/IntegrationTestsBundle/DependencyInjection/AkeneoIntegrationTestsExtension.php
  tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoaderInterface.php
  tests/back/Integration/TestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductModelMediaFileEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListSearchAfterProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/DeleteVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Category/GetDescendentCategoryCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Classification/ClassifyProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/RemovingProductModelFromIndexIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Counter/CountProductsPerCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ProductMassActionRepositoryIntegration.php
  tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
  tests/back/Pim/Enrichment/Integration/EventSubscriber/RemoveCategoryFilterInJobInstanceSubscriberIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardSortedCollectionIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/CompletenessFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ExportCompletenessFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/GridCompletenessFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ParentFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/RemoveProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/CategoryTreeFixturesLoader.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountNotIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountNotIncludingSubCategoriesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetGroupAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductModelAssociationsByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetCategoryCodesByProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetValuesAndPropertiesFromProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetCategoryCodesByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetValuesAndPropertiesFromProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/FlatFileHeaderSpec.php
  tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SearchAttributeEndToEnd.php
  tests/back/Pim/Structure/Integration/Attribute/Query/AttributeIsAFamilyVariantAxisIntegration.php
  tests/back/Pim/Structure/Integration/Remover/AttributeOptionRemoverIntegration.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetLastOperationsIntegration.php
  tests/legacy/features/Behat/Context/DBALPurger.php
Labels: towards SF4

#10860 TIP-1278 Catalog installation
  Makefile
  config/services/behat/parameters.yml
  config/services/pim_parameters.yml
  config/services/test/parameters.yml
  config/services/test_fake/parameters.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
  src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixturePathProvider.php
  src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/JobInstancesConfigurator.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/fixture_loader.yml
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Platform/Specification/Bundle/InstallerBundle/FixtureLoader/FixturePathProviderSpec.php
  tests/back/Platform/Specification/Bundle/InstallerBundle/FixtureLoader/JobInstancesConfiguratorSpec.php
  tests/legacy/features/Context/CatalogConfigurationContext.php
Labels: to review

#10882 PIM-8876: Merge 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletion.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/RangeGuesser.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/ValidNumberRange.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/ValidNumberRangeValidator.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/MediaField.less
  tests/back/Pim/Enrichment/Integration/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletionIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/RangeGuesserSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/ValidNumberRangeValidatorSpec.php
Labels: PULLUP

#10832 Automatically deploy JS legacy code coverage
  .gitignore
  package.json
  tests/legacy/features/Behat/Context/HookContext.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  webpack.config.js
  yarn.lock
Labels: to merge

#10880 PIM-8585: fix incorrect displayed order in attributes groups
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
  tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Labels: to review

#10889 PIM-7691: Users were able to edit their own roles
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  tests/legacy/features/user-management/group/edit_user_group_assignations.feature
  tests/legacy/features/user-management/role/edit_user_role_assignations.feature
Labels: to review

#10911 PIM-8893: update dompdf because the pdf export fail on some products
  CHANGELOG-3.2.md
  composer.json
  composer.lock
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
Labels: to review

#10959 TIP-1327 Fix docker script (wait for elasticsearch)
  docker/wait_docker_up.sh
Labels: to review

#10773 TIP-1263: upgrade Symfony to v4.3
  .gitignore
  composer.json
  composer.lock
  config/bootstrap.php
  config/bundles.php
  config/services/test/test_services.yml
  make-file/dev.mk
  phpstan.neon
  src/Acme/Bundle/AppBundle/Resources/config/savers.yml
  src/Akeneo/Channel/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_indexing.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/AbstractProductValueNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/ValueCollectionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/PropertiesNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/repositories.yml
  src/Akeneo/Platform/Bundle/UIBundle/Normalizer/ConstraintViolationListNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/JobQueueConsumerCommandIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Launcher/QueueJobLauncherIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php
  src/Akeneo/UserManagement/Bundle/Resources/config/context.yml
  src/Oro/Bundle/DataGridBundle/Resources/config/mass_actions.yml
  src/Oro/Bundle/SecurityBundle/Acl/Persistence/AbstractAclManager.php
  symfony.lock
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Channel/EndToEnd/Locale/ExternalApi/FilterLocaleEndToEnd.php
  tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
  tests/back/Integration/TestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductModelMediaFileEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListProductModelWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Export/AbstractExportTestCase.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/ValueCollectionNormalizerSpec.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetLastOperationsIntegration.php
  tests/back/Platform/Specification/Bundle/UIBundle/Normalizer/ConstraintViolationListNormalizerSpec.php
  tests/legacy/features/Behat/Context/ImportExportFileContext.php
  tests/legacy/features/Behat/Context/MassEditJobContext.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Behat/Context/PimContext.php
  tests/legacy/features/Context/FeatureContext.php
  tests/legacy/features/Context/SecurityContext.php
Labels: to review, towards SF4

#10973 TIP-1262: make services public for test env
  tests/back/Integration/IntegrationTestsBundle/AkeneoIntegrationTestsBundle.php
  tests/back/Integration/IntegrationTestsBundle/DependencyInjection/MakeServicesPublicForTestEnv.php
Labels: to review, towards SF4

#10961 PIM-8668: use an Asset Collection attribute as main image
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/generator/media-url-generator.js
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature
  tests/legacy/features/pim/structure/family/import/import_families.feature
Labels: to review
