Repository akeneo/pim-community-dev, pull requests merged in 2020-02, with the labels that each got.

#11513 API-953: Add unit & integration tests
  src/Akeneo/Connectivity/Connection/front/src/audit/api-hooks/use-fetch-connections-audit-data.ts
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connection-form-reducer.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connections-reducer.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/Dashboard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/audit/reducers/dashboard-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/api-hooks/use-create-connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/api-hooks/use-update-connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/reducers/connection-form-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/reducers/connection-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/fetch-result/fetch-result.test.ts
Labels: octopus

#11511 Handle SaaS version
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/twig.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Twig/UpdateExtension.php
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/version.html.twig
  src/Akeneo/Platform/VersionProvider.php
  src/Akeneo/Platform/VersionProviderInterface.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/Twig/UpdateExtensionSpec.php
  tests/back/Platform/Specification/VersionProviderSpec.php
Labels: to review

#11549 PIM-9087: Merge branch 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Checker/DuplicateValueChecker.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/checkers.yml
  src/Akeneo/Tool/Bundle/ApiBundle/spec/Checker/DuplicateValueCheckerSpec.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/legacy/features/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
Labels: PULLUP

#11570 PIM-9097: PULL-UP 4.0 => MASTER
  CHANGELOG-4.0.md
  behat.yml
  composer.json
  composer.lock
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/react/react-controller.ts
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectEventDatesToRefreshQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalEventCountRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/front/src/audit/api-hooks/use-fetch-connections-audit-data.ts
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/Select2.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCreateForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/FlowTypeSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connection-form-reducer.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connections-reducer.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/fetch-result/fetch-result.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/Dashboard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/audit/reducers/dashboard-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/api-hooks/use-create-connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/api-hooks/use-update-connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/reducers/connection-form-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/reducers/connection-reducer.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/fetch-result/fetch-result.test.ts
  src/Akeneo/Connectivity/Connection/tests/Context/Page/Connections/Create.php
  src/Akeneo/Connectivity/Connection/tests/Context/Page/Connections/Index.php
  src/Akeneo/Connectivity/Connection/tests/Context/SettingsContext.php
  src/Akeneo/Connectivity/Connection/tests/Decorator/Settings/CreationForm.php
  src/Akeneo/Connectivity/Connection/tests/features/create_connection.feature
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Platform/PimRequirements.php
  src/Oro/Bundle/TranslationBundle/Resources/config/services.yml
  tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Context/Page/Client/Creation.php
  tests/legacy/features/Context/Page/Client/Index.php
Labels: PULLUP, to review

#11575 PIM-9098: Regression: Product Form / Attribute. The display-position move after clicking SAVE-button
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/attributes.js
  tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Labels: bug, core-team, to review

#11582 API-999: Fix FlowType selector
  src/Akeneo/Connectivity/Connection/front/src/common/components/Select2.tsx
Labels: octopus

#11542 API-953: Add unit tests
  src/Akeneo/Connectivity/Connection/front/src/common/components/button/SecondaryActionsDropdownButton.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Figure.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Helper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/InlineHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Modal.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageContent.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageHeader.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/RuntimeError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Section.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/SmallHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Figure.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Helper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/InlineHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Modal.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageContent.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageHeader.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/RuntimeError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Section.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/SmallHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/Breadcrumb.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/BreadcrumbItem.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/ApplyButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/Button.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/SecondaryActionsButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/ApplyButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/Button.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/SecondaryActionsButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/Form.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/__snapshots__/Form.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/Select.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/__snapshots__/Select.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/EditConnection.test.tsx
Labels: octopus

#11611 #11583: Remove useless GLOB_BRACE flag from standard Kernel
  CHANGELOG-4.0.md
  std-build/Kernel.php
Labels: Community

#11624 Corrected the link to upgrade 3.2 to 4.0
  UPGRADE.md
Labels: contribution, needs-contrib-agreement

#11648 Dockerize storybook
  Makefile
  akeneo-design-system/Makefile
Labels: design-system

#11650 Fix Storybook build config
  akeneo-design-system/.storybook/main.js
  akeneo-design-system/jest.config.js
  akeneo-design-system/package.json
  akeneo-design-system/src/global.d.ts
  akeneo-design-system/tsconfig.json
  akeneo-design-system/yarn.lock
Labels: design-system

#11632 API-1002: Change command/handler + Write model according with the new Auditable field
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/UpdateConnectionCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/UpdateConnectionHandler.php
  src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Write/Connection.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/CreateConnectionCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/ConnectionController.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalConnectionRepository.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryConnectionRepository.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/update_a_connection.feature
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/CountDailyEventsByConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/CommandTestCase.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/DeleteConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/GetConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/ListConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/RegenerateConnectionPasswordEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/RegenerateConnectionSecretEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/UpdateConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/ConnectionLoader.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalConnectionRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalEventCountRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/User/Internal/UpdateUserPermissionsIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/CreateConnectionCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/CreateConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/DeleteConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionPasswordHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionSecretHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/UpdateConnectionCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/UpdateConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Validation/Connection/CodeMustBeUniqueValidatorSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Write/ConnectionSpec.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
Labels: octopus

#11640 API-1003: Change query/handler and read model according the new auditable field
  src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Read/Connection.php
  src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Read/ConnectionWithCredentials.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectConnectionsQuery.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/ListConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/CreateConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Query/FetchConnectionsHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Query/FindAConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Read/ConnectionSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Read/ConnectionWithCredentialsSpec.php
Labels: octopus
