Repository akeneo/pim-community-dev, pull requests merged in 2020-11, with the labels that each got.

#13052 CPM-35: update mysql version
  docker-compose.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectErrorCountPerConnectionQueryIntegration.php
Labels: wip

#13123 DAPI - add key indicators in DQI dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardKeyIndicatorsController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/section.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProgressBar.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/SectionTitle.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/KeyIndicatorsContext.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/KeyIndicatorsTips.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchKeyIndicators.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/UseKeyIndicatorTips.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchKeyIndicators.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/KeyIndicator.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderWithAppContextHelper.tsx
Labels: weasels

#13160 DAPI-1414: Renaming
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ComputeProductsKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicatorsInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/KeyIndicator/ProductsWithGoodEnrichment.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/KeyIndicator/ProductsWithImage.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetProductKeyIndicatorsQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/KeyIndicatorCode.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardKeyIndicatorsController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ComputeProductsKeyIndicatorsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuerySpec.php
Labels: weasels

#13151 DAPI-1419: Change "missing image" recommendation text
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#13170 DAPI-1414: Fix Dashboard key indicators properties
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
Labels: weasels

#13171 DAPI-1417: register 2 new key indicator related filters on the product grid
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/KeyIndicatorFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/KeyIndicatorFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterKeyIndicatorFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#13180 DAPI-1417: redirect on filtered product grid when clicking on a key indicator
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/section.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/CategoryFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/FamilyFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/DashboardContext.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/useInitDashboardContextState.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnCategory.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnFamily.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/__mocks__/pim/datagrid/state.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderDashboardWithProvider.tsx
Labels: weasels

#13190 PIM-9553: Merge branch 4.0 into master
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.zh_CN.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.de_DE.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.zh_CN.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/messages.zh_CN.yml
Labels: PULLUP

#12492 Correct phpdoc
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
Labels: contribution

#12806 replicate fix from v4 to have product asscociation display when their…
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
Labels: contribution

#12805 Bugfix/fix association display
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
Labels: contribution

#13179 DAPI-1427 - fix enrichment sort behavior
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/EnrichmentSorter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
Labels: weasels

#13198 Add sanity check to prevent decoding null json
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryIntegration.php
Labels: weasels

#13200 DAPI-1430 - land to the product grid with products ungrouped
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: weasels

#13201 DAPI-1429 - add traduction for key indicators filters
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: weasels

#13199 DAPI-1431 - update 'more than x products' link
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#13212 Fix InMemoryChannelRepository::getChannelCodes()
  tests/back/Acceptance/Channel/InMemoryChannelRepository.php
  tests/back/Acceptance/spec/Channel/InMemoryChannelRepositorySpec.php
Labels: to review

#13202 DAPI-1414: Fix filter key indicators by category
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
Labels: weasels

#13215 DAPI: display a placehoder when there is no key indicator yet
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/images/empty-key-indicators.svg
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/EmptyKeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
Labels: weasels

#13213 DAPI-1393: update default timelapse to weekly
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
Labels: weasels

#13228 DAPI-1425: Add helper methods to key indicator model
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
Labels: weasels

#13227 DAPI-1367: update family attribute grid filter to use code instead of ids
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/AttributeGridRouter.ts
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/FamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/RegisterFamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Family/GetAllFamiliesLabelByLocaleQuery.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Structure/Component/Query/InternalApi/GetAllFamiliesLabelByLocaleQueryInterface.php
  tests/back/Pim/Structure/Integration/Family/GetAllFamiliesLabelByLocaleQueryIntegration.php
Labels: weasels

#13233 DAPI-1367: always display all key indicators
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/LocaleCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.ts
Labels: weasels

#13229 DAPI-1422: Missing image - recommendations improvements on current devs
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Axis/AxisError.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Axis/AxisHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Axis/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Attribute.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/AttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/EnrichmentImageMessage.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Recommendation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/RecommendationWithAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/TooManyAttributesLink.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/constant/FamilyEditForm.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/constant/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/CriterionHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/EvaluationHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/RateHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/RecommendationHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followAttributeRecommendation.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followNotApplicableEnrichmentImageRecommendation.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Attribute.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/TooManyAttributesLink.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/ChangeTimePeriod.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/ProductEvaluationTab/DisplayAxisEvaluation.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderCriterion.tsx
Labels: weasels

#13250 DAPI-1412 - fix key indicator missing image
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuerySpec.php
Labels: weasels

#13146 DAPI-1353: declare icons for recommendations in the DQI tab of the PEF
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Criterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Icon.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Title.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderCriterion.tsx
Labels: weasels

#13256 Add migration script to add dynamic templates for dqi key indicator a…
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
  upgrades/schema/Version_5_0_20201116133700_dqi_put_elasticsearch_mapping.php
Labels: weasels

#13246 DAPI: deactivate key indicator related visible features
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
Labels: weasels

#13279 DAPI reduce queries key indicators
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/Enrichment/EvaluateCompleteness.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CompletenessCalculationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductCompleteness.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/Enrichment/EvaluateCompletenessSpec.php
  upgrades/schema/Version_5_0_20201118150500_dqi_reset_enrichment_evaluations.php
Labels: weasels

#13283 DAPI-1397: Adaptations to get product evaluation with unique score
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/ProductEvaluation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEmptyScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetLatestProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetLatestProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/ProductScoreRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
Labels: weasels

#13281 Dapi 1439 - Migration script for already consolidated axis
  upgrades/schema/Version_5_0_20201117133700_add_dqi_unique_score_tables.php
  upgrades/schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score.php
  upgrades/schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection.php
  upgrades/test_schema/Version_5_0_20201117133700_add_dqi_unique_score_tables_Integration.php
  upgrades/test_schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score_Integration.php
  upgrades/test_schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection_Integration.php
Labels: weasels

#13278 PIM-9550: add integration tests on internal services used by the command "pim:product:clean-removed-attributes"
  config/services/test/test_services.yml
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  tests/back/Common/EntityWithValue/Builder/Product.php
  tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsAndProductModelsWithInheritedRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Product/CleanValuesOfRemovedAttributesSpec.php
Labels: bug, core-team

#13297 DAPI-1436 - reactivate key indicators
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
Labels: weasels

#13298 DAPI-1397: Index product score in ES
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/ChannelLocaleRateCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
Labels: weasels

#13300 PIM-9565: Quick export modify empty Boolean value
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverterSpec.php
Labels: bug

#13292 PIM-9554 Discrepancy on the user dashboard due to difference between UI locale and catalog locale
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useGetAttributeGroupLabel.ts
Labels: bug

#13181 PIM-9540: do not strip HTML tags on textara content before index them in ES
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/TextAreaNormalizer.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogTestCase.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/PimCatalogTextAreaIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/TestData/VeryLongText.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/TextArea/TextAreaFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/Value/TextAreaNormalizerSpec.php
Labels: bug, core-team

#13293 DAPI-1347: remove axes rates from PEF sidebar
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/data-quality-insights-overview.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/Sidebar/AxisRatesOverview.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/Sidebar/AxisRatesOverviewPortal.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/Sidebar/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
Labels: weasels

#13294 DAPI-1349: display product quality score in PEF header
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductQualityScoreController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/data-quality-insights-app.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/product-model-quality-score.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/product-quality-score.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScorePortal.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreBar.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/ProductEditForm/ProductContextListener.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/ProductQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchProductQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchProductAxisRates.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchProductQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useProductAxesRates.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
Labels: weasels

#13308 DAPI-1444: Replace axis rate by unique score in the product-grid
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/EnrichmentFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Sorter/EnrichmentSorter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Sorter/QualityScoreSorter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/AddProductModelScoreProperty.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/AddProductScoreProperty.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/FetchEnrichmentForProductRows.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/QualityScoreSorter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterQualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/datagrid/custom_product_enrichment.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/ProductGrid/RegisterQualityScoreFilterSpec.php
Labels: weasels

#13317 DAPI-1348: remove axis scores on DQI tab evaluation
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Axis/AxisHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/EvaluationHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/EvaluationHelper.unit.ts
Labels: weasels

#13318 Dapi 1437 - When coming from a KI, the product grid should display the Quality Score column
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: weasels

#13323 Dapi 1346 - As a PM, in the product grid, I want one column with Quality Score to replace E&C scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/datagrid/custom_product_enrichment.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/quality-score-badge-cell.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/rate-badge-cell.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScore.tsx
Labels: weasels

#13326 Fix migration script to handle empty tables of evaluation/consolidation
  upgrades/schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score.php
  upgrades/schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection.php
  upgrades/test_schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score_Integration.php
  upgrades/test_schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection_Integration.php
Labels: weasels

#13334 DAPI-1351: Visualize the distribution of the data quality score from the product catalog on the dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Charts/EmptyChartPlaceholder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Charts/Header.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Charts/TimePeriodAxisChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/CategoryModal.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/CategoryTreeNode.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Overview.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/EmptyChartPlaceholder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Legend.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChartByTimePeriod.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Tooltip.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Filters/CategoryFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Filters/FamilyFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Filters/TimePeriodFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Filters/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/FormatBackendRanksToVictoryFormat.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/Score.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchDqiDashboardData.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/CalculateAverageGrade.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/FormatBackendRanksToVictoryFormat.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/ChangeTimePeriod.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnCategory.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnFamily.unit.tsx
Labels: weasels

#13324 DAPI-1435: Missing image - improvements when coming from link "no image attribute or asset collection for family"
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/family/edit.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/pim-view/back-link.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/BackLinkButton.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followNotApplicableEnrichmentImageRecommendation.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
Labels: weasels

#13332 PIM-9572: Merge branch 4.0 into master
  .prettierignore
  CHANGELOG-4.0.md
  config/services/test/test_services.yml
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Product/CleanValuesOfRemovedAttributes.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/product_values.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsAndProductModelsWithInheritedRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductModelsWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsAndProductModelsWithInheritedRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductIdentifiersWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductModelIdentifiersWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/ValuesRemover/CleanValuesOfRemovedAttributesInterface.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  tests/back/Acceptance/Channel/InMemoryChannelRepository.php
  tests/back/Acceptance/spec/Channel/InMemoryChannelRepositorySpec.php
  tests/back/Common/EntityWithValue/Builder/Product.php
  tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsAndProductModelsWithInheritedRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Product/CleanValuesOfRemovedAttributesSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverterSpec.php
  tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepositoryApiResourceIntegration.php
  yarn.lock
Labels: PULLUP

#13344 DAPI-1345: As a PM, in the dashboard, I want one column with Quality Score to replace E&C scores in the widgets (family and category)
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetAverageRanksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardWidgetCategoriesController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/grid.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/index.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/AddItem.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/CategoryWidget.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/FamilyWidget.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/RemoveItem.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/SeeInGrid.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/Table.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetAverageRanksQueryIntegration.php
Labels: weasels

#13352 DAPI: use the new table to consolidate product scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateDashboardRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetDashboardScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/DashboardScoresProjectionRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetAverageRanksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetDashboardScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/DashboardScoresProjectionRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardOverviewController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/repositories.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetAverageRanksQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetDashboardScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/DashboardScoresProjectionRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/ConsolidateDashboardRatesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Symfony/Controller/Dashboard/DashboardOverviewControllerSpec.php
Labels: weasels

#13357 DAPI-1351: fix hidden filters issue when Score distribution is not valid
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChartByTimePeriod.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
Labels: weasels

#13345 DAPI-1354: display quality score evolution in a new chart on the DQI dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/CatalogQualityScoreEvolution.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/DashboardRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetCatalogProductScoreEvolutionQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetCatalogProductScoreEvolutionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/AddProductScoreProperty.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardQualityScoreEvolutionController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/EmptyChartPlaceholder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/SectionTitle.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChartByTimePeriod.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchQualityScoreEvolution.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchQualityScoreEvolution.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/CatalogQualityScoreEvolutionSpec.php
Labels: weasels

#13366 DAPI-1449: fix "display all missing attributes" filter
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/attribute-filter-all-missing-attributes.ts
Labels: weasels

#13380 DAPI-1438: change the "not applicable" criterion message
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Recommendation.tsx
Labels: weasels

#13364 DAPI-1398: remove dead code related to axes
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ComputeAxisRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateAxesRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductAxesRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductAxesRatesInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/AxisRegistry.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/AxisRegistryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Axis.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Axis/Enrichment.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/AxisEvaluation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/AxisEvaluationCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/AxisRankCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/AxisRateCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/CriterionEvaluationCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/ProductAxisRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestAxesRatesQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductAxesRanksQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/ProductAxisRateRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/AxisCode.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PurgeOutdatedDataTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetLatestAxesRatesQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetLatestProductAxesRanksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestAxesRatesQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductAxesRanksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductAxisRateRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductAxesRatesController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/repositories.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/ProductAxesRates.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchProductAxisRates.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/ProductEditForm/productAxesRatesReducer.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/store/productEditFormStore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetLatestAxesRatesQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetLatestProductAxesRanksQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/ProductAxisRateRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/ComputeAxisRatesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductAxesRatesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Axis/Consistency.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/CatalogQualityScoreEvolutionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/CriterionEvaluationCollectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestAxesRatesQuerySpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductAxesRanksQuerySpec.php
Labels: weasels

#13388 DAPI-1368: fix project creation with quality score
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
Labels: weasels

#13386 PIM-9581: Merge 3.2 into 4.0
  CHANGELOG-3.2.md
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
Labels: PULLUP

#13370 DAPI-1351: fix tooltip issues
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Summary.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Tooltip.tsx
Labels: weasels

#13402 DAPI-1438: fix unit tests with not applicable recommendation
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/ProductEvaluationTab/ClickOnAnAttributeWithRecommandation.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/ProductEvaluationTab/DisplayAxisEvaluation.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttribute.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAxisEvaluation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderCriterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderRecommendationWithAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderTooManyAttributesLink.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderWithProductEditFormContextHelper.tsx
Labels: weasels
