Repository akeneo/pim-community-dev, pull requests merged in 2020-10, with the labels that each got.

#12869 DAPI-1288: make attribute groups grid filterable
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/NoSearchResult.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DraggableRowWrapper.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/HeaderRow.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableContainer.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableHeadCell.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/providers/DataGridStateProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDataGridState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDataGridState.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
Labels: weasels

#12894 DAPI-1287 / DAPI-1314: add DQI status badges on attribute groups grid
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Structure/GetAllAttributeGroupsActivationQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Structure/GetAllAttributeGroupsActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetAllAttributeGroupsActivationController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/index.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/quality-badges.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/NoSearchResult.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DraggableRowWrapper.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/HeaderRow.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableContainer.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableHeadCell.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/providers/DataGridStateProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsDataGridState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDataGridState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/fetchers/attributeGroupDqiStatusFetcher.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/fetchers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/__mocks__/pim/feature-flags.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupsDataGridState.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDataGridState.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideAttributeGroupHelper.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
Labels: weasels

#12911 PIM-9484: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
Labels: PULLUP

#12914 PIM-9487: Merge branch 4.0 into master
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
  tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
Labels: PULLUP

#12480 pass bubble exception for attribute remove action.
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
Labels: contribution

#12935 DAPI-1243 - Add the ACL in a dedicated dqi group
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl_groups.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: weasels

#12920 DAPI-1290: display evaluated attribute groups on DQI tab
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/images/QualityScore.svg
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/NoAttributeGroups.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/AttributeGroup/attributeGroupDqiStatusFetcher.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/AttributeGroup/attributeGroupsFetcher.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.unit.tsx
Labels: weasels

#12973 DAPI-1283: Re-evaluate products impacted by attribute group activation updates
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateMissingCriteriaEvaluations.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/MarkCriteriaToEvaluate.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/MarkCriteriaToEvaluateInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductModelsCriteriaEvaluationTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductsCriteriaEvaluationTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CreateMissingCriteriaEvaluationsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/MarkCriteriaToEvaluateSpec.php
  upgrades/schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation.php
Labels: weasels

#12980 Dapi 1376 optimize evaluation possible within 30 min window
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductModelsCriteriaTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsCriteriaTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
Labels: weasels

#12978 DAPI-1290: display attribute group helper also on product models
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.unit.tsx
Labels: weasels

#12996 DAPI-1376: Interrupt evaluation job when there is nothing left to evaluate...
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php
Labels: weasels

#13019 DAPI-1406: fix no attribute group message when a product evaluation has not been refreshed
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.unit.tsx
Labels: weasels

#13016 DAPI-1407: Fix get products to re-evaluate because attribute-group activation
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQueryIntegration.php
Labels: weasels

#12961 DAPI-1386: update style for badges
  akeneo-design-system/src/components/Badge/Badge.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/complete-variant-product.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Badge.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/product-completeness.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/variant-navigation/product-item.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/variant-navigation/product-model-item.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product_model/complete-variant-product.html
  src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/cell/enabled-cell.html
  tests/legacy/features/Behat/Context/Domain/Enrich/CompletenessContext.php
  tests/legacy/features/pim/enrichment/product-model/complete_variant_product.feature
  tests/legacy/features/pim/enrichment/product/completeness/completeness_dropdown.feature
  tests/legacy/features/pim/enrichment/product/completeness/display_completeness.feature
Labels: weasels

#11569 TIP-1233: upgrade to PHP 7.4
  .circleci/config.yml
  .circleci/detect_structure_changes.sh
  CHANGELOG.md
  Dockerfile.base
  Dockerfile.dev
  composer.json
  composer.lock
  docker-compose.yml
  docker/build/docker-php-entrypoint
  make-file/test.mk
  src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/MetricComparator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/ScalarComparator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/AttributeColumnInfoExtractor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Copier/AttributeCopier.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Copier/MetricAttributeCopier.php
  src/Akeneo/Platform/PimRequirements.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
  symfony.lock
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/AttributeCopierSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/MetricAttributeCopierSpec.php
  tests/legacy/features/Context/Page/Attribute/Creation.php
Labels: contribution

#13047 DAPI-1339: Consolidate unit tests before adding recommendation on images
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesListWithVariations.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/RecommendationAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/Evaluation.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/Product.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Attribute.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesList.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesListWithVariations.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/TooManyAttributesLink.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/provider/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/provider/provideCatalogHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/provider/provideProductEvaluationHelper.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttribute.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttributesList.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderCriterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderTooManyAttributesLink.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderWithAppContextHelper.tsx
Labels: weasels

#13093 DAPI-1374: Implement key indicator query for products with image
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithAnImageQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithImageQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithImageQuerySpec.php
Labels: weasels

#12998 DAPI-1374: Index product key indicators in ES
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductsKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetProductsKeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/IndexProductRates.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithImageQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/GetProductsEnrichmentStatusQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductsKeyIndicatorsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithImageQuerySpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
Labels: weasels, wip
