Repository akeneo/pim-community-dev, pull requests merged in 2020-12, with the labels that each got.

#13407 DAPI: fix integration tests on unique score feature
  src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php
Labels: weasels

#13394 DAPI-1447: Move the Category and Family filters in the header of the dashboard page
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/dqi_dashboard/dqi_dashboard.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/dashboard-filters.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/CategoryFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/FamilyFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/TimePeriodFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/ChangeTimePeriod.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnCategory.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnFamily.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
Labels: weasels

#13396 PIM-9582: Merge 4.0 into master
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/GroupSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/GroupUpdater.php
  src/Akeneo/Pim/Structure/Bundle/Event/AttributeEvents.php
  src/Akeneo/Pim/Structure/Bundle/EventListener/RemoveNonExistingProductValuesSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/SqlCreateJobInstance.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Component/Batch/Query/CreateJobInstanceInterface.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/navigate-action.js
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/GroupSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/GroupUpdaterSpec.php
  tests/back/Pim/Structure/Specification/Bundle/EventListener/RemoveNonExistingProductValuesSubscriberSpec.php
Labels: PULLUP

#13410 DAPI: display quality score column & filter only when feature flag is active and allow quallity score to be used as default filter
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterQualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterQualityScoreFilterAndColumn.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/datagrid/custom_product_enrichment.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: weasels

#13419 DAPI - fix enrichment filter and image filter behavior with projects
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
Labels: weasels

#13414 DAPI-1453: UI improvements for the dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Legend.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/FormatDateWithUserLocale.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/FormatDateWithUserLocale.unit.ts
Labels: weasels

#13423 DAPI: fix unique score feedbacks
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/EnrichmentImageMessage.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Recommendation.tsx
Labels: weasels

#13453 DAPI-1418: Deport data migration into a command
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/MigrateProductCriterionEvaluationCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  upgrades/schema/Version_5_0_20201201095420_dqi_rework_evaluations_storage.php
Labels: weasels

#13425 DAPI-1446: Adaptations for family evaluation
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/CriterionEvaluationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/FamilyId.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/CriterionEvaluationRepository.php
Labels: weasels

#13455 DAPI-1454: Fix product model creation in integration tests
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
Labels: weasels

#13468 DAPI-1457: Regression on DQI Dashboard - Key indicator attribute spelling do not work as expected
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/dashboard-filters.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/section.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/CategoryFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/FamilyFilter.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/DashboardContext.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/useInitDashboardContextState.ts
Labels: weasels

#13471 Fix CleanRemovedAttributesFromProductAndProductModelCommand dependency with EventDispatcher
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
Labels: bug

#13449 Add React hooks for using debounced value or callback
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useDebounce.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/tools/debounce.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/tools/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useDebounce.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/tools/debounce.unit.ts
Labels: weasels

#13477 DAPI-1304: Add helper which explain that locales are activated in channels screen
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx
Labels: weasels

#13482 DAPI-1392: Change format and filter by channel/locales
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
Labels: weasels

#13408 DAPI-1377 & DAPI-1466: Reduce DQI database size
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/CriterionEvaluationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/CriterionEvaluationRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/FamilyId.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/JobLauncher/RunUniqueProcessJob.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RemoveEvaluationsWithoutProductTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsToEvaluateQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsToEvaluateQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/CriterionEvaluationRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductCriterionEvaluationRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductModelCriterionEvaluationRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultTransformationFailedException.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/MigrateProductCriterionEvaluationCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/DependencyInjection/AkeneoDataQualityInsightsExtension.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/repositories.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/transformation.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetPendingCriteriaEvaluationsByProductIdsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductIdsToEvaluateQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductModelIdsToEvaluateQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/ProductCriterionEvaluationRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/ProductModelCriterionEvaluationRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Transformation/TransformCriterionEvaluationResultCodesIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Transformation/TransformCriterionEvaluationResultIdsIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsSpec.php
  upgrades/schema/Version_5_0_20201201095420_dqi_rework_evaluations_storage.php
Labels: Feature branch, weasels

#13426 DAPI-1392: add product quality scores in API
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductScoresByIdentifiersQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetLatestProductScoresByIdentifiersQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetLatestProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQuery.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductListSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductsQueryHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
Labels: weasels

#13505 AOB-1234: Implement InMemoryProductRepository::findAll()
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
Labels: to review

#13506 DAPI: fix family filter "All" on dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/useInitDashboardContextState.ts
Labels: weasels

#13511 DAPI-1392: Fix API end-to-end tests
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
Labels: weasels

#13504 DAPI-1462: fix redirect on attribute grid when dashboard is filtered on category
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
Labels: weasels

#13520 Fix "in memory" channel repository
  tests/back/Acceptance/Channel/InMemoryChannelRepository.php
Labels: to review

#13522 DAPI: Fix linter issue on KeyIndicator component
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
Labels: CI, weasels

#13509 DAPI-1461: Update template for Forgotten password pages
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/_fields.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/request.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/reset.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/sendEmail.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Security/login.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: weasels

#13507 DAPI-1460: Update template for Login page
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/login/Artboard.png
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/login/Logo.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/_fields.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/request.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/reset.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/sendEmail.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Security/login.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: weasels

#13540 DAPI-1467: Add command to initialize products criteria evaluations
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/InitializeProductsEvaluationsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
Labels: weasels

#13472 DAPI-1458: Cleaning
  config/packages/dev/monolog.yml
  config/packages/monolog.yml
  config/packages/test/monolog.yml
  config/packages/test_fake/monolog.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/LogMetricsTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  upgrades/schema/Version_5_0_20201208134018_dqi_drop_deprecated_tables.php
Labels: weasels

#13564 Update docker-compose.override.yml.dist
  docker-compose.override.yml.dist
Labels: to review

#13327 DAPI-1444: remove fallback on quality score sorter and filter
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Sorter/QualityScoreSorter.php
Labels: weasels

#13565 DAPI: fix homepage logo not displayed in firefox
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: weasels

#13595 PIM-9607: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
Labels: PULLUP

#13620 PIM-9612: Fix no image preview for Association with quantities when the image is an asset collection
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/useProductThumbnail.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/utils.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/hooks/useProductThumbnail.unit.tsx
Labels: to review
