Repository akeneo/pim-community-dev, pull requests merged in 2020-07, with the labels that each got.

#12390 DAPI-1115 fix color impact
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
Labels: weasels

#12379 DAPI-1085: Fix css bug when collapsed panel
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/public/bridge/view/panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/public/less/components/Panel.less
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Header.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/ListAnnouncement.tsx
Labels: communication-channel, to review

#12367 GITHUB-APD-163: Add infinite scroll
  make-file/communication-channel.mk
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsHandler.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsQuery.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindAnnouncementItemsInterface.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/InMemoryFindAnnouncementItems.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/ListAction.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Announcement/ListAnnouncementIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/ListAnnouncementsHandlerSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/actions/infiniteScrollActions.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/ListAnnouncement.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/fetcher/announcementFetcher.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/hooks/useAnnouncements.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/hooks/useInfiniteScroll.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/reducers/infiniteScrollReducer.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/fetcher/announcementFetcher.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/hooks/useAnnouncements.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/hooks/useInfiniteScroll.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/reducers/infiniteScrollReducer.unit.ts
Labels: communication-channel, to review

#12396 PIM-9340: Merge branch 4.0 into master
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.pl_PL.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.pl_PL.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/locale_provider.yml
Labels: PULLUP

#12382 TIP-1493: launch a "regular CE build" from the same PR workflow
  .circleci/config.yml
Labels: to review

#12380 GITHUB-APD-178: Add akeneo_communication_channel_announcements_viewed table
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/DependencyInjection/AkeneoCommunicationChannelExtension.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Installer/InstallerSubscriber.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Installer/Query/CreateViewedAnnouncementsTableQuery.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/installer.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/.php_cd.php
  upgrades/schema/Version_5_0_20200630044018_create_communication_channel_viewed_announcements_table.php
Labels: communication-channel, to review

#12420 PIM-9320: Merge 3.0 into 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
Labels: PULLUP

#12395 DAPI-1118: Preserve the selection of the catalogLocale when we navigate from the product edit form
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
Labels: core-team, weasels

#12426 PIM 9345: Merge 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  composer.lock
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  symfony.lock
Labels: PULLUP

#12432 GITHUB-APD-186: Rename in FileStorage query instead of InMemory
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindAnnouncementItems.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindNewAnnouncementIds.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/serenity-updates.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/announcement_list.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/has_new_announcements.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Delivery/InternalApi/Announcement/ListAnnouncementsActionIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Resources/config/in_memory.yml
Labels: communication-channel, to review

#12421 TIP-1492: test_upgrade_from_serenity_to_master is stable now
  .circleci/config.yml
Labels: to review

#12431 DAPI-1191: Regression on attribute grid search
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/grid.js
Labels: bug, weasels

#12434 PIM-9346: Merge 4.0 into master
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  composer.lock
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  symfony.lock
Labels: PULLUP

#12433 GITHUB-APD-188: Update to fetch announcements only when we open the panel
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/reducers/infiniteScrollReducer.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/reducers/infiniteScrollReducer.unit.ts
  tests/front/unit/jest/unit.jest.js
Labels: communication-channel, to review

#12444 GITHUB-APD-193: Add README to explain useful commands on the BC
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/README.md
Labels: communication-channel, to review

#12463 DAPI-1217: Fix pagination & configure columns button
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
Labels: weasels

#12469 PIM-9354: Merge 4.0 into master
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf1.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf2.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf3.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
Labels: PULLUP

#12477 PIM-9352: Merge branch 3.0 into 3.2
  CHANGELOG-3.0.md
Labels: PULLUP

#12483 PIM 9353: Merge 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
Labels: PULLUP

#12101 DAPI-921: attribute spellcheck feature branch
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/FamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/RegisterFamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/EditingOptionContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptionsListState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useEditingOptionContextState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useScrollIntoView.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/AttributeOption.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsExtraDataReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/grid.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/common/default-template.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
  src/Akeneo/Tool/Bundle/VersioningBundle/UpdateGuesser/AttributeOptionUpdateGuesser.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/FamilyFilterSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/RegisterFamilyFilterSpec.php
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
  tests/front/unit/structure/attribute-option/hooks/useAttributeOptionsListState.unit.tsx
  tests/front/unit/structure/attribute-option/hooks/useEditingOptionContextState.unit.ts
  tests/front/unit/structure/attribute-option/hooks/useScrollIntoView.unit.ts
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsExtraDataReducer.unit.tsx
Labels: weasels

#12443 GITHUB-APD-150: Add queries to fetch data from the external service
  .env
  composer.json
  composer.lock
  config/services/behat/services.yml
  config/services/pim_parameters.yml
  config/services/test/test_services.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/HasNewAnnouncementsHandler.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/HasNewAnnouncementsQuery.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsHandler.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsQuery.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindAnnouncementItemsInterface.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindNewAnnouncementIdsInterface.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/Api/ApiFindAnnouncementItems.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/Api/ApiFindNewAnnouncementIds.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindAnnouncementItems.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindNewAnnouncementIds.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/serenity-updates.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/HasNewAnnouncementsAction.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/ListAnnouncementsAction.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/announcement_list.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/has_new_announcements.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/.php_cd.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindAnnouncementItemsIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindNewAnnouncementIdsIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/firstAnnoucements.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/newAnnouncements.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/nextAnnoucements.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Delivery/InternalApi/Announcement/AddViewedAnnouncementsActionIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Delivery/InternalApi/Announcement/ListAnnouncementsActionIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/HasNewAnnouncementsHandlerSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/ListAnnouncementsHandlerSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Domain/Announcement/Model/Read/AnnouncementItemSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/fetcher/announcementFetcher.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/hooks/useInfiniteScroll.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/fetcher/announcementFetcher.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/hooks/useInfiniteScroll.unit.tsx
  symfony.lock
Labels: communication-channel

#12517 PIM-9378: Merge branch 4.0 into master
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetValuesAndPropertiesFromProductIdentifiers.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
Labels: PULLUP
