Repository akeneo/pim-community-dev, pull requests merged in 2020-04, with the labels that each got.

#11887 PIM-9171: Merge branch 3.0 into 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Query/Sql/EmailDomains.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Platform/Acceptance/Analytics/Query/Sql/EmailDomainsInMemory.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
Labels: PULLUP

#11890 MET-179: Fix locale flag being displayed on measurement attributes
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/metric-field.js
Labels: to review

#11899 MET-158: Refactor Helper/Warning component, add HelperRibbon
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ErrorFlashMessage.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/HelperRibbon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SubsectionHelper.tsx
Labels: to review

#11897 Pullup api 1025
  src/Akeneo/Connectivity/Connection/back/Application/Audit/Query/CountDailyEventsByConnectionHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Audit/Query/CountDailyEventsByConnectionQuery.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/DailyEventCount.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/HourlyEventCount.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/PeriodEventCount.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/WeeklyEventCounts.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/SelectConnectionsEventCountByDayQuery.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/SelectPeriodEventCountsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/AggregateProductEventCounts.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectPeriodEventCountsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/WeeklyAuditEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectPeriodEventCountsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Query/CountDailyEventsByConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Query/CountDailyEventsByConnectionQuerySpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/DailyEventCountSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/HourlyEventCountSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/PeriodEventCountSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Audit/AggregateProductEventCountsSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Install/FileSystemAssetsInstallerSpec.php
Labels: octopus

#11898 PIM-9172: Merge branch 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizer.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/product-model-fetcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.it_IT.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
Labels: PULLUP

#11881 PIM-9147: clean completeness on delete
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnDelete/DeleteCompletenessSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/removers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/CompletenessRemover.php
  tests/back/Pim/Enrichment/Integration/Completeness/RemoveCompletenessWhenDeletingProductIntegration.php
Labels: to review

#11924 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: Community

#11889 TIP-1403: Feature Flag system
  config/bundles.php
  config/packages/akeneo_feature_flag.yml
  config/routes/routes.yml
  frontend/build/update-extensions.js
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundle.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/EnvVarFeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/AkeneoFeatureFlagExtension.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/Configuration.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/FeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/FeatureFlags.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Controller.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/FilterRoutesSubscriber.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Registry.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/feature-flags.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/config-provider.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
  tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Configuration/EnvVarFeatureFlagSpec.php
  tests/back/Platform/Specification/Bundle/FeatureFlagBundle/FeatureFlagsSpec.php
  tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Internal/RegistrySpec.php
  tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
Labels: to review

#11907 MET-146: use flysystem to cache thumbnails
  config/packages/behat/oneup_flysystem.yml
  config/packages/dev/oneup_flysystem.yml
  config/packages/liip_imagine.yml
  config/packages/oneup_flysystem.yml
  config/packages/prod/oneup_flysystem.yml
  config/packages/prod_onprem_paas/oneup_flysystem.yml
  config/packages/test/oneup_flysystem.yml
  config/packages/test_fake/oneup_flysystem.yml
Labels: to review

#11955 PIM-9191: Merge branch 3.0 into 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Tool/Component/Localization/Presenter/DatePresenter.php
  src/Akeneo/Tool/Component/Localization/spec/Presenter/DatePresenterSpec.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
Labels: PULLUP

#11962 PIM-9210: Merge branch 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/FindAttributeCodesForAttributeGroup.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html
  src/Akeneo/Tool/Component/Localization/Presenter/DatePresenter.php
  src/Akeneo/Tool/Component/Localization/spec/Presenter/DatePresenterSpec.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
  tests/back/Pim/Structure/Integration/AttributeGroup/Query/SqlFindAttributeCodesForAttributeGroupIntegration.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/InternalApi/AttributeGroupNormalizerSpec.php
Labels: PULLUP

#11976 PIM-9215: Merge branch 4.0 into master
  CHANGELOG-4.0.md
  Dockerfile.base
  composer.json
  composer.lock
  config/packages/behat/oneup_flysystem.yml
  config/packages/dev/oneup_flysystem.yml
  config/packages/liip_imagine.yml
  config/packages/oneup_flysystem.yml
  config/packages/prod/oneup_flysystem.yml
  config/packages/prod_onprem_paas/oneup_flysystem.yml
  config/packages/test/oneup_flysystem.yml
  config/packages/test_fake/oneup_flysystem.yml
  docker-compose.yml
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Pim/Enrichment/Component/Product/Localization/Localizer/AttributeConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/FindAttributeCodesForAttributeGroup.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/product-model-fetcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/attributes/validation-error.html
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.it_IT.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
  src/Akeneo/Tool/Component/Localization/Presenter/DatePresenter.php
  src/Akeneo/Tool/Component/Localization/spec/Presenter/DatePresenterSpec.php
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductNormalizer.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
  src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
  tests/back/Acceptance/Resources/config/behat/services.yml
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Localization/Localizer/AttributeConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php
  tests/back/Pim/Structure/Integration/AttributeGroup/Query/SqlFindAttributeCodesForAttributeGroupIntegration.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/InternalApi/AttributeGroupNormalizerSpec.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
  tests/parallel_api_calls/README.md
  tests/parallel_api_calls/parallel_api_calls.php
  upgrades/schema/Version_4_0_20200415194400_remove_product_foreign_key_pim_catalog_completeness.php
Labels: PULLUP

#11991 PIM-9212: Keep vertical scroll position of the attribute form after editing values
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
Labels: to review

#11997 AOB-925: Fix front-end override capabilities
  frontend/webpack/requirejs-utils.js
Labels: wip

#12014 PIM-9225: Merge branch 4.0 into master
  CHANGELOG-4.0.md
  composer.json
  composer.lock
  frontend/webpack/requirejs-utils.js
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Platform/CommunityVersion.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjectionSpec.php
Labels: PULLUP

#12015 GITHUB-11995: Fixes invalid Jquery generic type (#11995)
  CHANGELOG-3.2.md
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
  yarn.lock
Labels: Community
