Repository akeneo/pim-community-dev, pull requests merged in 2020-03, with the labels that each got.

#11663 Move services definitions to Enrichment
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/archivers.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/archiving.yml
Labels: to review

#11667 Pull up 4 into master
  CHANGELOG-4.0.md
  src/Akeneo/Connectivity/Connection/front/src/common/components/button/SecondaryActionsDropdownButton.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Figure.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Helper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/InlineHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Modal.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageContent.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageHeader.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/RuntimeError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Section.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/SmallHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Figure.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Helper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/InlineHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Modal.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageContent.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageHeader.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/RuntimeError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Section.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/SmallHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/Breadcrumb.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/BreadcrumbItem.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/ApplyButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/Button.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/SecondaryActionsButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/ApplyButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/Button.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/SecondaryActionsButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/Form.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/__snapshots__/Form.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/Select.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/__snapshots__/Select.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/EditConnection.test.tsx
  std-build/Kernel.php
Labels: PULLUP

#11674 Move migrations
  .circleci/detect_structure_changes.sh
  upgrades/schema/Version_4_0_20190801083247_remove_indexes.php
  upgrades/schema/Version_4_0_20190801084247_remove_native_json_type.php
  upgrades/schema/Version_4_0_20190813091149_remove_missing_attributes_and_ratio_from_completeness.php
  upgrades/schema/Version_4_0_20190822090606_update_empty_raw_values.php
  upgrades/schema/Version_4_0_20191013162543_update_user_table.php
  upgrades/schema/Version_4_0_20191014111427_create_connection_table.php
  upgrades/schema/Version_4_0_20191031000000_modify_session_lifetime_type.php
  upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
  upgrades/schema/Version_4_0_20191202144736_create_app_audit_table.php
  upgrades/schema/Version_4_0_20191223132437_data_quality_insights_add_dynamic_template.php
  upgrades/schema/Version_4_0_20200113145800_fix_versioning_indexes.php
  upgrades/schema/Version_4_0_20200116122239_remove_product_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs.php
  upgrades/test_schema/Version_4_0_20191031124707_update_from_clients_to_connections_Integration.php
  upgrades/test_schema/Version_4_0_20200116122239_remove_product_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
Labels: to review

#11683 PIM-9126: Pull-up 3.2 -> 4.0
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/jstree/jquery.jstree.tree_selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
Labels: PULLUP

#11691 PIM-9127: Merge branch 4.0 into master
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/jstree/jquery.jstree.tree_selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
  src/Akeneo/Platform/CommunityVersion.php
Labels: PULLUP

#11657 Add design system CI configuration for tests
  .circleci/config.yml
  akeneo-design-system/Makefile
Labels: design-system

#11689 MET-36: Rename Metric to Measurement in attributes UI
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  tests/back/Channel/Integration/Channel/Validation/ChannelValidationIntegration.php
  tests/back/Pim/Structure/Integration/Family/CreateFamilyVariantIntegration.php
  tests/legacy/features/pim/structure/attribute/display_available_field_options.feature
Labels: wip

#11678 API-1010: Change collect of Audit Data Source events to support Timezone
  make-file/connectivity-connection.mk
  src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateProductEventCountCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateProductEventCountHandler.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/HourlyInterval.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Write/HourlyEventCount.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/ExtractConnectionsProductEventCountQuery.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Repository/EventCountRepository.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/MigrateAudit40Master.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionAuditTableQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectEventDatesToRefreshQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectHourlyIntervalsToRefreshQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalEventCountRepository.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/install.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/AuditLoader.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Install/MigrateAudit40MasterIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectEventDatesToRefreshQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectHourlyIntervalsToRefreshQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalEventCountRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/loaders.yml
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Command/UpdateProductEventCountCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/HourlyIntervalSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Write/DailyEventCountSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Write/HourlyEventCountSpec.php
Labels: octopus

#11712 MET-32: As Julia, I can display all the measurement families
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/routing.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/controller/settings.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/dependencies.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/legacy/pim-view/PimView.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/legacy/pim-view/view-builder.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/legacy/translator.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/legacy-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/router-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/translate-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/user-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-families.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/index.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/index/Index.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/MeasurementFamilyRow.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/index.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Caret.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/NoData.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageContent.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ResultCount.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SearchBar.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/helper.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/link.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/search.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/illustrations/MeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/measurement-family.unit.ts
Labels: wip

#11729 PIM-9141: Merge branch 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  package.json
  src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ImageUploader.tsx
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.it_IT.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
  yarn.lock
Labels: PULLUP

#11734 MET-80: Add unit tests
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/dependencies.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/legacy/pim-view/PimView.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/legacy/pim-view/view-builder.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/react/react-controller.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/react/react-element-helper.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/legacy-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/router-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/translate-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/user-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-families.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/index.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/MeasurementFamilyRow.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/Table.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Breadcrumb.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/BreadcrumbItem.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Caret.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Helper.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Link.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/NoData.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageHeader.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/RootProvider.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SearchBar.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/hooks/use-focus.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/hooks/use-shortcut.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/Search.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/illustrations/MeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/key.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/theme.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/list/Table.unit.tsx
  tests/front/unit/jest/unit.jest.js
Labels: to review

#11741 MET-103: Add Button component
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Button.tsx
Labels: to review

#11747 MET-102: Unify export use
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/notify-context.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-toggle-state.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/validation-error.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/form/create-measurement-family-form.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/hooks/use-create-measurement-family-saver.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/hooks/use-create-measurement-family-state.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Flag.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/FormGroup.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/InputErrors.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Modal.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageContent.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ResultCount.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SearchBar.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Subsection.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SubsectionHelper.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/CloseIcon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/SearchIcon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/WarningIcon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/illustrations/MeasurementFamilyIllustration.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
Labels: to review

#11633 API-1004: Add auditable option to connection settings
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/Checkbox.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/form/FormGroup.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/model/connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-create-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-fetch-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-update-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/components/AuditableHelper.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionEditForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ImageUploader.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connections-reducer.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Figure.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/InlineHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageHeader.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/RuntimeError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Section.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/SmallHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/__snapshots__/Form.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/__snapshots__/Select.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/api-hooks/use-update-connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/Connection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/ConnectionGrid.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/NoConnection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/EditConnection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/reducers/connection-reducer.test.ts
Labels: octopus, wip

#11777 PIM-9142: Pullup 4.0 into Master
  CHANGELOG-4.0.md
  package.json
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.de_DE.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ImageUploader.tsx
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.it_IT.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
  yarn.lock
Labels: PULLUP

#11765 MET-31: As Julia, I can display a measurement family with all its units
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/requirejs.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/routing.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/controller/settings.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-families.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-family.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/index.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/locale.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/OperationCollection.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/Table.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/PropertyTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/index.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/MeasurementFamilyRow.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/MeasurementFamilyTable.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Button.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/FormGroup.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageContent.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageHeader.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SearchBar.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SecondaryActionsDropdownButton.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/fetcher/base-fetcher.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/hooks/use-ui-locales.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/DownIcon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/SubArrowRightIcon.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/theme.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/measurement-family.unit.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/common/OperationCollection.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/CreateMeasurementFamily.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/list/MeasurementFamilyTable.unit.tsx
Labels: to review

#11786 PIM-9158: Merge branch 3.0 into 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/product-model-fetcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php
  tests/legacy/features/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
Labels: PULLUP

#11807 API-1009: Change Audit message when no connection exist
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/NoConnection.tsx
Labels: octopus

#11808 API: Remove snapshot testing
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Figure.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Helper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/InlineHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Modal.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageContent.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageHeader.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/RuntimeError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Section.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/SmallHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Figure.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Helper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/InlineHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Modal.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageContent.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageHeader.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/RuntimeError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Section.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/SmallHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/Breadcrumb.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/BreadcrumbItem.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/ApplyButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/Button.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/SecondaryActionsButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/ApplyButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/Button.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/SecondaryActionsButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/Form.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/__snapshots__/Form.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/Select.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/__snapshots__/Select.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/Connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/ConnectionGrid.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/FlowTypeHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/FlowTypeSelect.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/NoConnection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/Connection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/ConnectionGrid.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/FlowTypeHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/FlowTypeSelect.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/NoConnection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/router/BreadcrumbRouterLink.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/router/__snapshots__/BreadcrumbRouterLink.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/translate/Translate.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/translate/__snapshots__/Translate.test.tsx.snap
Labels: octopus

#11810 API-1033: Rename fetch audit data route
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/EventTypes.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/audit.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/connection.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/WeeklyAuditEndToEnd.php
Labels: octopus

#11818 API-1035: Calculate Audit weekly total
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/WeeklyEventCounts.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/model/weekly-event-counts.ts
Labels: octopus

#11813 MET-29: As Julia, I can delete a unit in a measurement family
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ConfirmDeleteModal.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Modal.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/illustrations/TrashIllustration.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
Labels: to review

#11823 API-1036: Display weekly total on Audit charts
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/model/weekly-event-counts.ts
Labels: octopus

#11793 DAPI-931: Keep the same tab when switching from a variant to a model (and vice versa)
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
Labels: core-team, weasels

#11811 PIM-9157: Fix performance issue when loading the data of a product group
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Group/SqlGetGroupProductIdentifiers.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetGroupProductIdentifiers.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Group/SqlGetGroupProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
Labels: to review

#11772 MET-91: Remove Measurement Family frontend (remover hook & confirm modal)
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-family-remover.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/hooks/use-measurement-family-remover.unit.ts
Labels: to review

#11828 MET-72: Cleanup EE headers
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/Code.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollection.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/Count.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/CountValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCount.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCountValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValue.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValueValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExist.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExistValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCount.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCountValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidatorSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/LabelCollectionSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/AcceptanceTestCase.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/SqlIntegrationTestCase.php
Labels: to review

#11826 API-1029: Format Audit dates on the backend
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/WeeklyEventCounts.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
Labels: octopus

#11830 MET-133: Fix portuguese labels being too long
  src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
  upgrades/schema/Version_5_0_20200324104437_migrate_measurement_table.php
Labels: to review

#11832 MET-117: Remove cache in measurement family repository
  src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
Labels: to review

#11836 API-1029: Fix Audit dates localization
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/WeeklyEventCounts.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
Labels: octopus

#11845 Merge branch 4.0 into master
  CHANGELOG-4.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/NoConnection.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Figure.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Helper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/InlineHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Modal.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageContent.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/PageHeader.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/RuntimeError.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/Section.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/SmallHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Figure.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Helper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/InlineHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Modal.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageContent.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/PageHeader.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/RuntimeError.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/Section.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/__snapshots__/SmallHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/Breadcrumb.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/BreadcrumbItem.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/breadcrumb/__snapshots__/BreadcrumbItem.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/ApplyButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/Button.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/SecondaryActionsButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/ApplyButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/Button.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/button/__snapshots__/SecondaryActionsButton.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/Form.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/form/__snapshots__/Form.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/Select.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/common/components/select/__snapshots__/Select.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/Connection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/ConnectionGrid.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/FlowTypeHelper.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/FlowTypeSelect.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/NoConnection.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/Connection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/ConnectionGrid.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/FlowTypeHelper.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/FlowTypeSelect.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/settings/components/__snapshots__/NoConnection.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/router/BreadcrumbRouterLink.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/router/__snapshots__/BreadcrumbRouterLink.test.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/translate/Translate.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/shared/translate/__snapshots__/Translate.test.tsx.snap
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.de_DE.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.de_DE.yml
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/UserManagement/Bundle/Resources/translations/validators.de_DE.yml
Labels: PULLUP

#11844 PIM-9164: Fix build property path for localized attributes validation
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Localization/Localizer/AttributeConverter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Localization/Localizer/AttributeConverterSpec.php
Labels: to review

#11856 MET-155: Fix updated measurement families
  src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
  upgrades/schema/Version_5_0_20200324104437_migrate_measurement_table.php
Labels: to review

#11866 MET-171: Redirect to newly created Measurement Family after creation
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
Labels: to review
