Repository akeneo/pim-community-dev, pull requests merged in 2020-05, with the labels that each got.

#12021 TIP-1456: require correct EE branch if it exists
  .circleci/config.yml
  .circleci/detect_structure_changes.sh
Labels: to review

#12020 PIM-9222: Error 500 when attempting bulk change with parent=empty filter
  CHANGELOG-3.2.md
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorCodeFilterSpec.php
Labels: bug, core-team

#12023 DAPI-963: update akeneo logo
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/logo.svg
Labels: weasels

#11998 PIM-9221: Performance issue on update product model through API
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
Labels: bug, core-team

#12028 TIP-1291: launch migrations in prod mode, as it will be done on Serenity
  config/services/test/test_services.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/repositories.yml
  src/Oro/Bundle/SecurityBundle/Resources/config/services.yml
  upgrades/test_schema/ExecuteMigrationTrait.php
Labels: to review

#12041 PIM-9235: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
  config/services/test/test_services.yml
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetCategoryCodesByProductIdentifiers.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
  tests/back/Integration/IntegrationTestsBundle/Query/PublicApi/AttributeOption/Cache/LRUClearableCachedGetExistingAttributeOptions.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorCodeFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
  yarn.lock
Labels: PULLUP

#12056 Merge 4.0 into master [pullup]
  CHANGELOG-4.0.md
  config/services/test/test_services.yml
  src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetCategoryCodesByProductIdentifiers.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
  src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
  tests/back/Integration/IntegrationTestsBundle/Query/PublicApi/AttributeOption/Cache/LRUClearableCachedGetExistingAttributeOptions.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
  yarn.lock
Labels: PULLUP

#12061 AOB-683: Add an extension point in family variant attribute-set
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
Labels: to review

#12066 PIM-9248: Merge branch 3.0 into 3.2
  CHANGELOG-3.0.md
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListUpdatedOrCreatedSinceNDaysProductModelEndToEnd.php
Labels: PULLUP

#12099 Minor improvements on CI PR workflow
  .circleci/config.yml
  .circleci/run_behat.sh
Labels: to review

#12007 TIP-1406: Add a tag to configure a DIC service based on a feature flag
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundle.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
  tests/back/Platform/Specification/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundleSpec.php
Labels: to review

#12112 HOTFIX: do not require deploy_upgrade_oldest_prod_environment as we h…
  .circleci/config.yml
Labels: to review

#12104 DAPI-1020: add a new family filter on attribute grid
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/FamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/RegisterFamilyFilter.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/FamilyFilterSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/RegisterFamilyFilterSpec.php
Labels: weasels

#12124 PIM-9265: Merge branch 3.2 into 4.0
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  frontend/build/compile-less.js
  frontend/build/update-extensions.js
  src/Akeneo/Pim/Enrichment/Component/Product/Job/JobParameters/ConstraintCollectionProvider/ComputeFamilyVariantStructureChanges.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/ProductExport.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content.html
Labels: PULLUP

#12086 RAC-23: Quantified Associations edition
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductAndProductModel/GetFromIdentifiersAction.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/useProductThumbnail.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/useProducts.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/product.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/quantified-association.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/quantified-link.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/row.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/HelperRibbon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/InfoIcon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/UnlinkIcon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/WarningIcon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useAutoFocus.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociationRow.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociations.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/hooks/useProducts.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/product.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/quantified-association.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/quantified-link.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/row.unit.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/OperationCollection.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Modal.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/CloseIcon.tsx
Labels: to review

#12160 PIM-9254: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
  config/packages/liip_imagine.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/locale_provider.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
Labels: PULLUP

#12157 DAPI-1000: allow HTML tags in form tab labels
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
Labels: weasels

#12039 DAPI-974: when I am on an attribute screen, I can see if I have spelling mistakes in one or several locales
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
Labels: weasels, wip

#12152 AOB-956: No more Onboarder specific configuration
  .circleci/config.yml
  .circleci/detect_structure_changes.sh
Labels: to review

#12171 GITHUB-APD-130: Update help menu link to redirect to the right version on the help center
  CHANGELOG-2.3.md
  src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/help.js
  src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/help.html
Labels: to review

#12155 GITHUB-APD-124: Fix link in the help button
  CHANGELOG-3.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
Labels: to review
