Repository akeneo/pim-community-dev, pull requests merged in 2020-09, with the labels that each got.

#12654 Merge 4.0
  CHANGELOG-4.0.md
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductDomainErrorEndToEnd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownProductException.php
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownProductExceptionSpec.php
Labels: PULLUP

#12605 PIM-9371: Disable save button when user creation form is not ready to submit
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/modal/create-user.js
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/create.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
  tests/back/UserManagement/Integration/Component/Updater/UserUpdaterIntegration.php
Labels: to review

#12646 RAC-111: Move Checkbox component in @akeneo-pim-community/shared
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/Checkbox.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/TickIcon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/icons/index.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/CheckboxField.tsx
  tests/front/unit/jest/unit.jest.js
Labels: to review

#12669 PIM-9427: Update datagrid selection count when clearing filter
  CHANGELOG-3.2.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
Labels: to review

#12666 PIM-9402: Add new ES filters for EMPTY operator
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/DateFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/MediaFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/MetricFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/NumberFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/OptionFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/PriceFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/ReferenceDataFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/TextAreaFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/TextFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/ProductAndProductModelSearchAggregator.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/EmptyFilterWithProductsAndProductModelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/ProductAndProductModelSearchAggregatorSpec.php
Labels: to review

#12700 PIM:9340: Avoid deadlock error when loading product and product models in parallel with the API
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/ImageAsLabel.php
  tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/ImageAsLabelSpec.php
Labels: API, bug, core-team

#12712 AOB-1023: Fix duplicated assets menu in PEF
  CHANGELOG-4.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
Labels: bug

#12723 DAPI-1250: Improve retrieval of products to evaluate
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateMissingCriteriaEvaluations.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetUpdatedProductsWithoutUpToDateEvaluationQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetUpdatedProductIdsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetUpdatedProductModelIdsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpdatedProductModelsWithoutUpToDateEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpdatedProductsWithoutUpToDateEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetUpdatedProductIdsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetUpdatedProductModelIdsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetUpdatedProductModelsWithoutUpToDateEvaluationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetUpdatedProductsWithoutUpToDateEvaluationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CreateMissingCriteriaEvaluationsSpec.php
Labels: weasels

#12722 Dapi 1325 - Add a logger in order to graph in datadog size of product table, product model table and dqi tables
  config/packages/dev/monolog.yml
  config/packages/monolog.yml
  config/packages/test/monolog.yml
  config/packages/test_fake/monolog.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/LogMetricsTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
Labels: weasels

#12749 PIM-9446: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/front.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/associationtype.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/family.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/family_variant.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/grouptype.yml
  tests/front/integration/pimenrich/fetcher/family-fetcher.integration.js
Labels: PULLUP

#12785 DAPI-1250: adapt the preparation of catalog evaluation for Data Quality Insights
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
Labels: weasels

#12789 PIM-9459: Merge 3.2 into 4.0
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetProductIdentifiersByGroup.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductIdentifiersByGroupInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
  tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductIdentifiersByGroupIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
  tests/front/unit/jest/unit.jest.js
Labels: PULLUP

#12807 Fix the Onboarder tests on the CI
  .circleci/config.yml
Labels: to review

#12803 PIM-9462: Merge branch 4.0 into master
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductEditDataFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
  tests/front/unit/jest/unit.jest.js
Labels: PULLUP

#12820 DAPI-1285: populate attribute groups activation during migration
  upgrades/schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation.php
  upgrades/test_schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation_Integration.php
Labels: weasels

#12825 DAPI-1243: Add ACL to edit attribute group activation
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/UpdateAttributeGroupActivationController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: weasels

#12860 DAPI-1280: attribute group activation / deactivation for DQI
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/UpdateAttributeGroupActivationController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/attribute-group/dqi-activation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/AttributeGroupDQIActivation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/HelperMessage.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/ToggleActivation.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/AttributeGroup/fetchAttributeGroupStatus.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useAttributeGroupState.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/saver/AttributeGroup/saveAttributeGroupActivation.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
Labels: weasels

#12861 PIM-9440: Fix locked MySQL tables during removing DQI evaluations without product
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductModelsCriteriaEvaluationTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductsCriteriaEvaluationTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RemoveEvaluationsWithoutProductTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductCriterionEvaluationRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductModelCriterionEvaluationRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
Labels: weasels
