Repository akeneo/pim-community-dev, pull requests merged in 2020-01, with the labels that each got.

#11330 PIM-9048: Merge branch 2.3 into 3.0
  CHANGELOG-2.3.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
Labels: PULLUP

#11295 AST-36: Remove PAM
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/DefaultMaskItemGenerator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
  src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  tests/front/common/builder/user.js
Labels: to review

#11338 PIM-9049: Merge 3.0 into 3.2
  CHANGELOG-2.3.md
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/PimCatalogTextAreaIntegration.php
  tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/TestData/VeryLongText.php
Labels: PULLUP

#11324 DAPI - Add events on before and after the rendering of the PEF
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
Labels: weasels

#11339 DAPI-710 add jwt library dependency and ext-openssl requirement
  composer.json
  composer.lock
  src/Akeneo/Platform/PimRequirements.php
Labels: weasels

#11318 Data Quality Insights - Feature branch 2
  composer.json
  composer.lock
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
  src/Akeneo/Platform/PimRequirements.php
  upgrades/test_schema/Version_4_0_20190916122239_remove_product_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20190917080512_remove_product_model_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20191004145507_remove_compute_model_descendant_jobs_Integration.php
  upgrades/test_schema/Version_4_0_20191223132437_data_quality_insights_add_dynamic_template_Integration.php
Labels: weasels

#11333 DAPI-595 Add badge colors for DQI charts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Badge.less
Labels: weasels

#11357 API-838: Add user role/group permissions to Connection settings
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/UpdateConnectionCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/UpdateConnectionHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Service/UpdateUserPermissionsInterface.php
  src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Read/ConnectionWithCredentials.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/ConnectionController.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryUserPermissionsRepository.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/CreateUser.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/UpdateUserPermissions.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Internal/UpdateUserPermissions.php
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/queries.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/repositories.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/update_a_connection.feature
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/UpdateConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/CreateConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/UpdateConnectionCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/UpdateConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Query/FindAConnectionHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Read/ConnectionWithCredentialsSpec.php
  src/Akeneo/Connectivity/Connection/front/src/common/components/InlineHelper.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/Select2.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/form/FormGroup.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/common/components/select/Select.tsx
  src/Akeneo/Connectivity/Connection/front/src/model/connection-user-permissions.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/actions/connections-actions.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-create-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-fetch-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-fetch-user-groups.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-fetch-user-roles.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-update-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCreateForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionEditForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/ConnectionPermissionsForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserGroupSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserRoleSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/reducers/connections-reducer.ts
Labels: octopus

#11375 API: Remove links from i18n
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/NoConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCredentials.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/FlowTypeHelper.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/ConnectionPermissionsForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserGroupSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserRoleSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/DeleteConnection.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/RegenerateConnectionPassword.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/RegenerateConnectionSecret.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/FlowTypeHelper.spec.tsx.snap
Labels: octopus

#11376 AST-253: Fix bulk actions asset selector
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
Labels: to review

#11388 API: Fix authenticate method for e2e tests
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/CountDailyEventsByConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/UpdateConnectionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
Labels: octopus

#11394 API-944: Fix acceptance tests for connection update
  make-file/connectivity-connection.mk
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectConnectionWithCredentialsByCodeQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryUserPermissionsRepository.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/CreateUser.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/UpdateUserPermissions.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/behat.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/update_a_connection.feature
Labels: octopus

#11392 API: Add phpstan
  make-file/connectivity-connection.mk
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/CodeMustBeUniqueValidator.php
  src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/ImageMustExistValidator.php
  src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/DailyEventCount.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/FileSystemAssetsInstaller.php
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon
Labels: octopus

#11416 TIP-1367: fix connection migration
  upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
Labels: to review

#11443 Add lodash types
  package.json
  yarn.lock
Labels: weasels

#11445 PIM-9061: Fix filters with numeric attribute codes for bulk actions
  CHANGELOG-3.0.md
  src/Oro/Bundle/DataGridBundle/Datagrid/RequestParameters.php
Labels: to review

#11433 API-899: Ignore API users in UserController
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
Labels: octopus

#11454 PIM-9062: Pull up 3.0 -> 3.2
  CHANGELOG-3.0.md
  src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
  tests/back/Pim/Structure/Specification/Component/Updater/AttributeUpdaterSpec.php
Labels: PULLUP

#11457 DAPI-695 : Fix "Green check icon"
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-check-green.svg
Labels: weasels

#11435 TIP-1367: make the completeness calculation work with legacy assets
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/DefaultMaskItemGenerator.php
Labels: to review

#11467 Fix migration order
  upgrades/schema/Version_4_0_20200116122239_remove_product_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs.php
  upgrades/test_schema/Version_4_0_20200116122239_remove_product_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values_Integration.php
  upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
Labels: weasels

#11458 PIM-9063: Pull up 3.2 -> 4.0
  src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php
  src/Akeneo/Channel/Bundle/Resources/config/controllers.yml
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/label.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-label.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/saver/base-saver.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/spec/Doctrine/ORM/Cursor/CursorSpec.php
  src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/category-tree.ts
  src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/channel.ts
  src/Oro/Bundle/DataGridBundle/Datagrid/RequestParameters.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/InternalApi/CategoryRepositorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidatePropertiesSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/CheckAttributeEditableSpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/AttributeUpdaterSpec.php
Labels: PULLUP

#11476 PIM-9065: Change the number decimal precision to 10
  CHANGELOG-3.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
  src/Akeneo/Tool/Component/Localization/Localizer/NumberLocalizer.php
  src/Akeneo/Tool/Component/Localization/Presenter/NumberPresenter.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateListVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php
  tests/legacy/features/pim/enrichment/product/export/export_products_with_localized_decimal.feature
Labels: to review

#11472 API-954: Add integration tests on each page
  src/Akeneo/Connectivity/Connection/front/src/common/components/__mocks__/Select2.tsx
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/Settings.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-create-connection.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCreateForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionGrid.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/Index.tsx
  src/Akeneo/Connectivity/Connection/front/src/shared/router/router-context.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/router/router.interface.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/router/use-route.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/translate/Translate.tsx
  src/Akeneo/Connectivity/Connection/front/src/shared/translate/translate-context.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/translate/translate.interface.ts
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/Connection.spec.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/ConnectionGrid.spec.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/CreateConnection.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/DeleteConnection.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/EditConnection.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/ListConnections.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/RegenerateConnectionPassword.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/RegenerateConnectionSecret.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/shared/translate/Translate.spec.tsx
  src/Akeneo/Connectivity/Connection/front/tests/utils/test-utils.tsx
Labels: octopus

#11497 API-921: Fix Victory style type
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart.tsx
Labels: octopus

#11495 API-957: Add connection dashboard survey url
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/UserSurvey.tsx
Labels: octopus

#11465 API-959: Fix chart data visualization
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart.tsx
Labels: octopus

#11496 API-936: Add React error boundaries
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/pages/AuditErrorBoundary.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/pages/Index.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/RuntimeError.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/Index.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/pages/SettingsErrorBoundary.tsx
  src/Akeneo/Connectivity/Connection/front/tests/unit/common/__snapshots__/PageHeader.spec.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/unit/common/__snapshots__/Section.spec.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/ConnectionGrid.spec.tsx.snap
  src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/NoConnection.spec.tsx.snap
Labels: octopus

#11504 AST-381: Fix media link preview black background
  config/packages/liip_imagine.yml
Labels: to review

#11289 PIM-9036: Rework version purger to use DBAL instead of ORM.
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlDeleteVersionsByIdsQuery.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetAllButLastVersionIdsByIdsQuery.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetAllResourceNamesQuery.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetFirstVersionIdsByIdsQuery.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetPurgeableVersionListQuery.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Event/PreAdvisementVersionEvent.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Event/PrePurgeVersionEvent.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Event/PurgeVersionEvents.php
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/PurgeProgressBarAdvancerSubscriber.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/KeepLastVersionPurgerAdvisor.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/PurgeableVersionList.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/SkipFirstVersionPurgerAdvisor.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/SkipLastVersionPurgerAdvisor.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurger.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurgerAdvisorInterface.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurgerInterface.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/model/doctrine/Version.orm.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/purgers.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/repositories.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Purger/KeepLastVersionPurgerAdvisorSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Purger/SkipFirstVersionPurgerAdvisorSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Purger/SkipLastVersionPurgerAdvisorSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Purger/VersionPurgerSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetAllButLastVersionIdsByIdsQueryIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetAllResourceNamesQueryIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetFirstVersionsByIdsQueryIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetPurgeableVersionListQueryIntegration.php
  tests/legacy/features/pim/structure/family/purge_versionning.feature
  upgrades/schema/Version_3_0_20191227141338_fix_versioning_indexes.php
Labels: to review
