Repository akeneo/pim-community-dev, pull requests merged in 2020-06, with the labels that each got.

#12172 RAC-67: Build yarn workspaces from node_modules directly
  frontend/webpack/requirejs-utils.js
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/PimUIExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Install/AssetsInstaller.php
  src/Akeneo/Platform/Bundle/UIBundle/Install/FileSystemAssetsInstaller.php
  src/Akeneo/Platform/Bundle/UIBundle/Install/InstallSubscriber.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/install.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/hooks/use-measurement-family-remover.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/common/OperationCollection.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/CreateMeasurementFamily.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/hooks/use-create-measurement-family-saver.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/CreateUnit.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/hooks/use-create-unit-validator.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitDetails.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitRow.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/list/MeasurementFamilyTable.unit.tsx
  tests/front/unit/jest/mocks.js
  tests/front/unit/jest/unit.jest.js
Labels: to review

#12140 RAC-53: Handle validation errors in the UI
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/IdMapping.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/useProducts.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/quantified-association.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/row.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/InputErrors.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/models/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/models/validation-error.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/components/HelperRibbon.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/components/InputErrors.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/components/SearchBar.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/models/validation-error.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociationRow.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociations.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/hooks/useProductThumbnail.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/hooks/useProducts.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/quantified-association.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/row.unit.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/OperationCollection.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/hooks/use-create-measurement-family-saver.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/form/create-unit-form.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/hooks/use-create-unit-validator.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/PropertyTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/hooks/use-save-measurement-family-saver.ts
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitDetails.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitTab.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/CheckboxField.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/hooks/use-measurement-family-remover.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/common/OperationCollection.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/CreateMeasurementFamily.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/hooks/use-create-measurement-family-saver.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/CreateUnit.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/hooks/use-create-unit-validator.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitDetails.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitRow.unit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/list/MeasurementFamilyTable.unit.tsx
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/IdMappingSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationsSpec.php
  tests/front/unit/jest/mocks.js
  tests/front/unit/jest/unit.jest.js
Labels: to review

#12164 RAC-43: Add standard to flat quantified associations method
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
Labels: to review

#12195 Add missing yarn workspaces to standard package.json
  std-build/package.json
Labels: to review

#12180 GITHUB-APD-135: Open/Close the panel when I click on the update link button
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/config/form_extensions/communication_channel.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/bridge/view/panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/components/panel/Panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/components/panel/index.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/components/Menu.less
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/components/Panel.less
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.html
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/__mocks__/oro/mediator.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/__mocks__/oro/translator.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/unit/components/panel/Panel.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Overlay.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/app.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactElementHelper.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactView.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/index.ts
Labels: to review

#12183 DAPI-1032: bootstrap react application / basic attribute options list
  package.json
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/Index.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useLocales.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/AttributeOption.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Locale.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/localesReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  tests/front/unit/structure/attribute-option/attributeOptionsReducer.unit.ts
  tests/front/unit/structure/attribute-option/localesReducer.unit.ts
  yarn.lock
Labels: weasels

#12198 DAPI-1033: display a dynamic attribute options list
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/Index.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/attributeContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/fetchers/baseFetcher.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useLocales.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
  tests/front/unit/structure/attribute-option/reducers/localesReducer.unit.ts
Labels: weasels

#12143 GITHUB-123 : Add link to redirect to a help center page to see the PIM updates
  config/bundles.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/AkeneoCommunicationChannelBundle.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/fetcher/campaign.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/icon-megaphone.svg
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.html
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/__mocks__/pim/data-collector.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/unit/fetcher/campaign.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/user-navigation.html
Labels: to review

#12209 DAPI-1037: allow attribute options translations to be edited
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/Index.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/LocalesContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useLocales.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/localesReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
  tests/front/unit/jest/unit.jest.js
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
  tests/front/unit/structure/attribute-option/reducers/localesReducer.unit.ts
Labels: weasels

#12218 Fixing product normalizer inte tests & front lint
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Tool/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
Labels: to review

#12219 DAPI-1037: allow attribute options to be added
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
Labels: weasels

#12225 Fixing QuantifiedAssociations coverage
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociations.unit.tsx
Labels: to review

#12232 DAPI-1034-1037: display basic validation errors on create and update
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useDeleteAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
Labels: weasels

#12125 DAPI-1008: Add versioning on attribute options
  src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php
  src/Akeneo/Tool/Bundle/VersioningBundle/UpdateGuesser/AttributeOptionUpdateGuesser.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php
Labels: weasels

#12253 DAPI-1035: allow options to be sorted alphabetically
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeContextState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Events.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
Labels: weasels

#12246 PIM-9293: Merge branch 4.0 into master
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  bin/check-pullup
  config/packages/liip_imagine.yml
  frontend/build/compile-less.js
  frontend/build/update-extensions.js
  src/Akeneo/Channel/Bundle/Resources/config/validation/locale.yml
  src/Akeneo/Channel/Bundle/Resources/config/validators.yml
  src/Akeneo/Channel/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Channel/Bundle/Resources/translations/validators.fr_FR.yml
  src/Akeneo/Channel/Component/Validator/Constraint/LocaleCode.php
  src/Akeneo/Channel/Component/Validator/Constraint/LocaleCodeValidator.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/tests/features/create_connection.feature
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/OptionFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.fr_FR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/JobParameters/ConstraintCollectionProvider/ComputeFamilyVariantStructureChanges.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/RegexGuesser.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/locale_provider.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/categories.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-associate.jstree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/ProductExport.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content.html
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Component/Console/CommandLauncher.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
  tests/back/Channel/Specification/Component/Validator/Constraint/LocaleCodeValidatorSpec.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Metric/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Number/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Option/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Options/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Text/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/TextArea/LocalizableScopableFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php
  tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Builder/EntityWithValuesBuilderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
  tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature
Labels: PULLUP

#12251 GITHUB-APD-133: Integrate all announcement content
  package.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/__mocks__/serenity-updates-sample.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/Associations_2-way-association-type.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/Optimize_jpeg_transformation.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/connection_user_warning_message.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/error-monitoring-connection-dashboard.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/measurements-api.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/new-connection-monitoring-page.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/images/cards/track-checkbox.png
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/components/panel/card/Description.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/components/panel/card/Title.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/definitions/card.schema.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/components/panel/Panel.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/fetcher/card.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/hooks/useCampaign.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/hooks/useCards.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/test-utils.tsx
  yarn.lock
Labels: to review

#12290 DAPI: fix options list when then backend returns an empty object where there is no option
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/fetchers/baseFetcher.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
Labels: weasels

#12291 DAPI-1076: ensure the redux store is resetted when unmounting the application
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
Labels: weasels

#12167 RAC-26: Flat files import
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/comparators.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/filters.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Filter/ProductAssociationFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/AssociationColumnsResolver.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/AttributeColumnInfoExtractor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/FieldConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel/FieldConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductModelAssociationProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductModelProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithQuantifiedAssociationsInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
  tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Filter/ProductAssociationFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/AssociationColumnsResolverSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/AttributeColumnInfoExtractorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/FieldConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel/FieldConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductModelAssociationProcessorSpec.php
Labels: to review

#12277 GITHUB-APD-162: Update front
  make-file/communication-channel.mk
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/bridge/view/panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/package.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/components/index.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/components/panel/Panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/definitions/pimAnalyticsData.schema.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/fetcher/announcement.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/fetcher/announcement.type.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/fetcher/campaign.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/fetcher/campaign.type.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/hooks/useAnnouncements.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/hooks/useCampaign.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/hooks/usePimVersion.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/tools/formatCampaign.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/validator/campaignData.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/src/validator/pimAnalyticsData.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/__mocks__/dataProvider.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/__mocks__/oro/mediator.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/__mocks__/pim/data-collector.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/components/panel/Panel.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/fetcher/announcement.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/fetcher/campaign.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/hooks/useAnnouncements.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/hooks/useCampaign.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/hooks/usePimVersion.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/front/unit/tools/formatCampaign.unit.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/workspaces/communication-channel/tests/test-utils.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/fetcher/baseFetcher.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/fetcher/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/utils.tsx
  tests/front/unit/jest/fetchMock.ts
  tests/front/unit/jest/unit.jest.js
Labels: to review

#12297 DAPI-1039: update end to end tests for the new options screen
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/pim/structure/attribute/display_available_field_options.feature
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
Labels: weasels

#12312 GITHUB-APD-132: Fix coverage unit front
  tests/front/unit/jest/unit.jest.js
Labels: communication-channel, to review

#12323 DAPI - revamp attribute options UI fixes
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-row-move.svg
Labels: weasels

#12229 TIP-1412: Onboarder bundle is always registred in EE
  .circleci/config.yml
Labels: to review

#12324 DAPI-1069: add yellow140 color as a Less variable
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
Labels: weasels

#12337 PIM-9321: Merge branch 3.2 into 4.0
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByLocalesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
Labels: PULLUP

#12339 PIM-9322: Merge branch 4.0 into master
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetValuesAndPropertiesFromProductIdentifiers.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/select.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/default-product-grid-view.ts
  src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
  tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantRepository.php
  tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantsByAttributeAxes.php
  tests/back/Acceptance/Resources/config/pim/queries.yml
  tests/back/Acceptance/spec/FamilyVariant/InMemoryFamilyVariantRepositorySpec.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
  tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByLocalesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
Labels: PULLUP

#12354 DAPI-997: add a new dropzone to be able to display the "back" button
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/common/default-template.html
Labels: weasels

#12363 Update composer dependencies
  composer.json
  composer.lock
Labels: dependencies, to review

#12360 PIM-9323: PDF doesn't export all Product Model values
  CHANGELOG-3.2.md
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
Labels: bug, core-team

#12369 TIP-1436: Remove deploy_upgrade_oldest_prod_environment_beta as it's …
  .circleci/config.yml
Labels: to review

#12273 DAPI - revamp attribute options
  package.json
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/OverridePimStyles.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/LocalesContext.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/fetchers/baseFetcher.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeContextState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useDeleteAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useLocales.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useManualSortAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/AttributeOption.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Events.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Locale.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/index.less
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-row-move.svg
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
  tests/front/unit/jest/unit.jest.js
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/pim/structure/attribute/display_available_field_options.feature
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
  yarn.lock
Labels: weasels

#12328 DAPI-1040: Trigger an event when the option list is being rendered
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptionsListState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsExtraDataReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  tests/front/unit/structure/attribute-option/hooks/useAttributeOptionsListState.unit.tsx
  tests/front/unit/structure/attribute-option/hooks/useEditingOptionContextState.unit.ts
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsExtraDataReducer.unit.tsx
Labels: weasels

#12385 DAPI-1115 fix filter label color and subsection font weight
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
Labels: weasels

#12342 GITHUB-APD-172: I want to be able to track which announcements meet the most success in the communication panel
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/InMemoryFindAnnouncementItems.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/serenity-updates.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Announcement/ListAnnouncementIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/ListAnnouncementsHandlerSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Domain/Announcement/Model/Read/AnnouncementItemSpec.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Announcement.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Link.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/definitions/announcement.schema.json
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/__mocks__/dataProvider.ts
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
Labels: communication-channel, to review
