Repository akeneo/pim-community-dev, pull requests merged in 2021-06, with the labels that each got.

#14607 PLG-263: auto apply permissions on upper and lower levels
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/permissionsHelper.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/helpers/permissionsHelper.unit.ts
Labels: weasels

#14619 PIM-9886: Fix display of completeness in the PEF when the selected locale is deactivated
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
Labels: bug

#14618 PLG-287 : Fix Wrong flash messages in categories
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14628 PLG-285: Improve permissions page helpers
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/categories/EditPermissionsForm.tsx
Labels: weasels

#14624 PIM-9891: Fix missing sanity checks when computing enrichment status
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
Labels: weasels

#14635 [WIP] PLG-170: update category/tree deletion end to end tests
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/DeleteCategoryModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
  tests/legacy/features/pim/enrichment/category/remove_a_category.feature
Labels: weasels, wip

#14639 PLG-170: update category edit end to end tests
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  tests/legacy/features/pim/enrichment/category/edit_a_category.feature
Labels: weasels

#14640 PLG-170: Cover creation of categories by e2e tests
  tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
  tests/legacy/features/Context/NavigationContext.php
  tests/legacy/features/Context/Page/Category/Tree.php
  tests/legacy/features/pim/enrichment/category/create_a_category.feature
Labels: weasels

#14655 PLG-292: New category tree overlay wrong text
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx
Labels: weasels

#14653 PLG-288: Categories permissions input should have 400px of width
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/categories/EditPermissionsForm.tsx
Labels: weasels

#14570 PIM-9876: Purge outdated data before consolidating dashboard data (master)
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/JobParameters/RecomputeProductScoresParameters.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PurgeOutdatedDataTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RecomputeProductScoresTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/RecomputeProductsScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  upgrades/schema/Version_6_0_20210527144217_dqi_init_recompute_products_scores.php
  upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
  upgrades/test_schema/Version_6_0_20210527144217_dqi_init_recompute_products_scores_Integration.php
Labels: weasels

#14573 PIM-9876: Purge outdated data before consolidating dashboard data (5.0)
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PurgeOutdatedDataTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
Labels: weasels

#14675 PLG-293: Improve ordering categories performances
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/providers/OrderableTreeProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/Tree.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/TreeIcon.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDragTreeNode.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDropTreeNode.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDragTreeNode.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDropTreeNode.unit.tsx
Labels: weasels

#14691 PLG-294: fix category app loaded several times
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
Labels: weasels

#14685 PLG-295: Adapt Behat tests for Categories in EE
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
  tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php
  tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
  tests/legacy/features/Context/NavigationContext.php
  tests/legacy/features/pim/enrichment/category/drag_and_drop_a_category.feature
  tests/legacy/features/pim/enrichment/category/list_categories.feature
Labels: weasels, wip

#14633 PLG-170: Adapt end to end tests on categories
  behat.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/DeleteCategoryModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php
  tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
  tests/legacy/features/Context/NavigationContext.php
  tests/legacy/features/Context/Page/Category/CategoryView.php
  tests/legacy/features/Context/Page/Category/Tree.php
  tests/legacy/features/pim/enrichment/category/create_a_category.feature
  tests/legacy/features/pim/enrichment/category/display_category_history.feature
  tests/legacy/features/pim/enrichment/category/drag_and_drop_a_category.feature
  tests/legacy/features/pim/enrichment/category/edit_a_category.feature
  tests/legacy/features/pim/enrichment/category/list_categories.feature
  tests/legacy/features/pim/enrichment/category/remove_a_category.feature
Labels: weasels

#14701 PLG-309: Add unit test for edit category form hook
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useEditCategoryForm.unit.ts
Labels: weasels

#14718 PLG-313 - Extract and test Category edition form formatting
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/Form/CategoryFormViewNormalizer.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/forms.yml
  src/Akeneo/Pim/Enrichment/Component/Category/Form/CategoryFormViewNormalizerInterface.php
Labels: weasels

#14716 PLG-311: Add ACL permission on category history tab
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
Labels: weasels

#14717 PLG-312: Rename route "countChildren" & Modify "useFetch"
  front-packages/shared/src/hooks/useFetch.ts
  front-packages/shared/src/hooks/useFetch.unit.ts
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategory.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountCategoryTreesChildren.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountProductsByCategory.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
Labels: weasels

#14726 PLG-94: Fix refresh issue of tree when the category id is changed in the url
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
Labels: weasels

#14777 [WIP] PLG-275
  composer.json
  config/routes/routes.yml
  front-packages/invite-user/src/feature/InviteUserApp.tsx
  front-packages/invite-user/src/feature/hooks/index.ts
  front-packages/invite-user/src/feature/hooks/useInvitedUsers.ts
  front-packages/invite-user/src/feature/index.ts
  front-packages/invite-user/src/feature/models/InvitedUser.ts
  front-packages/invite-user/src/feature/models/index.ts
  front-packages/invite-user/src/feature/providers/InvitedUserProvider.tsx
  front-packages/invite-user/src/index.tsx
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useFetch.ts
  make-file/free-trial.mk
  phpspec.yml.dist
  phpunit.xml.dist
  src/Akeneo/FreeTrial/README.md
  src/Akeneo/FreeTrial/akeneo-connect-api/Dockerfile
  src/Akeneo/FreeTrial/akeneo-connect-api/docker-compose.yml
  src/Akeneo/FreeTrial/akeneo-connect-api/index.js
  src/Akeneo/FreeTrial/akeneo-connect-api/package.json
  src/Akeneo/FreeTrial/back/Application/InviteUsers.php
  src/Akeneo/FreeTrial/back/Domain/API/InviteUserAPI.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvalidEmailException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationAlreadySentException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationFailedException.php
  src/Akeneo/FreeTrial/back/Domain/Model/InviteUsersAcknowledge.php
  src/Akeneo/FreeTrial/back/Domain/Model/InvitedUser.php
  src/Akeneo/FreeTrial/back/Domain/Query/GetInvitedUsersQuery.php
  src/Akeneo/FreeTrial/back/Domain/Repository/InvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Domain/ValueObject/InvitedUserStatus.php
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/APIClient.php
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/AkeneoConnectInviteUserAPI.php
  src/Akeneo/FreeTrial/back/Infrastructure/Controller/RetrieveUsersController.php
  src/Akeneo/FreeTrial/back/Infrastructure/Controller/SaveUsersController.php
  src/Akeneo/FreeTrial/back/Infrastructure/Install/EventSubscriber/InitFreeTrialDbSchemaSubscriber.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlGetInvitedUsersQuery.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlInvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Infrastructure/RetrievePimFQDN.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/DependencyInjection/AkeneoFreeTrialExtension.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/akeneo_connect.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/mysql.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/PimInvitedUserProvider.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/controller.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlGetInvitedUsersQueryIntegration.php
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlInvitedUserRepositoryIntegration.php
  src/Akeneo/FreeTrial/tests/back/Specification/Application/InviteUsersSpec.php
  src/Akeneo/FreeTrial/tests/back/Specification/Infrastructure/AkeneoConnect/APIClientSpec.php
  src/Akeneo/FreeTrial/tests/back/Specification/Infrastructure/AkeneoConnect/AkeneoConnectInviteUserAPISpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Form/CategoryFormViewNormalizerSpec.php
  yarn.lock
Labels: weasels, wip

#14689 PLG-271: Add the "invite users" entry in the header
  composer.json
  config/routes/routes.yml
  front-packages/invite-user/src/feature/InviteUserApp.tsx
  front-packages/invite-user/src/feature/InviteUserButton.tsx
  front-packages/invite-user/src/feature/hooks/index.ts
  front-packages/invite-user/src/feature/hooks/useInvitedUsers.ts
  front-packages/invite-user/src/feature/index.ts
  front-packages/invite-user/src/feature/models/InvitedUser.ts
  front-packages/invite-user/src/feature/models/index.ts
  front-packages/invite-user/src/feature/providers/InvitedUserProvider.tsx
  front-packages/invite-user/src/index.tsx
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useFetch.ts
  make-file/free-trial.mk
  phpspec.yml.dist
  phpunit.xml.dist
  src/Akeneo/FreeTrial/README.md
  src/Akeneo/FreeTrial/akeneo-connect-api/Dockerfile
  src/Akeneo/FreeTrial/akeneo-connect-api/docker-compose.yml
  src/Akeneo/FreeTrial/akeneo-connect-api/index.js
  src/Akeneo/FreeTrial/akeneo-connect-api/package.json
  src/Akeneo/FreeTrial/back/Application/InviteUsers.php
  src/Akeneo/FreeTrial/back/Domain/API/InviteUserAPI.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvalidEmailException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationAlreadySentException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationException.php
  src/Akeneo/FreeTrial/back/Domain/Exception/InvitationFailedException.php
  src/Akeneo/FreeTrial/back/Domain/Model/InviteUsersAcknowledge.php
  src/Akeneo/FreeTrial/back/Domain/Model/InvitedUser.php
  src/Akeneo/FreeTrial/back/Domain/Query/GetInvitedUsersQuery.php
  src/Akeneo/FreeTrial/back/Domain/Repository/InvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Domain/ValueObject/InvitedUserStatus.php
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/APIClient.php
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/AkeneoConnectInviteUserAPI.php
  src/Akeneo/FreeTrial/back/Infrastructure/Controller/RetrieveUsersController.php
  src/Akeneo/FreeTrial/back/Infrastructure/Controller/SaveUsersController.php
  src/Akeneo/FreeTrial/back/Infrastructure/Install/EventSubscriber/InitFreeTrialDbSchemaSubscriber.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlGetInvitedUsersQuery.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlInvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Infrastructure/RetrievePimFQDN.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/DependencyInjection/AkeneoFreeTrialExtension.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/akeneo_connect.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/mysql.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/PimInvitedUserProvider.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/controller.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlGetInvitedUsersQueryIntegration.php
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlInvitedUserRepositoryIntegration.php
  src/Akeneo/FreeTrial/tests/back/Specification/Application/InviteUsersSpec.php
  src/Akeneo/FreeTrial/tests/back/Specification/Infrastructure/AkeneoConnect/APIClientSpec.php
  src/Akeneo/FreeTrial/tests/back/Specification/Infrastructure/AkeneoConnect/AkeneoConnectInviteUserAPISpec.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/user-navigation.html
  tests/back/Pim/Enrichment/Specification/Bundle/Form/CategoryFormViewNormalizerSpec.php
  yarn.lock
Labels: weasels

#14767 PLG: fix category edit form display when the current translation is null
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
Labels: weasels

#14824 PIM-9933: Fix delete category menu that stays displayed on screen
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
Labels: weasels

#14830 PLG-349: The size of the illustration is wrong
  front-packages/invite-user/src/feature/InviteUserApp.tsx
Labels: weasels

#14867 PLG-350: The navigation stay active when I am on the Invite user page
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/controller.tsx
Labels: weasels
