Repository akeneo/pim-community-dev, pull requests merged in 2021-01, with the labels that each got.

#13646 DAPI-1469: Fix the size issue with the logo on login page
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Login.less
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: bug, weasels

#13659 Do not translate Akeneo baseline
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: weasels

#13667 PIM-9622: Fix query that can generate a MySQL memory allocation error
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
Labels: weasels

#13688 PIM-9618: PULL-UP-5.0
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Channel/Bundle/Resources/translations/messages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_group.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_product_model.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.en_NZ.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Tag.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associated-product-row-view.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.ca_ES.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.sv_SE.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_NZ.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_NZ.yml
  src/Oro/Bundle/DataGridBundle/Extension/Formatter/FormatterExtension.php
  src/Oro/Bundle/DataGridBundle/spec/Extension/Formatter/FormatterExtensionSpec.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/boolean-cell.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/listener/column-form-listener.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/pageable-collection.js
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductModelDatasourceSpec.php
Labels: PULLUP

#13730 the integration test make target was wrong
  .circleci/config.yml
  make-file/test.mk
Labels: weasels

#13732 the integration test make target was wrong
  .circleci/config.yml
  make-file/test.mk
Labels: weasels

#13724 DAPI: fix useDebounceCallback typehinting to allow callbacks with several parameters
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useDebounce.ts
Labels: weasels

#13747 PLG: improve tracking
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-onboarding.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: weasels

#13750 DAPI-1477: Fix unstable DQI integration tests
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/CompletenessTestCase.php
Labels: weasels

#13754 Pullup 5.0 master 20120119
  CHANGELOG-5.0.md
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/UrlReachabilityCheckerInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/WebhookController.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/Signature.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/RequestHeaders.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/SignatureSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php
  src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-webhook-check-reachability.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/CompletenessTestCase.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.fr_FR.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fr_FR.yml
Labels: PULLUP

#13731 PIM-9630: Dashboard completeness broken due to mysql buffer size
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
Labels: bug

#13691 DAPI-1471 - TagInput component
  akeneo-design-system/src/Introduction.stories.mdx
  akeneo-design-system/src/components/Input/TagInput/TagInput.stories.mdx
  akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
  akeneo-design-system/src/components/Input/TagInput/TagInput.unit.tsx
  akeneo-design-system/src/components/Input/index.ts
  akeneo-design-system/src/shared/key.ts
Labels: weasels, wip

#13790 DAPI-1471: Create TagInput component in DSM
  akeneo-design-system/src/Introduction.stories.mdx
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-duplicates-allowed-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-existing-tags-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-existing-value-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-standard-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-variation-on-invalid-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-variation-on-readonly-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-with-a-high-number-of-tags-correctly-1-snap.png
  akeneo-design-system/src/components/Input/TagInput/TagInput.stories.mdx
  akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
  akeneo-design-system/src/components/Input/TagInput/TagInput.unit.tsx
  akeneo-design-system/src/components/Input/index.ts
  akeneo-design-system/src/shared/array.ts
  akeneo-design-system/src/shared/index.ts
  akeneo-design-system/src/shared/key.ts
Labels: design-system, weasels
