Repository akeneo/pim-community-dev, pull requests merged in 2021-07, with the labels that each got.

#14873 PLG-272 / PLG-273: disable all fields in general and password tabs of user edit form
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/form_extensions/user_edit.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/user-profile-readonly-tab-content.ts
Labels: weasels

#14845 PLG-351: Configure CI tests
  make-file/free-trial.mk
  make-file/test.mk
  src/Akeneo/FreeTrial/back/Application/InviteUsers.php
  src/Akeneo/FreeTrial/back/Domain/API/InviteUserAPI.php
  src/Akeneo/FreeTrial/back/Domain/Query/GetInvitedUsersQuery.php
  src/Akeneo/FreeTrial/back/Domain/Repository/InvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Domain/ValueObject/InvitedUserStatus.php
  src/Akeneo/FreeTrial/back/Infrastructure/Controller/RetrieveUsersController.php
  src/Akeneo/FreeTrial/back/Infrastructure/Install/EventSubscriber/InitFreeTrialDbSchemaSubscriber.php
  src/Akeneo/FreeTrial/tests/back/.php_cd.php
  src/Akeneo/FreeTrial/tests/back/phpstan.neon.dist
Labels: weasels

#14882 PLG-278: Activate user when he logs in for the first time in the Free Trial
  src/Akeneo/FreeTrial/back/Domain/Model/InvitedUser.php
  src/Akeneo/FreeTrial/back/Domain/Query/GetInvitedUserQuery.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlGetInvitedUserQuery.php
  src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlInvitedUserRepository.php
  src/Akeneo/FreeTrial/back/Infrastructure/Subscriber/UserFirstConnectionSubscriber.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/mysql.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlGetInvitedUserQueryIntegration.php
  src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlInvitedUserRepositoryIntegration.php
Labels: weasels

#14823 PLG-289: English - Product Grid - Created at / Updated at
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/datagrid/history.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php
  tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature
  tests/legacy/features/pim/enrichment/product/datagrid/sorting/sort_products_per_date_field.feature
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature
Labels: weasels

#14880 PLG-283: Configure Akeneo-connect API from env variables
  .env
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/akeneo_connect.yml
Labels: weasels

#14883 PLG-359: When the user invitation failed I should see a readable erro…
  front-packages/invite-user/src/feature/hooks/useInvitedUsers.ts
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14903 PIM-9951: Fix wrong locale used by spellcheck when comparing product attributes
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/ProductEditForm/CatalogContextListener.tsx
Labels: bug, weasels

#14879 PLG-274: Mock the Akeneo-Connect API client
  config/services/dev/free_trial.yml
  src/Akeneo/FreeTrial/akeneo-connect-api/Dockerfile
  src/Akeneo/FreeTrial/akeneo-connect-api/docker-compose.yml
  src/Akeneo/FreeTrial/akeneo-connect-api/index.js
  src/Akeneo/FreeTrial/akeneo-connect-api/package.json
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/APIClient.php
  src/Akeneo/FreeTrial/back/Infrastructure/AkeneoConnect/MockGuzzleHttpClient.php
Labels: weasels

#14924 PIM-9943: Fix product-grid quality score filter all
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/ProductGrid/QualityScoreFilterSpec.php
Labels: bug, weasels

#14967 PLG-212: Add migration script
  upgrades/schema/Version_6_0_20210713134208_create_table_invited_users.php
  upgrades/test_schema/Version_6_0_20210713134208_create_table_invited_users_Integration.php
Labels: weasels

#14977 PLG-261: Define the category label at the same time as the category code
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/createCategory.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx
Labels: weasels

#14998 PLG-212: Free trial - Invite user
  config/bundles.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/AkeneoCommunityFreeTrialBundle.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/DependencyInjection/AkeneoCommunityFreeTrialExtension.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
Labels: weasels

#15008 PLG-210 / PLG-209 : display fake widget and helpers on the dashboards of the FT
  front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/SectionTitle.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
Labels: weasels

#14933 PLG-386: update content security policy for Appcues
  src/Akeneo/FreeTrial/back/Infrastructure/ExternalJavascriptDependencies/Appcues.php
Labels: weasels

#14984 PLG-107: In product grid, improve the page title when a view is selected
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/product/product-grid-view-title-context.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/ProductGridProjectDetails.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/ProductGridViewTitle.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15026 PLG-392: Main navigation is blurred after DSM changes
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.unit.tsx
  front-packages/akeneo-design-system/src/icons/AssetsIcon.tsx
  front-packages/akeneo-design-system/src/icons/CardIcon.tsx
  front-packages/akeneo-design-system/src/icons/ConnectIcon.tsx
  front-packages/akeneo-design-system/src/icons/DownloadIcon.tsx
  front-packages/akeneo-design-system/src/icons/EntityIcon.tsx
  front-packages/akeneo-design-system/src/icons/HelpIcon.tsx
  front-packages/akeneo-design-system/src/icons/ProductIcon.tsx
  front-packages/akeneo-design-system/src/icons/SettingsIcon.tsx
  front-packages/akeneo-design-system/src/icons/SystemIcon.tsx
  front-packages/akeneo-design-system/src/icons/UploadIcon.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/menu.ts
Labels: weasels

#15027 PLG-362: Remove helper messages in Connectivity for Free-Trial
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/dependencies.ts
  src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx
  src/Akeneo/Connectivity/Connection/front/src/error-management/components/ConnectionErrors.tsx
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/dependencies-provider.tsx
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags-context.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags.interface.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/index.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/use-feature-flags.ts
Labels: weasels

#15020 PLG-361: Remove helper from DQI dashboard for Free-Trial
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/DashboardHelper.tsx
Labels: weasels

#15033 PLG-360: Remove helpers for the Free-Trial
  front-packages/measurement/src/feature/pages/list/List.tsx
  front-packages/shared/src/DependenciesContext.tsx
  front-packages/shared/src/DependenciesProvider.type.ts
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useFeatureFlags.ts
  front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/dependencies.ts
  src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx
  src/Akeneo/Connectivity/Connection/front/src/error-management/components/ConnectionErrors.tsx
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/dependencies-provider.tsx
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags-context.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags.interface.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/index.ts
  src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/use-feature-flags.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/DashboardHelper.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/__mocks__/dependencies.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/dependencies.ts
Labels: weasels

#15032 PIM-9987: Fix product grid count not accurate after specific SKU selection
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/mass-actions.ts
Labels: wip
