Repository akeneo/pim-community-dev, pull requests merged in 2021-03, with the labels that each got.

#14003 PLG-63: Fix product-grid grouped variant filter dropdown
  CHANGELOG.md
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/grouped-variant-filter.js
Labels: weasels

#14024 BH-420: reactivate Behat retry
  .circleci/config.yml
  .circleci/run_behat.sh
Labels: CI

#13947 PLG-40: Revamp the Product Gallery row by using the Card component from the DSM
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-card-big-stacked-card-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-card-small-stacked-card-correctly-1-snap.png
  akeneo-design-system/src/components/Card/Card.stories.mdx
  akeneo-design-system/src/components/Card/Card.tsx
  akeneo-design-system/src/components/Card/Card.unit.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/ProductGrid.less
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/ProductGalleryRow.tsx
Labels: weasels

#14038 DAPI: update DQI labels in product export builder
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14039 PIM-9728: add missing daemon wrapper to CE
  bin/queue-daemon-wrapper.sh
Labels: wip

#13993 PLG-39: minor UI fix for PageHeader State component
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/page/header/State.tsx
Labels: weasels

#14073 PLG-86 - Update dashboard name to Activity dashboard
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14072 PLG-83 - Move CVM entry menu from Activity to System
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/catalog_volume/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
Labels: weasels

#14074 PLG-92 - Organize settings menu items
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/form_extensions.yml
Labels: weasels

#14075 PLG-104: reactify the activity/dashboard page (first iteration)
  package.json
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/dashboard.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/CompletenessWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/page/header/Illustration.tsx
Labels: weasels

#14092 PLG-89: display the last operations widget on the dashboard
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/operation.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardLastOperations.ts
  tests/front/unit/jest/unit.jest.js
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/platform/dashboard/display_last_operations_widget.feature
  tests/legacy/features/platform/security/login.feature
Labels: weasels

#14089 PLG-87: display the completeness widget on the dashboard
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/ChannelLocalesCompletenesses.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/CompletenessWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/completeness.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/operation.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/convertBackendDashboardCompletenessData.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/dashboard.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardCompleteness.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardLastOperations.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/tests/front/unit/helpers/convertBackendDashboardCompletenessData.unit.ts
  tests/front/unit/jest/unit.jest.js
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/platform/dashboard/display_last_operations_widget.feature
  tests/legacy/features/platform/security/login.feature
Labels: weasels

#14098 PLG 134
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/twig.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Twig/UpdateExtension.php
  src/Akeneo/Platform/Bundle/DashboardBundle/Controller/VersionController.php
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/PimVersion.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/usePimVersion.ts
  src/Akeneo/Platform/VersionProvider.php
  src/Akeneo/Platform/VersionProviderInterface.php
  src/Oro/Bundle/ConfigBundle/Resources/public/js/form/system/tab/notification.js
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/Twig/UpdateExtensionSpec.php
  tests/back/Platform/Specification/Bundle/DashboardBundle/Controller/VersionControllerSpec.php
  tests/back/Platform/Specification/VersionProviderSpec.php
Labels: weasels, wip

#14130 PLG-99: display progress messages on completeness component (+CS)
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/ChannelLocalesCompletenesses.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/usePimVersion.ts
  src/Oro/Bundle/ConfigBundle/Resources/public/js/form/system/tab/notification.js
Labels: weasels

#14134 PIM-9737: Pull-up 4.0 => 5.0
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php
  src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
  tests/back/Acceptance/Attribute/InMemoryGetExistingReferenceDataCodes.php
  tests/back/Acceptance/Resources/config/pim/queries.yml
  tests/back/Acceptance/spec/Attribute/InMemoryGetExistingReferenceDataCodesSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScopeIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
Labels: PULLUP

#14136 PIM-9737: Pull-up 4.0 => 5.0 (fix squashed history)
  CHANGELOG-4.0.md
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
Labels: PULLUP

#14137 PIM-9729: Pull up 5.0 => master
  .circleci/detect_structure_changes.sh
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  CHANGELOG-5.0.md
  composer.lock
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/Channel/Bundle/Resources/translations/validators.fi_FI.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.fi_FI.yml
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart/WeeklyAuditChart.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.fi_FI.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.nl_NL.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fi_FI.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.nl_NL.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.fi_FI.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fi_FI.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.nl_NL.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.nl_NL.yml
  std-build/install-required-files.sh
  std-build/migration/32_to_40/oneup_flysystem.yml
  std-build/migration/32_to_40/rector.yaml
  std-build/migration/32_to_40/rector_ce_auto.yaml
  std-build/migration/get_renamed_php_classes.php
  std-build/migration/prepare_40_to_50.sh
  tests/back/Acceptance/Attribute/InMemoryGetExistingReferenceDataCodes.php
  tests/back/Acceptance/Resources/config/pim/queries.yml
  tests/back/Acceptance/spec/Attribute/InMemoryGetExistingReferenceDataCodesSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScopeIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
  yarn.lock
Labels: PULLUP

#14103 PLG-101
  akeneo-design-system/src/components/Dropdown/Overlay/Overlay.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/index.ts
Labels: weasels, wip

#14120 PLG-135: add the Search component in the DSM
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-basic-search-input-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-example-inside-a-dropdown-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-example-with-only-a-filter-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-example-with-only-the-search-input-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-example-with-results-and-a-filter-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-inside-a-dropdown-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-standard-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-with-only-a-filter-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-search-with-results-and-a-filter-correctly-1-snap.png
  akeneo-design-system/src/components/Search/Search.stories.mdx
  akeneo-design-system/src/components/Search/Search.tsx
  akeneo-design-system/src/components/Search/Search.unit.tsx
  akeneo-design-system/src/components/index.ts
Labels: weasels

#14141 PLG fix translations
  CHANGELOG-5.0.md
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterKeyIndicatorFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  tests/legacy/features/channel/locale/browse_locales.feature
Labels: weasels

#14196 PLG-90: Fix end-to-end of dashboard proposals widget
  tests/legacy/features/Context/Page/Dashboard/Index.php
Labels: weasels
