Repository akeneo/pim-community-dev, pull requests merged in 2021-08, with the labels that each got.

#15041 PLG-303: Adapt the styles for the Options grid
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
Labels: weasels

#15061 PLG-302: Add Label column
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
Labels: weasels

#15065 PLG-298: As Julia, I want the label of my options to be always visible so that it is easier for me to manage
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
Labels: weasels

#15064 PLG-299: As Julia, I want to search within my options so that it is easier for me to manage
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NoResultOnSearch.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15068 PLG-306: Ensure the End to End tests work fine
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
Labels: weasels

#15085 PLG-298: As Julia, I want the label of my options to be always visible so that it is easier for me to manage
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
Labels: weasels

#15086 PLG-306-bis: Replace role by data-testid
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
Labels: weasels

#15074 PIM-9877: Optimize DQI dashboard data consolidation
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Structure/GetCategoryChildrenCodesQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Structure/GetCategoryChildrenCodesQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Structure/GetCategoryChildrenCodesQueryIntegration.php
Labels: weasels

#15009 PLG-388: Fix performance issue with the opening of the menu
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-navigation-sub-navigation-panel-collapsed-expanded-content-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.stories.mdx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.tsx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.unit.tsx
  front-packages/akeneo-design-system/static/illustrations/Settings.svg
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.tsx
  front-packages/shared/src/components/Navigation/SubNavigationDropdown.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
Labels: weasels

#14888 PLG-352: As UX designer, I want the PIM navigation to be consistent with the DSM components
  cypress/support/commands.js
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-navigation-sub-navigation-panel-collapsed-expanded-content-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.tsx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationItem/SubNavigationItem.tsx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.stories.mdx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.tsx
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.unit.tsx
  front-packages/akeneo-design-system/src/icons/AssetsIcon.tsx
  front-packages/akeneo-design-system/src/icons/CardIcon.tsx
  front-packages/akeneo-design-system/src/icons/ConnectIcon.tsx
  front-packages/akeneo-design-system/src/icons/DownloadIcon.tsx
  front-packages/akeneo-design-system/src/icons/EntityIcon.tsx
  front-packages/akeneo-design-system/src/icons/HelpIcon.tsx
  front-packages/akeneo-design-system/src/icons/ProductIcon.tsx
  front-packages/akeneo-design-system/src/icons/SettingsIcon.tsx
  front-packages/akeneo-design-system/src/icons/SystemIcon.tsx
  front-packages/akeneo-design-system/src/icons/UploadIcon.tsx
  front-packages/akeneo-design-system/src/icons/index.ts
  front-packages/akeneo-design-system/static/illustrations/Settings.svg
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.unit.tsx
  front-packages/shared/src/components/Navigation/SubNavigationDropdown.tsx
  front-packages/shared/src/components/Navigation/SubNavigationDropdown.unit.tsx
  front-packages/shared/src/components/Navigation/index.ts
  front-packages/shared/src/components/Navigation/navigationHelper.tsx
  front-packages/shared/src/components/__mocks__/PimView.tsx
  front-packages/shared/src/components/index.ts
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/column.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/item.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/menu.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/navigation-block.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/tab.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
Labels: weasels, Feature branch

#15040 PLG-308: Add Label column in 5.0
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
Labels: weasels

#14935 PLG-317: add fake EE features in PIM menus and dashboards for the free trial
  front-packages/akeneo-design-system/src/components/Navigation/SubNavigationItem/SubNavigationItem.tsx
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.tsx
  front-packages/shared/src/components/Navigation/navigationHelper.tsx
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/form_extensions/menu.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/user-groups-menu-item.ts
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/SectionTitle.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/item.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/navigation-menu/menu.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
Labels: weasels

#15095 PLG-306: Ensure the End to End tests work fine
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/Context/Page/Base/Base.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
  tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
Labels: weasels

#15097 PLG-456: Currencies - English improvements
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/views/Property/activated.html.twig
Labels: weasels

#15125 PLG-452: Auto-collapse left-column when starting compare/translate
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sub-navigation.ts
Labels: weasels

#15102 PLG-457: Improve english on bulk actions selection page
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15108 PLG-454: Change the 404 page English message
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15107 PLG-460: Families bulk actions - English improvements
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15106 PLG-459: Attribute main screen - English improvements
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15099 PLG-455: CVM page - English improvements
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#15060 PLG-401: Open the category tree to the last selected category, if any
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/treeHelper.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/helpers/treeHelper.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts
Labels: weasels

#15101 PLG-348: Improve display of compare/translate
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sub-navigation.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AttributeActions.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/ComparableFields.less
Labels: weasels, Feature branch

#15134 PLG-476: "Add option" button size to small
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
Labels: weasels

#15111 PLG-471: Move Free-Trial bundle content in EE/tria
  src/Akeneo/FreeTrial/back/Infrastructure/ExternalJavascriptDependencies/Appcues.php
  src/Akeneo/FreeTrial/back/Infrastructure/ExternalJavascriptDependencies/ExternalDependenciesFeatureFlag.php
  src/Akeneo/FreeTrial/back/Infrastructure/ExternalJavascriptDependencies/Heap.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/DependencyInjection/AkeneoCommunityFreeTrialExtension.php
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/external_javascript_dependencies.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/form_extensions/menu.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcues-agent.ts
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcues-onboarding.ts
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/user-groups-menu-item.ts
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/onboarding/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/onboarding/pim-onboarding.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.ts
Labels: weasels

#15147 PLG-136: UX - Improve English
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/views/Property/activated.html.twig
  tests/legacy/features/Context/Page/Batch/Operation.php
  tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/add_attribute_value.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_images.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_metric.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_per_families.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_scopable_localizable.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_action_count_impacted_products_and_variant_products.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_edit_and_update_attribute_history.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/mass_associate.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_boolean_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_date_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_file_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_image_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_numeric_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_select_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_text_attributes.feature
  tests/legacy/features/pim/enrichment/reference-data/mass-action/edit_common_attributes.feature
Labels: weasels

#15021 PLG-97: Views & projects - IMP UX
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/product/product-grid-view-title-context.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/ProductGridProjectDetails.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/ProductGridViewTitle.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels, Feature branch

#15069 PLG-297: Options - IMP UX
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NoResultOnSearch.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/Context/Page/Base/Base.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
  tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
Labels: weasels, Feature branch

#15148 PLG-136: UX - Improve English
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/views/Property/activated.html.twig
  tests/legacy/features/Context/Page/Batch/Operation.php
  tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/add_attribute_value.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_images.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_metric.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_per_families.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_scopable_localizable.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_action_count_impacted_products_and_variant_products.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_edit_and_update_attribute_history.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/mass_associate.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_boolean_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_date_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_file_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_image_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_numeric_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_select_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_text_attributes.feature
  tests/legacy/features/pim/enrichment/reference-data/mass-action/edit_common_attributes.feature
Labels: weasels, Feature branch

#15129 PLG-260: Create a menu page for System
  front-packages/akeneo-design-system/src/icons/UserIcon.tsx
  front-packages/akeneo-design-system/src/icons/index.ts
  package.json
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/public/js/SystemInfo.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Controller/SystemController.php
  src/Akeneo/Platform/Bundle/UIBundle/Query/CountSystemEntitiesQueryInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Query/Sql/CountSystemEntitiesQuery.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/queries.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/system-index.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCountEntities.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/index.ts
  tests/back/Platform/Integration/UI/Query/CountSystemEntitiesQueryIntegration.php
Labels: weasels

#15116 PLG-300: As a PM, I want the improvements of the options to be available for 5.0 customers
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
Labels: weasels

#15177 Revert "PLG-297: Options - IMP UX"
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NoResultOnSearch.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/Context/Page/Base/Base.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
  tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
Labels: weasels

#15181 BH-681: Bundle notation is deprecated
  config/packages/oro_filter.yml
  config/packages/twig.yml
  config/routes/routes.yml
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
  src/Akeneo/Channel/Bundle/Resources/config/datagrid/locale.yml
  src/Akeneo/Channel/Bundle/Resources/config/view_elements/attribute.yml
  src/Akeneo/Channel/Bundle/Twig/LocaleExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/renderers.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/SystemInfoController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/job_execution.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/job_tracker.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_executions.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/views/layout.html.twig
  src/Akeneo/Platform/Bundle/NotificationBundle/Controller/NotificationController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/config/placeholders.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/placeholders.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/JobExecution/index.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/actions/update.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/actions/view.html.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/placeholders.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/view_elements/group.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/view_elements/user.yml
  src/Akeneo/UserManagement/Bundle/Resources/views/Group/update.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Mail/reset.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/_fields.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Reset/reset.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Role/update.html.twig
  src/Oro/Bundle/DataGridBundle/Provider/SystemAwareResolver.php
  src/Oro/Bundle/FilterBundle/DependencyInjection/Configuration.php
  src/Oro/Bundle/FilterBundle/Resources/views/Filter/header.html.twig
  src/Oro/Bundle/TranslationBundle/Resources/config/services.yml
  tests/back/Platform/Specification/Bundle/NotificationBundle/Controller/NotificationControllerSpec.php
Labels: symfony5

#15219 BH-681: Fix Doctrine deprecation
  src/Akeneo/Channel/Component/Repository/ChannelRepositoryInterface.php
  src/Akeneo/Channel/Component/Repository/CurrencyRepositoryInterface.php
  src/Akeneo/Channel/Component/Repository/LocaleRepositoryInterface.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookUserAuthenticator.php
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/InitializeJobs.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnSave/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTree.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/GroupRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductModelRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductUniqueDataRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ReferenceDataRepositoryInterface.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletion.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/RemoveFamilyFromJobInstanceFiltersOnFamilyDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/AttributeGroupNormalizer.php
  src/Akeneo/Pim/Structure/Component/Repository/AssociationTypeRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeGroupRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeOptionRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/AttributeRequirementRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/FamilyRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/FamilyVariantRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Repository/GroupTypeRepositoryInterface.php
  src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Entity/Repository/UserNotificationRepositoryInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Form/Transformer/EntityToIdentifierTransformer.php
  src/Akeneo/Platform/Bundle/UIBundle/Form/Type/ObjectIdentifierType.php
  src/Akeneo/Tool/Component/Api/Repository/ApiResourceRepositoryInterface.php
  src/Akeneo/Tool/Component/BatchQueue/Factory/JobExecutionMessageFactory.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Factory/JobExecutionMessageFactorySpec.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
  src/Akeneo/Tool/Component/Classification/Repository/CategoryRepositoryInterface.php
  src/Akeneo/Tool/Component/Classification/Repository/TagRepositoryInterface.php
  src/Akeneo/Tool/Component/Connector/Reader/Database/Reader.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/Database/ReaderSpec.php
  src/Akeneo/Tool/Component/FileStorage/Repository/FileInfoRepositoryInterface.php
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/EventListener/AddDefaultPrivilegesSubscriber.php
  src/Akeneo/UserManagement/Bundle/EventListener/CreateUserSystemListener.php
  src/Akeneo/UserManagement/Bundle/Manager/UserManager.php
  src/Akeneo/UserManagement/Component/Connector/Reader/Database/User.php
  src/Akeneo/UserManagement/Component/Connector/Reader/Database/UserRole.php
  src/Akeneo/UserManagement/Component/Repository/UserRepositoryInterface.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/Datasource.php
Labels: symfony5

#15225 BH-681: Fix Doctrine deprecation
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/LocalizableSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithValues/LoadEntityWithValuesSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/TimestampableSubscriber.php
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/LoadJobParametersListener.php
  src/Akeneo/Tool/Bundle/BatchBundle/spec/EventListener/LoadJobParametersListenerSpec.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/MappingsOverrideConfiguratorInterface.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/ORM/MappingsOverrideConfigurator.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/EventSubscriber/ConfigureMappingsSubscriber.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/EventSubscriber/ResolveTargetRepositorySubscriber.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/spec/EventSubscriber/ResolveTargetRepositorySubscriberSpec.php
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriber.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/EventSubscriber/TimestampableSubscriberSpec.php
  src/Oro/Bundle/PimDataGridBundle/EventSubscriber/FilterEntityWithValuesSubscriber.php
  src/Oro/Bundle/PimDataGridBundle/spec/EventSubscriber/FilterEntityWithValuesSubscriberSpec.php
  tests/back/Acceptance/Category/InMemoryCategoryRepository.php
  tests/back/Acceptance/Currency/InMemoryCurrencyRepository.php
  tests/back/Acceptance/User/InMemoryGroupRepository.php
  tests/back/Acceptance/User/InMemoryRoleRepository.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Filter/ObjectCodeResolverSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ProductModelRepositorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ReferenceDataRepositoryResolverSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Category/OnSave/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTreeSpec.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/RemoveFamilyFromJobInstanceFiltersOnFamilyDeletionSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/InternalApi/AttributeGroupNormalizerSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/Form/Transformer/EntityToIdentifierTransformerSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Reader/Database/UserRoleSpec.php
  tests/back/UserManagement/Specification/Component/Updater/UserUpdaterSpec.php
Labels: symfony5
