Repository akeneo/pim-community-dev, pull requests merged in 2021-09, with the labels that each got.

#15242 PIM-10057: Pull-up 4.0 to 5.0
  CHANGELOG-4.0.md
Labels: PULLUP

#15238 BH-681: Fix various deprecations
  composer.json
  composer.lock
  src/Akeneo/Channel/Bundle/Doctrine/Repository/InternalApi/ChannelRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductValuesEditDataFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Form/Subscriber/FilterLocaleSpecificValueSubscriber.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/AttributeColumnInfoExtractor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/FamilyRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/FamilyVariantRepository.php
  src/Akeneo/Pim/Structure/Component/Model/AbstractAttribute.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeInterface.php
  src/Akeneo/Tool/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php
  src/Akeneo/Tool/Component/Classification/Repository/CategoryFilterableRepositoryInterface.php
  tests/back/Pim/Enrichment/Specification/Bundle/Form/Subscriber/FilterLocaleSpecificValueSubscriberSpec.php
Labels: symfony5

#15218 BH-681: Update Doctrine dependencies
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yml
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookUserAuthenticator.php
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ReferenceDataRepositoryResolver.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/LocalizableSubscriber.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ReferenceDataRepositoryResolverInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/spec/Doctrine/ORM/MappingsOverrideConfiguratorSpec.php
  src/Oro/Bundle/SecurityBundle/Acl/Persistence/AbstractAclManager.php
  symfony.lock
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ProductRepositorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Updater/TwoWayAssociationUpdaterSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/AttributeOption/LocalizableSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithValues/LoadEntityWithValuesSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/TimestampableSubscriberSpec.php
  tests/back/UserManagement/Specification/Bundle/Doctrine/ORM/Repository/RoleWithPermissionsRepositorySpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/RoleNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Storage/Saver/RoleWithPermissionsSaverSpec.php
  tests/back/UserManagement/Specification/Component/Updater/RoleWithPermissionsUpdaterSpec.php
  tests/legacy/features/Behat/Context/HookContext.php
  upgrades/schema/Version_4_0_20200113145800_fix_versioning_indexes.php
  upgrades/test_schema/Version_4_1_20200127171059_unauthorized_view_all_jobs_permission_Integration.php
Labels: symfony5

#15255 PLG-537: When there is an error at code creation, loading freezes the page
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
Labels: weasels

#15239 PLG-529: Track application events to complete the checklist #1 (Customize your workspace)
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/Product.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js
Labels: weasels

#15132 PLG-301: Improve the Boolean Input in DSM
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-boolean-input-invalid-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.tsx
Labels: weasels

#15166 PLG-474: improve attribute options performances
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionQualityBadge.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionRow.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AutoOptionSorting.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NoResultOnSearch.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/QualityBadge.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/helper/getQualityBadgeLevel.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptionsListState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSortedAttributeOptions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/AttributeOption.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/SpellcheckEvaluation.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsExtraDataReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
  tests/front/unit/structure/attribute-option/components/AttributeOptionForm.unit.tsx
  tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx
  tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
  tests/front/unit/structure/attribute-option/components/List.unit.tsx
  tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
  tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
  tests/front/unit/structure/attribute-option/hooks/useAttributeOptionsListState.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsExtraDataReducer.unit.tsx
  tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
  tests/legacy/features/Context/Page/Attribute/Creation.php
  tests/legacy/features/Context/Page/Base/Base.php
  tests/legacy/features/Context/WebUser.php
  tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
  tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
Labels: weasels

#15272 BH-681: Downgrade Doctrine before fixing migrations
  composer.json
  composer.lock
  config/packages/doctrine.yml
  symfony.lock
Labels: symfony5

#15280 BH-681: Use doctrine/migrations v3
  composer.json
  composer.lock
  config/packages/doctrine.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  upgrades/test_schema/ExecuteMigrationTrait.php
Labels: symfony5

#15306 SDS-20187: fix wrong check before saving consolidated product scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateProductScores.php
Labels: bug, weasels

#15307 SDS-20187: backport in 5.0, fix wrong check before saving consolidated product scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateProductScores.php
Labels: bug, weasels

#15298 PLG-531: Track application events to complete the checklist #3 (Localize your catalog for new markets)
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js
Labels: weasels

#15165 PLG-56: Free-Trial catalog installation
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
Labels: weasels

#15264 BH-681: Use FriendsOfBehat libraries
  behat.yml
  composer.json
  composer.lock
  config/bundles.test.php
  config/services/behat/services.yml
  config/services/test_fake/services.yml
  docker-compose.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/repositories.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/behat-coverage.yml
  src/Akeneo/Connectivity/Connection/back/tests/Acceptance/behat.yml
  symfony.lock
  tests/back/Acceptance/Attribute/AttributeContext.php
  tests/legacy/features/Behat/Context/Domain/Enrich/ProductContext.php
  tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php
  tests/legacy/features/Behat/Context/FixturesContext.php
  tests/legacy/features/Behat/Context/HookContext.php
  tests/legacy/features/Behat/Context/MassEditJobContext.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Behat/Context/PimContext.php
  tests/legacy/features/Behat/Context/Storage/FileInfoStorage.php
  tests/legacy/features/Behat/Context/Storage/ProductModelStorage.php
  tests/legacy/features/Behat/Decorator/ElementDecorator.php
  tests/legacy/features/Context/AssertionContext.php
  tests/legacy/features/Context/CatalogConfigurationContext.php
  tests/legacy/features/Context/CommandContext.php
  tests/legacy/features/Context/ConnectivityContext.php
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/Context/FeatureContext.php
  tests/legacy/features/Context/FixturesContext.php
  tests/legacy/features/Context/NavigationContext.php
  tests/legacy/features/Context/Spin/SpinCapableTrait.php
  tests/legacy/features/Context/TransformationContext.php
  tests/legacy/features/Context/WebUser.php
Labels: symfony5

#15363 BH-681: Fixes Twig deprecated classes
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Channel/Bundle/Twig/LocaleExtension.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Twig/AttributeExtension.php
  src/Akeneo/Pim/Enrichment/Bundle/Twig/CategoryExtension.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Twig/UpdateExtension.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Twig/NotificationExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/AttributeExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/ContentSecurityPolicyExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/ExternalJavascriptDependenciesExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/LocaleExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/Node/PlaceholderNode.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/ObjectClassExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/StyleExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/TranslationsExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/UiExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/VersionExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Twig/ViewElementExtension.php
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Twig/AclGroupsExtension.php
  src/Oro/Bundle/ConfigBundle/Twig/ConfigExtension.php
  src/Oro/Bundle/DataGridBundle/Twig/MetadataExtension.php
  src/Oro/Bundle/FilterBundle/Twig/AbstractExtension.php
  src/Oro/Bundle/FilterBundle/Twig/RenderHeaderExtension.php
  src/Oro/Bundle/FilterBundle/Twig/RenderLayoutExtension.php
  src/Oro/Bundle/PimDataGridBundle/Twig/FilterExtension.php
  src/Oro/Bundle/SecurityBundle/Twig/OroSecurityExtension.php
  tests/back/Channel/Specification/Bundle/Twig/LocaleExtensionSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/Twig/ViewElementExtensionSpec.php
Labels: symfony5

#15369 PIM-464: the catalog parameter is required for enterprise edition when the post_load_fixture
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
Labels: weasels

#15347 PLG-559: As a PM, I want IDs created on main and sub-navigation items so that I can guarantee proper EE features display and track user behavior in Appcues and Heap.io
  front-packages/akeneo-design-system/src/components/IconCard/IconCard.tsx
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
Labels: weasels

#15372 Run cypress in prod mode
  .circleci/config.yml
Labels: CI

#15348 PLG-407: Add Analytics module to track user actions
  front-packages/shared/src/DependenciesContext.tsx
  front-packages/shared/src/DependenciesProvider.type.ts
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useAnalytics.ts
  front-packages/shared/src/hooks/useAnalytics.unit.ts
  front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx
  front-packages/shared/src/tests/mockedDependencies.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/Product.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/mass-edit.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/family-variant.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector-save-view.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/launch.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/choose.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/family/set-requirements.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-analytics.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/field.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/dependencies.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js
Labels: weasels
