Repository akeneo/pim-community-dev, pull requests merged in 2021-02, with the labels that each got.

#13827 DAPI-1488: Export products quality scores (Backend)
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilterSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
  src/Akeneo/Tool/Component/Connector/Writer/File/DefaultColumnSorter.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/DefaultColumnSorterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
Labels: weasels

#13812 DAPI-1307: set a fixed width for the checkbox column in tables
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-with-a-high-number-of-tags-correctly-1-snap.png
  akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
  akeneo-design-system/src/components/Table/TableHeader/TableHeader.tsx
  akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
Labels: weasels

#13854 DAPI-1487: export a product set depending on the Quality Score (front)
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/quality-score.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/filter.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/select-operator.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/select-score.html
Labels: weasels

#13888 PIM-9671: Provide a data quality insight status context for attribute groups
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/AttributeGroupsStatusContext.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useFetchAllAttributeGroupsStatus.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useFetchAllAttributeGroupsStatus.unit.ts
Labels: bug, weasels

#13904 PIM-9670: Fix attribute filter Group issue when several attribute groups have the same label
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeGroupRepository.php
Labels: bug, core-team

#13898 DAPI-1260: update legacy behat regarding locales
  tests/legacy/features/channel/locale/browse_locales.feature
Labels: weasels

#13916 DAPI-1443: Disable operator when no seleted score
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/quality-score.js
Labels: weasels

#13868 DAPI-1490: fix redirect to product grid from DQI dashboard when a default view is activated on the user profile
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: weasels

#13925 DAPI-1491: pass locale to followCriterionRecommendation callback
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Criterion.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followCriterionRecommendation.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.tsx
Labels: weasels

#13928 PIM-9684: Merge branch 3.2 into 4.0
  .circleci/config.yml
  CHANGELOG-3.2.md
  package.json
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
  src/Akeneo/Tool/Bundle/ApiBundle/EventListener/CheckApiRequestContentSizeListener.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/event_listeners.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
  yarn.lock
Labels: PULLUP

#13822 DAPI-1443: Export products with quality score
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilterSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/quality-score.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/filter.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/select-operator.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/product/quality-score/select-score.html
  src/Akeneo/Tool/Component/Connector/Writer/File/DefaultColumnSorter.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/DefaultColumnSorterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
Labels: Feature branch, weasels

#13800 DAPI-1480: Add the ability to filter products on Quality Score through the API
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/Rank.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/ValueObject/RankSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreFilterSpec.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
Labels: weasels

#13923 PLG-36 / PLG-37: update title styles in Connections by using DSM
  src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart/WeeklyAuditChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/DataDestinationCharts.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/DataSourceCharts.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/ErrorManagement/BusinessErrorCountWidget.tsx
  src/Akeneo/Connectivity/Connection/front/src/audit/components/ErrorManagement/DataSourceErrorChart.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/Section.tsx
  src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCredentials.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionEditForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionGrid.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/credentials/Credential.tsx
  src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/ConnectionPermissionsForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
Labels: weasels

#13901 PLG-18: ease the add of external javascript dependencies and their content security policy
  src/Akeneo/Platform/Bundle/UIBundle/EventListener/AddContentSecurityPolicyListener.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProvider.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/ContentSecurityPolicyProvider.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/ContentSecurityPolicyProviderInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ExternalDependencyProviderInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ExternalJavascriptDependenciesProvider.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/twig.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Twig/ExternalJavascriptDependenciesExtension.php
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
  tests/back/Platform/Specification/Bundle/UIBundle/EventListener/AddContentSecurityPolicyListenerSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/Provider/ContentSecurityPolicy/ContentSecurityPolicyProviderSpec.php
Labels: weasels
