Repository akeneo/pim-community-dev, pull requests merged in 2021-04, with the labels that each got.

#14166 PLG-93: Revamp PEF completeness panels
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/completeness/formatProductCompleteness.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/completeness.js
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/product/completeness/formatProductCompleteness.unit.ts
  tests/legacy/features/Behat/Context/Domain/Enrich/CompletenessContext.php
  tests/legacy/features/Behat/Decorator/Completeness/PanelDecorator.php
  tests/legacy/features/Context/Page/Product/Edit.php
  tests/legacy/features/pim/enrichment/product/completeness/display_completeness.feature
Labels: weasels

#14224 PLG-175 - fix design review
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-field-channel-and-locale-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-locale-label-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-locale-standard-correctly-1-snap.png
  akeneo-design-system/src/components/Locale/Locale.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/completeness/formatProductCompleteness.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  tests/back/Platform/Specification/VersionProviderSpec.php
Labels: weasels

#14207 PLG-150: Add new workspace Enrichment
  package.json
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/package.json
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/index.ts
Labels: weasels

#14233 PLG-168: Initialize the list of category trees page
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/CategoriesApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/EmptyCategoryTreeList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
Labels: weasels

#14238 PLG-169: Show the list of category trees
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts
Labels: weasels

#14239 PLG-187: Initialize the category tree page
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/CategoriesApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useSetPageTitle.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useSetPageTitle.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14252 PLG-173: Follow a category tree from the category tree list
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
Labels: weasels

#14071 PLG-64: Revamp Association-types data-grid
  akeneo-design-system/src/icons/DeleteIcon.tsx
  behat.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/AssociationTypesSettings.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AssociationTypesApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/AssociationTypesDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/DeleteConfirmation.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/NoAssociationTypes.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/association-types/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/association-types/useAssociationTypes.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/removers/associationTypeRemover.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AssociationType.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/association_type/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  tests/legacy/features/Behat/Context/Domain/Structure/AssociationTypeContext.php
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/Context/Page/AssociationType/Index.php
  tests/legacy/features/pim/structure/association-type/browse_association_types.feature
  tests/legacy/features/pim/structure/association-type/delete_association_type.feature
Labels: weasels

#14262 PLG-178: Add ACL on catalog volume monitoring
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Controller/VolumeMonitoringController.php
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/acl.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  tests/back/Platform/Specification/Bundle/CatalogVolumeMonitoringBundle/Controller/VolumeMonitoringControllerSpec.php
Labels: weasels

#14290 PLG-84: display a random welcome sentence as title
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
Labels: weasels

#14217 PLG-151: Revamp completeness panel in PEF header
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/helpers/formatCurrentCompleteness.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/helpers/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/helpers/scrollToPefAttribute.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/hooks/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/hooks/useScrollToAttribute.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/CurrentCompleteness.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/Product.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/index.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/tests/front/unit/helpers/formatCurrentCompleteness.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/completeness-follow-missing-attribute.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/completeness.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-completeness.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/product-completeness.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/provider/DependenciesProvider.type.ts
Labels: weasels

#14296 OB-752: Fix php-memcached version
  CHANGELOG-5.0.md
  Dockerfile.base
Labels: to review

#14272 PLG-183: Initialize the category edition page
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/CategoriesApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategory.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useFetch.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useSetPageTitle.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useFetch.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useSetPageTitle.unit.ts
Labels: weasels

#14274 PLG-186: Follow a category from the category tree
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
Labels: weasels

#14318 PLG-215: rename settings navigation block labels
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: weasels

#14307 PLG-220: add IconCard component in the DSM
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-big-icon-card-grid-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-icon-card-grid-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-long-title-and-content-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-readonly-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-standard-correctly-1-snap.png
  akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-icon-card-with-no-content-correctly-1-snap.png
  akeneo-design-system/src/components/IconCard/IconCard.stories.mdx
  akeneo-design-system/src/components/IconCard/IconCard.tsx
  akeneo-design-system/src/components/IconCard/IconCard.unit.tsx
  akeneo-design-system/src/components/index.ts
Labels: weasels

#14254 PLG-195 : new settings index page
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/settings.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/column.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
Labels: weasels

#14326 PLG-64: Prevent pagination crash when empty search result
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
Labels: weasels

#14331 PLG-224: Fix the completeness for the channel and locale in the header of the PEF
  src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
Labels: weasels

#14332 PLG-225: Fix Wrong display of the Settings landing page when all catalog entries are not available
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
Labels: weasels

#14325 PLG-172 - Search category trees on label or code
  akeneo-design-system/src/components/Search/Search.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
Labels: weasels

#14335 PLG-165: create a category tree
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/categoryTreeSaver.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx
Labels: weasels

#14347 PLG-226: Settings entry should not be displayed when a user has no right on Settings items
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/menu.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/tab.js
Labels: weasels

#12987 Update Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: to review

#14353 PLG-166: delete category tree
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/DeleteCategoryModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/removers/deleteCategory.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/removers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx
Labels: weasels

#14352 PLG-216: Display count entities figures in settings home page
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/settings/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/settings/useCountEntities.ts
  src/Akeneo/Platform/Bundle/UIBundle/Controller/SettingsController.php
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/PimUIExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Query/CountSettingsEntitiesQueryInterface.php
  src/Akeneo/Platform/Bundle/UIBundle/Query/Sql/CountSettingsEntitiesQuery.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/queries.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  tests/back/Platform/Integration/UI/Query/CountSettingsEntitiesQueryIntegration.php
Labels: weasels

#14364 PLG-164: Display the number of categories in trees list
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/CountTreesChildren.php
  src/Akeneo/Pim/Enrichment/Component/Category/Query/CountTreesChildrenInterface.php
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountCategoryTreesChildren.ts
  tests/back/Pim/Enrichment/Integration/Category/CountTressChildrenIntegration.php
Labels: weasels

#14371 PIM-9836: Pull-up 5.0 → master
  CHANGELOG-5.0.md
  config/services/test_fake/services.yml
  make-file/test.mk
  phpunit.xml.dist
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
  src/Akeneo/Tool/Bundle/MeasureBundle/Application/CreateMeasurementFamily/CreateMeasurementFamilyHandler.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Application/DeleteMeasurementFamily/DeleteMeasurementFamilyHandler.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandler.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyCreated.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyDeleted.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyUpdated.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Model/MeasurementFamily.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
  src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/FindAllMeasurementFamilies.php
  src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/MeasurementFamily.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandlerSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyCreatedSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyDeletedSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyUpdatedSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/DeleteMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyActionEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/SaveMeasurementFamilyActionEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/Onboarder/FindAllMeasurementFamiliesIntegration.php
  tests/back/Acceptance/EventDispatcher/EventDispatcherMock.php
Labels: PULLUP
