Repository akeneo/pim-community-dev, pull requests merged in 2021-11, with the labels that each got.

#15587 PLG-334: Remove display of catalog-volume-monitoring warnings
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/section.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/catalog-volume/average-max.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/catalog-volume/number.html
Labels: weasels

#15575 PLG-472: Improve rounding key indicators extremities
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/KeyIndicatorSpec.php
Labels: weasels

#15661 BH-859: Fix Doctrine deprecations for migrations
  upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
  upgrades/schema/Version_4_0_20200116122239_remove_product_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs.php
  upgrades/schema/Version_4_0_20200415194400_remove_product_foreign_key_pim_catalog_completeness.php
  upgrades/schema/Version_4_1_20200127171059_unauthorized_view_all_jobs_permission.php
  upgrades/schema/Version_5_0_20200309165300_remove_product_foreign_key_pim_catalog_completeness.php
  upgrades/schema/Version_5_0_20200313140000_regenerate_missing_data_for_the_connection_audit.php
  upgrades/schema/Version_5_0_20200702232424_create_communication_channel_viewed_announcement_index.php
  upgrades/schema/Version_5_0_20200826153300_add_primary_key_connection.php
  upgrades/schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score.php
  upgrades/schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection.php
  upgrades/schema/Version_5_0_20201127102539_fix_pressure_operations.php
  upgrades/schema/Version_5_0_20201211081205_fix_duration_conversion.php
  upgrades/schema/Version_5_0_20211018134301_migrate_longtext_to_json.php
  upgrades/schema/Version_6_0_20210331105730_remove_datagrid_view_unique_label_constraint.php
  upgrades/schema/Version_6_0_20210510102539_fix_micro_operations.php
  upgrades/schema/Version_6_0_20210908142400_add_product_web_api_acl.php
  upgrades/test_schema/Version_4_0_20191031124707_update_from_clients_to_connections_Integration.php
  upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
  upgrades/test_schema/Version_5_0_20200217155537_add_measurement_table_Integration.php
  upgrades/test_schema/Version_5_0_20200313140000_regenerate_missing_data_for_the_connection_audit_Integration.php
  upgrades/test_schema/Version_5_0_20200320095430_add_is_two_way_col_to_associations_Integration.php
  upgrades/test_schema/Version_5_0_20200324104437_migrate_measurement_table_Integration.php
  upgrades/test_schema/Version_5_0_20200504084844_add_quantified_column_on_association_type_Integration.php
  upgrades/test_schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation_Integration.php
  upgrades/test_schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score_Integration.php
  upgrades/test_schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection_Integration.php
  upgrades/test_schema/Version_5_0_20201127102539_fix_pressure_operations_Integration.php
  upgrades/test_schema/Version_5_0_20201211081205_fix_duration_conversion_Integration.php
  upgrades/test_schema/Version_5_0_20210507154610_update_pim_catalog_completeness_id_Integration.php
  upgrades/test_schema/Version_5_0_20211018134301_migrate_longtext_to_json_Integration.php
  upgrades/test_schema/Version_6_0_20210330143635_sanitize_users_and_channels_having_link_to_subcategory_Integration.php
  upgrades/test_schema/Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted_Integration.php
  upgrades/test_schema/Version_6_0_20210505180000_add_updated_to_category_Integration.php
  upgrades/test_schema/Version_6_0_20210510102539_fix_micro_operations_Integration.php
  upgrades/test_schema/Version_6_0_20210527144217_dqi_init_recompute_products_scores_Integration.php
  upgrades/test_schema/Version_6_0_20210908142400_add_product_web_api_acl_Integration.php
  upgrades/test_schema/Version_6_0_20211025161901_set_default_role_type_Integration.php
Labels: symfony5, PHP8

#15655 BH-859: Use lazy commands
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/ConsolidateDashboardRatesCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/InitializeProductsEvaluationsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/LaunchEvaluationsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/MigrateProductCriterionEvaluationCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PrepareEvaluationsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/RecomputeProductsScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/SchedulePeriodicTasksCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Tool/Bundle/ApiBundle/Command/ListClientsCommand.php
Labels: symfony5

#15660 Fix Version_6_0_20210331105730
  upgrades/schema/Version_6_0_20210331105730_remove_datagrid_view_unique_label_constraint.php
Labels: bug

#15634 PLG-641: Create a feature flag to able to switch between "old CVM page" and "new CVM page"
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/DependencyInjection/PimCatalogVolumeMonitoringExtension.php
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/feature_flag.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/catalog-volume.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/catalog-volume.tsx
Labels: weasels

#15678 BH-859: Update Doctrine dependencies
  composer.json
  composer.lock
Labels: PHP8

#15665 PLG-640: Initialize a Microfrontend for Catalog Volume Monitoring
  .circleci/config.yml
  .prettierignore
  package.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/.env
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/.gitignore
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/.prettierrc.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/package.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/public/index.html
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/FakePIM.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/Dummy.test.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/Dummy.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/index.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/react-app-env.d.ts
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/setupTests.ts
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/tsconfig.build.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/tsconfig.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/yarn.lock
  std-build/package.json
Labels: weasels

#15691 PLG-645: Initialize the Catalog Volume Monitoring page in React
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/FakePIM.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/CatalogVolumeMonitoringApp.test.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/CatalogVolumeMonitoringApp.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/Dummy.test.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/Dummy.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/index.tsx
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/index.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/catalog-volume.tsx
Labels: weasels

#15693 BH-859: Update Behat dependencies
  behat.yml
  composer.json
  composer.lock
  tests/legacy/features/Context/DataGridContext.php
  tests/legacy/features/Context/FeatureContext.php
Labels: PHP8

#15690 PLG-642: Add key figure component in DSM
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-key-figure-key-figure-grid-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-key-figure-standard-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-key-figure-value-only-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/KeyFigure/KeyFigure.stories.mdx
  front-packages/akeneo-design-system/src/components/KeyFigure/KeyFigure.tsx
  front-packages/akeneo-design-system/src/components/KeyFigure/KeyFigure.unit.tsx
  front-packages/akeneo-design-system/src/components/index.ts
Labels: weasels

#15766 BH-859: Use PHP 8.0
  .circleci/config.yml
  Dockerfile
  composer.json
  composer.lock
  docker-compose.yml
  docker/cypress/Dockerfile
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Write/CriterionEvaluationSpec.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/FileGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotDecimalValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/NotDecimalValidator.php
  src/Akeneo/Tool/Component/Batch/Job/ExitStatus.php
  src/Akeneo/Tool/Component/Batch/Step/ItemStep.php
  src/Akeneo/Tool/Component/Batch/spec/Job/ExitStatusSpec.php
  src/Akeneo/Tool/Component/Batch/spec/Model/JobExecutionSpec.php
  src/Akeneo/Tool/Component/Batch/spec/Model/StepExecutionSpec.php
  src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php
  src/Akeneo/Tool/Component/Localization/Validator/Constraints/DateFormatValidator.php
  src/Oro/Bundle/PimDataGridBundle/Normalizer/FamilyVariantNormalizer.php
  tests/legacy/features/pim/enrichment/product/validation/validate_localized_price_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_price_attributes.feature
Labels: PHP8

#15814 PLG-646: Add hook test
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/hooks/useCatalogVolumeByAxis.test.ts
Labels: weasels
