Repository akeneo/pim-community-dev, pull requests merged in 2022-09, with the labels that each got.

#17739 CPM-698: Add uuid in UpsertProductCommand
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
  src/Akeneo/Pim/Enrichment/Product/back/API/ValueObject/ProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Product/back/API/ValueObject/ProductUuid.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
  src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetCategoryCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetNonViewableCategoryCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/GetNonViewableCategoryCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetCategoryCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/IsUserOwnerOfTheProductValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetCategoryCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Resources/config/services.yml
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetCategoryCodesSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetProductUuidsSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Feature/upsert.feature
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/SqlGetCategoryCodesIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetCategoriesApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/GetNonViewableCategoryCodesSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
Labels: echoes/intent: feature

#17802 RAB-998: Add service API to delete user
  src/Akeneo/UserManagement/Bundle/Resources/config/service_api/handler.yml
  src/Akeneo/UserManagement/back/Application/Handler/DeleteUserHandler.php
  src/Akeneo/UserManagement/back/ServiceApi/User/DeleteUserCommand.php
  src/Akeneo/UserManagement/back/ServiceApi/User/DeleteUserHandlerInterface.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/DeleteUserHandlerIntegration.php
Labels: echoes/intent: feature

#17809 CXP-1250: AttributeTextareaCriterion
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextareaCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextareaCriterionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
Labels: echoes/intent: feature

#17803 CXP-1271: GetProductsQuery
  components/catalogs/back/.php_cd.php
  components/catalogs/back/.php_cs.php
  components/catalogs/back/src/Application/Persistence/GetProductUuidsQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetProductsQueryInterface.php
  components/catalogs/back/src/Infrastructure/Installer/InstallerSubscriber.php
  components/catalogs/back/src/Infrastructure/Persistence/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetProductsQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Integration/Fakes/Clock.php
  components/catalogs/back/tests/Integration/Fakes/TimestampableSubscriber.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  upgrades/schema/Version_7_0_20220830000000_add_catalog_product_values_filters.php
Labels: echoes/intent: technical

#17814 RAB-1009: Fetch only simple users in process tracker user filter
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobUser.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobUserTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesUserHelper.php
Labels: echoes/effort: XS, echoes/intent: feature

#17747 PIM-10598: Fix "Cleaning removed attribute values" job failing if attribute is deleted during mass deletion of products
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php
Labels: echoes/effort: XS, echoes/intent: maintenance

#17734 RAB-949: Add download & upload steps for every jobs
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/RemoteStorageFeatureFlag.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePathValidator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/step.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/job/common/edit/storage-form.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/FetchRemoteFileBeforeImport.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/FetchRemoteFilesAfterExport.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/spec/EventListener/FetchRemoteFilesAfterExportSpec.php
  src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
  tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
  tests/legacy/features/Behat/Context/ImportExportFileContext.php
  tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_media.feature
Labels: echoes/effort: M, echoes/intent: feature

#17821 CXP-1271: whistelist properties of normalized products
  components/catalogs/back/src/Infrastructure/Persistence/GetProductsQuery.php
Labels: echoes/intent: technical

#17692 CXP-1246: Selection criteria - Measurement
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Persistence/FindOneAttributeByCodeQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetMeasurementsFamilyQueryInterface.php
  components/catalogs/back/src/Application/Persistence/SearchAttributesQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsAction.php
  components/catalogs/back/src/Infrastructure/Persistence/FindOneAttributeByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetMeasurementsFamilyQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/MaxNumberOfCatalogsPerUser.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMeasurementCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidMeasurement.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidMeasurementValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/FindOneAttributeByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetMeasurementsFamilyQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMeasurementCriterionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsActionTest.php
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.ts
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useMeasurements.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useMeasurements.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Attribute.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Measurement.d.ts
  components/catalogs/front/tests/setup-integration.ts
Labels: echoes/intent: feature

#17829 Cxp 1246 deploy
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Persistence/FindOneAttributeByCodeQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetMeasurementsFamilyQueryInterface.php
  components/catalogs/back/src/Application/Persistence/SearchAttributesQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsAction.php
  components/catalogs/back/src/Infrastructure/Persistence/FindOneAttributeByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetMeasurementsFamilyQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/MaxNumberOfCatalogsPerUser.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMeasurementCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidMeasurement.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidMeasurementValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/FindOneAttributeByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetMeasurementsFamilyQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMeasurementCriterionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetMeasurementsFamilyUnitsActionTest.php
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.ts
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useMeasurements.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useMeasurements.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Attribute.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Measurement.d.ts
  components/catalogs/front/tests/setup-integration.ts
Labels: echoes/intent: feature

#17820 CPM-632: Update product with uuid from PEF
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php
Labels: echoes/intent: feature

#17686 CXP-1247: add AttributeBooleanCriterion
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeBooleanCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeBooleanCriterionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
Labels: echoes/intent: feature

#17819 PIM-10615: Pull up 5.0 => 6.0
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
  upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
  upgrades/test_schema/Version_5_0_20220830143500_fix_volume_flow_conversion_integration.php
Labels: contribution, echoes/intent: maintenance

#17815 PIM-10610: backport PIM-10504
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/JobLauncherInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SynchronousJobLauncher.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php
Labels: contribution, echoes/effort: S, echoes/intent: maintenance

#17831 OCT-120: fix migration
  upgrades/schema/Version_7_0_20220830000000_add_catalog_product_values_filters.php
  upgrades/test_schema/Version_7_0_20220830000000_add_catalog_product_values_filters_Integration.php
Labels: echoes/intent: maintenance

#17811 RAB-995: Refactor BatchCommand to accept and send email to several recipients
  src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/NotificationSubscriber.php
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/Notifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Launcher/QueueJobLauncherSpec.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Launcher/QueueJobLauncherIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
  tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
Labels: echoes/intent: feature

#17830 RAB-1011: Add fake mailer service
  config/services/test_fake/services.yml
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php
  src/Akeneo/Tool/Component/BatchQueue/Exception/InvalidJobException.php
  tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php
  tests/back/Platform/Acceptance/NotificationBundle/Resources/config/services.yml
Labels: echoes/intent: feature

#17838 RAB-1008: Add Job ServiceApi
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/File.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/FindJobInstances.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstance.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQuery.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQueryPagination.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceCommand.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceHandlerInterface.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceResult.php
Labels: echoes/effort: S, echoes/intent: feature

#17835 PIM-10617: pull up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Platform/CommunityVersion.php
  upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
  upgrades/test_schema/Version_5_0_20220830143500_fix_volume_flow_conversion_integration.php
Labels: contribution, echoes/intent: maintenance

#17832 RAB-1019: Rework email template and send one for all recipients
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
  src/Akeneo/UserManagement/Bundle/Notification/MailResetNotifier.php
  tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php
  tests/back/UserManagement/Specification/Bundle/Notification/MailResetNotifierSpec.php
Labels: echoes/effort: XS, echoes/intent: feature

#17847 CPM-716: Fix UpsertProductCommand validation on permissions
  src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Cache/LRUCacheGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetProductUuidsSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/GetProductUuidsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
Labels: echoes/intent: feature

#17848 RAB-1045: Migrate user_to_notify from a string to an array (code)
  src/Akeneo/Pim/Enrichment/Bundle/MassEditAction/OperationJobLauncher.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductAndProductModelMassDelete.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/SimpleMassEdit.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlImportSpec.php
  src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
  tests/back/Pim/Enrichment/Specification/Bundle/MassEditAction/OperationJobLauncherSpec.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GenerateZipArchiveEndToEnd.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Specification/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserRoleIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
Labels: echoes/intent: feature

#17766 CPM-645: New API endpoint: "PatchProductsByUUID"
  config/packages/akeneo_api.yml
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/PartialUpdateListProductsByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/stream.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
Labels: contribution, echoes/intent: feature

#17859 CPM-715: Update controllers for associations and quantified associations
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/UpdateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetUuidMappingQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetAncestorProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedLink.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/UuidMapping.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php
Labels: echoes/intent: feature

#17856 GRF-318 : Add applier services
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/appliers.yml
Labels: griffins

#17870 PIM-10620: Fix export product options values with label to be case insensitive with codes
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
Labels: contribution, echoes/effort: S, echoes/intent: maintenance

#17861 RAB-1038: Fix exception when we try to override a file with a move
  src/Akeneo/Platform/Bundle/ImportExportBundle/Domain/StorageClientInterface.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/FileSystemStorageClient.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFile.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFileSpec.php
Labels: echoes/intent: feature

#17858 RAB-932: User notifications (fail / success) after a job is launched
  src/Akeneo/Pim/Enrichment/Bundle/MassEditAction/OperationJobLauncher.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductAndProductModelMassDelete.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/SimpleMassEdit.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php
  src/Akeneo/Platform/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlImportSpec.php
  src/Akeneo/UserManagement/Bundle/Notification/MailResetNotifier.php
  src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
  tests/back/Pim/Enrichment/Specification/Bundle/MassEditAction/OperationJobLauncherSpec.php
  tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GenerateZipArchiveEndToEnd.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Specification/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserRoleIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
  tests/back/UserManagement/Specification/Bundle/Notification/MailResetNotifierSpec.php
  upgrades/schema/Version_7_0_20220905141238_update_job_instance_parameter_user_to_notify.php
  upgrades/test_schema/Version_7_0_20220905141238_update_job_instance_parameter_user_to_notify_Integration.php
Labels: echoes/intent: feature

#17871 CXP-1251: AttributeDateCriterion
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeDateCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeDateCriterionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueMultiInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueSingleInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/DateInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
Labels: echoes/intent: feature

#17822 OCT-117: Automatically launch database tests only when a migration is added
  .circleci/config.yml
  .circleci/config/parameters.yml
  .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
  .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
Labels: echoes/intent: technical

#17790 OCT-63: Accelerate integration tests with transactions⚡
  .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
  .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
  .circleci/jobs/features/connectivity.yml
  components/catalogs/Makefile
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetFamiliesActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  config/services/behat/services.yml
  config/services/test/test_services.yml
  docker-compose.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/GenerateAsymmetricKeysHandlerIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetAsymmetricKeysQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/SaveAsymmetricKeysQueryIntegration.php
  tests/back/Integration/IntegrationTestsBundle/Helper/ExperimentalTransactionHelper.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Integration/TestCase.php
Labels: echoes/intent: technical

#17837 OCT-101: Trigger the connect app wizard externally
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/AuthorizeAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/controllers.yml
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlActionSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/AuthorizeActionSpec.php
Labels: echoes/intent: maintenance

#17823 CXP-1254: Filter product values by channel
  components/catalogs/back/src/Application/Persistence/GetCatalogProductValueFiltersQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetChannelsByCodeQueryInterface.php
  components/catalogs/back/src/Application/Persistence/UpdateCatalogProductValueFiltersQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogAction.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetChannelsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/UpdateCatalogAction.php
  components/catalogs/back/src/Infrastructure/Persistence/GetCatalogProductValueFiltersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetChannelsByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/UpdateCatalogProductValueFiltersQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsValidChannel.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsValidChannelValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/UpdateCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCatalogProductValueFiltersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetChannelsByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/UpdateCatalogProductValueFiltersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelsActionTest.php
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx
  components/catalogs/front/src/components/CatalogEdit/components/Edit.tsx
  components/catalogs/front/src/components/CatalogEdit/components/TabBar.tsx
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalog.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
  components/catalogs/front/src/components/CatalogEdit/models/CatalogFormValues.d.ts
  components/catalogs/front/src/components/CatalogEdit/reducers/CatalogFormReducer.ts
  components/catalogs/front/src/components/CatalogEdit/reducers/CatalogFormReducer.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.unit.ts
  components/catalogs/front/src/components/ProductSelection/components/ScopeInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeSimpleSelectCriterion/AttributeSimpleSelectValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessScopeInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilySelectInput.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useChannel.ts
  components/catalogs/front/src/components/ProductValueFilters/ProductValueFilters.tsx
  components/catalogs/front/src/components/ProductValueFilters/components/FilterChannel.integration.tsx
  components/catalogs/front/src/components/ProductValueFilters/components/FilterChannel.tsx
  components/catalogs/front/src/components/ProductValueFilters/index.ts
  components/catalogs/front/src/components/ProductValueFilters/models/ProductValueFiltersErrors.d.ts
  components/catalogs/front/src/components/ProductValueFilters/models/ProductValueFiltersValues.d.ts
  components/catalogs/front/src/hooks/useCatalogQuery.ts
  components/catalogs/front/src/hooks/useChannelsByCodes.ts
  components/catalogs/front/src/hooks/useChannelsByCodes.unit.ts
  components/catalogs/front/src/hooks/useInfiniteChannels.ts
  components/catalogs/front/src/hooks/useInfiniteChannels.unit.ts
  components/catalogs/front/src/hooks/useUniqueEntitiesByCode.ts
  components/catalogs/front/src/hooks/useUniqueEntitiesByCode.unit.ts
  components/catalogs/front/src/models/Channel.d.ts
Labels: echoes/intent: feature

#17875 CXP-1256: Be abe to filter product value by currencies
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Persistence/GetCurrenciesQueryInterface.php
  components/catalogs/back/src/Application/Persistence/IsCurrencyActivatedQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCurrenciesAction.php
  components/catalogs/back/src/Infrastructure/Persistence/GetCurrenciesQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/IsCurrencyActivatedQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedCurrency.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedCurrencyValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCurrenciesActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCurrenciesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/IsCurrencyActivatedQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/front/src/components/CatalogEdit/reducers/CatalogFormReducer.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.ts
  components/catalogs/front/src/components/ProductValueFilters/ProductValueFilters.tsx
  components/catalogs/front/src/components/ProductValueFilters/components/FilterCurrencies.integration.tsx
  components/catalogs/front/src/components/ProductValueFilters/components/FilterCurrencies.tsx
  components/catalogs/front/src/components/ProductValueFilters/hooks/useCurrencies.ts
  components/catalogs/front/src/components/ProductValueFilters/hooks/useCurrencies.unit.ts
  components/catalogs/front/src/components/ProductValueFilters/models/ProductValueFiltersValues.d.ts
Labels: echoes/intent: feature

#17899 CXP-1254: format removed channel in the filter
  components/catalogs/front/src/hooks/useChannelsByCodes.ts
  components/catalogs/front/src/hooks/useChannelsByCodes.unit.ts
Labels: echoes/intent: feature

#17887 CPM-522: Fix coupling detector
  components/catalogs/Makefile
  components/catalogs/back/.php_cd.php
  composer.json
  composer.lock
  make-file/category.mk
  make-file/channel.mk
  make-file/communication-channel.mk
  make-file/connectivity-connection.mk
  make-file/data-quality-insights.mk
  make-file/enrichment-product.mk
  make-file/enrichment.mk
  make-file/import-export.mk
  make-file/job.mk
  make-file/structure.mk
  make-file/test.mk
  make-file/user-management.mk
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php
  src/Akeneo/Platform/Job/back/tests/.php_cd.php
  src/Akeneo/UserManagement/.php_cd.php
  upgrades/.php_cd.php
Labels: echoes/intent: technical

#17793 PH-195: JobMessageHandler for scheduled jobs
  src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/SqlCreateJobInstance.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/README.md
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/PurgeVersioningWatchdogIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/MessageHandler/JobMessageHandlerIntegration.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/steps.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Job/PurgeVersioning.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/jobs.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Normalizer/JobExecutionMessageNormalizer.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/ScheduledJobMessage.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/ScheduledJobMessageInterface.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Normalizer/JobExecutionMessageNormalizerSpec.php
  src/Akeneo/Tool/Component/Connector/Step/CheckJobUniqueStep.php
Labels: ucs

#17869 RAB-1035: Add a filter on process tracker
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
  src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobExecutionAction.php
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/AutomationFilter.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/AutomationFilter.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionSearchBar.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/index.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobInstanceDetail.tsx
Labels: contribution, echoes/intent: feature

#17901 PIM-10624: Fix very slow query when counting variants for mass delete
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/CountVariantProducts.php
Labels: echoes/intent: maintenance

#17906 OCT-124: updates phpcs rules
  components/catalogs/back/.php_cs.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelsActionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.integration.tsx
Labels: echoes/intent: technical

#17913 CPM-522: Fix after rebase master
  upgrades/.php_cd.php
Labels: echoes/intent: technical

#17908 CPM-637: Handle drafts in PATCH endpoint
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/UpdateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FindProduct.php
Labels: echoes/intent: feature

#17836 RAB-997: Remove running user on delete scheduled job
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/UserManagement/DeleteRunningUser.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Remover/JobInstanceRemover.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Remover/JobInstanceRemoverSpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/UserManagement/DeleteRunningUserSpec.php
Labels: echoes/intent: feature

#17867 CPM-633: Enable identifier configuration for family attribute requirements
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Family/DefaultSqlGetRequiredAttributesMasks.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/FamilyNormalizer.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family/tab/attributes/attributes.html
  tests/back/Pim/Structure/EndToEnd/Family/ExternalApi/PartialUpdateFamilyEndToEnd.php
  tests/back/Pim/Structure/Integration/Family/ImportFamilyIntegration.php
  tests/back/Pim/Structure/Integration/Query/InternalApi/Family/DefaultSqlGetRequiredAttributesMasksIntegration.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/FamilyRequirementsValidatorSpec.php
Labels: echoes/intent: feature

#17756 OCT-110 Error management on the family criterion
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/FamilyCriterionContainsValidFamilies.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/FamilyCriterionContainsValidFamiliesValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/CompletenessCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/EnabledCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/FamilyCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/AbstractSystemCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/CategoriesCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/CompletenessCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/EnabledCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/FamilyCriterionTest.php
Labels: echoes/intent: maintenance

#17889 OCT-119: Events with UUID
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/UpdateWebhookCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/UpdateWebhookHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookEventBuilder.php
  src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Read/ActiveWebhook.php
  src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Read/ConnectionWebhook.php
  src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Read/EventSubscriptionFormData.php
  src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Write/ConnectionWebhook.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Connections/Install/CreateConnectionTableQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Controller/Internal/UpdateWebhookAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Persistence/DbalGetAConnectionWebhookQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Persistence/DbalSelectActiveWebhooksQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Persistence/UpdateConnectionWebhookQuery.php
  src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/WebhookLoader.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/Controller/Internal/GetEventSubscriptionFormDataEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/Controller/Internal/UpdateEventSubscriptionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/Persistence/DbalGetAConnectionWebhookQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/Persistence/DbalSelectActiveWebhooksQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/Persistence/UpdateConnectionWebhookQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/UpdateWebhookCommandSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/UpdateWebhookHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Log/EventSubscriptionSendApiEventRequestLogSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/Logger/SendApiEventRequestLoggerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/EventSubscriptionsLimitValidatorSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/WebhookEventBuilderSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Client/WebhookRequestSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Read/ActiveWebhookSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Read/ConnectionWebhookSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Read/EventSubscriptionFormDataSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Write/ConnectionWebhookSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
  src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-event-subscription.ts
  src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-update-webhook.tsx
  src/Akeneo/Connectivity/Connection/front/src/webhook/model/Webhook.ts
  src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php
  src/Akeneo/Platform/Component/Webhook/Context.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
  tests/back/Platform/Specification/Component/Webhook/ContextSpec.php
  upgrades/schema/Version_7_0_20220907143028_add_connection_webhook_is_using_uuid_flag.php
  upgrades/test_schema/Version_7_0_20220907143028_add_connection_webhook_is_using_uuid_flag_Integration.php
Labels: echoes/intent: technical

#17910 PIM-10566: migration script for updating resource_name with correct namespace of categories
  CHANGELOG.md
  upgrades/schema/Version_7_0_20220912132436_update_namespace_in_resource_name_for_category_history.php
  upgrades/test_schema/Version_7_0_20220912132436_update_namespace_in_resource_name_for_category_history_Integration.php
Labels: griffins, echoes/intent: maintenance

#17924 Quickfix job validation following flaky migration
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php
Labels: echoes/intent: maintenance

#17850 RAB-943: Handle invalid job notifications before a job is launched
  tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeNotifier.php
  tests/back/Platform/Acceptance/NotificationBundle/Resources/config/services.yml
Labels: contribution, echoes/intent: feature

#17907 RAB-720: Replace "processed" by "updated" in PT for some jobs
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductModelDescendantsWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductWriter.php
  src/Akeneo/Pim/Structure/Component/Writer/Database/AttributeGroupWriter.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Tool/Component/Connector/Writer/Database/JobInstanceWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/Database/Writer.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/Database/JobInstanceWriterSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/Database/WriterSpec.php
  src/Akeneo/UserManagement/Component/Connector/Writer/Database/RoleWithPermissionsWriter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/ProductModelDescendantsWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/ProductWriterSpec.php
  tests/back/Pim/Structure/Specification/Component/Writer/Database/AttributeGroupWriterSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Writer/Database/RoleWithPermissionsWriterSpec.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_media.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature
  tests/legacy/features/pim/structure/attribute/import/import_attributes.feature
  tests/legacy/features/pim/structure/family/family-variant/import/xlsx/update_family_variant.feature
  tests/legacy/features/pim/structure/product-group/import_groups.feature
  tests/legacy/features/pim/structure/product-group/import_groups_xlsx.feature
Labels: echoes/intent: feature

#17868 GRF-109 fetch template and display attributes in Category edit form
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextAreaFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/index.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplate.ts
  src/Akeneo/Category/front/src/feature/models/Attribute.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
  src/Akeneo/Category/front/src/feature/models/Template.ts
  src/Akeneo/Category/front/src/feature/models/TemplateMocking.ts
  src/Akeneo/Category/front/src/feature/models/index.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: feature

#17935 GRF-328 fix DX issue within category microfrontend in dev mode
  src/Akeneo/Category/front/src/FakePIM.tsx
  src/Akeneo/Category/front/src/index.tsx
Labels: contribution, griffins, echoes/intent: technical

#17905 PH-195: Symfony Messenger configuration for scheduled jobs
  .env
  .env.behat
  .env.test
  .env.test_fake
  config/packages/behat/messenger.yml
  config/packages/dev/messenger.yml
  config/packages/prod/messenger.yml
  config/packages/test/messenger.yml
  config/services/behat/services.yml
  config/services/test/test_services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Launcher/QueueJobLauncherIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
Labels: ucs

#17878 CPM-632: Implement empty/not empty filter on attribute and use it on product list REST API
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductsQueryHandlerSpec.php
Labels: echoes/intent: feature

#17915 OCT-125: Add acceptance test for /products, /product-identifiers and /product-uuids catalog endpoints
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Acceptance/AuthenticationContext.php
  components/catalogs/features/api.feature
Labels: echoes/intent: technical

#17763 PIM-10568: Error when running Version_7_0_20220629142647_dqi_update_pk_on_product_score during On-Premise/Flex to Serenity migration
  CHANGELOG.md
  upgrades/schema/Version_7_0_20220629142647_dqi_update_pk_on_product_score.php
Labels: griffins, echoes/intent: maintenance

#17925 RAB: migrate user_to_notify for quick_export jobs
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php
  src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php
  upgrades/schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export.php
  upgrades/test_schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export_Integration.php
Labels: echoes/intent: feature

#17923 RAB-1031: Use DSM into quantified associations
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
Labels: echoes/intent: feature

#17863 GRF-233 : Add value collection in query sql to save a base category
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/base.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Storage/Save/CategorySaverRegistrySpec.php
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
Labels: griffins

#17933 PIM-10635: update dompdf/dompdf package
  .circleci/jobs/features/other.yml
  composer.json
  composer.lock
Labels: echoes/intent: maintenance

#17873 GRF-308: Display text & textarea attribute values
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeImage.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeRichText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeTextArea.php
  src/Akeneo/Category/back/Domain/Model/Template.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/TemplateSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/models/Attribute.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
Labels: griffins, echoes/intent: feature

#17926 CPM-721: Add line break support for attribute guidelines
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/field-guidelines.html
Labels: echoes/intent: maintenance

#17896 GRF-313: Display image attribute
  config/packages/liip_imagine.yml
  src/Akeneo/Category/back/Api/Command/UserIntents/SetImage.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueImageUserIntent.php
  src/Akeneo/Category/back/Application/Converter/Checker/AttributeRequirementChecker.php
  src/Akeneo/Category/back/Application/Handler/StoreUploadedFile.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/ImagePreviewController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UploadController.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/Loader/ImageLoader.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/AbstractPreviewGenerator.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/BinaryImageGenerator.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/CouldNotGeneratePreviewException.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/DefaultImageProvider.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/DefaultImageProviderInterface.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/PreviewGeneratorInterface.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/PreviewGeneratorRegistry.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/AkeneoCategoryBundle.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/CompilerPass/RegisterPreviewGeneratorPass.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/files.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/parameters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/preview_generators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/enriched_category.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/FileSystem/PreviewGenerator/BinaryImageGeneratorIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
  src/Akeneo/Category/front/src/feature/components/file/preview/fullscreen-preview.tsx
  src/Akeneo/Category/front/src/feature/components/file/preview/media-preview.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
  src/Akeneo/Category/front/src/feature/models/File.ts
  src/Akeneo/Category/front/src/feature/models/MediaPreview.ts
  src/Akeneo/Category/front/src/feature/models/index.ts
  src/Akeneo/Category/front/src/feature/tools/media-url-generator.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Labels: griffins, echoes/intent: feature

#17953 CXP-1283: New bucket for catalogs mapping
  components/catalogs/Makefile
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Infrastructure/Exception/FilesystemException.php
  components/catalogs/back/src/Infrastructure/Storage/CatalogsMappingStorage.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Integration/Infrastructure/Storage/CatalogsMappingStorageTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  config/packages/behat/oneup_flysystem.yml
  config/packages/dev/oneup_flysystem.yml
  config/packages/oneup_flysystem.yml
  config/packages/prod/oneup_flysystem.yml
  config/packages/test/oneup_flysystem.yml
  config/packages/test_fake/oneup_flysystem.yml
  docker-compose.yml
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
Labels: echoes/intent: feature

#17931 GRF-311 category edition form : locales are taken from back (and depe…
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
Labels: contribution, echoes/intent: feature

#17950 PH-268: Create `job_executions_purge` scheduled job
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Job/JobParameters/PurgeJobExecutions.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Job/PurgeJobExecutions.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/jobs.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20220919145300_add_scheduled_jobs.php
  upgrades/test_schema/Version_7_0_20220919145300_add_scheduled_jobs_Integration.php
Labels: ucs

#17841 RAB-1039: Fix user normalizer sending visible groups ids as object
  src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
Labels: echoes/effort: XS, echoes/intent: feature

#17980 DPE: Remove auto pullup
  .circleci/workflows/editions/community.yml
Labels: tech-improvement

#17979 PIM-10648: Migrate all job conf which contains old user_to_notify param
  CHANGELOG.md
  upgrades/schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs.php
  upgrades/test_schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs_Integration.php
Labels: echoes/intent: maintenance

#17972 PIM-10646: Fix export with label from a select attribute containing uppercase in its code exports code and not labels
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
Labels: echoes/intent: maintenance

#17981 PIM-10622: Fix save options labels when using the automatic correction in Firefox
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
Labels: bug, griffins, echoes/intent: maintenance

#17971 OCT-128: deduplicate ES indices
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
  upgrades/schema/Version_7_0_20220920000000_deduplicate_elasticsearch_indices.php
  upgrades/test_schema/Version_7_0_20220920000000_deduplicate_elasticsearch_indices_Integration.php
Labels: echoes/intent: maintenance

#17987 CXP-1299: fix experimental transaction in job test
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/UpdateCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnAttributeOptionRemovalTaskletTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/DisableCatalogsQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Helper/ExperimentalTransactionHelper.php
Labels: echoes/intent: feature

#17956 CPM-733: Add front models
  components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
  components/identifier-generator/front/src/feature/__tests__/IdentifierGeneratorApp.test.tsx
  components/identifier-generator/front/src/index.tsx
  components/identifier-generator/front/src/models/conditions.ts
  components/identifier-generator/front/src/models/delimiter.ts
  components/identifier-generator/front/src/models/identifierGenerator.ts
  components/identifier-generator/front/src/models/identifierGeneratorCode.ts
  components/identifier-generator/front/src/models/index.ts
  components/identifier-generator/front/src/models/labelCollection.ts
  components/identifier-generator/front/src/models/properties/autoNumber.ts
  components/identifier-generator/front/src/models/properties/freeText.ts
  components/identifier-generator/front/src/models/properties/index.ts
  components/identifier-generator/front/src/models/structure.ts
  components/identifier-generator/front/src/models/target.ts
  components/identifier-generator/front/src/validators/Validator.ts
  components/identifier-generator/front/src/validators/Violation.ts
  components/identifier-generator/front/src/validators/__tests__/validateConditions.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateDelimiter.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateIdentifierGenerator.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateIdentifierGeneratorCode.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateLabelCollection.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateStructure.test.ts
  components/identifier-generator/front/src/validators/__tests__/validateTarget.test.ts
  components/identifier-generator/front/src/validators/validateConditions.ts
  components/identifier-generator/front/src/validators/validateDelimiter.ts
  components/identifier-generator/front/src/validators/validateIdentifierGenerator.ts
  components/identifier-generator/front/src/validators/validateIdentifierGeneratorCode.ts
  components/identifier-generator/front/src/validators/validateLabelCollection.ts
  components/identifier-generator/front/src/validators/validateStructure.ts
  components/identifier-generator/front/src/validators/validateTarget.ts
  make-file/identifier-generator.mk
  package.json
Labels: echoes/intent: feature

#17992 OCT-130: fix phpcd from OCT-128
  .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
  make-file/test.mk
  upgrades/.php_cd.php
Labels: echoes/intent: maintenance

#17970 PIM-10647: pull-up 6.0 to master
  CHANGELOG-6.0.md
  composer.json
  composer.lock
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.ru_RU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/field-guidelines.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.ru_RU.yml
  upgrades/schema/Version_7_0_20220429132029_remove_temporary_indexes_from_uuid_migration.php
Labels: echoes/intent: maintenance

#17955 CPM-726: Create Domain Objects
  components/identifier-generator/back/.php_cs.php
  components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Delimiter.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorCode.php
  components/identifier-generator/back/src/Domain/Model/LabelCollection.php
  components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Domain/Model/Target.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/DelimiterSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorCodeSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/AutoNumberSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FreeTextSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/TargetSpec.php
  make-file/identifier-generator.mk
  phpspec.yml.dist
Labels: echoes/intent: feature

#17962 PIM-10634: Fix media filter values normalizer to be case insensitive
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/MediaFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateMappingIndexCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMapping.php
  tests/back/Integration/fixtures/Akeneo Logo.jpg
  tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php
Labels: echoes/intent: maintenance

#17973 OCT-85: Update Catalogs internal documentation
  components/catalogs/README.md
  components/catalogs/docs/development-setup.md
  components/catalogs/docs/tests.md
  components/catalogs/docs/trophy.jpg
Labels: echoes/intent: technical

#17961 CPM-632: Adapt enrichment cursors to work without identifier
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/AbstractCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/CursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResult.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResults.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cursors.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveNonExistingProductValuesTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Storage/GetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetIdentifierValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/Value/IdentifierValueUserIntentFactory.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Elasticsearch/ProductQueryBuilderAdapter.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/Elasticsearch/ProductQueryBuilderAdapterSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/CursorFactory.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/FromSizeCursorFactory.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/SearchAfterSizeCursorFactory.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/ORM/Cursor/CursorFactory.php
  src/Akeneo/Tool/Component/StorageUtils/Cursor/CursorFactoryInterface.php
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScopeIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchQueryBuilderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/ProductReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveNonExistingProductValuesTaskletSpec.php
Labels: echoes/intent: feature

#17976 GRF-345 : re design category internal endpoint (attribute_codes key for values)
  src/Akeneo/Category/back/Application/Converter/Checker/AttributeApiRequirementChecker.php
  src/Akeneo/Category/back/Application/Converter/Checker/InternalApiRequirementChecker.php
  src/Akeneo/Category/back/Application/Converter/Checker/ValueCollectionRequirementChecker.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/converters.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/InternalApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/ValueCollectionRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/ValueCollectionSpec.php
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
Labels: griffins, echoes/intent: feature

#17942 GRF-349 fix DSM InputTextArea : richtext : selected dropdown items in…
  front-packages/akeneo-design-system/src/components/Input/TextAreaInput/TextAreaInput.tsx
Labels: contribution, echoes/intent: feature

#17265 Fix Gherkin parser deprecation warnings
  tests/legacy/features/channel/edit_channel.feature
  tests/legacy/features/pim/enrichment/product-group/remove_products_from_a_group.feature
  tests/legacy/features/pim/enrichment/product-model/create_product_model.feature
  tests/legacy/features/pim/enrichment/product-model/edit_product_model.feature
  tests/legacy/features/pim/enrichment/product/create_product_and_save_added_attributes.feature
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_product_per_boolean.feature
  tests/legacy/features/pim/enrichment/product/import/import_products.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_invalid_data.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_invalid_headers.feature
  tests/legacy/features/pim/enrichment/product/import/import_products_with_product_model_associations.feature
  tests/legacy/features/pim/enrichment/product/import/upload_and_import_products_with_media.feature
  tests/legacy/features/pim/enrichment/product/import/validate_unicity_when_importing_products.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_dates.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_numbers.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_scopable_localizable.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_edit_and_update_attribute_history.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_locale_specific_value.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_product.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_date_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_file_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_image_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_textarea_attributes.feature
  tests/legacy/features/pim/enrichment/product/validation/validate_unique_attribute.feature
  tests/legacy/features/pim/enrichment/product/versioning/display_history.feature
  tests/legacy/features/pim/enrichment/product/versioning/display_removed_value_history.feature
  tests/legacy/features/pim/structure/attribute/delete_attribute.feature
  tests/legacy/features/pim/structure/attribute/import/import_attributes.feature
  tests/legacy/features/pim/structure/family/add_attributes_to_a_family.feature
  tests/legacy/features/pim/structure/family/add_attributes_to_family_by_group.feature
  tests/legacy/features/platform/acl/api.feature
  tests/legacy/features/platform/security/security.feature
  tests/legacy/features/user-management/role/edit_user_role_assignations.feature
  tests/legacy/features/user-management/user/edit_my_account.feature
  tests/legacy/features/user-management/user/edit_user.feature
Labels: echoes/effort: S, echoes/intent: maintenance

#17912 OCT-121: catch cold boot of the kernel
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: maintenance

#18009 CPM-632: Update product group grid to handle products without identifier
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/GroupController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command_handlers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product_group.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/FindProductIdentifiers.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductUuidsInGroup.php
  src/Akeneo/Pim/Enrichment/Component/Product/Command/GroupProductsCommand.php
  src/Akeneo/Pim/Enrichment/Component/Product/Command/GroupProductsHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FindProductIdentifiersInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FindProductUuidsInGroup.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/group/form/products.js
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Group/FindProductIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Group/FindProductUuidsInGroupIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/GroupSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Command/GroupProductsHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
  tests/legacy/features/Context/FixturesContext.php
Labels: echoes/intent: feature

#17999 PIM-10649: Fix wrong attributes displayed when selecting attribute group in export profile filter when there is too much attribute selected
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js
Labels: echoes/intent: maintenance

#17994 RAB-1012: Add LastOperationsWidget in Job BC
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetLastOperations.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetLastOperationsInterface.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/queries.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/widget.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Widget/LastOperationsFetcher.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Widget/LastOperationsWidget.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/operation.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardLastOperations.ts
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Job/front/process-tracker/src/FakePIM.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.test.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/index.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/LastOperationsWidget.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/LastOperationsWidget.tsx
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetLastOperationsIntegration.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Query/GetLastOperationsSpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Widget/LastOperationsFetcherSpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Widget/LastOperationsWidgetSpec.php
  tests/legacy/features/platform/dashboard/display_last_operations_widget.feature
Labels: echoes/intent: technical

#18006 OCT-115: Use Measurement ServiceAPI
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Infrastructure/Persistence/Measurement/GetMeasurementsFamilyQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogProductValueFiltersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/UpdateCatalogProductValueFiltersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Channel/GetChannelsByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/GetCurrenciesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/IsCurrencyActivatedQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Locale/GetLocalesByCodeQueryTest.php
Labels: echoes/intent: technical

#18015 OCT-116: reorganize coupling in Infrastructure to have a better view
  components/catalogs/back/.php_cd.php
Labels: echoes/intent: technical

#18002 GRF-342 category attributes handle issue in front related to the "unsaved changes" warning
  src/Akeneo/Category/back/Application/Converter/Checker/AttributeApiRequirementChecker.php
  src/Akeneo/Category/back/Application/Converter/Checker/ValueCollectionRequirementChecker.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/ValueCollectionRequirementCheckerSpec.php
  src/Akeneo/Category/front/src/FakePIM.tsx
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/file/preview/media-preview.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplate.ts
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: contribution, griffins

#18018 RAB-1046: Remove fallback to user_to_notify
  src/Akeneo/Platform/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php
  tests/back/Platform/Specification/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php
Labels: echoes/intent: feature

#18012 CPM-738 + CPM-711: Unhide route and change links
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/UpdateProductByUuidController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantWithUuidEndToEnd.php
Labels: echoes/intent: feature

#17916 OCT-118: the Product selection UI consistency pass
  components/catalogs/front/src/components/ProductSelection/components/CriterionFields.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueMultiInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeSimpleSelectCriterion/AttributeSimpleSelectCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextCriterion/AttributeTextCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilyCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/StatusCriterion.tsx
Labels: echoes/intent: feature

#17975 RAB-1068: Update legacy mail when job failed
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
Labels: echoes/intent: feature

#17977 OCT-126: Broken link to the marketplace in the PIM app store
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/Controller/Internal/GetWebMarketplaceUrlEndToEnd.php
Labels: echoes/intent: maintenance

#18005 RAB-1016: Use CreateJobExecutionHandler in PublishJobToQueue
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Component/Batch/Exception/InvalidJobException.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
Labels: echoes/intent: feature

#18001 PIM-10576: Fix product model mass edit acl check
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Job/DeleteProductsAndProductModelsTasklet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/DeleteProductsAndProductModelsTaskletSpec.php
Labels: echoes/intent: maintenance

#18014 GRF-351 leaving category edition page with unsaved change : modified …
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: contribution, griffins

#17982 CXP-1300: Adds first product meta schema
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.1.json
  components/catalogs/back/src/Infrastructure/Validation/ProductSchema.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchemaValidatorTest.php
  composer.json
  composer.lock
  src/Akeneo/Channel/back/Infrastructure/Component/Repository/CurrencyRepositoryInterface.php
Labels: echoes/intent: feature

#17986 CXP-1288: Added mapping tab to catalog
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/FakeCatalogEditContainer.tsx
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.tsx
  components/catalogs/front/src/components/CatalogEdit/components/Edit.tsx
  components/catalogs/front/src/components/CatalogEdit/components/TabBar.tsx
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.unit.ts
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePlaceholder.tsx
  components/catalogs/front/src/components/ProductMapping/index.ts
  components/catalogs/front/src/hooks/useProductMappingSchema.ts
  components/catalogs/front/src/hooks/useProductMappingSchema.unit.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
Labels: echoes/intent: feature

#17985 CPM-728: Create IdentifierGenerator InMemory Repository
  components/identifier-generator/back/src/Application/CreateGeneratorCommand.php
  components/identifier-generator/back/src/Application/CreateGeneratorHandler.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/.php_cs.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/contexts.yml
  components/identifier-generator/back/tests/Specification/Application/CreateGeneratorHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
  components/identifier-generator/back/tests/behat.yml
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  composer.json
  config/services/test_fake/services.yml
  make-file/identifier-generator.mk
  make-file/test.mk
Labels: echoes/intent: feature

#17990 RAB-1073: refacto publish job command
  src/Akeneo/Platform/Bundle/ImportExportBundle/Domain/ResolveScheduledJobRunningUsername.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueueInterface.php
Labels: contribution, echoes/intent: feature

#18026 RAB-833: Job ServiceAPI
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SqlFindJobInstance.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/FindJobInstanceInterface.php
  src/Akeneo/Platform/Job/back/tests/.php_cd.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SqlFindJobInstanceTest.php
Labels: echoes/effort: S, echoes/intent: feature

#18025 Pull up 5.0 to 6.0
  CHANGELOG-5.0.md
  src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.pt_BR.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/JobLauncherInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
  src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SynchronousJobLauncher.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.sv_SE.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pt_BR.yml
Labels: echoes/intent: maintenance

#18039 Fix error during migration test does not display revelant message
  upgrades/test_schema/ExecuteMigrationTrait.php
Labels: echoes/effort: XS, echoes/intent: technical

#18033 OCT-141: Access PIM translator in microfrontends
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeOptions.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeOptions.unit.ts
  components/catalogs/front/src/index.tsx
  front-packages/shared/legacy/translate.js
  front-packages/shared/legacy/translator.js
  front-packages/shared/legacy/user-context.js
  front-packages/shared/src/dependencies/index.ts
  front-packages/shared/src/dependencies/init-translator.ts
  front-packages/shared/src/dependencies/init-translator.unit.ts
  front-packages/shared/src/dependencies/translate.ts
  front-packages/shared/src/dependencies/user-context.ts
  front-packages/shared/src/index.ts
  front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/init-translator.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/translator.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/user-context.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js
Labels: echoes/intent: technical

#18024 GRF-348 fix ghost warning about unsaved change when going back to cat…
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
Labels: contribution, griffins
