Repository akeneo/pim-community-dev, pull requests merged in 2022-12, with the labels that each got.

#18517 CXP 1291: Select scope and locale
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectChannelDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectChannelLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/models/SourceErrors.d.ts
  components/catalogs/front/src/components/ProductSelection/components/ScopableLocaleInput.tsx
  components/catalogs/front/src/components/ProductSelection/components/ScopeInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessLocaleInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessScopeInput.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useLocales.ts
  components/catalogs/front/src/components/ProductValueFilters/components/FilterLocale.tsx
  components/catalogs/front/src/components/ProductValueFilters/models/Locale.d.ts
  components/catalogs/front/src/hooks/useChannel.ts
  components/catalogs/front/src/hooks/useChannel.unit.ts
  components/catalogs/front/src/hooks/useChannelLocales.ts
  components/catalogs/front/src/hooks/useChannelLocales.unit.ts
  components/catalogs/front/src/hooks/useInfiniteLocales.ts
  components/catalogs/front/src/hooks/useInfiniteLocales.unit.ts
  components/catalogs/front/src/hooks/useLocalesByCodes.ts
  components/catalogs/front/src/hooks/useLocalesByCodes.unit.ts
  components/catalogs/front/src/models/Locale.d.ts
Labels: echoes/intent: feature

#18525 CXP-1354: Display errors messages
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSourceTest.php
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
  components/catalogs/front/src/components/ProductMapping/components/SelectAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectChannelDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectChannelLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductSelection/components/UnknownCriterion.tsx
Labels: echoes/intent: feature

#18553 OCT-177: transform errors into logs
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/commands.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
Labels: echoes/intent: technical

#18537 GRF-448 : Update end to end tests to cover the with enriched values use case
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ApiCategoryTestCase.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
Labels: griffins, echoes/intent: feature

#18541 CXP-1326: Add the open app button in the app header
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
Labels: echoes/intent: feature

#18539 CXP 1349: Apply the limit of 25 of product selection criteria
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/front/src/components/ProductSelection/ProductSelection.integration.tsx
  components/catalogs/front/src/components/ProductSelection/ProductSelection.tsx
  components/catalogs/front/src/components/ProductSelection/components/AddCriterionDropdown.tsx
Labels: echoes/intent: feature

#18562 CXP-1303: Display selection criteria per attribute groups
  components/catalogs/back/src/Application/Persistence/Attribute/FindOneAttributeByCodeQueryInterface.php
  components/catalogs/back/src/Application/Persistence/Attribute/SearchAttributesQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetAttributeAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Attribute/FindOneAttributeByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Attribute/SearchAttributesQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributeActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Attribute/FindOneAttributeByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Attribute/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteAttributes.unit.ts
  components/catalogs/front/src/components/ProductSelection/components/AddCriterionDropdown.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeCriterionFactories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeCriterionFactories.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/usePartitionAttributesByGroup.ts
  components/catalogs/front/src/components/ProductSelection/hooks/usePartitionAttributesByGroup.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/CriterionFactory.d.ts
  components/catalogs/front/src/hooks/useAttribute.unit.ts
  components/catalogs/front/src/models/Attribute.d.ts
Labels: echoes/intent: feature

#18568 CXP-1333: Be able to count the number of products in the selection criteria
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductSelection/ProductSelection.tsx
  components/catalogs/front/src/components/ProductSelection/components/CountSelectedProductsByCriteria.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.unit.ts
Labels: echoes/intent: feature

#18549 PIM-10739 : Data Quality Insights dashboard: get family grades for EE
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
Labels: griffins, echoes/intent: maintenance

#18584 GRF-646 : Add parent code in the returned json
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php
Labels: echoes/intent: feature

#18588 CPM-823: Add translation for identifier generator edit page
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#18569 RAB-1104: Amazon S3 support
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/Compiler/CredentialsEncrypterPass.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/FileSystemStorageClient.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/PimImportExportBundle.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/security.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/index.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  src/Akeneo/Platform/Bundle/PimVersionBundle/PimVersionBundle.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
Labels: echoes/intent: feature

#18554 CXP-1369: DSM - Add a size property to the boolean input
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-boolean-input-small-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.tsx
  front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.unit.tsx
Labels: echoes/intent: feature

#18434 RAB-1149: Enable authenticator manager
  composer.json
  composer.lock
  config/packages/security.yml
  config/packages/test/security.yml
  config/services/test/test_services.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php
  src/Akeneo/Platform/Bundle/UIBundle/Http/FormAuthenticationEntryPoint.php
  src/Akeneo/Platform/Bundle/UIBundle/Http/FormLoginAuthenticator.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/JobExecutionAuthenticator.php
  src/Akeneo/UserManagement/Bundle/EventListener/LoginRateLimitListener.php
  src/Akeneo/UserManagement/Bundle/Provider/CustomDaoAuthenticationProvider.php
  src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Oro/Bundle/PimDataGridBundle/tests/Integration/Controller/ControllerIntegrationTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Helper/AuthenticatorHelper.php
  tests/back/Integration/IntegrationTestsBundle/Security/SystemUserAuthenticator.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/IndexProductModelDescendantsIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php
  tests/back/UserManagement/EndToEnd/LoginRateLimitIntegration.php
  tests/back/UserManagement/Integration/Bundle/ControllerIntegrationTestCase.php
  tests/back/UserManagement/Specification/Bundle/EventListener/LoginRateLimitListenerSpec.php
  tests/back/UserManagement/Specification/Bundle/Provider/CustomDaoAuthenticationProviderSpec.php
  tests/legacy/features/Behat/Context/NavigationContext.php
  tests/legacy/features/Context/SecurityContext.php
Labels: contribution, echoes/effort: XL, echoes/intent: technical

#18587 CXP-1353 : Add the open app button in the catalog header
  front-packages/akeneo-design-system/src/icons/ExternalLinkIcon.tsx
  front-packages/akeneo-design-system/src/icons/index.ts
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/OpenAppButton.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/OpenAppButton.test.tsx
Labels: echoes/intent: feature

#18586 CXP-1333: Be able to display the number of selected products by criteria
  components/catalogs/back/src/Application/Exception/InvalidProductSelectionCriteriaException.php
  components/catalogs/back/src/Application/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php
  components/catalogs/back/src/Infrastructure/Service/FormatProductSelectionCriteria.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Service/FormatProductSelectionCriteriaTest.php
  components/catalogs/front/src/components/ProductSelection/ProductSelection.tsx
  components/catalogs/front/src/components/ProductSelection/components/CountSelectedProductsByCriteria.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.unit.ts
Labels: echoes/intent: feature

#18599 GRF-625 : SEO Meta Description and SEO Keywords must be of type Textarea
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
Labels: griffins, echoes/intent: feature

#18606 Revert "Merge pull request #18483 from akeneo/CPM-791"
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/OpenAppButton.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_identifier_or_uuid-filter.js
  src/Oro/Bundle/PimFilterBundle/Filter/Product/LabelIdentifierOrUuidFilter.php
  src/Oro/Bundle/PimFilterBundle/Resources/config/filters.yml
  src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/LabelIdentifierOrUuidFilterSpec.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelIdentifierOrUuidFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilterSpec.php
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature
Labels: echoes/intent: feature

#18605 OCT-183: add 2 try catch to log TableNotFound and ConnectionLost exceptions
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
Labels: echoes/intent: technical

#18597 RAB-1149: Fix minors depreciations
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/AppRoleWithScopesFactoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/UpdateConnectedAppScopesWithAuthorizationHandlerIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Install/AddAclToRolesIntegration.php
  src/Akeneo/Connectivity/Connection/tests/Context/AppActivateContext.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/UserContext.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/WebTestCase.php
  tests/back/Acceptance/User/UserContext.php
  tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
  tests/back/Platform/EndToEnd/InternalApiTestCase.php
  upgrades/test_schema/Version_6_0_20210908142400_add_product_web_api_acl_Integration.php
Labels: echoes/intent: technical

#18593 GRF-347 : Allow image attribute fields to be also locale (and channel)-specific
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemory.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/FileSystem/PreviewGenerator/BinaryImageGeneratorIntegration.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/TemplateSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
Labels: griffins, echoes/intent: feature

#18266 OCT-166 Use mapped id field for connection_error index
  src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Persistence/PurgeConnectionErrorsQuery.php
Labels: echoes/intent: technical

#18268 OCT-167: Updated queries to use mapped field id instead of ES _id
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/GetAllEventSubscriptionDebugLogsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/PurgeEventsApiSuccessLogsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/SearchEventSubscriptionDebugLogsQuery.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/EventsApiDebug/Controller/Internal/DownloadEventSubscriptionLogsEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/EventsApiDebug/Controller/Internal/SearchEventSubscriptionLogsEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/GetAllEventSubscriptionDebugLogsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/PurgeEventsApiSuccessLogsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/SearchEventSubscriptionDebugLogsQueryIntegration.php
Labels: echoes/intent: technical

#18604 RAB-1124: Remove outdated dependency sensio/framework-extra-bundle
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yml
  config/packages/sensio_framework_extra.yml
  src/Akeneo/Channel/back/Infrastructure/Controller/UI/CurrencyController.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
  src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
  src/Akeneo/UserManagement/Bundle/Controller/RoleController.php
  src/Akeneo/UserManagement/Bundle/Controller/SecurityController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/routing/old_oro_routes.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.ca_ES.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.da_DK.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.de_DE.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_NZ.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.es_ES.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.es_VE.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.ja_JP.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.ko_KR.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.nl_NL.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.no_NO.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pl_PL.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.sv_SE.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.zh_CN.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.zh_TW.yml
  src/Akeneo/UserManagement/Component/Repository/RoleRepositoryInterface.php
  symfony.lock
Labels: echoes/intent: technical

#18617 CPM-871: Forbid attribute creation named "identifier"
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
Labels: echoes/intent: feature, echoes/intent: technical

#18609 CPM-865: Identifier generator feature flag
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/form_extensions.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/requirejs.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/DeleteIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ListIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasFeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
Labels: echoes/intent: feature

#18591 CXP-1325: Display the catalog status button in the catalog header
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/FakeCatalogEditContainer.tsx
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.tsx
  components/catalogs/front/src/components/CatalogEdit/components/CatalogStatusWidget.tsx
  components/catalogs/front/src/components/CatalogEdit/components/Edit.tsx
  components/catalogs/front/src/components/CatalogEdit/components/EnabledInput.integration.tsx
  components/catalogs/front/src/components/CatalogEdit/components/EnabledInput.tsx
  components/catalogs/front/src/components/CatalogEdit/components/Settings.tsx
  components/catalogs/front/src/components/CatalogEdit/components/TabBar.tsx
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.unit.ts
  src/Akeneo/Connectivity/Connection/front/src/common/components/PageHeader.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.test.tsx
Labels: echoes/intent: feature

#18602 CPM-807: Add subscriber to show warnings on import
  components/identifier-generator/back/src/Application/Exception/UnableToSetIdentifierException.php
  components/identifier-generator/back/src/Infrastructure/Event/UnableToSetIdentifierEvent.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/UnableToSetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Integration/Import/ImportProductsIntegration.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/UnableToSetIdentifiersSubscriberSpec.php
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/PropertiesList.test.tsx
  make-file/identifier-generator.mk
  make-file/test.mk
  phpunit.xml.dist
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
  tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
Labels: echoes/intent: feature

#18623 GRF-655: Create make category-ci on EE + phpstan & lint fix
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/phpstan.neon.dist
Labels: griffins

#18608 GRF-498 : only enrich the locales linked to the active channels in a category
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
Labels: griffins, echoes/intent: feature

#18612 RAB-1124: Update guzzlehttp/guzzle
  composer.json
  composer.lock
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/services_test.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleJsonHistoryContainer.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleMockHandlerStackFactory.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/IncrementEventsApiRequestCountEndToEnd.php
Labels: echoes/intent: technical

#18527 RAB-1204: upgrade elastic search image
  docker-compose.yml
Labels: contribution, echoes/intent: technical

#18629 Pim 10762 pullup 6.0 to master
  CHANGELOG-6.0.md
Labels: echoes/intent: maintenance

#18637 OCT-185: Add javascript-dev-strict command to CXP CI
  .circleci/jobs/features/connectivity.yml
  .circleci/workflows/squads/octopus/octopus_connectivity_pull_request.yml
Labels: echoes/intent: technical

#18627 RAB-1124: Update flysystem dependencies
  composer.json
  composer.lock
Labels: echoes/intent: technical

#18636 CPM-852: Add Enabled validation
  components/identifier-generator/back/src/Application/Update/UpdateGeneratorHandler.php
  components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/Enabled.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Validation/ConditionsShouldNotContainMultipleEnabled.php
  components/identifier-generator/back/src/Infrastructure/Validation/ConditionsShouldNotContainMultipleEnabledValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/EnabledShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/EnabledShouldBeValidValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/StructureShouldNotContainMultipleAutoNumberValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EnabledSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/ConditionsShouldNotContainMultipleEnabledValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/EnabledShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FreeTextShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Labels: echoes/intent: feature

#18614 GRF-540: Disable Enrich Category feature for the 7.0 release
  config/packages/akeneo_feature_flag.yml
Labels: griffins, echoes/intent: feature

#18650 CPM-853: Update match method for enabled
  components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/Enabled.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Model/ProductProjection.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EnabledSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
Labels: echoes/intent: feature

#18661 OCT-190: CI master : fix lint due to Psalm update
  components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsWithFilteredValuesQuery.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidScopeValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidScopeValidator.php
Labels: echoes/intent: technical

#18634 PIM-10753: Fix 500 error in the API when patching a product metric with a mathematical notation
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php
  src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/MetricValueFactorySpec.php
Labels: echoes/intent: maintenance

#18658 PIM-10751: Avoid 500 error and print a violation when user try to save measurement value with space
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumeric.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumericValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/MetricGuesserSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/NumericGuesserSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsNumericSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsNumericValidatorSpec.php
Labels: echoes/intent: maintenance

#18622 CPM-808: Add warnings on PEF create/update
  components/identifier-generator/back/src/API/Presenter/UnableToSetIdentifierExceptionPresenterInterface.php
  components/identifier-generator/back/src/API/Subscriber/UnableToSetIdentifiersSubscriberInterface.php
  components/identifier-generator/back/src/Application/Exception/UnableToSetIdentifierException.php
  components/identifier-generator/back/src/Application/Validation/ErrorList.php
  components/identifier-generator/back/src/Infrastructure/Presenter/UnableToSetIdentifierExceptionPresenter.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/UnableToSetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/presenters.yml
  components/identifier-generator/back/tests/.php_cd.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/create.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/modal.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/modal.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
Labels: echoes/intent: feature

#18645 RAB-1235: Add storage type badge & better error message
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/DownloadFileFromStorage.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFile.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/import/file-path.html
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
Labels: echoes/intent: feature

#18662 Fix PIM requirements check
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/PimRequirements.php
  src/Akeneo/Platform/Requirements.php
Labels: echoes/intent: feature

#18656 CPM-854: Add Enabled condition
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/models/conditions.ts
  components/identifier-generator/front/src/feature/models/conditions/conditions.ts
  components/identifier-generator/front/src/feature/models/conditions/enabled.ts
  components/identifier-generator/front/src/feature/models/conditions/index.ts
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__mocks__/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/index.ts
  components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts
Labels: echoes/intent: feature

#18628 GRF-277 : Display Product Category Permissions
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/CategorySpec.php
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.test.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useFetchUserGroups.ts
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CategoryPermission.ts
Labels: griffins, echoes/intent: feature

#18641 PIM-10750 fix category code validation to allow '0'
  CHANGELOG.md
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCode.php
  src/Akeneo/Category/back/Domain/ValueObject/Code.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateCode.php
  src/Akeneo/Category/back/tests/Integration/Domain/ValueObject/CodeIntegration.php
Labels: griffins, echoes/intent: maintenance

#18669 [Backport PIM-10246] PIM-10765: Fix oom in Process Tracker
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionRow.php
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionTracking.php
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/StepExecutionTracking.php
  src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/StepExecutionTrackingHydrator.php
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionRowSpec.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionTableSpec.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionTrackingSpec.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/StepExecutionTrackingSpec.php
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/LastExecutionTable.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/LastExecutionTable.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/common/ProgressCell.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.test.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/StepExecutionRowTracking.test.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/StepExecutionRowTracking.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobInstanceDetail.test.tsx
Labels: echoes/intent: maintenance

#18651 PH-430: Store database install time
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Persistence/Sql/InstallData.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
  tests/back/Platform/Integration/Installer/Persistence/Sql/InstallDataIntegration.php
  upgrades/schema/Version_7_0_20221212160000_add_database_install_time.php
  upgrades/test_schema/Version_7_0_20221212160000_add_database_install_time_Integration.php
Labels: echoes/intent: feature

#18652 CXP-1363: Add route to reach connected app edit page by id with redirection
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/controllers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/routing.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/RedirectToEditConnectedAppActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppActionSpec.php
Labels: echoes/intent: feature

#18686 OCT-191: properly declare connection property
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/RedirectToEditConnectedAppActionEndToEnd.php
Labels: echoes/intent: technical

#18644 GRF-661 : Add front commands on category MakeFile
  make-file/category.mk
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.test.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: echoes/intent: feature

#18683 OCT-108: Upgrade lcobucci/jwt to ^4.2
  composer.json
  composer.lock
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateJsonWebToken.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateJsonWebTokenSpec.php
Labels: echoes/intent: technical

#18675 CPM-880: Fix double save on new identifier
  components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
Labels: echoes/intent: feature

#18676 CPM-844: Fix Table ActionCell width
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-table-table-with-actions-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx
  front-packages/akeneo-design-system/src/components/Table/TableActionCell/TableActionCell.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionRow.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/AssociationTypesDataGrid.tsx
Labels: echoes/intent: feature

#18688 PIM-10690: [Backport] Command to create/add roles with all existing permission
  CHANGELOG-6.0.md
  src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Component/Connector/RoleWithPermissions.php
  src/Akeneo/UserManagement/Component/Updater/RoleWithPermissionsUpdater.php
  src/Akeneo/UserManagement/back/Application/Exception/UnknownUserRole.php
  src/Akeneo/UserManagement/back/Application/RestoreAdminRolePermissions.php
  src/Akeneo/UserManagement/back/Infrastructure/Cli/RestoreAdminRolePermissionsCommand.php
  src/Akeneo/UserManagement/back/tests/Integration/Application/RestoreAdminRolePermissionsIntegration.php
Labels: griffins, echoes/intent: maintenance

#18698 CPM-854
  components/identifier-generator/back/src/Application/Create/CreateGeneratorCommand.php
  components/identifier-generator/back/src/Application/Update/UpdateGeneratorCommand.php
  components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/Enabled.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Model/LabelCollection.php
  components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/models/conditions/conditions.ts
  components/identifier-generator/front/src/feature/models/conditions/enabled.ts
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/AddConditionButton.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/AddConditionButton.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/AddConditionButton.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/index.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateConditions.test.ts
  components/identifier-generator/front/src/feature/validators/index.ts
  components/identifier-generator/front/src/feature/validators/validateConditions.ts
  components/identifier-generator/front/src/feature/validators/validateEnabled.ts
  make-file/identifier-generator.mk
Labels: echoes/intent: feature

#18615 CXP-1359: Currency : Disable catalog if at least 1 FILTER becomes invalid
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsContainingCurrenciesQueryInterface.php
  components/catalogs/back/src/Infrastructure/EventSubscriber/CurrencyDeactivationSubscriber.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationConstraint.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationTasklet.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsContainingCurrenciesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoCatalogsExtension.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/jobs.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationConstraintTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationTaskletTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsContainingCurrenciesQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Notifier/DisabledCatalogNotifier.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221207140900_add_disable_catalogs_on_currency_deactivation_job_instance.php
  upgrades/test_schema/Version_7_0_20221207140900_add_disable_catalogs_on_currency_deactivation_job_instance_Integration.php
Labels: echoes/intent: feature

#18691 CXP-1361: Locale : Disable catalog if at least 1 FILTER becomes invalid
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingLocalesAsFilterQueryInterface.php
  components/catalogs/back/src/Infrastructure/EventSubscriber/LocaleDeactivationSubscriber.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationConstraint.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTasklet.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesAsFilterQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/jobs.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationConstraintTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTaskletTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesAsFilterQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221214103600_add_disable_catalogs_on_locale_deactivation_job_instance.php
  upgrades/test_schema/Version_7_0_20221214103600_add_disable_catalogs_on_locale_deactivation_job_instance_Integration.php
Labels: echoes/intent: feature

#18654 GRF-529 Add a set of static attributes to help Julia enrich categories
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: echoes/intent: feature

#18672 GRF-647 : Create Category from database and for external api use.
  src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
Labels: griffins

#18714 RAB-7.0: Make 7.0 a real version
  .circleci/jobs/build_and_deploy.yml
  CHANGELOG-7.0.md
  package.json
  src/Akeneo/Platform/Bundle/PimVersionBundle/Version/CommunityVersion.php
  src/Akeneo/Platform/Bundle/PimVersionBundle/Version/FlexibilityVersion.php
  tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
  tests/back/Platform/Integration/PimVersion/VersionProviderIntegration.php
  tests/back/Platform/Specification/Bundle/PimVersionBundle/Version/CommunityVersionSpec.php
  tests/back/Platform/Specification/Bundle/PimVersionBundle/Version/FlexibilityVersionSpec.php
  version.txt
Labels: echoes/intent: technical

#18607 RAB-1148: Update NodeJS version
  .circleci/jobs/build_and_deploy.yml
  .github/workflows/dsm-extract.yml
  .github/workflows/dsm-test.yml
  Makefile
  components/catalogs/front/package.json
  components/identifier-generator/front/package.json
  docker-compose.yml
  docker/Dockerfile_node
  front-packages/akeneo-design-system/.github/workflows/cleanup-staging.yml
  front-packages/akeneo-design-system/.github/workflows/deploy.yml
  front-packages/akeneo-design-system/.github/workflows/tag-and-publish-to-npm.yml
  front-packages/akeneo-design-system/example/package.json
  front-packages/akeneo-design-system/package.json
  front-packages/measurement/package.json
  front-packages/measurement/src/feature/context/unsaved-changes-context.ts
  front-packages/shared/src/hooks/useDateFormatter.unit.tsx
  package.json
  src/Akeneo/Category/front/package.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/package.json
  src/Akeneo/Platform/Job/front/process-tracker/package.json
  src/Oro/Bundle/ConfigBundle/front/package.json
  webpack.config.js
  yarn.lock
Labels: echoes/intent: technical

#18695 CPM-860: Validate Family Condition
  components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/Enabled.php
  components/identifier-generator/back/src/Domain/Model/Condition/Family.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Validation/ConditionsShouldNotContainMultipleCondition.php
  components/identifier-generator/back/src/Infrastructure/Validation/ConditionsShouldNotContainMultipleConditionValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/ConditionsShouldNotContainMultipleEnabledValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyCodesShouldExist.php
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyCodesShouldExistValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyShouldBeValidValidator.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/FamilySpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/ConditionsShouldNotContainMultipleConditionValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/EnabledShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyCodesShouldExistValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  config/services/test_fake/services.yml
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/InMemory/InMemoryFindFamilyCodes.php
  src/Akeneo/Pim/Structure/Family/back/Test/Acceptance/Resources/config/services.yml
Labels: echoes/intent: feature

#18708 CPM-861: Update match method for family
  components/identifier-generator/back/src/Domain/Model/Condition/Family.php
  components/identifier-generator/back/src/Domain/Model/ProductProjection.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EnabledSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/FamilySpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
Labels: echoes/intent: feature

#18701 CPM-858: Create a Controller to get the families list
  components/identifier-generator/back/src/Infrastructure/Controller/GetFamiliesController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetFamiliesControllerEndToEnd.php
Labels: echoes/intent: feature

#18721 CPM-859: Add FamiliesSelector component
  components/identifier-generator/back/src/Domain/Model/Condition/Enabled.php
  components/identifier-generator/back/src/Domain/Model/Condition/Family.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/FamiliesSelector.tsx
  components/identifier-generator/front/src/feature/components/IdentifierAttributeSelector.tsx
  components/identifier-generator/front/src/feature/components/__tests__/FamiliesSelector.test.tsx
  components/identifier-generator/front/src/feature/components/__tests__/IdentifierAttributeSelector.test.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/errors/Unauthorized.ts
  components/identifier-generator/front/src/feature/errors/index.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetFamilies.test.tsx
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/models/family.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-multi-select-input-invalid-value-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/ChipInput.tsx
  front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
Labels: echoes/intent: feature

#18626 GRF-654: Replace mock values by the real finder service
  src/Akeneo/Category/back/Application/Converter/StandardFormatToUserIntents.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/UserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/UserIntentFactoryRegistry.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/tests/Integration/Application/Converter/StandardFormatToUserIntentsIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/LabelUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/UserIntentFactoryRegistrySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Converter/InternalApi/InternalApiToStdSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.test.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useFetchUserGroups.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CategoryPermission.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
Labels: griffins, echoes/intent: feature

#18625 GRF-585 : Visualize the product category permissions in category edition
  src/Akeneo/Category/back/Application/Registry/FindCategoryAdditionalProperties.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UserGroupController.php
  src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/permissions.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/registry.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/user_group.yml
  src/Akeneo/Category/back/ServiceApi/Handler/CategoryAdditionalPropertiesFinder.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/CategorySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistrySpec.php
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.test.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useFetchUserGroups.ts
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CategoryPermission.ts
Labels: griffins, echoes/intent: feature

#18624 GRF-338: As Griffin dev team I want to save the product category permissions in category edition (without applying to the children)
  src/Akeneo/Category/back/Application/Converter/StandardFormatToUserIntents.php
  src/Akeneo/Category/back/Application/Filter/CategoryEditAclFilter.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverProcessor.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverRegistry.php
  src/Akeneo/Category/back/Application/Storage/Save/SaveCategory.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategorySaver.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/UserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/UserIntentFactoryRegistry.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/converters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/save.yml
  src/Akeneo/Category/back/tests/Integration/Application/Converter/StandardFormatToUserIntentsIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/LabelUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/UserIntentFactoryRegistrySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Converter/InternalApi/InternalApiToStdSpec.php
Labels: griffins, echoes/intent: feature

#18731 RAB-1243: Add prepare_60_to_70.sh into std-build directories
  std-build/migration/prepare_60_to_70.sh
Labels: echoes/intent: technical

#18724 OCT-194: Remove slack notifications when `test_catalogs` fails on a PR but keep it for the nightly
  .circleci/workflows/pull_request.yml
Labels: echoes/intent: technical

#18720 OCT-193: Make the test_performance_catalogs_ce step required in the CI
  .circleci/workflows/squads/octopus/octopus_catalogs_pull_request.yml
Labels: echoes/intent: technical

#18693 OCT-192: Fix Connectivity & Catalogs CI to include deprecations checks
  components/catalogs/Makefile
  components/catalogs/back/phpstan-deprecations.neon
  components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php
  make-file/connectivity-connection.mk
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/RedirectToEditConnectedAppActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/phpstan-deprecations.neon
Labels: echoes/intent: technical

#18707 OCT-192: apply phpstan to the tests directory
  components/catalogs/Makefile
  components/catalogs/back/src/Application/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryInterface.php
  components/catalogs/back/src/Domain/Catalog.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsAsFilterQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingCurrenciesAsFilterQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesAsFilterQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/UpsertCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AbstractAttributeSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/back/tests/Integration/ServiceAPI/Command/CreateCatalogCommandValidationTest.php
  components/catalogs/back/tests/Unit/Application/Handler/CreateCatalogHandlerTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoriesActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoryChildrenActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelLocalesActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelsActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetFamiliesActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetLocalesActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Validation/MaxNumberOfCatalogsPerUserValidatorTest.php
Labels: echoes/intent: technical

#18728 OCT-195: CI: improve catalog steps in pull_request pipeline
  .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
  .circleci/workflows/pull_request.yml
Labels: echoes/intent: technical

#18739 GRF-540: Disable Enrich Category feature for the 7.0 release
  config/packages/akeneo_feature_flag.yml
Labels: griffins, echoes/intent: feature

#18673 CPM-856: Remove a condition
  components/identifier-generator/front/src/feature/pages/SimpleDeleteModal.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/SimpleDeleteModal.tsx
  components/identifier-generator/front/src/feature/pages/index.ts
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#18671 RAB-1087: Add Google Cloud Storage support (front)
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/index.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
Labels: echoes/intent: feature

#18746 RAB-1245: Fix 7.0 for flex team
  std-build/package.json
Labels: echoes/intent: technical

#18738 PIM-10687: Fix high memory consumption when computing completeness for prices with inactive currencies
  CHANGELOG-6.0.md
  docker/cypress/Dockerfile
  src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php
  src/Akeneo/Channel/Component/Query/PublicApi/FindActivatedCurrenciesInterface.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness_mask_generators.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php
  tests/back/Acceptance/Channel/InMemoryFindActivatedCurrencies.php
  tests/back/Acceptance/Resources/config/pim/queries.yml
  tests/back/Acceptance/spec/Channel/InMemoryFindActivatedCurrenciesSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/FindActivatedCurrenciesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
Labels: echoes/intent: maintenance
