Repository akeneo/pim-community-dev, pull requests merged in 2022-07, with the labels that each got.

#17339 PIM-10503 : fix regexp to support strict word boundaries
  CHANGELOG.md
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/IsChannelUsedInProductProductExportJob.php
  tests/back/Channel/Integration/Channel/Query/Sql/IsChannelUsedInProductProductExportJobIntegration.php
Labels: griffins

#17232 GRF-44: User information & password, create user button
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/index.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/requirejs.yml
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/create-user-button.ts
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/user-profile-tab-content.ts
Labels: griffins

#17097 GRF-33: Do not spellcheck unchanged values
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetCriterionEvaluationByProductIdAndCriterionCodeQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Hydrator/hydrateCriterionEvaluationResult.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductCriterionEvaluationByProductIdAndCriterionCodeQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelCriterionEvaluationByProductIdAndCriterionCodeQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCommonCriterionResultDataIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductCriterionEvaluationByProductIdAndCriterionCodeQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelCriterionEvaluationByProductIdAndCriterionCodeQueryIntegration.php
Labels: griffins

#17361 GRF-45: Move Compare/Translate from FT to serenity
  package.json
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/free-trial-start-copy.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/product/package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/product/src/components/CompareTranslateButton.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/product/src/components/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/product/src/index.ts
Labels: wait_pm_validation, griffins

#17452 CPM-682: Fix reindexation step
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidReindexElasticsearch.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
Labels: echoes/intent: feature

#17399 RAB-838: Encrypt password for SFTP connection
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/Compiler/CredentialsEncrypterPass.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypter.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/PimImportExportBundle.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/security.yml
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
  tests/legacy/features/platform/import/execute_an_import.feature
Labels: contribution, echoes/effort: S, echoes/intent: feature

#17463 PIM-10542: Fix int attribute code breaks ValueUserIntentFactoryRegistry
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/ValueUserIntentFactoryRegistry.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/ValueUserIntentFactoryRegistrySpec.php
Labels: echoes/effort: XS, echoes/intent: maintenance

#17445 CPM-681: Remove indentifiers from ProductIndexer
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductCompleteness.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Enrichment/CalculateProductCompletenessSpec.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexer.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithAssociations/PersistTwoWayAssociationSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/ComputeProductsAndAncestorsSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductModel/OnSave/ComputeProductAndAncestorsSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Job/IndexFamilyProductsAndProductModelsTasklet.php
  src/Akeneo/Pim/Enrichment/Bundle/Product/ComputeAndPersistProductCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetAncestorProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetDescendantVariantProductUuids.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessCalculator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Storage/Indexer/ProductIndexerInterface.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/DateTimeFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/CompletenessFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetAncestorProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetDescendantVariantProductUuidsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexerSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Product/OnSave/ComputeProductsAndAncestorsSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductModel/OnSave/ComputeProductAndAncestorsSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Job/IndexFamilyProductsAndProductModelsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/CompletenessCalculatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
  upgrades/schema/Version_4_0_20200116122239_remove_product_empty_raw_values.php
  upgrades/schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs.php
  upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
Labels: echoes/intent: feature

#17477 RAB-914: fix SFTP credentials encryption for GROWTH & TRIAL
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
Labels: contribution, echoes/intent: feature

#17400 RAB-873: Migrate existing job instances (JobConfiguration[storage][file_path] and JobConfiguration[filePath])
  upgrades/schema/Version_7_0_20220704141138_update_job_instance_parameter_path.php
  upgrades/test_schema/Version_7_0_20220704141138_update_job_instance_parameter_path_Integration.php
Labels: contribution, echoes/effort: S, echoes/intent: feature, echoes/intent: maintenance

#17456 RAC-1254: Use the AuthenticatedJobLauncher in every edition
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
Labels: echoes/intent: maintenance

#17367 CPM-634: Add Connector Product creation through Uuids
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductList.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetConnectorProducts.php
  src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
Labels: echoes/intent: feature

#17415 PIM-10494: Fix memory issue when trying to delete a job profile with many warnings
  CHANGELOG-6.0.md
  src/Akeneo/Tool/Bundle/BatchBundle/Job/JobInstanceRepository.php
  src/Akeneo/Tool/Bundle/BatchBundle/Remover/JobInstanceRemover.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobExecution.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/StepExecution.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Remover/JobInstanceRemoverSpec.php
  src/Akeneo/Tool/Component/StorageUtils/Repository/RemovableObjectRepositoryInterface.php
  tests/back/Integration/integration/BatchBundle/Job/JobInstanceRepositoryIntegration.php
Labels: contribution, echoes/effort: M, echoes/intent: maintenance

#17472 PIM-10543: Fix selected categories sent to listCategories
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/AbstractListCategoryController.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/TreeAssociate.tsx
Labels: echoes/intent: maintenance

#17496 RAB-837: Add min-width on remove tag icon
  front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
Labels: echoes/intent: feature, echoes/intent: technical

#17484 RAB-912: Export to an sftp directory does not work
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/DownloadStep.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/UploadStep.php
Labels: contribution, echoes/intent: feature

#17504 PIM-10545: catalogs fix
  components/catalogs/Makefile
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: maintenance

#17493 RAB-915: Migrate quick export jobs to remove legacy filePath
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductAndProductModelQuickExport.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
  src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
Labels: contribution

#17482 PIM-10545 - Remove merge of non viewable categories on SetCategories userIntent
  components/catalogs/Makefile
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetCategoriesApplier.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/PQB/GetProductUuidsHandlerIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductVariantIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertQuantifiedAssociationsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetCategoriesApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
  src/Akeneo/Platform/Job/back/tests/Integration/ControllerIntegrationTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Helper/AuthenticatorHelper.php
  tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Classification/ClassifyProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Classification/ClassifyProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
  tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php
  tests/back/Pim/Enrichment/Integration/Completeness/RemoveCompletenessWhenDeletingProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ComputeDescendantProductCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/RemovingProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Query/FindNonExistingProductIdentifiersQueryIntegration.php
  tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
  tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/RemoveNonExistingProductValuesIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/EmptyFilterWithProductsAndProductModelsIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Association/CreateTwoWayAssociationIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/ConvertVariantToSimpleProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/Export/AbstractExportTestCase.php
  tests/back/Pim/Enrichment/Integration/Product/LoadProductAndProductModelIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetAncestorProductModelCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlFindProductIdentifierIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductModelImagesFromCodesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/CountVariantProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetDescendantVariantProductUuidsIntegration.php
  tests/back/Pim/Enrichment/Integration/Updater/Copier/AbstractCopierTestCase.php
  tests/back/Pim/Enrichment/Integration/Updater/PropertyClearerIntegration.php
  tests/back/Pim/Enrichment/Integration/Updater/Setter/MediaAttributeSetterIntegration.php
Labels: echoes/intent: maintenance

#17508 RAB-924: Add migration to remove old filePath on product and product model quick export
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
  upgrades/schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job.php
  upgrades/test_schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job_Integration.php
Labels: echoes/intent: feature

#17526 GRF-207: Fix MYSQL error during the calculation of the completeness
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommand.php
Labels: griffins

#17523 GRF-209: Fix deprecation on ES
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndexSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/UpdateIndexesOnCategoryDeletion.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Family/FamilyAttributeAsLabelChangedSubscriber.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Family/FamilyAttributeAsLabelChangedSubscriberSpec.php
Labels: griffins

#17474 RAB-782: Add a service api to search families
  composer.json
  config/bundles.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/Sql/SqlCountFamilyCodes.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/Sql/SqlFindFamiliesWithLabels.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/Sql/SqlFindFamilyCodes.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Symfony/AkeneoPimStructureFamilyBundle.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Symfony/DependencyInjection/AkeneoPimStructureFamilyExtension.php
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/CountFamilyCodes.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FamilyQuery.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FamilyQueryPagination.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FamilyQuerySearch.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FamilyWithLabels.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FindFamiliesWithLabels.php
  src/Akeneo/Pim/Structure/Family/back/ServiceAPI/Query/FindFamilyCodes.php
  src/Akeneo/Pim/Structure/Family/back/Test/Integration/Query/Sql/SqlCountFamilyCodesIntegration.php
  src/Akeneo/Pim/Structure/Family/back/Test/Integration/Query/Sql/SqlFindFamiliesWithLabelsIntegration.php
  src/Akeneo/Pim/Structure/Family/back/Test/Integration/Query/Sql/SqlFindFamilyCodesIntegration.php
Labels: echoes/effort: M, echoes/intent: feature

#17528 RAB: Fix deprecated self::$container of symfony
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/Command/UpdateAuditDataCommandEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Audit/Persistence/DbalExtractConnectionsProductEventCountQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/Persistence/GetUserProfileQueryIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindAnnouncementItemsIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindNewAnnouncementIdsIntegration.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/WebTestCase.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/Acceptance/AckMessageEventListenerTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/AcceptanceTestCase.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/WebTestCase.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/SqlIntegrationTestCase.php
  src/Akeneo/Tool/Bundle/MessengerBundle/tests/integration/OrderingKeySolverIntegration.php
  src/Oro/Bundle/PimDataGridBundle/tests/Integration/Controller/ControllerIntegrationTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/EntityWithQuantifiedAssociations/AbstractQuantifiedAssociationsTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/AbstractMassEditEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AbstractProductWithQuantifiedAssociationsTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/InternalApi/QuantifiedAssociations/AbstractProductModelWithQuantifiedAssociationsTestCase.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/InternalApi/UpdateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
  tests/back/Platform/EndToEnd/InternalApiTestCase.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
  tests/back/UserManagement/Integration/Bundle/ControllerIntegrationTestCase.php
Labels: echoes/effort: XS, echoes/intent: technical

#17511 CPM-634: Add Uuids in IdentifierResult from PQB
  components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/CursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResult.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResults.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultsSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
Labels: echoes/intent: feature

#17298 PIM-10478: Disable compute_family_variant_structure_changes on familySave
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
  tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Labels: echoes/intent: maintenance

#17409 GRF-89 : create enriched category feature flag.
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
Labels: wip, griffins, echoes/intent: feature

#17539 Pull up for OCT-76 and PIM-10494
  CHANGELOG-6.0.md
  config/packages/framework.yml
  config/packages/security.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Job/JobInstanceRepository.php
  src/Akeneo/Tool/Bundle/BatchBundle/Remover/JobInstanceRemover.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobExecution.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/StepExecution.orm.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Remover/JobInstanceRemoverSpec.php
  src/Akeneo/Tool/Component/StorageUtils/Repository/RemovableObjectRepositoryInterface.php
  tests/back/Integration/integration/BatchBundle/Job/JobInstanceRepositoryIntegration.php
Labels: echoes/intent: maintenance

#17455 CPM-634: Replace calls to fromIdentifier(s) with fromUuid(s) for connector products
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/GetConnectorProducts.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
Labels: echoes/intent: feature

#17541 PH-13: Extract services from BatchCommand
  src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/JobExecution/CreateJobExecutionHandlerIntegration.php
Labels: tech-improvement, ucs

#17552 CPM-696: fix performance issue on versioning purge that last several days even on small catalogs
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetAllButLastVersionIdsByIdsQuery.php
Labels: echoes/intent: feature
