Repository akeneo/pim-community-dev, pull requests merged in 2022-06, with the labels that each got.

#17155 OBS-157: Remove the 500ms waiting between the screenshot of each story
  front-packages/akeneo-design-system/src/all.visual.tsx
Labels: to review, CI, design-system

#17079 PIM-10452: Fix migration to set some fields to NOT NULL on job & step execution tables
  CHANGELOG-6.0.md
  upgrades/schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables.php
  upgrades/test_schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables_Integration.php
Labels: contribution

#17196 RAB-761: Add id field on CategoryTree
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/SqlFindCategoryTrees.php
  src/Akeneo/Pim/Enrichment/Component/Category/Query/PublicApi/CategoryTree.php
  tests/back/Pim/Enrichment/Integration/Category/SqlFindCategoryTreesIntegration.php
Labels: contribution

#17208 BH-1159: Use available JobMessage class for denormalisation
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/MigrateJobMessagesFromOldQueueCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/MigrateJobMessagesFromOldQueueCommandIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Factory/JobExecutionMessageFactoryIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Factory/JobExecutionMessageFactory.php
  src/Akeneo/Tool/Component/BatchQueue/Normalizer/JobExecutionMessageNormalizer.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Factory/JobExecutionMessageFactorySpec.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Normalizer/JobExecutionMessageNormalizerSpec.php
Labels: ucs

#17179 GRF-44: Read only in user edit form and hide create user button for free trial
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/index/create-button.js
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/index.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/requirejs.yml
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/create-user-button.ts
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/user-profile-tab-content.ts
Labels: griffins

#17186 fix(datagrid views): PIM-10461: Proper pagination for view search end…
  src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
  src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepository.php
  src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepositoryInterface.php
Labels: contribution, griffins

#17212 PIM-10484: [SLA] Failed jobs shouldn't be filtered with 'In progress' filter in the process tracker
  CHANGELOG.md
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionHealthCheck.php
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionRow.php
  src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/JobExecutionHealthCheckHydrator.php
  src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/JobExecutionRowHydrator.php
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/hydrators.yml
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionHealthCheckSpec.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionRowSpec.php
  src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionTableSpec.php
Labels: contribution

#17256 PIM-10487: Fix import of very tiny measurement values (e.g. 0.000075 GRAM)
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
Labels: contribution

#17333 PIM-10509: Pull-up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
Labels: griffins

#17263 PIM-10485 : get category tree for channel context without filter user…
  CHANGELOG.md
  src/Akeneo/Channel/back/Infrastructure/Controller/InternalApi/ChannelController.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/routing/internal_api/channel.yml
  src/Akeneo/Channel/back/tests/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/CategoryController.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/SqlFindCategoryTrees.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/channel/form/properties/general/category-tree.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/channel-fetcher.js
  tests/back/Pim/Enrichment/Integration/Category/SqlFindCategoryTreesIntegration.php
Labels: griffins

#17284 PH-20: UCS - Do not persist tenant ID in JobMessage
  src/Akeneo/Channel/back/tests/phpstan.neon.dist
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Factory/JobExecutionMessageFactoryIntegration.php
  src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php
  src/Akeneo/Tool/Component/BatchQueue/Factory/JobExecutionMessageFactory.php
  src/Akeneo/Tool/Component/BatchQueue/Normalizer/JobExecutionMessageNormalizer.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessage.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessageInterface.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Factory/JobExecutionMessageFactorySpec.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Normalizer/JobExecutionMessageNormalizerSpec.php
Labels: ucs

#16974 WSL-29: Storage optimization - Products scores (release 2)
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/ProductScoreRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductScoreRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanProductScoresCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  upgrades/schema/Version_7_0_20220629142647_dqi_update_pk_on_product_score.php
  upgrades/test_schema/Version_7_0_20220629142647_dqi_update_pk_on_product_score_Integration.php
Labels: griffins
