Repository akeneo/pim-community-dev, pull requests merged in 2022-04, with the labels that each got.

#16707 PIM-10372 make sure labels are saved with know locale codes correctly spelled regarding letter cases
  CHANGELOG.md
  src/Akeneo/Channel/Component/Updater/ChannelUpdater.php
  tests/back/Channel/Specification/Component/Updater/ChannelUpdaterSpec.php
  tests/back/Integration/TestCase.php
  upgrades/schema/Version_7_0_20220330095652_ensure_locale_codes_for_labels_in_channels_have_correct_case.php
  upgrades/test_schema/Version_7_0_20220330095652_ensure_locale_codes_for_labels_in_channels_have_correct_case_integration.php
Labels: bug, contribution, weasels

#16754 PLG-696: Add command to clean deprecated data in completeness results
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/OneTimeTaskCommandTrait.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommandIntegration.php
Labels: weasels

#16764 PIM-10392: merge 5.0 => master
  CHANGELOG-5.0.md
Labels: contribution

#16713 PLG-792: add getFamilyCode for RequiredAttributeMask
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/RequiredAttributesMask.php
Labels: weasels

#16681 PLG-783 simplify useFetchProductScores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductModelScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/ChannelLocaleRateCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/data-quality-insights-app.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreBarPEF.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchProductModelQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchProductQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/ProductEditForm/catalogContextReducer.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/ProductEditForm/productReducer.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductModelScoresSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductScoresSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/QualityScoreProductHeader.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/ProductEditForm/useFetchQualityScore.unit.ts
Labels: contribution, weasels

#16776 PIM-10392: merge 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/Cursor.php
Labels: contribution

#16827 PIM-10404 Pull up 5.0 => 6.0
  CHANGELOG-5.0.md
Labels: contribution

#16832 PIM-10406: Pull Up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
Labels: contribution

#16810 RAB-640: Retrieve all channels information (Query)
  src/Akeneo/Channel/back/API/Query/Channel.php
  src/Akeneo/Channel/back/API/Query/FindChannels.php
  src/Akeneo/Channel/back/API/Query/LabelCollection.php
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindChannels.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Channel/back/tests/.php_cs.php
  src/Akeneo/Channel/back/tests/Integration/Query/Sql/SqlFindChannelsIntegration.php
  src/Akeneo/Channel/back/tests/Specification/API/Query/ChannelSpec.php
  src/Akeneo/Channel/back/tests/Specification/API/Query/LabelCollectionSpec.php
Labels: contribution

#16843 RAB-614: Retrieve all locales information (Query)
  src/Akeneo/Channel/back/API/Query/FindLocales.php
  src/Akeneo/Channel/back/API/Query/Locale.php
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindLocales.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Channel/back/tests/Integration/Query/Sql/SqlFindLocalesIntegration.php
  src/Akeneo/Channel/back/tests/Specification/API/Query/LocaleSpec.php
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Sql/SqlFindLocalesSpec.php
Labels: contribution

#16850 RAB-695: Channel Service API: split cached queries into 2 classes
  src/Akeneo/Channel/back/Infrastructure/Query/Cache/CachedFindChannels.php
  src/Akeneo/Channel/back/Infrastructure/Query/Cache/CachedFindLocales.php
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindChannels.php
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindLocales.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Cache/CachedFindChannelsSpec.php
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Cache/CachedFindLocalesSpec.php
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Sql/SqlFindLocalesSpec.php
Labels: contribution

#16854 PLG-837: Adapt ranks distribution for double scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQueryIntegration.php
Labels: weasels

#16886 PLG-853: Fix fetching and launching product models evaluation
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluateOutdatedProductModel.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/EvaluateProductModelController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductModelEvaluationController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/EvaluateOutdatedProductModelSpec.php
Labels: weasels

#16807 PIM-10396: DQI "Enrichment" suggestion does not take into account Table attribute
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/BuildSqlMaskField.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/AddPriceCollectionCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/AttributeCase.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetNonRequiredAttributesMasksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetNonRequiredProductModelAttributesMaskQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetRequiredAttributesMasksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetRequiredProductModelAttributesMaskQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/BuildSqlMaskFieldSpec.php
Labels: weasels
