Repository akeneo/pim-community-dev, pull requests merged in 2022-03, with the labels that each got.

#16425 PLG-752: display quality score in PEF
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/data-quality-insights-app.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/product-model-quality-score.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/QualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/ProductEditForm/fetchProductModelQualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
Labels: contribution, weasels

#16430 PLG-771: Adapt the persistence of the Key Indicators for product models
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductModelProjection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductModelsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductModelProjectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductModelsIndexSpec.php
Labels: weasels

#16398 PLG-776 Option screen broken with small screen
  CHANGELOG-6.0.md
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Attribute.less
Labels: weasels

#16459 PLG-754-pending-status-UX-in-grid-and-PEF
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/quality-score-badge-cell.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Summary.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Tooltip.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreBar.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreLoader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScorePending.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/QualityScore.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/QualityScoreModel.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchQualityScoreEvolution.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/QualityScoreProductHeader.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/QualityScore.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/QualityScoreBar.unit.tsx
Labels: contribution, weasels

#16463 PLG-782: Rework criterion results transformation from ids to codes
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductModelsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/AttributesInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/InMemoryAttributes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/SqlAttributes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/ChannelsInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/InMemoryChannels.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/SqlChannels.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCommonCriterionResultDataIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCompletenessResultDataIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformResultDataIdsInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/InMemoryLocales.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/LocalesInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/SqlLocales.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformChannelLocaleDataIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIds.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/transformation.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Attributes/InMemoryAttributesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Channels/InMemoryChannelsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCommonCriterionResultDataIdsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCompletenessResultDataIdsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Locales/InMemoryLocalesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformChannelLocaleDataIdsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsSpec.php
Labels: weasels

#16494 PLG-782: Compute Enrichment status KI for product models
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductModelCompleteness.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductModelsAndCriterionQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Enrichment/CalculateProductModelCompletenessIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductModelsEnrichmentStatusQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductModelsAndCriterionQueryIntegration.php
Labels: weasels

#16509 [BACKPORT] Skip flaky test on updating a channel conversion units
  tests/legacy/features/channel/edit_channel.feature
Labels: bug, CI

#16405 RAC-1215: fix error when attributeOption doesn't have label
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Sql/SqlSearchAttributeOptions.php
  tests/back/Pim/Structure/Integration/AttributeOption/SqlSearchAttributeOptionsIntegration.php
Labels: contribution

#16431 PLG-781: Fix migration task related to calculating product quality scores
  CHANGELOG-6.0.md
  upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
  upgrades/test_schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores_Integration.php
Labels: weasels

#16515 PLG-807: Adapt command to populate the product models KI
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PopulateProductModelScoresAndKeyIndicatorsCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
Labels: weasels

#16497 PLG-772: Fetch key indicators for products and product models
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/KeyIndicatorSpec.php
Labels: wip, weasels

#16552 PLG-810: Fix publishing the data_quality_insights_recompute_product_scores job during migration
  upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
Labels: bug, CI

#16561 Pim-10333 Import category without correct locale should be impossible
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Component/Category/Connector/ArrayConverter/FlatToStandard/Category.php
  tests/back/Pim/Enrichment/Specification/Component/Category/Connector/ArrayConverter/FlatToStandard/CategorySpec.php
  tests/legacy/features/channel/edit_channel.feature
  tests/legacy/features/pim/enrichment/product-model/classify_product_model.feature
  tests/legacy/features/pim/enrichment/product/export/export_products_by_categories.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature
Labels: contribution

#16517 PLG-733 Service API for product models scores
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductModelScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductModelScoresByCodesQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresByCodesQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductModelScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/AddProductScoreProperty.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/public_api/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Model/ProductScore.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Model/ProductScoreCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Model/QualityScore.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Model/QualityScoreCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetLatestProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetLatestProductScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductModelScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductModelScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresByCodesQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/PublicApi/Query/ProductEvaluation/GetProductModelScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/PublicApi/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductModelScoresSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductScoresSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductModelsIndexSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductModelScoresQuerySpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductScoresQuerySpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/ProductGrid/AddProductScorePropertySpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/PublicApi/Model/ProductScoreCollectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/PublicApi/Model/QualityScoreCollectionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/PublicApi/Model/QualityScoreSpec.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjectionIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
Labels: weasels

#16554 PLG-728: Make scores available in product models from the public API
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQuery.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelListSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
Labels: weasels

#16553 PLG-770 front : product models in key indicators
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/AttributeMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorBase.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorNoData.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/messageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/styled.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/keyIndicatorDescriptorsCE.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/IntegerPercent.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/Product.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchKeyIndicators.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicateorAboutAttributes.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/KeyIndicator.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Domain/IntegerPercent.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: contribution, weasels

#16585 [PLG-727] display export product model filter
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
Labels: weasels

#16534 PLG-727: Expose product models scores in exports
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
Labels: wip, weasels

#16598 PLG-770 post-merge CR fixes
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/AttributeMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/keyIndicatorDescriptorsCE.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.unit.tsx
Labels: contribution, weasels

#16562 PIM-10338: The number of options to improve is not correctly refreshed
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Events.ts
Labels: weasels

#16538 PLG-785: DQI - PM - Update KI on dashboard
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/AttributeMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorBase.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorNoData.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/messageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/styled.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/keyIndicatorDescriptorsCE.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/Dashboard/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/IntegerPercent.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/Product.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchKeyIndicators.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/KeyIndicatorSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/KeyIndicator.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Domain/IntegerPercent.unit.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
Labels: weasels, Feature branch

#16591 PLG-786-787: Expose PM scores in exports and API
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQuery.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelListSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductsQueryHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilderSpec.php
Labels: weasels

#16581 RAC-1214: [Shared Catalogs] Displayed logo not resized
  front-packages/akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.tsx
Labels: contribution

#16607 PIM-10345: Having a full numerical attribute code cause an error on product model import
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
Labels: contribution

#16638 PIM-10346: Fix spellcheck badge not displayed on attribute options
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
Labels: weasels

#16637 PLG-821 fix(DQI) keyindicator ES queries for product models : ignoring submodels
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
Labels: bug, contribution, weasels

#16660 PLG-784: Optimize Elasticsearch indexation for Product Quality evaluation
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductModelsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductModelsIndexSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
Labels: weasels

#16628 PLG-822 fix (Data quality insights) Key indicator component must be ready when key product_models is missing.
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
Labels: bug, contribution, weasels

#16691 Add new FindUnit query in the public API of MeasurementBundle
  src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/FindUnit.php
  src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlFindUnit.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/SqlFindUnitIntegration.php
Labels: contribution
