Repository akeneo/pim-community-dev, pull requests merged in 2022-02, with the labels that each got.

#16229 PLG-718 : Display quality score skeleton when product is evaluating only on save action
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreLoader.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/ProductEditForm/ProductContextListener.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/state/PageContextState.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchProductQualityScore.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useProductEvaluation.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/ProductEditForm/pageContextReducer.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/index.ts
Labels: weasels, wait_pm_validation

#16238 PLG-239 : add footer on plain text batch email
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.html.twig
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Mail/reset.txt.twig
Labels: weasels, wait_pm_validation

#16240 PIM-10250: [Backport] PIM-9806: Enable authentication temporary lock to protect against brute force attack
  CHANGELOG-5.0.md
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/EventListener/DatabaseInstallerSubscriber.php
  src/Akeneo/UserManagement/Bundle/EventListener/LoadLoginAttemptInformationSubscriber.php
  src/Akeneo/UserManagement/Bundle/Model/LockedAccountException.php
  src/Akeneo/UserManagement/Bundle/Provider/CustomDaoAuthenticationProvider.php
  src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Component/Model/User.php
  tests/back/UserManagement/Specification/Bundle/Provider/CustomDaoAuthenticationProviderSpec.php
  upgrades/schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts.php
Labels: contribution

#16279 Pull up 6.0 into master
  CHANGELOG-3.0.md
  CHANGELOG-3.2.md
  CHANGELOG-4.0.md
  CHANGELOG-6.0.md
  CHANGELOG.md
  front-packages/akeneo-design-system/src/components/Input/ColorInput/ColorInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/TableInput/TableInput.stories.mdx
  src/Akeneo/UserManagement/Bundle/Provider/CustomDaoAuthenticationProvider.php
  src/Akeneo/UserManagement/Component/Model/User.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
  upgrades/schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts.php
  upgrades/schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts.php
  upgrades/test_schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts_Integration.php
  upgrades/test_schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts_Integration.php
Labels: PULLUP

#16237 PLG-670: Zoom problem on the resolution on several users screens
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
Labels: weasels

#16314 PIM-10281: Update Circle CI machine executors
  .circleci/jobs/build_and_deploy.yml
  .circleci/jobs/features/connectivity.yml
  .circleci/jobs/features/other.yml
Labels: CI

#16296 PLG-737: Update SQL Schema to store the Quality score for product model
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  upgrades/schema/Version_7_0_20220214101647_add_dqi_product_model_score_table.php
  upgrades/test_schema/Version_7_0_20220214101647_add_dqi_product_model_score_table_Integration.php
Labels: weasels

#16300 PLG-738: Add job informations to monitor evaluations duration
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTaskletSpec.php
Labels: weasels

#16374 PLG-761-no-impact-on-ui-when-productmodels-scores-will-be-computed
  .gitignore
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/quality-score-badge-cell.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreFilterSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchQueryBuilder.php
Labels: contribution

#16365 PLG-745 : product model fetch quality score
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductModelScores.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/GetUpToDateProductModelScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductModelScoresQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/HasUpToDateEvaluationQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductModelEvaluationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductModelQualityScoreController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductEvaluationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductModelScoresSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/GetUpToDateProductModelScoresQuerySpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductScoresQuerySpec.php
Labels: weasels

#16364 PIM-10293 add batch-size option to pim completness command
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
Labels: contribution

#16383 PLG-743: Populate Quality Score for product models on the first deployment
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RecomputeProductScoresTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductModelsIndex.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/UpdateProductModelsIndexSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PopulateProductModelScoresCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductModelsIndexSpec.php
Labels: weasels

#16399 PLG-720: Fix ES integration test
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjectionIntegration.php
Labels: weasels
