Repository akeneo/pim-community-dev, pull requests merged in 2022-08, with the labels that each got.

#17559 Do not throw an exception when filepath is null
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePathValidator.php
  tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/Storage/ValidateLocalStorageTest.php
  tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/Storage/ValidateNoneStorageTest.php
  tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/ValidateFilePathTest.php
Labels: echoes/intent: feature

#17546 Update phpstan version on asset manager, the normalizer need to say that returned value is array
  src/Akeneo/Tool/Component/Api/Normalizer/Exception/ViolationNormalizer.php
Labels: echoes/intent: technical

#17551 GRF-91: Decouple the Categories Microfrontend from the PIM
  src/Akeneo/Category/front/src/FakePIM.tsx
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/configuration/index.ts
  src/Akeneo/Category/front/src/configuration/useConfiguration.ts
  src/Akeneo/Category/front/src/feature/pages/NewCategoryModal.tsx
  src/Akeneo/Category/front/src/index.tsx
Labels: griffins, echoes/intent: feature

#17549 PIM-10561: Fix associationUserIntentFactory to cast in to string
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/AssociationsUserIntentFactory.php
  src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/QuantifiedAssociationUserIntentFactory.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/AssociationsUserIntentFactorySpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/QuantifiedAssociationUserIntentFactorySpec.php
Labels: echoes/intent: maintenance

#17568 PIM-10557: Fix notifications not displayed for obsolete route parameters
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/NotificationBundle/Controller/NotificationController.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/config/controllers.yml
  tests/back/Platform/Specification/Bundle/NotificationBundle/Controller/NotificationControllerSpec.php
Labels: echoes/intent: maintenance

#17570 GRF-214: Implementation of SqlFindOneByIdentifier service + Integration test
  src/Akeneo/Category/back/Infrastructure/Storage/SQL/SqlFindOneByIdentifier.php
  src/Akeneo/Category/back/Infrastructure/Storage/SQL/SqlFindOneByIdentifierStub.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/SQL/SqlFindOneByIdentifierIntegration.php
Labels: griffins

#17524 PIM-10551: Add filtering on locale specific attributes when fetching values
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
Labels: echoes/intent: maintenance

#17579 Use Google mirror cache registry to pull Docker images
  .circleci/configure_docker_mirrors.sh
  .circleci/jobs/features/other.yml
  docker-compose.yml
Labels: CI

#17535 PIM-10558 add new contexts to std build
  std-build/package.json
Labels: griffins, echoes/intent: maintenance

#17577 GRF-229 categories microfrontend configuration now persisting in localstorage
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/index.tsx
Labels: contribution, griffins, echoes/intent: technical

#17548 PH-13: Refresh versioning with a batch job
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/DependencyInjection/AkeneoVersioningExtension.php
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/RefreshVersioningSubscriber.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Job/JobParameters/RefreshVersioning.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Job/RefreshVersioning.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/event_subscribers.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/jobs.yml
  src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php
  src/Akeneo/Tool/Component/Connector/Step/TaskletStep.php
  upgrades/schema/Version_7_0_20220726143600_add_scheduled_jobs.php
  upgrades/test_schema/Version_7_0_20220726143600_add_scheduled_jobs_Integration.php
Labels: tech-improvement, ucs

#17566 RAC-1264: Using number_format whitout toushand separator specified will add one has comma in the value
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
Labels: contribution, echoes/effort: S, echoes/intent: maintenance

#17575 GRF-108 tab 'attributes' in category edition component
  front-packages/akeneo-design-system/src/components/Field/Field.tsx
  front-packages/akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.tsx
  src/Akeneo/Category/front/src/FakePIM.tsx
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/Style.tsx
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: contribution, griffins

#17587 PIM-10553: Fix initialization of the associations grid in product edit form
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
Labels: echoes/intent: maintenance

#17588 GRF-230: Update configuration page in microfrontend
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
Labels: griffins, echoes/intent: feature

#17561 PIM-10556: Fix cannot create a measurement attribute if measurement family or unit code is too long
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Attribute.orm.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
  upgrades/schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit.php
  upgrades/test_schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit_Integration.php
Labels: echoes/effort: S, echoes/intent: maintenance

#17586 GRF-72: Fix message on 403
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
Labels: griffins

#17457 PIM-10530: Fix case issue when querying products with attribute options
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
Labels: echoes/intent: maintenance

#17592 PIM-10572: Fix product publishing when associated to a published product with a 2-way association
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithAssociations/PersistTwoWayAssociationSubscriber.php
Labels: echoes/intent: maintenance

#17593 GRF-236: Fix FT and GE build issue
  src/Akeneo/Category/front/src/feature/legacy/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/legacy/components/EditPropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/legacy/components/StyleLegacy.tsx
Labels: griffins

#17591 GRF-217: InternalAPI to standard format
  src/Akeneo/Category/back/Application/Converter/FieldsRequirementChecker.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalAPI/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalAPI/InternalAPIToStd.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalAPI/InternalAPIToStdStub.php
  src/Akeneo/Category/back/Infrastructure/Exception/ArrayConversionException.php
  src/Akeneo/Category/back/Infrastructure/Exception/ContentArrayConversionException.php
  src/Akeneo/Category/back/Infrastructure/Exception/StructureArrayConversionException.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/converters.yml
  src/Akeneo/Category/back/tests/Specification/Application/Converter/FieldsRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Converter/InternalAPI/InternalAPIToStdSpec.php
Labels: griffins

#17605 GRF-238: The frontend build fails for FT and GE
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/components/EditPropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/Style.tsx
  src/Akeneo/Category/front/src/feature/legacy/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/legacy/components/EditPropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/legacy/components/StyleLegacy.tsx
Labels: griffins

#17595 PIM-10569: Fix associate bulk action screen for quantified associations
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
Labels: echoes/intent: maintenance

#17610 Pull up 60 into master
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
  upgrades/schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit.php
  upgrades/test_schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit_Integration.php
Labels: echoes/intent: maintenance

#17606 SP-223: Implement findAll method in InMemoryUserRepository
  tests/back/Acceptance/User/InMemoryUserRepository.php
  tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
Labels: to review, echoes/effort: XS, echoes/intent: feature

#17612 GRF-122: Add JSON value collection field for the category in the database
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  upgrades/schema/Version_7_0_20220808143128_add_value_collection_to_category.php
Labels: griffins

#17614 PIM-10574: Fix link to product page in quantified association row
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
Labels: echoes/intent: maintenance

#17618 PIM-10574: Fix link to product page in quantified association row
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
Labels: echoes/intent: maintenance

#17609 PIM-10548: Fix yaml reader does not display an error message when imported file does not contain the root level
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/readers.yml
  src/Akeneo/Tool/Component/Connector/Exception/InvalidYamlFileException.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/File/Yaml/ReaderSpec.php
Labels: echoes/intent: maintenance

#17594 PIM-10571: Fix infinite scroll of attribute group selector in family edit form
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/toolbar/add-select/attribute-group/select.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/add-select/select.js
Labels: echoes/intent: maintenance

#17632 PIM-10512: Fix empty group labels format for attribute endpoints
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Structure/Component/Normalizer/ExternalApi/AttributeNormalizer.php
  tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/ExternalApi/AttributeNormalizerSpec.php
Labels: echoes/intent: maintenance

#17637 GRF-234: Query to retrieve category information
  src/Akeneo/Category/back/Domain/Query/GetCategoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByIdentifierIntegration.php
Labels: griffins

#17634 RAC-1265: Fix error when user display the data_quality_insights_evaluations job
  src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizer.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizerSpec.php
Labels: echoes/intent: maintenance

#17616 RAB-945: migration DB
  src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
  src/Akeneo/Tool/Component/Batch/Model/JobInstance.php
  upgrades/schema/Version_7_0_20220802151250_add_automation_column_in_job_instance.php
  upgrades/test_schema/Version_7_0_20220802151250_add_automation_column_in_job_instance_integration.php
Labels: contribution, echoes/intent: feature

#17621 RAB-946: Migration code
  src/Akeneo/Tool/Component/Batch/Normalizer/Standard/JobInstanceNormalizer.php
  src/Akeneo/Tool/Component/Batch/Updater/JobInstanceUpdater.php
  src/Akeneo/Tool/Component/Batch/spec/Normalizer/Standard/JobInstanceNormalizerSpec.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
Labels: contribution, echoes/intent: feature

#17635 CXP-1245: refactor criterion registry
  components/catalogs/front/src/components/ProductSelection/components/AddCriterionDropdown.tsx
  components/catalogs/front/src/components/ProductSelection/components/Criterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/components/Criterion.tsx
  components/catalogs/front/src/components/ProductSelection/hooks/useCriteriaRegistry.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCriteriaRegistry.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindCriterionByField.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindCriterionByField.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/CriterionFactory.d.ts
Labels: echoes/intent: feature

#17652 GRF : Fix make file acceptance test and coupling test
  make-file/category.mk
  src/Akeneo/Category/back/tests/.php_cd.php
Labels: griffins

#17645 CPM-704: Fix Error 500 when trying to update multiselect value with an array containing empty string
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueFactory.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/OptionsValueFactorySpec.php
Labels: echoes/intent: maintenance

#17644 GRF-234: value_collection in the Category model
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByCode.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByCodeIntegration.php
Labels: griffins

#17547 Versionnize OS X configuration for docker
  docker-compose.override-osx.yml
Labels: echoes/effort: XS, echoes/intent: technical

#17624 PIM-10555: [Backport PIM-10462] Fix compute_family_variant_structure_…
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyVariantUpdater.php
  tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php
Labels: echoes/intent: maintenance

#17534 CXP-1239: Catalog Completeness criterion Front
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/CatalogEdit/components/EnabledInput.tsx
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.ts
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.unit.ts
  components/catalogs/front/src/components/ProductSelection/ProductSelection.tsx
  components/catalogs/front/src/components/ProductSelection/components/Criterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessLocaleInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessScopeInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/criteria/ErrorHelpers.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilyCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilyCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilyOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilySelectInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/StatusCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/StatusCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannel.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannel.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannelLocales.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannelLocales.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannelsWithSelectedChannel.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useChannelsWithSelectedChannel.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCriteriaRegistry.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCriteriaRegistry.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteChannels.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteChannels.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Channel.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
  components/catalogs/front/src/components/ProductSelection/models/CriterionErrors.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Locale.d.ts
  components/catalogs/front/tests/setup-integration.ts
  components/catalogs/front/tests/setup-unit.ts
Labels: echoes/intent: feature

#17636 PIM-10559: [Backport PIM-10478]: Disable compute_family_variant_structure_changes on familySave
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
  tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Labels: echoes/intent: maintenance

#17625 CPM-691: Remove triggers introduced during UUID migration + Clean versioning #17544
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersions.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/MigrateZddCommand.php
  tests/back/Pim/Enrichment/Integration/Product/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersionsIntegration.php
  upgrades/schema/Version_7_0_20220728121643_remove_uuid_triggers.php
  upgrades/test_schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job_Integration.php
  upgrades/test_schema/Version_7_0_20220728121643_remove_uuid_triggers_Integration.php
Labels: echoes/intent: feature

#17619 CPM-632: Allow creating products without an identifier
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductModelCompleteness.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Enrichment/CalculateProductModelCompletenessSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResult.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRows.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MissingRequiredAttributesCalculator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Model/CompletenessProductMask.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/Row.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Event/ProductWasCreated.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Event/ProductWasUpdated.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromUuidsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/CompletenessCalculatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MissingRequiredAttributesCalculatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/Model/CompletenessProductMaskSpec.php
Labels: echoes/intent: feature

#17676 Pim 10582 : Pullup 5.0 into 6.0
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
  src/Akeneo/Pim/Structure/Component/Normalizer/ExternalApi/AttributeNormalizer.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyVariantUpdater.php
  tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
  tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/ExternalApi/AttributeNormalizerSpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
  tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php
  tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Labels: echoes/intent: maintenance

#17673 PIM-10581: Fix attribute option code in linked data returned as an integer instead of a string
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
Labels: echoes/intent: maintenance

#17670 GRF-121
  src/Akeneo/Category/back/Application/Query/GetTemplate.php
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeImage.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeRichText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeTextArea.php
  src/Akeneo/Category/back/Domain/Model/Template.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCode.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeIsLocalizable.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeOrder.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeType.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeUuid.php
  src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateCode.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateUuid.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/TemplateSpec.php
Labels: griffins

#17623 PIM-10529: Fix links on product grid
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/datagrid/action/toggle-product-action.js
  src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/AjaxAction.php
  src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/DeleteAction.php
Labels: echoes/intent: maintenance

#17680 Pim 10583: Pullup 6.0 - master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Structure/Component/Normalizer/ExternalApi/AttributeNormalizer.php
  tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php
  tests/back/Pim/Structure/Specification/Component/Normalizer/ExternalApi/AttributeNormalizerSpec.php
Labels: echoes/intent: maintenance

#17622 GRF-231 internal API endpoint to GET a category for edition purpose
  make-file/category.mk
  src/Akeneo/Category/back/Api/CategoryTree.php
  src/Akeneo/Category/back/Api/Command/CommandMessageBus.php
  src/Akeneo/Category/back/Api/Command/Exceptions/ViolationsException.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetLabel.php
  src/Akeneo/Category/back/Api/GetCategoryChildrenCodesPerTreeInterface.php
  src/Akeneo/Category/back/Api/Model/Read/Category.php
  src/Akeneo/Category/back/Api/Query/GetCategoryQuery.php
  src/Akeneo/Category/back/Application/Applier/UserIntentApplier.php
  src/Akeneo/Category/back/Application/Converter/ConverterInterface.php
  src/Akeneo/Category/back/Application/Converter/FieldsRequirementChecker.php
  src/Akeneo/Category/back/Application/Converter/StandardFormatToUserIntents.php
  src/Akeneo/Category/back/Application/Filter/CategoryEditACLFilter.php
  src/Akeneo/Category/back/Application/Filter/CategoryEditUserIntentFilter.php
  src/Akeneo/Category/back/Application/GetCategoryQueryHandler.php
  src/Akeneo/Category/back/Application/Storage/ProcessCategoryUpdateMock.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeImage.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeRichText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeText.php
  src/Akeneo/Category/back/Domain/Model/Attribute/AttributeTextArea.php
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Domain/Model/Template.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/UserIntentFactoryRegistry.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeIsLocalizable.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeOrder.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeType.php
  src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/message_buses.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category.yml
  src/Akeneo/Category/back/tests/.php_cs.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/CreateCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/GetCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/PartialUpdateCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/PartialUpdateListCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/Specification/Api/Model/Read/CategorySpec.php
Labels: contribution, griffins

#17684 CPM-692: sf migration to force replaying ZDD migration
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
  upgrades/schema/Version_7_0_20221808143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table.php
  upgrades/test_schema/Version_7_0_20220802151250_add_automation_column_in_job_instance_Integration.php
  upgrades/test_schema/Version_7_0_20221808143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table_Integration.php
Labels: echoes/effort: XS, echoes/intent: feature

#17627 GRF-240: Initialize service API to list user groups
  composer.json
  make-file/user-management.mk
  src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
  src/Akeneo/UserManagement/Bundle/Resources/config/queries.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/service_api/queries.yml
  src/Akeneo/UserManagement/back/Application/Handler/ListUserGroupHandler.php
  src/Akeneo/UserManagement/back/Domain/Model/Group.php
  src/Akeneo/UserManagement/back/Domain/Storage/FindUserGroups.php
  src/Akeneo/UserManagement/back/Infrastructure/Storage/SqlFindUserGroups.php
  src/Akeneo/UserManagement/back/ServiceApi/UserGroup/ListUserGroupInterface.php
  src/Akeneo/UserManagement/back/ServiceApi/UserGroup/UserGroup.php
  src/Akeneo/UserManagement/back/ServiceApi/UserGroup/UserGroupQuery.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Storage/SqlFindUserGroupsIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/UserGroup/ListUserGroupQueryIntegration.php
Labels: wip, griffins

#17677 RAB-935: Add UpsertUser ServiceAPI
  src/Akeneo/UserManagement/Bundle/Resources/config/service_api/queries.yml
  src/Akeneo/UserManagement/Component/Model/User.php
  src/Akeneo/UserManagement/Component/Model/UserInterface.php
  src/Akeneo/UserManagement/back/Application/Handler/UpsertUserHandler.php
  src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserCommand.php
  src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserHandlerInterface.php
  src/Akeneo/UserManagement/back/ServiceApi/ViolationsException.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/UpsertUserHandlerIntegration.php
Labels: echoes/intent: feature

#17681 CXP-1245: Proposal on validation refactoring
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/MaxNumberOfCatalogsPerUser.php
  components/catalogs/back/src/Infrastructure/Validation/MaxNumberOfCatalogsPerUserValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocale.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidScope.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidScopeValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeTextCriterion/AttributeTextCriterionValuesValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CompletenessCriterion/CompletenessCriterionStructure.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CompletenessCriterion/CompletenessCriterionValuesValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionContainsScopeAndLocale.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionContainsScopeAndLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionOperatorsRequireEmptyValue.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionOperatorsRequireEmptyValueValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/FamilyCriterion/FamilyCriterionStructure.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/CompletenessCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/EnabledCriterion.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/FamilyCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeTextCriterionTest.php
Labels: echoes/intent: feature

#17685 CXP-1245: rewrite validation test with mocks on queries
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextCriterionTest.php
Labels: echoes/intent: feature

#17682 CPM-708: Define uuid during product instantiation
  src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilder.php
  src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilderInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Builder/ProductBuilderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Labels: echoes/intent: feature

#17696 OCT-107: downgrade to lcobucci 4.1.5
  composer.json
  composer.lock
Labels: echoes/intent: maintenance

#17693 OCT-89: Authenticate automatically in a microfrontend
  components/catalogs/front/src/index.tsx
  front-packages/shared/src/microfrontend/DangerousMicrofrontendAutomaticAuthenticator.ts
  front-packages/shared/src/microfrontend/index.ts
Labels: echoes/intent: technical

#17691 PIM-10587: Fix warnings count in process tracker
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetWarningCount.php
Labels: contribution, echoes/effort: S, echoes/intent: maintenance

#17669 RAB-955: Add SetPriceValue service API
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetPriceValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetPriceCollectionValueApplier.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetPriceValueApplier.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetPriceValueSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetPriceCollectionValueApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetPriceValueApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserIntentsShouldBeUniqueValidatorSpec.php
Labels: echoes/intent: feature

#17709 OCT-109: fallback to product UUID when identifier is null
  components/catalogs/back/src/Infrastructure/Persistence/GetProductIdentifiersQuery.php
Labels: echoes/intent: maintenance

#17708 PIM-10595: Fix not being able to add record with code 0 on a product
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetSimpleReferenceEntityValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetSimpleReferenceEntityValueSpec.php
Labels: echoes/intent: maintenance

#17550 CXP-1253: Added notifications to user when catalog is saved
  components/catalogs/front/src/FakeCatalogEditContainer.tsx
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Catalog/ConnectAppCatalogContainer.test.tsx
Labels: echoes/intent: feature

#17630 PIM-10566: Category versions do not appear consistently after 2022-07-27
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/form_extensions/category/edit.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/public/js/category/history.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/legacy/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/legacy/pages/HistoryPimView.tsx
  src/Akeneo/Category/front/src/feature/legacy/pages/LegacyCategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/HistoryPimView.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/config/requirejs.yml
Labels: griffins, echoes/intent: maintenance

#17713 OCT-107: Lock lcobucci/jwt version to ~4.1.5
  CHANGELOG-6.0.md
  composer.json
  composer.lock
Labels: echoes/intent: maintenance

#17717 PIM-10597: Pull-up 5.0 => 6.0
  CHANGELOG-5.0.md
Labels: griffins, echoes/intent: maintenance

#17722 PIM-10599: Pull-up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Platform/CommunityVersion.php
Labels: griffins, echoes/intent: maintenance

#17683 PIM-10584: add migration & update fixtures to fix volume flow conversion
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
  upgrades/schema/Version_7_0_20220818093018_fix_volume_flow_conversion.php
  upgrades/test_schema/Version_7_0_20220818093018_fix_volume_flow_conversion_Integration.php
Labels: contribution, echoes/effort: S, echoes/intent: maintenance

#17723 GRF-273: Fix query not returning anything when a category has no associated translations
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
Labels: griffins, echoes/intent: technical

#17724 CPM-692: Fix migration name
  upgrades/schema/Version_7_0_20220818143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table.php
  upgrades/test_schema/Version_7_0_20220818143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table_Integration.php
Labels: echoes/intent: feature

#17730 CPM-691: revert for deploy
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersions.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  tests/back/Pim/Enrichment/Integration/Product/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersionsIntegration.php
  upgrades/schema/Version_7_0_20220728121643_remove_uuid_triggers.php
  upgrades/test_schema/Version_7_0_20220728121643_remove_uuid_triggers_Integration.php
Labels: echoes/intent: feature

#17735 CPM-698: Use createFromCollection for UpsertProductCommand
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/ProductContext.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductVariantIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertQuantifiedAssociationsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/CommandMessageBusSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/AttributeGroupShouldBeEditableValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/CategoriesShouldBeViewableValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleShouldBeEditableByUserValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
Labels: echoes/intent: feature

#17728 RAB-979: Add additional properties drop zone
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/common/edit/properties.html
Labels: echoes/effort: XS, echoes/intent: feature

#17738 PIM-10601: Backport PIM-9718 on 5.0 branch
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php
Labels: echoes/intent: maintenance

#17702 PIM-10590: Fix capitalizing every first letter of attribute label in Data Quality Insights tab
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
Labels: echoes/intent: maintenance

#17725 PIM-10577: Fix PASTE event for summernote
  CHANGELOG-5.0.md
  frontend/webpack/requirejs-utils.js
  package.json
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/summernote/summernote.js
  webpack.config.js
  yarn.lock
Labels: echoes/intent: maintenance

#17736 PIM-10580: Backport PIM-10499 on 5.0 branch
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
Labels: echoes/intent: maintenance

#17701 RAB-956: Add clear price value user intent
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/ClearPriceValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/ClearPriceValueApplier.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/ClearPriceValueSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetPriceCollectionValueSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/ClearPriceValueApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/ClearValueApplierSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserIntentsShouldBeUniqueValidatorSpec.php
Labels: echoes/intent: feature

#17726 PH-172: Purge versioning batch job
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Job/JobParameters/PurgeVersioning.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Job/PurgeVersioning.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurger.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurgerInterface.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/jobs.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/purgers.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
  tests/back/Integration/catalog/technical/jobs.yml
  upgrades/schema/Version_7_0_20220823094700_add_scheduled_jobs.php
  upgrades/test_schema/Version_7_0_20220822173400_add_scheduled_jobs_Integration.php
Labels: ucs

#17746 PIM-10604: Pull-up 5.0 into 6.0
  CHANGELOG-5.0.md
  frontend/webpack/requirejs-utils.js
  package.json
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/summernote/summernote.js
  webpack.config.js
  yarn.lock
Labels: echoes/intent: maintenance

#17703 RAB-967: Write service API
  src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
  src/Akeneo/UserManagement/Bundle/Resources/config/queries.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/service_api/handler.yml
  src/Akeneo/UserManagement/back/Application/Handler/ListUserGroupHandler.php
  src/Akeneo/UserManagement/back/Application/Handler/ListUsersHandler.php
  src/Akeneo/UserManagement/back/Domain/Model/User.php
  src/Akeneo/UserManagement/back/Domain/Storage/FindUsers.php
  src/Akeneo/UserManagement/back/Infrastructure/Storage/SqlFindUsers.php
  src/Akeneo/UserManagement/back/ServiceApi/User/ListUsersHandlerInterface.php
  src/Akeneo/UserManagement/back/ServiceApi/User/User.php
  src/Akeneo/UserManagement/back/ServiceApi/User/UsersQuery.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Storage/SqlFindUsersIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/ListUsersHandlerIntegration.php
Labels: contribution, echoes/effort: S, echoes/intent: feature

#17759 RAB-974: Fix typescript error
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base-interface.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/tools/validator.ts
Labels: echoes/intent: feature

#17740 PIM-10588: Add migration to create potentially missing job instance
  CHANGELOG.md
  upgrades/schema/Version_7_0_20220824134638_add_missing_remove_completeness_for_channel_and_locale_job_instance.php
  upgrades/test_schema/Version_7_0_20220824134638_add_missing_remove_completeness_for_channel_and_locale_job_instance_Integration.php
Labels: echoes/intent: maintenance

#17762 Cxp 1247 renaming
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeBooleanCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeBooleanCriterionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeYesNoCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
Labels: echoes/intent: feature

#17733 RAB-981: Add ListUserRole service API
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUser.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Resources/config/queries.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/service_api/handler.yml
  src/Akeneo/UserManagement/back/Application/Handler/ListUserRoleHandler.php
  src/Akeneo/UserManagement/back/Domain/Model/UserRole.php
  src/Akeneo/UserManagement/back/Domain/Storage/FindAllUserRoles.php
  src/Akeneo/UserManagement/back/Infrastructure/Storage/SqlFindAllUserRoles.php
  src/Akeneo/UserManagement/back/ServiceApi/UserRole/ListUserRoleInterface.php
  src/Akeneo/UserManagement/back/ServiceApi/UserRole/UserRole.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Storage/SqlFindAllUserRolesIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/UserRole/ListUserRoleQueryIntegration.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUserSpec.php
Labels: echoes/effort: S, echoes/intent: feature

#17751 RAC-1241: Throw business exception in BaseSaver & FileStorer
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Saver/BaseSaverSpec.php
  src/Akeneo/Tool/Component/FileStorage/Exception/FileAlreadyExistsException.php
  src/Akeneo/Tool/Component/FileStorage/File/FileStorer.php
  src/Akeneo/Tool/Component/FileStorage/File/FileStorerInterface.php
  src/Akeneo/Tool/Component/StorageUtils/Exception/DuplicateObjectException.php
  src/Akeneo/Tool/Component/StorageUtils/Saver/SaverInterface.php
Labels: contribution, echoes/effort: M, echoes/intent: maintenance

#17765 OCT-113: fix DangerousMicrofrontendAutomaticAuthenticator
  front-packages/shared/src/microfrontend/DangerousMicrofrontendAutomaticAuthenticator.ts
Labels: echoes/intent: technical

#17764 PIM-10607: Only request /announcements when the panel is open
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Panel.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
Labels: echoes/intent: maintenance

#17753 CXP-1249: AttributeNumberCriterion
  components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeNumberCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeNumberCriterionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberValueInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useNumberValue.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useNumberValue.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
Labels: echoes/intent: feature

#17779 OCT-114: adds purge() to FixturesLoaderInterface
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoaderInterface.php
Labels: echoes/intent: technical

#17674 RAC: Commit rector config file
  make-file/job.mk
  make-file/measurement.mk
  make-file/test.mk
  src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionTracking.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/FindJobType/FindJobTypeHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobUser/SearchJobUserHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/FindJobTypeTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobUserTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/IntegrationTestCase.php
  src/Akeneo/Platform/Job/back/tests/rector.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/MeasurementFamilyCodeSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/UnitCodeSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Installer/MeasurementInstallerIntegration.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/rector.php
Labels: echoes/effort: XS, echoes/intent: technical

#17617 GRF-221 Add Category Update processor and query for base data and translations update
  src/Akeneo/Category/back/Api/Command/UserIntents/SetLabel.php
  src/Akeneo/Category/back/Api/Model/Read/Category.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverProcessor.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverRegistry.php
  src/Akeneo/Category/back/Application/Storage/Save/Query/UpsertCategoryBase.php
  src/Akeneo/Category/back/Application/Storage/Save/Query/UpsertCategoryTranslations.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryBaseSaver.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategorySaver.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryTranslationsSaver.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Domain/Model/Template.php
  src/Akeneo/Category/back/Domain/ValueObject/CategoryId.php
  src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/base.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/save.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/translations.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Storage/Save/CategorySaverProcessorSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Storage/Save/CategorySaverRegistrySpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
Labels: griffins, echoes/intent: technical

#17718 MW-370: PIM App store integration of the app-store-api service in the PIM
  CHANGELOG-6.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceApi.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/GetWebMarketplaceUrlEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/WebMarketplaceApiSpec.php
Labels: echoes/intent: maintenance

#17781 RAB-1003: Save ids instead of username & labels in automation parameters
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Doctrine/ORM/Repository/GroupRepository.php
  src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
  src/Akeneo/UserManagement/Component/Repository/GroupRepositoryInterface.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  src/Akeneo/UserManagement/back/Application/Handler/UpsertUserHandler.php
  src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserCommand.php
  src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/UpsertUserHandlerIntegration.php
  tests/back/Acceptance/User/InMemoryGroupRepository.php
  tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Updater/UserUpdaterSpec.php
Labels: contribution, echoes/effort: XS, echoes/intent: feature

#17792 RAB-907: Remove fallback on legacy filePath
  src/Akeneo/Tool/Component/Connector/Archiver/CsvInvalidItemWriter.php
  src/Akeneo/Tool/Component/Connector/Archiver/FileReaderArchiver.php
  src/Akeneo/Tool/Component/Connector/Archiver/XlsxInvalidItemWriter.php
  src/Akeneo/Tool/Component/Connector/Item/CharsetValidator.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractFileWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
Labels: echoes/effort: XS, echoes/intent: feature

#17761 CXP-1221 Added category criterion to catalogs
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Persistence/GetCategoriesByCodeQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetCategoryChildrenQueryInterface.php
  components/catalogs/back/src/Application/Persistence/GetCategoryTreeRootsQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCategoriesAction.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCategoryChildrenAction.php
  components/catalogs/back/src/Infrastructure/Persistence/GetCategoriesByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetCategoryChildrenQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/GetCategoryTreeRootsQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CategoriesCriterionContainsValidCategories.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CategoriesCriterionContainsValidCategoriesValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionOperatorsRequireEmptyValueValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/SystemCriterion/CategoriesCriterion.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCategoriesActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCategoryChildrenActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCategoriesByCodeQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCategoryChildrenQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCategoryTreeRootsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetChannelsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoriesActionTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoryChildrenActionTest.php
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryCriterion.integration.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryCriterion.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryOperatorInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategorySelectInput.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategorySelection.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategorySelector.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryTree.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryTreeSelector.tsx
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/factory.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/factory.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/index.ts
  components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/types.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategories.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoriesByCodes.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoriesByCodes.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoryChildren.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoryChildren.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoryTreeRoots.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useCategoryTreeRoots.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFamiliesByCodes.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindCriterionByField.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useFindCriterionByField.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSelectedTree.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSelectedTree.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useSystemCriterionFactories.unit.ts
  components/catalogs/front/src/components/ProductSelection/models/Category.d.ts
  components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
  components/catalogs/front/tests/ReactQueryWrapper.tsx
  components/catalogs/front/tests/setup-unit.ts
Labels: echoes/intent: feature

#17780 PIM-10606: Fix computeFamilyVariantStructureChange on attribute removal
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
Labels: echoes/intent: maintenance

#17795 GRF-263: Replace FindCategoryByCode and FindCategoryById by GetCategory
  src/Akeneo/Category/back/Application/Query/FindCategoryByCode.php
  src/Akeneo/Category/back/Application/Query/FindCategoryByIdentifier.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByCode.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByIdentifier.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/service_api/handler.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/base.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/translations.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByCodeIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByIdentifierIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
Labels: griffins, echoes/intent: feature

#17806 Try to fix CI
  .circleci/config.yml
  .circleci/configure_docker_mirrors.sh
  .circleci/jobs/build_and_deploy.yml
  .circleci/jobs/features/other.yml
Labels: echoes/intent: maintenance

#17804 RAB-1010: Fix storage configuration are badly validated because of CredentialsEncryption
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
Labels: echoes/intent: feature, echoes/intent: maintenance

#17796 PIM-10608: backport PIM-10584
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
  upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
  upgrades/test_schema/Version_5_0_20220830143500_fix_volume_flow_conversion_integration.php
Labels: contribution, echoes/intent: maintenance

#17799 CPM-717: Replace null bytes by empty strings in VersionBuilder
  src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
Labels: echoes/intent: maintenance

#17675 CPM-703: Handle uuids in AssociationFieldSetter
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
Labels: echoes/intent: feature

#17754 RAB-952: Add validation on scheduled job
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/validation/jobinstance.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/validators.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Validator/Constraints/DummySchedulingValidator.php
  src/Akeneo/Tool/Bundle/BatchBundle/Validator/Constraints/Scheduling.php
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Validator/Constraints/SchedulingSpec.php
Labels: echoes/intent: feature

#17750 PIM-10591: Fix download log should not be possible when job is running
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
Labels: echoes/effort: XS, echoes/intent: maintenance

#17778 GRF-235: Implement the service API to retrieve the category information
  src/Akeneo/Category/back/Api/Model/Read/Category.php
  src/Akeneo/Category/back/Application/GetCategoryQueryHandler.php
  src/Akeneo/Category/back/Application/Handler/CategoryQueryHandler.php
  src/Akeneo/Category/back/Application/Query/FindCategoryByCode.php
  src/Akeneo/Category/back/Application/Query/FindCategoryByIdentifier.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByCode.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByIdentifier.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/service_api/handler.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/base.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/translations.yml
  src/Akeneo/Category/back/ServiceApi/Category.php
  src/Akeneo/Category/back/ServiceApi/CategoryQueryInterface.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByCodeIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/SqlFindOneByIdentifierIntegration.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/CategoryQueryIntegration.php
  src/Akeneo/Category/back/tests/Specification/Api/Model/Read/CategorySpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
Labels: griffins
