Repository akeneo/pim-community-dev, pull requests merged in 2022-05, with the labels that each got.

#16944 Handle case where channel has no currency nor locale
  src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindChannels.php
Labels: contribution

#16885 fix(api-1586): update violation error message
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
  src/Akeneo/Pim/Enrichment/Component/Validator/Constraints/Type.php
  src/Akeneo/Pim/Enrichment/Component/Validator/Constraints/TypeValidator.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/FamilyRepository.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/repositories.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/Type.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/TypeValidator.php
  tests/back/Pim/Enrichment/EndToEnd/Category/ExternalApi/GetCategoryEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepositorySpec.php
Labels: contribution

#16760 PLG-469: Storage optimization - Products scores (release 2)
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/ProductScoreRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductScoreRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanProductScoresCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Repository/ProductScoreRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Symfony/Command/OneTimeTask/CleanProductScoresCommandIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  upgrades/schema/Version_7_0_20220404152647_dqi_update_pk_on_product_score.php
  upgrades/test_schema/Version_7_0_20220404152647_dqi_update_pk_on_product_score_Integration.php
Labels: weasels

#16888 OBS-78: Add support for rows with warnings in Table component
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-table-warnable-rows-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-table-warning-rows-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx
  front-packages/akeneo-design-system/src/components/Table/Table.tsx
  front-packages/akeneo-design-system/src/components/Table/TableContext.ts
  front-packages/akeneo-design-system/src/components/Table/TableHeader/TableHeader.tsx
  front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
Labels: to review

#16962 Revert "PLG-469: Storage optimization - Products scores (release 2)
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/ProductScoreRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductScoreRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanProductScoresCommand.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Repository/ProductScoreRepositoryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Symfony/Command/OneTimeTask/CleanProductScoresCommandIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
  upgrades/schema/Version_7_0_20220404152647_dqi_update_pk_on_product_score.php
  upgrades/test_schema/Version_7_0_20220404152647_dqi_update_pk_on_product_score_Integration.php
Labels: weasels

#16951 chore(api-1784): add limitation on IN filter for products
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ListProductsQueryValidator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimit.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ListProductsQueryValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimitSpec.php
Labels: contribution, API

#16979 PIM-10430: add missing translations
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.fr_FR.yml
Labels: contribution

#17015 PIM-10441 Pull Up 5.0 => 6.0
  CHANGELOG-5.0.md
  config/packages/liip_imagine.yml
  src/Akeneo/Platform/Bundle/UIBundle/Imagine/IccStripFilter.php
Labels: contribution

#17019 PIM-10442: Pull Up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  config/packages/liip_imagine.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.ru_RU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.ru_RU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.ru_RU.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/validators.ru_RU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Imagine/IccStripFilter.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.fr_FR.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilterSpec.php
Labels: contribution

#17035 WSL-30: Integration of Mekras lib open source code in CE
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Spellcheck/Dictionary/SpellerDictionary.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Spellcheck/Filter/HTMLFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Spellcheck/Filter/HTMLFilterSpec.php
Labels: weasels

#17047 WSL-13: Fix flaky integration tests
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
Labels: weasels

#17054 WSL-13: Fix flaky integration test (bis)
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Repository/ProductScoreRepositoryIntegration.php
Labels: weasels

#17044 [DNM] PIM-10439-fixing-corrupted-category-trees
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/CategoriesPool.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/Category.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/CheckCategoryTrees.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Category/Category.orm.yml
  tests/back/Pim/Enrichment/Integration/Command/Category/CheckCategoryTrees/CheckCategoryTreesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Command/Category/CheckCategoryTrees/CategorySpec.php
Labels: contribution, weasels

#17095 PIM-10457 Fixed inconsistency with column oro_user.consecutive_authentication_failure_counter when migrating from v6 to serenity
  CHANGELOG-6.0.md
  upgrades/schema/Version_6_0_20220524122443_oro_user_field_consecutive_authentication_failure_counter_is_not_nullable.php
Labels: contribution

#17129 BH-1159: Bootstrap refactoring
  config/bootstrap.php
Labels: tech-improvement
