Repository akeneo/pim-community-dev, pull requests merged in 2022-11, with the labels that each got.

#18042 CXP-1306: Disable a catalog when the product selction fails
  components/catalogs/back/src/Application/Handler/GetProductIdentifiersHandler.php
  components/catalogs/back/src/Application/Handler/GetProductUuidsHandler.php
  components/catalogs/back/src/Application/Handler/GetProductsHandler.php
  components/catalogs/back/src/Application/Persistence/Catalog/DisableCatalogQueryInterface.php
  components/catalogs/back/src/Application/Service/DispatchInvalidCatalogDisabledEventInterface.php
  components/catalogs/back/src/Application/Validation/IsCatalogValidInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/DisableCatalogQuery.php
  components/catalogs/back/src/Infrastructure/Service/DispatchInvalidCatalogDisabledEvent.php
  components/catalogs/back/src/Infrastructure/Validation/IsCatalogValid.php
  components/catalogs/back/src/ServiceAPI/Events/InvalidCatalogDisabledEvent.php
  components/catalogs/back/src/ServiceAPI/Exception/CatalogDisabledException.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductUuidsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/DisableCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/IsCatalogValidTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/features/api.feature
  tests/back/Integration/IntegrationTestsBundle/Helper/ExperimentalTransactionHelper.php
Labels: contribution, echoes/intent: feature

#18190 CPM-763: Add menu
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/form_extensions.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/public/js/controller/identifier-generator.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
Labels: echoes/intent: feature

#18051 CXP-1282: add a notifier and a subscriber
  src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/FlagAppContainingOutdatedScopesHandler.php
  src/Akeneo/Connectivity/Connection/back/Application/Apps/Notifier/AuthorizationRequestNotifierInterface.php
  src/Akeneo/Connectivity/Connection/back/Application/Apps/Notifier/DisabledCatalogNotifierInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/NotifyOnDisabledCatalogEventSubscriber.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Notifier/AuthorizationRequestNotifier.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Notifier/DisabledCatalogNotifier.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/event_subscribers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/NotifyOnDisabledCatalogEventSubscriberIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/FlagAppContainingOutdatedScopesHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Notifier/AuthorizationRequestNotifierSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Notifier/DisabledCatalogNotifierSpec.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
Labels: contribution, echoes/intent: feature

#17974 PIM-10631: increase the FOS OAuth scope column to VARCHAR(1000)
  CHANGELOG-6.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseScopeLengthQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseScopeLengthQueryIntegration.php
Labels: echoes/intent: maintenance

#18291 GRF-358: Add view template button
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
Labels: griffins, echoes/intent: feature

#18301 CXP-1282: fix test for EE
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/NotifyOnDisabledCatalogEventSubscriberIntegration.php
Labels: echoes/intent: feature

#18047 CXP-1288: Completed placeholder with an illustration and text
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/components/SourcePlaceholder.tsx
Labels: echoes/intent: feature

#18271 CPM-787: Check type of sort_order in attribute option updater
  src/Akeneo/Pim/Structure/Component/Updater/AttributeOptionUpdater.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/CreateAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/PartialUpdateAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/Specification/Component/Updater/AttributeOptionUpdaterSpec.php
Labels: echoes/intent: maintenance

#18311 GRF-358 : Fix routing declaration
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
Labels: echoes/intent: feature

#18310 Grf 289 fix event propagation after changing style applying
  front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx
  front-packages/akeneo-design-system/src/components/Table/TableActionCell/TableActionCell.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
Labels: echoes/intent: feature

#18281 RAB-973: Launch job instance ServiceAPI
  src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/GenerateJobExecutionUrlInterface.php
  src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/LaunchJobInstanceHandler.php
  src/Akeneo/Platform/Job/back/Domain/JobFileStorerInterface.php
  src/Akeneo/Platform/Job/back/Infrastructure/FileStorage/JobFileStorer.php
  src/Akeneo/Platform/Job/back/Infrastructure/Routing/GenerateJobExecutionUrl.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/File.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceResult.php
  src/Akeneo/Platform/Job/back/tests/.php_cd.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/LaunchJobInstance/LaunchJobInstanceHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/FakeJobExecution.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryCreateJobExecutionHandler.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryExecuteJobExecutionHandler.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryGenerateJobExecutionUrl.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryJobFileStorer.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/FileStorage/JobFileStorerTest.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Routing/GenerateJobExecutionUrlTest.php
  src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandlerInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandlerInterface.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/JobExecution/CreateJobExecutionHandlerIntegration.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/RefreshVersioningSubscriber.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/event_subscribers.yml
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
Labels: echoes/effort: M, echoes/intent: feature

#17783 CPM-653: do not sort on _id in ES cursors
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetUpdatedEntityIdsQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Cursor/SequentialEditProduct.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsByUuidQueryHandler.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Elasticsearch/ElasticsearchProductUuidQueryFetcher.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/Cursor.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/CursorFactory.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/FromSizeCursor.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/FromSizeCursorFactory.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/SearchAfterSizeCursor.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/SearchAfterSizeCursorFactory.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/AkeneoElasticsearchExtension.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/cursors.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorFactorySpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/FromSizeCursorFactorySpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/FromSizeCursorSpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorFactorySpec.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactorySpec.php
Labels: echoes/intent: maintenance

#18178 RAB-1125: [php 8.0 => 8.1] Fix breaking change
  composer.json
  composer.lock
  config/packages/doctrine.yml
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/RequestAppAuthenticationHandlerSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Apps/Exception/InvalidAppAuthenticationExceptionSpec.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/AsynchronousCriterionEvaluationsFilterIterator.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/ChannelLocaleCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/ProductValuesCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/RanksDistributionCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/DashboardPurgeDateCollection.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Structure/EditableAttributeFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/AbstractCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResultCursor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Model/ProductCompletenessCollection.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Model/ProductCompletenessWithMissingAttributeCodesCollection.php
  src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/AdditionalProperties.php
  src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductCreated.php
  src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductRemoved.php
  src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductUpdated.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ReadValueCollection.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/WriteValueCollection.php
  src/Akeneo/Pim/Enrichment/Product/back/Domain/PQB/ProductUuidCursor.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetAllResourceNamesQueryIntegration.php
  src/Akeneo/Tool/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Processor/Denormalization/ProcessorSpec.php
  src/Akeneo/Tool/Component/Localization/spec/Presenter/NumberPresenterSpec.php
  src/Akeneo/Tool/Component/Localization/spec/Validator/Constraints/DateFormatValidatorSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetDescendantVariantProductUuidsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductModelAssociationProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/MassEdit/AddToExistingProductModelProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Localization/Presenter/MetricPresenterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/UuidMappingSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/DateValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UrlValidatorSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
  tests/legacy/features/Context/DataGridContext.php
Labels: contribution, echoes/intent: technical

#18304 RAB-1171: Handle null Pagination object in SqlFindJobInstances
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SqlFindJobInstance.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SqlFindJobInstanceTest.php
Labels: echoes/effort: S, echoes/intent: feature

#18317 GRF-551 : Replace local selection by the catalog local on template page
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
Labels: griffins, echoes/intent: feature, echoes/intent: technical

#18320 GRF-552 : Hide the description settings panel on view template
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
Labels: griffins, echoes/intent: feature

#18325 Grf 559 : Delete Activate template button on category tree page
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
Labels: echoes/intent: feature, echoes/intent: technical

#18247 CPM-782: Create controller and rest route to GET an identifier generator
  components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
Labels: echoes/intent: feature

#18263 OCT-164: Add 'id' to connection_error ES index
  src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/ApiError.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/connection_error_mapping.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectDomainErrorFromProductEndpointEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductDomainErrorEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductValidationErrorEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/ElasticsearchBusinessErrorRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/ElasticsearchSelectLastConnectionBusinessErrorsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/PurgeConnectionErrorsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/BusinessErrorSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/TechnicalErrorSpec.php
  upgrades/schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping.php
  upgrades/test_schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping_Integration.php
Labels: echoes/intent: technical

#18267 OCT-165: Add 'id' to events_api_debug index
  src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugLogger.php
  src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Repository/EventsApiDebugRepositoryInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/events_api_debug_mapping.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/ElasticsearchEventsApiDebugRepositoryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/EventsApiDebugLoggerSpec.php
  upgrades/schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping.php
  upgrades/test_schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping_Integration.php
Labels: echoes/intent: technical

#18324 CPM-783: Add front for edit
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/controllers/Edit.tsx
  components/identifier-generator/front/src/feature/controllers/__tests__/Edit.test.tsx
  components/identifier-generator/front/src/feature/errors/IdentifierGeneratorNotFound.ts
  components/identifier-generator/front/src/feature/errors/index.ts
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useIdentifierGenerator.ts
Labels: echoes/intent: feature

#18255 CPM-781: Controller to SAVE an existing identifier generator
  components/identifier-generator/back/src/Application/Update/UpdateGeneratorCommand.php
  components/identifier-generator/back/src/Application/Update/UpdateGeneratorHandler.php
  components/identifier-generator/back/src/Domain/Exception/UnableToUpdateIdentifierGeneratorException.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Validation/UpdateGeneratorCommandValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
  components/identifier-generator/back/tests/behat.yml
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Labels: echoes/intent: feature

#18034 CPM-737: Fix brittle test
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
Labels: echoes/intent: feature

#18308 PIM-10631: Pull-up
  CHANGELOG-6.0.md
Labels: echoes/intent: maintenance

#18330 GRF-560: Sync category edition page locale with Products pages
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
Labels: griffins, echoes/intent: feature

#18302 CXP-1341: Update 200 OK - error message catalog disabled
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductUuidsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
Labels: echoes/intent: feature

#18315 GRF-534 : Reorder categories ACL
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-table-multiple-actions-correctly-1-snap.png
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Category/front/src/configuration/Page.tsx
Labels: griffins

#18306 GRF-374: Create a new controller to list the categories on the REST API
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/external_api/category.yml
Labels: griffins

#18341 RAB-301: Use shared translator in Job&Measurements
  front-packages/measurement/package.json
  front-packages/measurement/src/index.tsx
  src/Akeneo/Platform/Job/front/process-tracker/package.json
  src/Akeneo/Platform/Job/front/process-tracker/src/index.tsx
Labels: echoes/intent: technical

#18257 RAB-985: Add optional fingerprint in SFTP connection
  front-packages/akeneo-design-system/src/components/Field/Field.tsx
  front-packages/shared/src/components/TextField.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
Labels: echoes/intent: feature

#18256 CPM-751: Add generator list page
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
  components/identifier-generator/front/src/feature/components/Common.tsx
  components/identifier-generator/front/src/feature/components/Header.tsx
  components/identifier-generator/front/src/feature/components/ListSkeleton.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/controllers/List.tsx
  components/identifier-generator/front/src/feature/controllers/__tests__/List.test.tsx
  components/identifier-generator/front/src/feature/hooks/__mocks__/useIdentifierAttributes.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetGenerators.test.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useIdentifierAttributes.test.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetGenerators.ts
  components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
  components/identifier-generator/front/src/feature/pages/styles/ListPageStyled.ts
  components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx
Labels: echoes/intent: feature

#18236 CPM-714: Move GetProductUuids to Enrichment\Product\API
  src/Akeneo/Pim/Enrichment/Product/back/API/Query/GetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Cache/LRUCacheGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/IsUserOwnerOfTheProductValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetProductUuids.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Resources/config/services.yml
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/GetProductUuidsIntegration.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/Cache/LRUCacheGetProductUuidsSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
Labels: echoes/intent: feature

#18333 PIM-10689: Add sorting on ES id for product associations grid
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
Labels: echoes/intent: maintenance

#18340 PIM-10664 Hidden sub-categories from the sub category trees unless page is refreshed
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
Labels: echoes/intent: maintenance

#18294 OCT-157 GET test-apps endpoint
  src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/TestApps/Persistence/GetTestAppsQueryInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Controller/External/GetTestAppsAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Persistence/GetTestAppsQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/controllers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/persistence.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/routing.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/TestApps/Controller/External/GetTestAppsActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/TestApps/Persistence/GetTestAppsQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/TestApps/Controller/External/GetTestAppsActionSpec.php
Labels: echoes/intent: technical

#18252 RAB-1127: [php 8.0 => 8.1] update image
  .circleci/jobs/build_and_deploy.yml
  Dockerfile
  composer.json
  composer.lock
  docker-compose.yml
Labels: contribution, echoes/intent: technical

#18339 GRF-381: Create a read model / DTO to adapt the categories data for the External API format
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
Labels: griffins

#18180 PIM-10671: Fix slowness on product association page with a lot of categories
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml
Labels: echoes/intent: maintenance

#18350 pull-up 6.0 master
  CHANGELOG-6.0.md
  src/Akeneo/Category/front/src/feature/components/providers/CategoryTreeProvider.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCategoryTreeNode.ts
Labels: echoes/intent: maintenance

#18272 PH-278 : Refactor CRON job akeneo:connectivity-connection:openid-keys:create
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Command/CreateOpenIdKeysCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Job/CreateOpenIdKeysTasklet.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Connections/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221028090000_add_scheduled_job_connectivity_create_openid_keys.php
  upgrades/test_schema/Version_7_0_20221028090000_add_scheduled_job_connectivity_create_openid_keys_Integration.php
Labels: ucs, echoes/intent: technical

#18356 GRF-544 : Display template label for enriched category
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: griffins, echoes/intent: feature

#18354 Cpm 792: Structure tab in Identifier Generator
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/Structure.tsx
  components/identifier-generator/front/src/feature/tabs/__mocks__/Structure.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/Structure.test.tsx
  components/identifier-generator/front/src/feature/tabs/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__mocks__/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/AddPropertyButton.test.tsx
Labels: echoes/intent: feature

#18364 Grf 375 Create a Query (CQRS) to retrieve a list of categories
  src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Labels: echoes/intent: feature

#18358 PIM-10708: Pull-up 5.0 into 6.0
  CHANGELOG-5.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml
Labels: echoes/intent: maintenance

#18338 GRF-541 : use category template and attribute database information
  src/Akeneo/Category/back/Application/Query/GetAttribute.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/Query/GetAttributeInMemory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateUuid.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/ImagePreviewController.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemoryImpl.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/CheckTemplateSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetLabelApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#18365 SCM-103: Fix identifier-generator front build
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/controllers/Edit.tsx
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx
  components/identifier-generator/front/src/feature/tabs/Structure.tsx
Labels: echoes/intent: maintenance

#18374 OCT-169: fix migration of ES index
  upgrades/.php_cd.php
  upgrades/schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping.php
  upgrades/schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping.php
  upgrades/test_schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping_Integration.php
  upgrades/test_schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping_Integration.php
Labels: echoes/intent: maintenance

#18289 GRF-532 : Get uuids to recompute product score command
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/JobParameters/RecomputeProductScoresParameters.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RecomputeProductScoresTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/RecomputeProductsScores.php
Labels: griffins, echoes/intent: maintenance

#18273 CPM-786: Delete an identifier from front
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/form_extensions.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/ListSkeleton.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useGetGenerators.ts
  components/identifier-generator/front/src/feature/hooks/useGetGenerators.ts
  components/identifier-generator/front/src/feature/hooks/useIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/DeleteGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/EditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/DeleteGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/DeleteGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
  components/identifier-generator/front/src/feature/pages/index.ts
  components/identifier-generator/front/src/feature/pages/styles/ListPageStyled.ts
  components/identifier-generator/front/src/feature/pages/styles/index.ts
  components/identifier-generator/front/src/setupTests.tsx
  src/Akeneo/Pim/Enrichment/Product/back/Domain/StandardFormat/Validator/QuantifiedAssociationsStructureValidator.php
Labels: echoes/intent: feature

#18305 OCT-150: Update value filters translations
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: technical

#18380 PIM-10711: Fix AbstractInvalidItemWriter does not pad empty values for trailing empty column
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
Labels: echoes/intent: maintenance

#18385 PIM-10699: [SLA] "All" is exported allong with the user groups on the user export
  CHANGELOG-6.0.md
  src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
Labels: griffins, echoes/intent: maintenance

#18390 PIM-10718: Categories with empty labels throw 500 error
  CHANGELOG.md
  src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
Labels: griffins, echoes/intent: maintenance

#18397 PIM-10719: Pull-up 6.0 => master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml
  src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
Labels: echoes/intent: maintenance

#18375 RAC-1283: Fix email subject of a job notification
  src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
Labels: echoes/intent: maintenance

#18355 Grf 562 : Order attributes in Template structure page same as in the static template itself
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/createTemplate.tsx
Labels: echoes/intent: feature, echoes/intent: technical

#18357 OCT-168: Delete errors when a cirteria is removed from the product selection
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
Labels: echoes/intent: maintenance

#18367 RAB-1122: Update MySQL
  docker-compose.yml
Labels: echoes/intent: technical

#18386 RAB-1170: Upgrade elasticsearch version to 7.17.7 in order to prepare upgrade to 8
  docker-compose.yml
Labels: echoes/intent: technical

#18414 Hotfix: Fixes dompdf/dompdf CVE and update Composer dependencies
  composer.json
  composer.lock
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Doctrine/ORM/Repository/CategoryRepositorySpec.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/LocaleAndChannelShouldBeConsistentValidator.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/GetAttributes.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/InternalApi/CategoryRepositorySpec.php
Labels: echoes/intent: maintenance

#18411 CPM-804: Add real query to get next identifier
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierCommand.php
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierCommandHandler.php
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GenerateAutoNumberHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GenerateFreeTextHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GeneratePropertyHandlerInterface.php
  components/identifier-generator/back/src/Domain/Query/GetNextIdentifierQuery.php
  components/identifier-generator/back/src/Infrastructure/Query/SqlGetNextIdentifierQuery.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateAutoNumberHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFreeTextHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/Command/CleanRemovedProductsCommandEndToEnd.php
Labels: echoes/intent: feature

#18399 PIM-10714: Fix family codes are not well-saved in export filters
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/FindFamiliesController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchFamiliesByCodes.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchFamiliesByCodes.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/unit.jest.js
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php
  tests/legacy/features/pim/enrichment/product/mass-edit/change_family.feature
  upgrades/schema/Version_7_0_20221114112755_clean_family_codes_from_export_job_filters.php
  upgrades/test_schema/Version_7_0_20221114112755_clean_family_codes_from_export_job_filters_Integration.php
Labels: echoes/intent: maintenance

#18418 PIM-10725: Fix get family variant case sensitive
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/FamilyVariantController.php
  tests/back/Pim/Structure/EndToEnd/FamilyVariant/ExternalApi/GetFamilyVariantEndToEnd.php
Labels: echoes/intent: maintenance

#18200 RAB-1132: Replace swiftmailer by symfony/mailer
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/akeneo_pim_user.yml
  config/packages/behat/pim_import_export.yml
  config/packages/dev/swiftmailer.yml
  config/packages/mailer.yml
  config/packages/swiftmailer.yml
  config/packages/test_fake/swiftmailer.yml
  config/services/pim_parameters.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/Configuration.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/mail_recorder.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Test/MailRecorder.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/config/emails.yml
  src/Akeneo/Tool/Component/Email/SenderAddress.php
  src/Akeneo/Tool/Component/Email/spec/SenderAddressSpec.php
  symfony.lock
  tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php
  tests/back/UserManagement/Specification/Bundle/Notification/MailResetNotifierSpec.php
  tests/legacy/features/Context/FeatureContext.php
  tests/legacy/features/Context/WebUser.php
Labels: echoes/intent: technical

#18417 PIM-10720: Fix price versioning normalizer to round numbers
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/PriceNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/PriceNormalizerSpec.php
Labels: echoes/intent: maintenance

#18363 CPM-784: Add useSaveGenerator hook
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/hooks/__tests__/useSaveGenerator.test.tsx
  components/identifier-generator/front/src/feature/hooks/useCreateIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/hooks/useGetIdentifierGenerators.ts
  components/identifier-generator/front/src/feature/hooks/useSaveGenerator.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/EditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx
Labels: echoes/intent: feature

#18425 PIM-10724: Fix textarea template so that first break line is not cons…
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/textarea.html
Labels: echoes/intent: maintenance

#18342 GRF-200: As Sarah, I want to export enriched categories (attribute values) via the API
  src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/external_api/category.yml
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
Labels: griffins, echoes/intent: feature

#18335 CPM-684 : limit Label and code length
  components/identifier-generator/back/src/Application/Validation/ErrorList.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/tests/.php_cs.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
Labels: echoes/intent: feature

#18435 PIM-10728: fix namespace
  upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
Labels: contribution, echoes/intent: maintenance

#18438 CPM-661: Add auto number (front)
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/TranslationWithLink.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/errors/InvalidIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/hooks/useCreateIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/hooks/useSaveGenerator.ts
  components/identifier-generator/front/src/feature/models/properties/autoNumber.ts
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/Preview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertyLine.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/AutoNumberEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/FreeTextEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/AutoNumberEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/FreeTextEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/line/AutoNumberLine.tsx
  components/identifier-generator/front/src/feature/tabs/structure/line/FreeTextLine.tsx
  components/identifier-generator/front/src/feature/tabs/structure/line/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/preview/AutoNumberPreview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/FreeTextPreview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/PropertyPreview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/index.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateConditions.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateFreeText.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateIdentifierGenerator.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateIdentifierGeneratorCode.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateLabelCollection.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateTarget.test.ts
  components/identifier-generator/front/src/feature/validators/index.ts
  components/identifier-generator/front/src/feature/validators/validateConditions.ts
  components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
  components/identifier-generator/front/src/feature/validators/validateFreeText.ts
  components/identifier-generator/front/src/feature/validators/validateIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/validators/validateStructure.ts
Labels: echoes/intent: feature

#18444 CPM-663: Add reorder properties
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/Preview.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/PropertiesList.test.tsx
Labels: echoes/intent: feature

#18442 CPM-806: Add placeholder when 1st generator has been created
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
Labels: echoes/intent: feature

#18398 CPM-799: Add context to handle unsaved changes on identifier generato…
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/public/js/controller/identifier-generator.tsx
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/public/js/dependencies.ts
  components/identifier-generator/front/src/feature/components/LabelTranslations.tsx
  components/identifier-generator/front/src/feature/context/IdentifierGeneratorContext.ts
  components/identifier-generator/front/src/feature/context/useIdentifierGeneratorContext.ts
  components/identifier-generator/front/src/feature/controllers/__tests__/Edit.test.tsx
  components/identifier-generator/front/src/feature/index.ts
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/__mocks__/StructureTab.tsx
  components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts
  components/identifier-generator/front/src/index.tsx
Labels: echoes/intent: feature

#18437 CPM-816: Identifier Generator Create table to store prefixes
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  upgrades/schema/Version_7_0_20221116131232_add_prefixes_identifier_generator_table.php
  upgrades/test_schema/Version_7_0_20221116131232_add_prefixes_identifier_generator_table_Integration.php
Labels: echoes/intent: feature

#18453 PIM-10730: Fix mass actions for quantified associations rendering
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
Labels: echoes/intent: maintenance

#18416 PIM-10688: Fix error on toLocaleLowerCase for select attribute options
  CHANGELOG-6.0.md
  composer.json
  composer.lock
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
Labels: echoes/intent: maintenance

#18457 Fix version name
  src/Akeneo/Platform/CommunityVersion.php
Labels: echoes/intent: maintenance

#18456 Pull-up 5.0 to 6.0
  CHANGELOG-5.0.md
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
  upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
Labels: echoes/intent: maintenance

#18459 Pull-up 6.0 to master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
Labels: echoes/intent: maintenance

#18423 OCT-158: add test on open id public key
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/GetOpenIdPublicKeyEndToEnd.php
Labels: echoes/intent: technical

#18467 Update Help Icon for DSM
  front-packages/akeneo-design-system/src/icons/HelpIcon.tsx
Labels: design-system

#18470 GRF-266: Template attributes scopable
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemoryImpl.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/FileSystem/PreviewGenerator/BinaryImageGeneratorIntegration.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/TemplateSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
Labels: griffins, echoes/intent: feature

#18108 OCT-151: test catalogs when on launching CE CI
  .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
  .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
  components/catalogs/Makefile
  components/catalogs/back/tests/Acceptance/AuthenticationContext.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: technical

#18475 GRF-591: Use is scopable info in POST
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Attribute.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
Labels: griffins, echoes/intent: feature

#18421 CXP-1293: Add mapping to catalog save
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogErrorsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/UpdateCatalogAction.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/IsCatalogValid.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidLocale.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidScope.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidScopeValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/SystemSource/UuidSource.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/UpdateCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AbstractAttributeSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/SystemSource/UuidSourceTest.php
  components/catalogs/front/src/components/CatalogEdit/components/Edit.tsx
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.unit.ts
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingErrors.d.ts
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/models/SourceErrors.d.ts
  components/catalogs/front/src/components/ProductSelection/models/CriterionErrors.d.ts
  components/catalogs/front/src/components/ProductSelection/models/ProductSelectionValues.d.ts
Labels: wip, echoes/intent: feature

#18477 GRF-394 Add channel selector on category edit form
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
  src/Akeneo/Category/front/src/feature/components/channel/index.ts
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
Labels: echoes/intent: feature

#18405 GRF-346: Refactor Value in ValueCollection
  src/Akeneo/Category/back/Application/Applier/SetImageApplier.php
  src/Akeneo/Category/back/Application/Applier/SetRichTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextAreaApplier.php
  src/Akeneo/Category/back/Application/Converter/Checker/ValueCollectionRequirementChecker.php
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/AbstractValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/ChannelValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/ImageDataValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/ImageValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/LocaleValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextAreaValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/Value.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Validation/LocalizeValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/CategoryQueryIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/ValueCollectionRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/ImageValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextAreaValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/ValueCollectionSpec.php
Labels: griffins, echoes/intent: feature

#18486 GRF-596 Add channel on scopable attributes in Category edit form
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextAreaFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
Labels: griffins, echoes/intent: feature

#18484 GRF-592: Scopable values on back side
  src/Akeneo/Category/back/Api/Command/UserIntents/SetImage.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetRichText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetTextArea.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueImageUserIntent.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueUserIntent.php
  src/Akeneo/Category/back/Application/Applier/SetImageApplier.php
  src/Akeneo/Category/back/Application/Applier/SetRichTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextAreaApplier.php
  src/Akeneo/Category/back/Application/Converter/Checker/AttributeApiRequirementChecker.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Validation/LocalizeValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUnique.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTreeTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/ImageValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextAreaValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/ValueCollectionSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidatorSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
Labels: griffins, echoes/intent: feature

#18471 CPM-796: Add Skeleton for labels on edit/create page
  components/identifier-generator/front/src/feature/components/LabelTranslations.tsx
  components/identifier-generator/front/src/feature/components/LabelTranslationsSkeleton.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/index.ts
Labels: echoes/intent: feature

#18493 GRF-598: Fix on Category linter
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Cli/CheckCategoryTrees/CategoriesPool.php
  src/Akeneo/Category/back/Infrastructure/Cli/CheckCategoryTrees/Category.php
  src/Akeneo/Category/back/Infrastructure/Cli/CheckCategoryTrees/CheckCategoryTrees.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/CategoryAwareInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Model/Category.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Model/CategoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Repository/CategoryFilterableRepositoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Repository/CategoryRepositoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Repository/ItemCategoryRepositoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Updater/CategoryUpdater.php
  src/Akeneo/Category/back/Infrastructure/Component/Connector/ArrayConverter/FlatToStandard/Category.php
  src/Akeneo/Category/back/Infrastructure/Component/Connector/ArrayConverter/StandardToFlat/Category.php
  src/Akeneo/Category/back/Infrastructure/Component/Connector/Reader/Database/CategoryReader.php
  src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolver.php
  src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolverInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Model/Category.php
  src/Akeneo/Category/back/Infrastructure/Component/Model/CategoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Model/CategoryTranslation.php
  src/Akeneo/Category/back/Infrastructure/Component/Model/CategoryTranslationInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Normalizer/InternalApi/CategoryNormalizer.php
  src/Akeneo/Category/back/Infrastructure/Component/Normalizer/Standard/CategoryNormalizer.php
  src/Akeneo/Category/back/Infrastructure/Component/Normalizer/Versioning/CategoryNormalizer.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CreateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/ImagePreviewController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Doctrine/ORM/Repository/CategoryRepository.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/Loader/ImageLoader.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/AbstractPreviewGenerator.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/DefaultImageProvider.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/DefaultImageProviderInterface.php
  src/Akeneo/Category/back/Infrastructure/FileSystem/PreviewGenerator/PreviewGeneratorRegistry.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemoryImpl.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTemplateSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTreeTemplateSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateByCategoryTreeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreeByCategoryTemplateSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/AkeneoCategoryBundle.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/CompilerPass/RegisterCategoryItemCounterPass.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/CompilerPass/ResolveDoctrineTargetModelPass.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Form/Type/CategoryType.php
  src/Akeneo/Category/back/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/Infrastructure/Validation/LocalizeValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/.php_cs.php
Labels: griffins, echoes/intent: feature, echoes/intent: technical

#18479 SP-389: Launch job asynchronously via JobQueue
  src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/JobFileStorerInterface.php
  src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/LaunchJobInstanceHandler.php
  src/Akeneo/Platform/Job/back/Infrastructure/FileStorage/JobFileStorer.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/tests/.php_cd.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/LaunchJobInstance/LaunchJobInstanceHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryCreateJobExecutionHandler.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryExecuteJobExecutionHandler.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryJobFileStorer.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryPublishJobToQueue.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/FileStorage/JobFileStorerTest.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueueInterface.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
Labels: to review, echoes/effort: M, echoes/intent: feature

#18487 CPM-820: Add helper and disable button when properties limit is reached
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/controllers/Edit.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx
Labels: echoes/intent: feature

#18496 GRF-595: Charge attributes values per channel dynamicaly
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
Labels: griffins, echoes/intent: feature, echoes/intent: technical

#18491 RAB-1203: Remove Request::HEADER_X_FORWARDED_ALL deprecation
  public/index.php
Labels: contribution, echoes/intent: technical

#18500 DSM: Update font size label collapse
  front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx
Labels: design-system

#18492 GRF-570 : Add a non regression test on managing LabelCollection
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSqlIntegration.php
Labels: echoes/intent: feature

#18433 RAB-1202: Bump composer dev dependencies
  composer.json
  composer.lock
  src/Akeneo/Category/back/Api/CategoryTree.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeAdditionalProperties.php
  src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/Cli/CheckCategoryTrees/Category.php
  src/Akeneo/Category/back/Infrastructure/Component/Classification/Repository/ItemCategoryRepositoryInterface.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/CategoryController.php
  src/Akeneo/Category/back/ServiceApi/Category.php
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/PartialUpdateListCategoryEndToEnd.php
  src/Akeneo/Channel/back/Infrastructure/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Spellcheck/Filter/HTMLFilter.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
  src/Akeneo/Pim/Enrichment/Bundle/Widget/CompletenessWidget.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsByUuidQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
  src/Akeneo/Pim/Enrichment/Component/Product/Converter/MassOperationConverter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/MediaAttributeSetter.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Indexing/FamilyNormalizer.php
  src/Akeneo/Pim/Structure/Component/Updater/GroupTypeUpdater.php
  src/Akeneo/Platform/PimRequirements.php
  src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
  src/Oro/Bundle/ConfigBundle/DependencyInjection/SystemConfiguration/ProcessorDecorator.php
  src/Oro/Bundle/DataGridBundle/Provider/SystemAwareResolver.php
  src/Oro/Bundle/SecurityBundle/Annotation/Acl.php
  src/Oro/Bundle/SecurityBundle/Annotation/AclAncestor.php
  src/Oro/Bundle/SecurityBundle/Metadata/AclAnnotationStorage.php
  src/Oro/Bundle/SecurityBundle/Metadata/ActionMetadata.php
  src/Oro/Bundle/SecurityBundle/Metadata/EntitySecurityMetadata.php
  symfony.lock
  tests/legacy/features/Context/DataGridContext.php
Labels: echoes/intent: technical

#18366 GRF-531 : enrich category attribute values according the static template activated for the category tree
  src/Akeneo/Category/back/Application/Query/GetAttribute.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/Query/GetAttributeInMemory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateUuid.php
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/ImagePreviewController.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemoryImpl.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/CheckTemplateSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetLabelApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
  src/Akeneo/Category/front/src/feature/components/CategoryPageContent.tsx
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
  src/Akeneo/Category/front/src/index.tsx
  src/Akeneo/Category/front/src/tests/CategoryRenderHook.tsx
Labels: griffins, echoes/intent: feature

#18332 RAB-1062: Handle SFTP login with private key
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useGetPublicKey.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useGetPublicKey.ts
Labels: echoes/effort: M, echoes/intent: feature

#18509 PIM:10741: Fix diff indexation of product models
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
Labels: echoes/intent: maintenance

#17828 CPM-691: with column removal deploy env
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  tests/back/Pim/Enrichment/Integration/Product/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumnsIntegration.php
Labels: echoes/intent: feature

#18482 GRF-494: As Julia, I want to be able to enrich channel-specific values
  src/Akeneo/Category/back/Api/Command/UserIntents/SetImage.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetRichText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetTextArea.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueImageUserIntent.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueUserIntent.php
  src/Akeneo/Category/back/Application/Applier/SetImageApplier.php
  src/Akeneo/Category/back/Application/Applier/SetRichTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextAreaApplier.php
  src/Akeneo/Category/back/Application/Converter/Checker/AttributeApiRequirementChecker.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Validation/LocalizeValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUnique.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTreeTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/ImageValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextAreaValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/ValueCollectionSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidatorSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidatorSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextAreaFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
  src/Akeneo/Category/front/src/feature/components/channel/index.ts
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Attribute.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: griffins, echoes/intent: feature

#18510 GRF-577: [POC] Integrate the live avatar component in the PEF
  config/packages/framework.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/LiveblocksController.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/Liveblocks.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/LiveblocksApp.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/components/Avatar.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/liveblocks.config.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/view.ts
Labels: griffins, echoes/intent: feature

#18504 GRF-599 fix blank page on categories when manipulating channels list before it is fetched
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.test.tsx
  src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
Labels: echoes/intent: feature, echoes/intent: technical

#18506 OCT-172: clean integration tests
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAllCatalogsByOwnerActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogErrorsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteProductMappingSchemaActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductUuidsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/DeleteCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/DisableCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/FindOneCatalogByIdQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogsByOwnerUsernameQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/IsCatalogsNumberLimitReachedQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductsWithFilteredValuesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetRawProductsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: technical

#18501 CPM-828: Invalidate getGenerator on create to refresh datas
  components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
Labels: echoes/intent: feature

#18526 GRF-379: Create a position handler to decouple legacy
  src/Akeneo/Category/back/Application/Handler/GetPositionInterface.php
  src/Akeneo/Category/back/Application/Query/GetDirectChildrenCategoryCodesInterface.php
  src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolver.php
  src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolverInterface.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Handler/GetPositionHandler.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodes.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodesIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Component/Manager/PositionResolverSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Handler/GetPositionHandlerSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/managers.yml
Labels: griffins, echoes/intent: feature

#18481 PIM-10735: Assets export fails because of a failed warning messages
  CHANGELOG-6.0.md
  src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php
  src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
Labels: echoes/intent: maintenance

#18502 CPM-830: Add currentTab to location state to stay on same tab after create
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useStructureTabs.ts
  components/identifier-generator/front/src/feature/models/generatorTab.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
Labels: echoes/intent: feature

#18508 CPM-788: Add the ability to filter the product grid using Uuids
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/uuid-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#18409 PIM-10716: Fix uuids in quantified association revert version
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
Labels: echoes/intent: maintenance

#18528 OCT-175: lazy load 2 job repositories
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/jobs.yml
Labels: echoes/intent: technical

#18536 CPM-817: Add migration
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  upgrades/schema/Version_7_0_20221129093347_add_cascade_on_prefixes.php
  upgrades/test_schema/Version_7_0_20221129093347_add_cascade_on_prefixes_Integration.php
Labels: echoes/intent: feature

#18523 GRF-380: Return categories with the count of items
  src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Labels: griffins, echoes/intent: feature

#18540 Pull-up 6.0 => master
  CHANGELOG-6.0.md
  src/Akeneo/Platform/CommunityVersion.php
  src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php
  src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
Labels: echoes/intent: maintenance

#18483 CPM-791: Be able to search by UUID in the searchbar
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_identifier_or_uuid-filter.js
  src/Oro/Bundle/PimFilterBundle/Filter/Product/LabelIdentifierOrUuidFilter.php
  src/Oro/Bundle/PimFilterBundle/Resources/config/filters.yml
  src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/LabelIdentifierOrUuidFilterSpec.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelIdentifierOrUuidFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilterSpec.php
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature
Labels: echoes/intent: feature

#18454 CPM-809: Only validate identifier values
  components/identifier-generator/back/src/Application/Exception/UnableToSetIdentifierException.php
  components/identifier-generator/back/src/Domain/Exception/UnableToSetIdentifierException.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
Labels: echoes/intent: feature

#18546 CXP-1333: Get number of products selected by criteria
  components/catalogs/back/src/Application/Exception/InvalidProductSelectionCriteriaException.php
  components/catalogs/back/src/Application/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php
  components/catalogs/back/src/Infrastructure/Service/FormatProductSelectionCriteria.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryTest.php
  components/catalogs/back/tests/Unit/Infrastructure/Service/FormatProductSelectionCriteriaTest.php
Labels: echoes/intent: feature

#18468 CPM-793: Add Delimiters in strucutre tab
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__mocks__/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/DelimiterEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/DelimiterEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__mocks__/DelimiterEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/index.ts
  components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts
  components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
Labels: echoes/intent: feature

#18552 CPM-817: Add migration for column type
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  upgrades/schema/Version_7_0_20221129093347_add_cascade_on_prefixes.php
  upgrades/schema/Version_7_0_20221130130031_update_identifier_generator_prefix_number_type.php
  upgrades/test_schema/Version_7_0_20221130130031_update_identifier_generator_prefix_number_type_Integration.php
Labels: echoes/intent: feature
