Repository akeneo/pim-community-dev, pull requests merged in 2022-10, with the labels that each got.

#17898 Use APP_DEBUG env var for test Kernel
  tests/back/Integration/TestCase.php
Labels: tech-improvement

#18060 Perf groupnormalizer
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
Labels: contribution, echoes/intent: feature

#18071 PIM-10658: Fix database product reader
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
Labels: contribution, echoes/intent: maintenance

#18066 PH-272: Add a job to aggregate volume queries
  composer.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Command/AggregateVolumesCommand.php
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/DependencyInjection/PimCatalogVolumeMonitoringExtension.php
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Job/AggregateVolumeQueries.php
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/jobs.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Component/CatalogVolumeMonitoring/Volume/Service/VolumeAggregation.php
  tests/back/Platform/Specification/Component/CatalogVolumeMonitoring/Volume/Service/VolumeAggregationSpec.php
  upgrades/schema/Version_7_0_20221004093900_add_scheduled_jobs.php
  upgrades/test_schema/Version_7_0_20221004093900_add_scheduled_jobs_Integration.php
Labels: ucs

#18075 CXP-1307: Catalog aggregate
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogProductValueFiltersQueryInterface.php
  components/catalogs/back/src/Application/Persistence/Catalog/UpdateCatalogProductValueFiltersQueryInterface.php
  components/catalogs/back/src/Domain/Catalog/Catalog.php
  components/catalogs/back/src/Domain/Catalog/GetCatalogQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogProductValueFiltersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
Labels: echoes/intent: feature

#18069 OCT-149: catch unavailable mysql or ES errors and log warnings
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/commands.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Command/PurgeEventsApiLogsCommand.php
Labels: echoes/intent: technical

#18083 CXP-1313: Move Catalog DTO & QueryInterface
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogQueryInterface.php
  components/catalogs/back/src/Domain/Catalog.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
Labels: echoes/intent: feature

#18062 CPM-732: Add GetIdentifierAttributes controller and route
  components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierAttributesController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php
  composer.json
  make-file/identifier-generator.mk
  make-file/test.mk
  phpunit.xml.dist
Labels: echoes/intent: feature

#18027 PIM-10633: No DQI dashboard average rankings if code case changed
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/DashboardScoresProjectionRepositoryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetAverageRanksQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/DashboardScoresProjectionRepository.php
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/FamilyWidget.tsx
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/removers.yml
  src/Akeneo/Pim/Structure/Component/Remover/FamilyRemover.php
  tests/back/Pim/Structure/Specification/Component/Remover/FamilyRemoverSpec.php
  tests/legacy/features/pim/enrichment/product/mass-edit/change_family.feature
Labels: contribution, griffins, echoes/intent: maintenance

#18046 PIM-10652: [Backport PIM-10646] Fix export with label from a select attribute containing uppercase in its code exports code and not labels
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
Labels: echoes/intent: maintenance

#18088 GRF-496 : Migrate ACL category configuration
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl_groups.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/acl.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
Labels: chipmunks, griffins

#18086 CXP-1317: Update Internal/GetCatalogAction
  components/catalogs/back/src/Application/Exception/CatalogNotFoundException.php
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogQueryInterface.php
  components/catalogs/back/src/Domain/Catalog.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
Labels: echoes/intent: feature

#18090 CXP-1318: IsProductBelongToCatalogQuery
  components/catalogs/back/src/Application/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
Labels: echoes/intent: feature

#18037 GRF-450 fix breadcrumb in category edition page
  phpunit.xml.dist
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: contribution, griffins, echoes/intent: feature

#18070 RAB-1021: Add CreateJob ServiceApi
  src/Akeneo/Platform/Job/back/Application/CreateJobInstanceHandler.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/CreateJobInstance/CreateJobInstanceCommand.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/CreateJobInstance/CreateJobInstanceHandlerInterface.php
  src/Akeneo/Platform/Job/back/tests/.php_cd.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/CreateJobInstanceHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryJobInstanceSaver.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Command/CreateJobInstanceCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
Labels: echoes/intent: feature

#18097 GRF-497 : Add manage category template permission
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: echoes/intent: feature

#18028 CPM-728: Create IdentifierGenerator SqlRepository
  components/identifier-generator/back/src/Application/CreateGeneratorCommand.php
  components/identifier-generator/back/src/Application/CreateGeneratorHandler.php
  components/identifier-generator/back/src/Domain/Exception/UnableToFetchIdentifierGeneratorException.php
  components/identifier-generator/back/src/Domain/Exception/UnableToSaveIdentifierGeneratorException.php
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorId.php
  components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php
  components/identifier-generator/back/tests/Specification/Application/CreateGeneratorHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorIdSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/AutoNumberSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FreeTextSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
  config/services/test_fake/services.yml
  upgrades/schema/Version_7_0_20220927080024_add_identifier_generator_table.php
  upgrades/test_schema/Version_7_0_20220927080024_add_identifier_generator_table_Integration.php
Labels: echoes/intent: feature

#18101 CXP-1318: Fix integration test
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
Labels: echoes/intent: feature

#18092 GRF-450: fix breadcrumb in category edition page
  phpunit.xml.dist
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: griffins, echoes/intent: feature

#18099 CXP-1324: Updated DenyAccessUnlessGrantedTrait
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php
  components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php
Labels: echoes/intent: feature

#18100 CPM-594: Update Product creation modal
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductPdfController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/create.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/breadcrumbs.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier-regarding-family.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/MessageBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/create-helper.html
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Controller/InternalApi/ProductPdfControllerSpec.php
  tests/legacy/features/pim/enrichment/product-model/add_product_model_children.feature
  tests/legacy/features/pim/enrichment/product/create_product_and_save_added_attributes.feature
  tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_edit_and_update_attribute_history.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_and_display_all_attributes.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_and_remove_a_product.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_boolean_value.feature
  tests/legacy/features/pim/enrichment/product/pef/edit_product_and_filter_attributes.feature
  tests/legacy/features/pim/enrichment/product/versioning/display_history.feature
  tests/legacy/features/pim/enrichment/product/versioning/display_removed_value_history.feature
  tests/legacy/features/pim/enrichment/reference-data/product/display_history.feature
  tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
Labels: echoes/intent: feature

#18084 CXP-1314: Remove GetCatalogProductSelectionCriteriaQuery
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogProductSelectionCriteriaQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogProductSelectionCriteriaQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogProductSelectionCriteriaQueryTest.php
Labels: echoes/intent: feature

#18102 GRF-500 : Add new category order trees permission
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: echoes/intent: feature

#18118 CXP-1327: Fix GetUserIdByUsernameQuery
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Infrastructure/Persistence/User/GetUserIdFromUsernameQuery.php
Labels: echoes/intent: feature

#18117 GRF-503
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
Labels: griffins, echoes/intent: feature

#18073 CPM-732: Add IdentifierAttributeSelector
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/jest.unit.js
  components/identifier-generator/front/package.json
  components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
  components/identifier-generator/front/src/feature/__tests__/IdentifierGeneratorApp.test.tsx
  components/identifier-generator/front/src/feature/components/IdentifierAttributeSelector.tsx
  components/identifier-generator/front/src/feature/components/__tests__/IdentifierAttributeSelector.test.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useIdentifierAttributes.test.tsx
  components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts
  components/identifier-generator/front/src/feature/models/flatten-attribute.d.ts
  components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx
  components/identifier-generator/front/src/feature/tests/test-utils.tsx
  components/identifier-generator/front/src/index.tsx
Labels: echoes/intent: feature

#18087 GRF-102: Add ACL "Edit category attributes"
  src/Akeneo/Category/back/Application/Filter/CategoryEditACLFilter.php
  src/Akeneo/Category/back/Application/Filter/CategoryEditAclFilter.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/filters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Category/back/tests/Specification/Application/Filter/CategoryEditAclFilterSpec.php
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: griffins, echoes/intent: feature

#18120 CXP-1321: Use Catalog Agg in GetProductsQuery
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Handler/GetProductsHandler.php
  components/catalogs/back/src/Application/Persistence/Catalog/Product/GetProductsQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsQuery.php
  components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php
  components/catalogs/back/src/ServiceAPI/Exception/CatalogNotFoundException.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductsQueryTest.php
Labels: echoes/intent: feature

#18116 GRF-502
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
Labels: echoes/intent: feature

#18130 PIM-10667: Fix product import when measurement contains line break
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
Labels: echoes/intent: maintenance

#18072 Cpm 752 : [back] Functional validation
  components/identifier-generator/back/src/Application/CreateGeneratorHandler.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Exception/ViolationsException.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Validation/IdentifierGeneratorCreationLimit.php
  components/identifier-generator/back/src/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifier.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifierValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldExist.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldExistValidator.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/.php_cs.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/Specification/Application/CreateGeneratorHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/DelimiterSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorCodeSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorIdSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/AutoNumberSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FreeTextSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/TargetSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifierValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/TargetAttributeShouldExistValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
Labels: echoes/intent: feature

#18129 CXP-1322: Use Catalog Agg in GetProductUuidsQuery
  components/catalogs/back/src/Application/Handler/GetProductUuidsHandler.php
  components/catalogs/back/src/Application/Handler/GetProductsHandler.php
  components/catalogs/back/src/Application/Persistence/Catalog/Product/GetProductUuidsQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
Labels: echoes/intent: feature

#18132 PIM-10669: The next 20 attributes are not displayed if you do not scroll the list
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
Labels: contribution, echoes/effort: XS, echoes/intent: maintenance

#18091 PIM-10651: replace a technical exception by a new business exception
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
  src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Component/Product/Exception/InvalidAssociationProductIdentifierException.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifierSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Exception/InvalidAssociationProductIdentifierExceptionSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
Labels: echoes/intent: maintenance

#18050 PIM-10655: Fix format of empty completeness in external API
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizerSpec.php
Labels: echoes/intent: maintenance

#18045 OCT-136: Migrate from `justinrainbow/json-schema` to `opis/json-schema` the MeasureBundle
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyCommonStructureValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php
  src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchemaErrorsFormatter.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidatorSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchemaErrorsFormatterSpec.php
  src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/SaveMeasurementFamiliesActionEndToEnd.php
Labels: echoes/intent: technical

#18145 CPM-761 : Forbid creation or update of an attribute called "uuid"
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQueryIntegration.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
Labels: echoes/intent: feature

#18149 Remove duplicated entry in composer.json's autoload-dev
  composer.json
Labels: echoes/intent: maintenance

#18155 OCT-156: add Catalog.svg to the DSM storybook
  front-packages/akeneo-design-system/src/illustrations/CatalogsIllustration.tsx
  front-packages/akeneo-design-system/src/illustrations/index.ts
  front-packages/akeneo-design-system/static/illustrations/Catalogs.svg
Labels: echoes/intent: technical

#18147 OCT-155: order catalog products by uuid
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: maintenance

#18152 PIM-10680: pull up 5.0->6.0
  CHANGELOG-5.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
  src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Component/Product/Exception/InvalidAssociationProductIdentifierException.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifierSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Exception/InvalidAssociationProductIdentifierExceptionSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
Labels: echoes/intent: maintenance

#18135 CXP-1295: Endpoint PUT product mapping schema
  components/catalogs/back/src/Application/Handler/GetProductMappingSchemaHandler.php
  components/catalogs/back/src/Application/Handler/UpdateProductMappingSchemaHandler.php
  components/catalogs/back/src/Application/Storage/CatalogsMappingStorageInterface.php
  components/catalogs/back/src/Domain/Catalog.php
  components/catalogs/back/src/Infrastructure/Controller/Public/UpdateProductMappingSchemaAction.php
  components/catalogs/back/src/Infrastructure/Storage/CatalogsMappingStorage.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductSchema.php
  components/catalogs/back/src/ServiceAPI/Command/UpdateProductMappingSchemaCommand.php
  components/catalogs/back/src/ServiceAPI/Query/GetProductMappingSchemaQuery.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateProductMappingSchemaActionTest.php
  components/catalogs/features/api.feature
Labels: echoes/intent: feature

#18119 Cpm 756 : Fix coupling in Application namespace
  components/identifier-generator/back/src/Application/CommandInterface.php
  components/identifier-generator/back/src/Application/Create/CreateGeneratorCommand.php
  components/identifier-generator/back/src/Application/Create/CreateGeneratorHandler.php
  components/identifier-generator/back/src/Application/Exception/ViolationsException.php
  components/identifier-generator/back/src/Application/Validation/CommandValidatorInterface.php
  components/identifier-generator/back/src/Application/Validation/Error.php
  components/identifier-generator/back/src/Application/Validation/ErrorList.php
  components/identifier-generator/back/src/Infrastructure/Exception/ViolationsException.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Validation/CreateGeneratorCommandValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifierValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldExistValidator.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/.php_cs.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Create/CreateGeneratorHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifierValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/TargetAttributeShouldExistValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  composer.json
Labels: echoes/intent: feature

#18159 PIM-10678: fix not working test
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/UuidFilterIntegration.php
Labels: echoes/intent: maintenance

#18136 CXP-1284: Endpoint GET product mapping schema
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductMappingSchemaAction.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductMappingSchemaActionTest.php
  components/catalogs/features/api.feature
Labels: echoes/intent: feature

#18146 PIM-10670: Fix memory leak on creating combinations for currencies
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
Labels: echoes/intent: maintenance

#18150 RAB-1130: Replace box/spout by openspout/openspout
  composer.json
  composer.lock
  src/Akeneo/Tool/Component/Connector/Reader/File/FlatFileIterator.php
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/FlatItemBufferFlusherSpec.php
  symfony.lock
  tests/back/Pim/Structure/Integration/Family/ImportFamilyIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
  tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php
  tests/legacy/features/Behat/Context/Domain/ImportExportContext.php
  tests/legacy/features/Behat/Context/Domain/Spread/XlsxFileContext.php
Labels: echoes/intent: technical

#18166 Pim 10679
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
Labels: echoes/intent: maintenance

#18125 GRF-501 : Add condition to select rights for ordering categories depe…
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Labels: griffins, echoes/intent: feature

#18165 CPM-755: [New API endpoints] Product versioning
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizerSpec.php
Labels: echoes/intent: feature

#18175 PIM-10662 Pull-up 6.0 to Master
  CHANGELOG-5.0.md
  CHANGELOG-6.0.md
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.pt_BR.yml
  src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Exception/InvalidAssociationProductIdentifierException.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.pt_BR.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.pt_BR.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.sv_SE.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pt_BR.yml
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifierSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Exception/InvalidAssociationProductIdentifierExceptionSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
  tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
  tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
Labels: echoes/intent: maintenance

#17951 PIM-10644: Fix identifier format check on multiple product update
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
Labels: echoes/intent: maintenance

#18067 CPM-632: Use Enrichment cursors
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/SequentialEditController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cursors.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/cursors.yml
Labels: echoes/intent: feature

#18183 CPM-735: Save on frontend
  components/identifier-generator/back/src/Application/Validation/ErrorList.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/LabelTranslations.tsx
  components/identifier-generator/front/src/feature/components/__tests__/IdentifierAttributeSelector.test.tsx
  components/identifier-generator/front/src/feature/controllers/Edit.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useIdentifierAttributes.test.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useUiLocales.test.tsx
  components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts
  components/identifier-generator/front/src/feature/hooks/useUiLocales.ts
  components/identifier-generator/front/src/feature/models/conditions.ts
  components/identifier-generator/front/src/feature/models/flatten-attribute.ts
  components/identifier-generator/front/src/feature/models/identifierGenerator.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/properties/autoNumber.ts
  components/identifier-generator/front/src/feature/models/properties/freeText.ts
  components/identifier-generator/front/src/feature/models/structure.ts
  components/identifier-generator/front/src/feature/models/ui-locale.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/EditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGenerator.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/index.ts
  components/identifier-generator/front/src/feature/validators/Violation.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateIdentifierGenerator.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts
  components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
  components/identifier-generator/front/src/feature/validators/validateStructure.ts
  components/identifier-generator/front/src/setupTests.tsx
Labels: echoes/intent: feature

#18148 PIM-10677: Fix job still shows under in progress when failed
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Job/back/Infrastructure/Clock/ClockInterface.php
  src/Akeneo/Platform/Job/back/Infrastructure/Clock/SystemClock.php
  src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/JobExecutionRowHydrator.php
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
Labels: echoes/effort: S, echoes/intent: maintenance

#18168 CPM-736 : Patch multiple : UUID is mandatory
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
Labels: echoes/intent: feature

#18205 PH-428: Fix pim_volume_monitoring.step.aggregate_volume_queries definition
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/jobs.yml
Labels: ucs

#18203 CPM-771: Fix product creation without sku
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
Labels: echoes/intent: feature

#18176 PIM-10673: Added default port to router request context
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/PimFrameworkBundle.php
Labels: echoes/intent: maintenance

#18207 CPM-766: Fix duplicate to allow empty identifier
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier.js
Labels: echoes/intent: feature

#18123 CXP-1323 GET catalogs/{id}/products/{uuid}
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Handler/GetProductHandler.php
  components/catalogs/back/src/Application/Persistence/Catalog/Product/GetProductQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/ServiceAPI/Exception/ProductNotFoundException.php
  components/catalogs/back/src/ServiceAPI/Query/GetProductQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductQueryTest.php
Labels: echoes/intent: feature

#18189 CPM-735: Fix react-query cache config
  components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
  components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts
  components/identifier-generator/front/src/feature/hooks/useUiLocales.ts
Labels: echoes/intent: feature

#18209 PH-419: Release job lock in watchdog
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Manager/JobExecutionManager.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
Labels: ucs

#18186 CXP-1338: Product mapping schema - 404 not found error instead of 500
  components/catalogs/back/src/Application/Handler/DeleteProductMappingSchemaHandler.php
  components/catalogs/back/src/Application/Handler/GetProductMappingSchemaHandler.php
  components/catalogs/back/src/Application/Handler/UpdateProductMappingSchemaHandler.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductMappingSchemaAction.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductMappingSchemaActionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: feature

#18210 CPM-773: Update MessageBox BEM to DSM style
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/CategoryModal/CategoryModal.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/MessageBox.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/create-helper.html
Labels: echoes/intent: feature

#18211 Cpm 776: Fix converting variant product into simple
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
Labels: echoes/intent: feature

#18223 GRF-289: Create model CategoryTree and service GetCategoryTreesSql
  src/Akeneo/Category/back/Domain/Model/Category.php
  src/Akeneo/Category/back/Domain/Model/CategoryTree.php
  src/Akeneo/Category/back/Domain/Query/GetCategoryTreesInterface.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreesSqlIntegration.php
Labels: griffins, echoes/intent: feature

#18227 Add HTMLTableCellElement on ActionCell Component
  front-packages/akeneo-design-system/src/components/Table/TableActionCell/TableActionCell.tsx
Labels: griffins, echoes/intent: feature

#18228 PH-269: Extract `akeneo:connectivity-audit:update-data` logic
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/UpdateAuditData.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/commands.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/services.yml
Labels: ucs

#17101 BH-1056: Upgrade phpseclib to v3.0
  composer.json
  composer.lock
  config/openssl.cnf
  config/services/pim_parameters.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AsymmetricKeysGenerator.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/AsymmetricKeysGeneratorSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/openssl.cnf
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriber.php
  symfony.lock
  upgrades/.php_cd.php
  upgrades/schema/Version_6_0_20211214000000_add_openid_keys_into_pim_configuration.php
Labels: echoes/effort: S, echoes/intent: technical

#18231 GRF-511
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplateIndex.tsx
  src/Akeneo/Category/front/src/feature/pages/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
Labels: griffins, echoes/intent: feature, echoes/intent: maintenance

#18234 PH-269: Add `update_audit_data` scheduled job
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Job/UpdateAuditDataTasklet.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221026090000_add_scheduled_job_update_audit_data.php
  upgrades/test_schema/Version_7_0_20221026090000_add_scheduled_job_update_audit_data_Integration.php
Labels: ucs

#18243 GRF-289: Update models
  src/Akeneo/Category/back/Application/Applier/SetImageApplier.php
  src/Akeneo/Category/back/Application/Applier/SetLabelApplier.php
  src/Akeneo/Category/back/Application/Applier/SetRichTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextApplier.php
  src/Akeneo/Category/back/Application/Applier/SetTextAreaApplier.php
  src/Akeneo/Category/back/Application/Applier/UserIntentApplier.php
  src/Akeneo/Category/back/Application/Query/GetTemplate.php
  src/Akeneo/Category/back/Application/Storage/ProcessCategoryUpdateMock.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverProcessor.php
  src/Akeneo/Category/back/Application/Storage/Save/Query/UpsertCategoryBase.php
  src/Akeneo/Category/back/Application/Storage/Save/Query/UpsertCategoryTranslations.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryBaseSaver.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategorySaver.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryTranslationsSaver.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTreeTemplate.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Template.php
  src/Akeneo/Category/back/Domain/Query/GetCategoryInterface.php
  src/Akeneo/Category/back/Domain/Query/GetCategoryTreesInterface.php
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetTemplateInMemory.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetLabelApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/Storage/Save/CategorySaverProcessorSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/TemplateSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
Labels: griffins, echoes/intent: feature

#18185 CXP-1280: Manage option/category deletion in the product selection
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogErrorsAction.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogErrorsActionTest.php
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogErrors.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogErrors.unit.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useAttributeOptionsByCodes.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useAttributeOptionsByCodes.unit.ts
Labels: echoes/intent: feature

#18242 RAB-1163: Return JobInstance read model in FindJobInstance query
  src/Akeneo/Platform/Job/back/Infrastructure/Query/SqlFindJobInstance.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQuery.php
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SqlFindJobInstanceTest.php
Labels: echoes/intent: feature

#18163 GRF-371: Display category templates column and hide it where there is no template
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/tests/provideCategoryHelper.ts
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/listTree.json.twig
  src/Akeneo/Pim/Enrichment/Bundle/Twig/CategoryExtension.php
  tests/back/Pim/Enrichment/Specification/Bundle/Twig/CategoryExtensionSpec.php
Labels: griffins, echoes/intent: feature

#18235 CPM-779: Allow uppercase in uuid inputs
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/product.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsByUuidQueryHandler.php
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductsWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
Labels: echoes/intent: feature

#18226 PH-271: Refactor CRON job akeneo:connectivity-audit:purge-error-count
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Job/PurgeAuditErrorTasklet.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Connections/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221025104400_add_scheduled_jobs_connectivity_audit_purge_error.php
  upgrades/test_schema/Version_7_0_20221025104400_add_scheduled_jobs_connectivity_audit_purge_error_Integration.php
Labels: ucs

#18167 RAB-1137: Upgrade openspout/openspout to v4
  composer.json
  composer.lock
  src/Akeneo/Tool/Component/Connector/Reader/File/FlatFileIterator.php
  src/Akeneo/Tool/Component/Connector/Reader/File/SpoutReaderFactory.php
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
  src/Akeneo/Tool/Component/Connector/Writer/File/SpoutWriterFactory.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/FlatItemBufferFlusherSpec.php
  tests/back/Pim/Structure/Integration/Family/ImportFamilyIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserGroupIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
  tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php
  tests/legacy/features/Behat/Context/Domain/ImportExportContext.php
  tests/legacy/features/Behat/Context/Domain/Spread/XlsxFileContext.php
Labels: echoes/intent: technical

#18214 PH-273: Add a job to schedule periodic tasks
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/SchedulePeriodicTasksTasklet.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  upgrades/schema/Version_7_0_20221024171500_add_scheduled_jobs.php
  upgrades/test_schema/Version_7_0_20221024171500_add_scheduled_jobs_Integration.php
Labels: ucs

#18258 CPM-594 fix category tests
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
Labels: echoes/intent: feature

#18191 PIM-10672: Command to create/add roles with all existing permissions
  src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Component/Connector/RoleWithPermissions.php
  src/Akeneo/UserManagement/Component/Updater/RoleWithPermissionsUpdater.php
  src/Akeneo/UserManagement/back/Application/Exception/UnknownUserRole.php
  src/Akeneo/UserManagement/back/Application/RestoreAdminRolePermissions.php
  src/Akeneo/UserManagement/back/Infrastructure/Cli/RestoreAdminRolePermissionsCommand.php
  src/Akeneo/UserManagement/back/tests/Integration/Application/RestoreAdminRolePermissionsIntegration.php
Labels: griffins, echoes/intent: maintenance

#18245 PIM-10674: Add possibility to send a loading method on Card component
  front-packages/akeneo-design-system/src/components/Card/Card.tsx
  front-packages/akeneo-design-system/src/components/Card/Card.unit.tsx
Labels: echoes/intent: maintenance

#18264 PIM-10686: Fix percentage of inaccurate completeness in the activity dashboard
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/convertBackendDashboardCompletenessData.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/tests/front/unit/helpers/convertBackendDashboardCompletenessData.unit.ts
Labels: echoes/intent: maintenance

#18229 GRF-296: As Julia, I want to go on managing simple categories
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/InMemory/GetTemplateInMemoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/tests/provideCategoryHelper.ts
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/listTree.json.twig
  src/Akeneo/Pim/Enrichment/Bundle/Twig/CategoryExtension.php
  tests/back/Pim/Enrichment/Specification/Bundle/Twig/CategoryExtensionSpec.php
Labels: griffins, echoes/intent: feature

#18274 GRF-491: Have category edition page locale be in sync with the catalog locale
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
Labels: griffins, echoes/intent: feature

#18280 CPM-767: Fix Product Connector for associations without sku
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
Labels: echoes/intent: feature

#18244 CPM-780: Controller to list Identifier Generators
  components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Controller/ListIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ListIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
Labels: echoes/intent: feature

#18285 GRF-539 plug template attribute saver to activateTemplate process
  src/Akeneo/Category/back/Application/ActivateTemplate.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/template.yml
  src/Akeneo/Category/back/tests/Integration/Application/ActivateTemplateIntegration.php
Labels: echoes/intent: technical

#18279 GRF-513 : Template form
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplate.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature

#18196 PIM-10683: Fix performance regression in CSV and XLSX product and pro…
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/LRUCachedGetAttributes.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/GetAttributes.php
  tests/back/Acceptance/Attribute/InMemoryGetAttributes.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
Labels: echoes/intent: maintenance
