Repository akeneo/pim-community-dev, pull requests merged in 2023-04, with the labels that each got.

#19504 OCT-232: add tests and refacto
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
Labels: echoes/intent: technical

#19474 RAB-1280: Update unitary attribute group deletion modal
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/DeleteAttributeGroupModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useDeleteAttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/DeleteAttributeGroupModal.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useDeleteAttributeGroup.unit.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/delete.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/delete.tsx
  tests/legacy/features/pim/structure/attribute-group/delete_attribute_group.feature
Labels: echoes/intent: feature

#19537 Pull up 7.0 into master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/messages.en_AU.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_AU.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_AU.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_AU.yml
  src/Akeneo/Channel/back/API/Query/GetCaseSensitiveChannelCodeInterface.php
  src/Akeneo/Channel/back/API/Query/GetCaseSensitiveLocaleCodeInterface.php
  src/Akeneo/Channel/back/Infrastructure/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/messages.en_AU.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/validators.en_AU.yml
  src/Akeneo/Channel/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_AU.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/translations/validators.en_AU.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_AU.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_AU.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_AU.yml
  tests/back/Channel/Specification/Infrastructure/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
Labels: echoes/intent: maintenance

#19425 PIM-10889 : Update the category updated at on update category
  CHANGELOG.md
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryTranslationsSaver.php
  src/Akeneo/Category/back/Domain/Query/UpdateCategoryUpdatedDate.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/Update/UpdateCategoryUpdatedDateSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/translations.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/Update/UpdateCategoryUpdatedDateSqlIntegration.php
Labels: griffins, echoes/intent: maintenance

#19524 CXP-1454: Map status (boolean)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Boolean/BooleanFromStatusValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeStatusSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Boolean/BooleanFromStatusValueExtractorTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeStatusSourceTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts
  components/catalogs/front/src/hooks/useAttribute.ts
  components/catalogs/front/src/hooks/useSystemAttributes.ts
  components/catalogs/front/src/hooks/useSystemAttributes.unit.ts
Labels: echoes/intent: feature

#19490 PIM-10908: Add zdd migration to add an index on akeneo_file_storage_file_info
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/FileStorageBundle/Command/V20230324153137AddIndexOnFileInfoZddMigration.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/model/doctrine/FileInfo.orm.yml
  tests/back/Tool/Integration/FileStorage/Command/V20230324153137AddIndexOnFileInfoZddMigrationIntegration.php
Labels: echoes/intent: maintenance

#19547 RAB-1369: Initialize AkeneoInstallerBundle
  .php_cs.php
  composer.json
  config/bundles.php
  config/services/test_fake/services.yml
  make-file/installer.mk
  make-file/test.mk
  phpspec.yml.dist
  src/Akeneo/Platform/Installer/back/src/Application/InstallPim/InstallFixtures.php
  src/Akeneo/Platform/Installer/back/src/Application/InstallPim/InstallPimHandler.php
  src/Akeneo/Platform/Installer/back/src/Domain/.gitkeep
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Fixtures/FixturesInstaller.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/AkeneoInstallerBundle.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoInstallerExtension.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/fixtures.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
  src/Akeneo/Platform/Installer/back/tests/.php_cs.src.php
  src/Akeneo/Platform/Installer/back/tests/.php_cs.tests.php
  src/Akeneo/Platform/Installer/back/tests/Acceptance/FakeServices/InMemoryFixturesInstaller.php
  src/Akeneo/Platform/Installer/back/tests/Acceptance/Resources/config/fake_services.yml
  src/Akeneo/Platform/Installer/back/tests/Acceptance/UseCases/InstallPim/InstallPimTest.php
  src/Akeneo/Platform/Installer/back/tests/Integration/DummyTest.php
  src/Akeneo/Platform/Installer/back/tests/Specification/Application/InstallPim/InstallPimHandlerSpec.php
  src/Akeneo/Platform/Installer/back/tests/phpstan.neon
  src/Akeneo/Platform/Installer/back/tests/phpunit.xml
  src/Akeneo/Platform/Installer/back/tests/rector.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
Labels: echoes/intent: feature

#19556 CPM-702: Improves number comparison
  src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Value/ScalarValueSpec.php
Labels: echoes/intent: technical

#19551 CPM-1035: Several identifiers - update wording helper for deployment
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#19555 RAB-1378: Attribute group unitary delete
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/AttributeGroupSecondaryActions.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/DeleteAttributeGroupModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/AttributeGroupSecondaryActions.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/DeleteAttributeGroupModal.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/secondary-actions.tsx
  tests/legacy/features/Behat/Decorator/Common/DropdownMenuDecorator.php
Labels: echoes/intent: feature

#19568 RAB: Fix constraints for bulk delete attributes
  src/Akeneo/Pim/Structure/Bundle/Resources/config/job_constraints.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
Labels: echoes/intent: feature, echoes/effort: XS

#19549 GRF-793 Add attribute settings panel in edit template page
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttributeOnTemplatePage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19510 CXP-1411: Map asset collection attributes > media file (string + URI)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/StringUri/StringUriFromAssetCollectionMediaFileAttributeValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
Labels: echoes/intent: feature

#19569 SP-463: add labels in GetAttributes public API
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
  tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php
Labels: echoes/intent: feature

#19566 SP-489: Add attribute codes in `SqlGetFamilies` query of `Structure` context public Api
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetFamilies.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/Family.php
  tests/back/Pim/Structure/Integration/Family/SqlGetFamilyIntegration.php
Labels: echoes/intent: feature

#19574 PIM-10925: The search by code is missing on the attribute page
  CHANGELOG.md
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/AttributeFilter.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/FilterBundle/Datasource/ExpressionBuilderInterface.php
  src/Oro/Bundle/FilterBundle/Datasource/Orm/OrmExpressionBuilder.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  tests/legacy/features/pim/structure/attribute/browse/filter.feature
Labels: echoes/intent: maintenance

#19552 OCT-240: Link to fix - There is no catalog
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/CatalogList/CatalogList.integration.tsx
  components/catalogs/front/src/components/CatalogList/components/Empty.tsx
  components/catalogs/front/src/components/ProductSelection/components/Empty.tsx
Labels: echoes/intent: maintenance

#19562 PIM-10922: Update dompdf library
  CHANGELOG-6.0.md
  composer.json
  composer.lock
Labels: echoes/intent: maintenance

#19553 OCT-238: Link to fix - create an app screen
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppForm.tsx
Labels: echoes/intent: maintenance

#19588 GROWTH-71: Remove feature from non executed phpspecs script
  .circleci/find_non_executed_phpspec.sh
Labels: butterfly

#19545 RAB-1330: DSM component: tiles
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-tiles-inline-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-tiles-size-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.stories.mdx
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.tsx
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.unit.tsx
Labels: contribution, echoes/intent: feature

#19532 PIM-10911: Add user-agent when sending an event
  CHANGELOG.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/services.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/RequestHeaders.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php
Labels: echoes/intent: maintenance

#19422 PIM-10885: Fix wrong flag for Réunion
  CHANGELOG.md
  front-packages/shared/src/components/LocaleSelector.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.tsx
  tests/legacy/features/Behat/Context/Domain/Spread/ExportBuilderContext.php
  tests/legacy/features/Behat/Decorator/ContextSwitcherDecorator.php
  tests/legacy/features/Behat/Decorator/ReactContextSwitcherDecorator.php
  tests/legacy/features/Context/Page/Base/Grid.php
  tests/legacy/features/Context/Page/Product/Edit.php
  tests/legacy/features/Context/Page/Product/Index.php
  tests/legacy/features/Context/Page/ProductGroup/Edit.php
  tests/legacy/features/Context/Page/ProductModel/Edit.php
Labels: echoes/intent: maintenance

#19596 CPM-1054: Fix 500 error when entities not found
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
Labels: echoes/intent: feature

#19573 OCT-243: Error when we select a property source and fill a Default value
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySource.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySourceTest.php
Labels: echoes/intent: maintenance

#19559 OCT-235: Display the default value in the target table
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/DefaultValue.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/DefaultValue.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation/SourceDefaultValue.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation/SourceLabel.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation/TargetPlaceholder.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation/TargetSourceAssociation.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation/TargetSourceAssociation.tsx
  components/catalogs/front/src/components/ProductMapping/models/Source.d.ts
Labels: echoes/intent: maintenance

#19595 GRF-816 Display values of attribute settings on readonly
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetActivatedLocalesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/catalog.yml
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/GetActivatedLocalesControllerEndToEnd.php
Labels: echoes/intent: feature

#19536 PIM-10887 : Prevent channel creation on validation error during import
  CHANGELOG.md
  src/Akeneo/Channel/back/Infrastructure/Component/Model/Channel.php
  src/Akeneo/Channel/back/Infrastructure/Component/Model/Locale.php
  src/Akeneo/Channel/back/Infrastructure/Component/Model/LocaleInterface.php
  src/Akeneo/Channel/back/Infrastructure/Component/Updater/ChannelUpdater.php
  src/Akeneo/Channel/back/Infrastructure/EventListener/ChannelLocaleSubscriber.php
  src/Akeneo/Channel/back/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriber.php
  src/Akeneo/Channel/back/Infrastructure/Processor/Denormalization/ChannelProcessor.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/doctrine/model/Locale.orm.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/processors.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Channel/back/tests/Integration/ChannelTestCase.php
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Processor/Denormalization/ChannelProcessorSpec.php
  tests/back/Acceptance/Channel/ChannelContext.php
  tests/back/Acceptance/Locale/LocaleContext.php
  tests/back/Channel/Specification/Infrastructure/Component/Updater/ChannelUpdaterSpec.php
  tests/back/Channel/Specification/Infrastructure/EventListener/ChannelLocaleSubscriberSpec.php
  tests/back/Channel/Specification/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriberSpec.php
  tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
  tests/features/channel/locale/locale_status.feature
Labels: echoes/intent: maintenance

#19589 PIM-10916 : Fix external categories endpoint with_position always return 1
  CHANGELOG.md
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19594 PIM-10929: Add limit on get product history
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/VersioningController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/history.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
  src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php
  tests/back/Pim/Enrichment/Integration/Controller/VersioningControllerIntegration.php
Labels: echoes/intent: maintenance

#19610 PIM-10941: Fix unitary attribute group deletion
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
Labels: echoes/intent: maintenance

#19608 OCT-245 WIP fh tests cleanup
  config/services/test/test_services.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/NotifyOnAttributeRemovalEventSubscriberIntegration.php
  upgrades/schema/Version_6_0_20210615084255_add_entity_updated_in_product_mapping.php
  upgrades/schema/Version_7_0_20220524134005_add_is_enabled_column_to_catalog.php
  upgrades/schema/Version_7_0_20220830000000_add_catalog_product_values_filters.php
  upgrades/schema/Version_7_0_20220920100616_add_product_mapping.php
  upgrades/schema/Version_7_0_20221207140900_add_disable_catalogs_on_currency_deactivation_job_instance.php
  upgrades/schema/Version_7_0_20221213091400_add_disable_catalogs_on_channel_removal_job_instance.php
  upgrades/schema/Version_7_0_20221214103600_add_disable_catalogs_on_locale_deactivation_job_instance.php
  upgrades/test_schema/Version_6_0_20210615084255_add_entity_updated_in_product_mapping_Integration.php
  upgrades/test_schema/Version_7_0_20220524134005_add_is_enabled_column_to_catalog_Integration.php
  upgrades/test_schema/Version_7_0_20220830000000_add_catalog_product_values_filters_Integration.php
  upgrades/test_schema/Version_7_0_20220920100616_add_product_mapping_Integration.php
  upgrades/test_schema/Version_7_0_20221207140900_add_disable_catalogs_on_currency_deactivation_job_instance_Integration.php
  upgrades/test_schema/Version_7_0_20221213091400_add_disable_catalogs_on_channel_removal_job_instance_Integration.php
  upgrades/test_schema/Version_7_0_20221214103600_add_disable_catalogs_on_locale_deactivation_job_instance_Integration.php
Labels: echoes/intent: technical

#19605 PIM-10937: backport PIM-10887
  CHANGELOG-6.0.md
  src/Akeneo/Channel/Bundle/EventListener/ChannelLocaleSubscriber.php
  src/Akeneo/Channel/Bundle/EventListener/RemoveLocalesFromChannelSubscriber.php
  src/Akeneo/Channel/Bundle/Processor/Denormalization/ChannelProcessor.php
  src/Akeneo/Channel/Bundle/Resources/config/doctrine/model/Locale.orm.yml
  src/Akeneo/Channel/Bundle/Resources/config/processors.yml
  src/Akeneo/Channel/Bundle/Resources/config/services.yml
  src/Akeneo/Channel/Component/Model/Channel.php
  src/Akeneo/Channel/Component/Model/Locale.php
  src/Akeneo/Channel/Component/Model/LocaleInterface.php
  src/Akeneo/Channel/Component/Updater/ChannelUpdater.php
  tests/back/Acceptance/Channel/ChannelContext.php
  tests/back/Acceptance/Locale/LocaleContext.php
  tests/back/Channel/Integration/Channel/ChannelTestCase.php
  tests/back/Channel/Specification/Bundle/EventListener/ChannelLocaleSubscriberSpec.php
  tests/back/Channel/Specification/Bundle/EventListener/RemoveLocalesFromChannelSubscriberSpec.php
  tests/back/Channel/Specification/Bundle/Processor/Denormalization/ChannelProcessorSpec.php
  tests/back/Channel/Specification/Component/Updater/ChannelUpdaterSpec.php
  tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
  tests/features/channel/locale/locale_status.feature
Labels: echoes/intent: maintenance

#19618 Pull up 7.0 into master
  CHANGELOG-6.0.md
  composer.json
  composer.lock
Labels: echoes/intent: maintenance

#19623 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Channel/back/Infrastructure/Component/Model/Channel.php
  src/Akeneo/Channel/back/Infrastructure/Component/Model/Locale.php
  src/Akeneo/Channel/back/Infrastructure/Component/Model/LocaleInterface.php
  src/Akeneo/Channel/back/Infrastructure/Component/Updater/ChannelUpdater.php
  src/Akeneo/Channel/back/Infrastructure/EventListener/ChannelLocaleSubscriber.php
  src/Akeneo/Channel/back/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriber.php
  src/Akeneo/Channel/back/Infrastructure/Processor/Denormalization/ChannelProcessor.php
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/doctrine/model/Locale.orm.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/processors.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Processor/Denormalization/ChannelProcessorSpec.php
  tests/back/Acceptance/Channel/ChannelContext.php
  tests/back/Acceptance/Locale/LocaleContext.php
  tests/back/Channel/Integration/Channel/ChannelTestCase.php
  tests/back/Channel/Specification/Infrastructure/Component/Updater/ChannelUpdaterSpec.php
  tests/back/Channel/Specification/Infrastructure/EventListener/ChannelLocaleSubscriberSpec.php
  tests/back/Channel/Specification/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriberSpec.php
  tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
  tests/features/channel/locale/locale_status.feature
Labels: echoes/intent: maintenance

#19601 PIM-10938: Fix getNextObject when use clicks on variant during sequential edit
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sequential-edit.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/provider/sequential-edit-provider.js
Labels: echoes/intent: maintenance

#19631 PIM-10948: Fix number value comparison
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Value/NumberValue.php
  src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/NumberValueFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Value/NumberValueSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Value/ScalarValueSpec.php
Labels: echoes/intent: maintenance

#19581 RAB-1326: Add Reset PIM confirmation modal
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetModal.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetModal.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/index.ts
Labels: echoes/intent: feature, echoes/effort: S

#19627 Pull up 7.0 into master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
Labels: echoes/intent: maintenance

#19641 PIM-10955: rollback PIM-10916 to fix perf issue on categories API
  CHANGELOG.md
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
Labels: griffins, griffins-risk-assessed

#19640 PIM-10951: Fix grid search with special characters
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/AttributeFilter.php
  src/Oro/Bundle/FilterBundle/Filter/SearchFilter.php
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
  tests/legacy/features/pim/structure/attribute/browse/filter.feature
Labels: echoes/intent: maintenance

#19646 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
Labels: echoes/intent: maintenance

#19648 PIM-10959: Fix API response when trying to associate a product model to itself in a 2-way association
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Updater/TwoWayAssociationUpdater.php
  src/Akeneo/Pim/Enrichment/Component/Product/Exception/TwoWayAssociationWithTheSameProductException.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
Labels: echoes/intent: maintenance

#19635 RAB-1386: Create JobInstance Deletion Service API
  src/Akeneo/Platform/Job/back/Application/DeleteJobInstance/DeleteJobInstanceHandler.php
  src/Akeneo/Platform/Job/back/Application/DeleteJobInstance/DeleteJobInstanceInterface.php
  src/Akeneo/Platform/Job/back/Infrastructure/Query/DeleteJobInstance.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/DeleteJobInstance/DeleteJobInstanceCommand.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/DeleteJobInstance/DeleteJobInstanceHandlerInterface.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Application/DeleteJobInstance/DeleteJobInstanceHandlerTest.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemoryDeleteJobInstance.php
  src/Akeneo/Platform/Job/back/tests/Acceptance/Resources/config/services.yml
  src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/DeleteJobInstanceTest.php
Labels: contribution, echoes/intent: feature

#19600 GRF-816 front - display template attribute's settings
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.test.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/DeactivateTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCatalogActivatedLocales.ts
  src/Akeneo/Category/front/src/feature/hooks/useCatalogLocales.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useFetchUserGroups.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuidInMemory.ts
  src/Akeneo/Category/front/src/feature/hooks/useUiLocales.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: echoes/intent: feature

#19649 PIM-10961: Use React component for product grid locale switcher
  CHANGELOG.md
  front-packages/shared/src/components/LocaleSelector.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/locale-switcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/locale-switcher.tsx
  tests/legacy/features/Behat/Decorator/ReactContextSwitcherDecorator.php
  tests/legacy/features/Context/Page/Product/Index.php
Labels: echoes/intent: maintenance

#19653 OCT-251: prevent elasticsearch error
  src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Persistence/PurgeConnectionErrorsQuery.php
Labels: echoes/intent: technical

#19652 CPM-1057: Fix user timezone on comments
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductCommentController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Labels: echoes/intent: feature

#19656 PIM-10916: Fix with_position on category Rest API
  CHANGELOG.md
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Labels: griffins, griffins-risk-assessed

#19647 PIM-10950: bring back code filter
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Oro/Bundle/PimDataGridBundle/Adapter/OroToPimGridFilterAdapter.php
Labels: contribution, echoes/intent: maintenance

#19662 PIM-10932: Fix data in NumberValueFactory if data contains a white space
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/NumberValueFactorySpec.php
Labels: echoes/intent: maintenance

#19660 PIM-10814: Wysiwyg now supports languages that use rtl
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-wysiwyg.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Labels: echoes/intent: maintenance

#19579 PIM-10909: Refactor command to remove non-existing products and model…
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedProductsCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetDeletedProductDocumentIds.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetDeletedProductModelDocumentIds.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetDeleteProductModelDocumentIdsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetDeletedProductDocumentIdsIntegration.php
Labels: echoes/intent: maintenance

#19539 GRF-782 : User can't view deleted attribute
  src/Akeneo/Category/back/Domain/Query/DeactivatedTemplateAttributes/DeactivatedTemplateAttributeIdentifier.php
  src/Akeneo/Category/back/Domain/Query/DeactivatedTemplateAttributes/DeactivatedTemplateAttributesInValueCollectionFilter.php
  src/Akeneo/Category/back/Domain/Query/DeactivatedTemplateAttributes/GetDeactivatedTemplateAttributes.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDeactivatedTemplateAttributesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cleaners.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ApiCategoryTestCase.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDeactivatedTemplateAttributesSqlIntegration.php
  src/Akeneo/Category/back/tests/Unit/Domain/Query/DeactivatedTemplateAttributes/DeactivatedTemplateAttributesInValueCollectionFilterTest.php
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/DeactivateTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19659 PIM-10914: Add title and ellipsis for long labels on attribute select
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/add-select/line.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/add-select/attribute/line.html
Labels: echoes/intent: maintenance

#19613 GRF-783: User can't edit template attribute values of deleted attribute
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19669 GRF: enable customize template feature flag
  .env
Labels: griffins, griffins-risk-assessed

#19668 GRF-783 rename folder containing service
  src/Akeneo/Category/back/Domain/Query/GetDeactivatedTemplateAttributes/DeactivatedTemplateAttributeIdentifier.php
  src/Akeneo/Category/back/Domain/Query/GetDeactivatedTemplateAttributes/DeactivatedTemplateAttributesInValueCollectionFilter.php
  src/Akeneo/Category/back/Domain/Query/GetDeactivatedTemplateAttributes/GetDeactivatedTemplateAttributes.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDeactivatedTemplateAttributesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cleaners.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryEnrichedValuesByTemplateUuid/CleanCategoryTemplateAndEnrichedValuesCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Application/Query/GetCategory/InternalApiCategoryIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeactivateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesParametersBuilderSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDeactivatedTemplateAttributesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Component/Classification/Updater/CategoryUpdaterSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelChangeSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryTemplateAndEnrichedValuesOnTemplateDeactivatedSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Handler/SearchFiltersSqlSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistrySpec.php
  src/Akeneo/Category/back/tests/Unit/Domain/Query/DeactivatedTemplateAttributes/DeactivatedTemplateAttributesInValueCollectionFilterTest.php
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
Labels: echoes/intent: feature

#19642 RAB-1382: Differentiate reset catalog and banner
  front-packages/shared/src/components/page/SandboxHelper.tsx
  front-packages/shared/src/components/page/SandboxHelper.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/form_extensions/dqi_dashboard/dqi_dashboard.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/association_type/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/channel/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/channel/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/currency/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/export/index-profile.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/family/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/family/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/group/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/group/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/group_type/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/group_type/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/import/index-profile.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/user/index-group.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/user/index-role.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/index.yml
Labels: echoes/intent: feature, echoes/effort: L

#19665 RAB-1385: Add display sandbox banner boolean in System conf
  components/identifier-generator/front/src/feature/tests/test-utils.tsx
  front-packages/shared/src/DependenciesContext.tsx
  front-packages/shared/src/DependenciesProvider.type.ts
  front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.unit.tsx
  front-packages/shared/src/components/Navigation/SubNavigationDropdown.unit.tsx
  front-packages/shared/src/components/page/SandboxHelper.tsx
  front-packages/shared/src/components/page/SandboxHelper.unit.tsx
  front-packages/shared/src/dependencies/index.ts
  front-packages/shared/src/dependencies/system-configuration.ts
  front-packages/shared/src/dependencies/system-configuration.unit.ts
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useSystemConfiguration.ts
  front-packages/shared/src/hooks/useSystemConfiguration.unit.ts
  front-packages/shared/src/tests/mockedDependencies.ts
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/dependencies-provider.tsx
  src/Akeneo/Connectivity/Connection/front/tests/test-utils.tsx
  src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Configuration.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/SandboxHelperView.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/system.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/__mocks__/dependencies.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/dependencies.ts
  src/Oro/Bundle/ConfigBundle/Resources/config/controllers.yml
  src/Oro/Bundle/ConfigBundle/front/src/feature/ConfigForm.tsx
  src/Oro/Bundle/ConfigBundle/front/src/feature/models/ConfigServicePayload.ts
Labels: echoes/intent: feature, echoes/effort: M
