Repository akeneo/pim-community-dev, pull requests merged in 2023-05, with the labels that each got.

#19678 PIM-10971: Pull Up 7.0 => master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
Labels: contribution, echoes/intent: maintenance

#19675 GRF-828: fix category tree deletion
  CHANGELOG.md
  src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAndEnrichedValues/CleanCategoryTemplateAndEnrichedValuesCommandHandler.php
  src/Akeneo/Category/back/Application/Command/DeleteCategoryCommand/DeleteCategoryCommand.php
  src/Akeneo/Category/back/Application/Command/DeleteCategoryCommand/DeleteCategoryCommandHandler.php
  src/Akeneo/Category/back/Application/Query/DeleteTemplateAndAttributes.php
  src/Akeneo/Category/back/Domain/Query/GetCategoryTreeTemplates.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/RemoveCategoryTreeTemplateSubscriber.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/RemoveTemplateAndAttributesAfterCategoryTreeDeletionSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByCategoryIdAndTemplateUuidSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByTemplateUuidSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteTemplateAndAttributesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreeTemplatesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/Integration/Application/Command/DeleteCategoryCommand/DeleteCategoryCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByCategoryIdAndTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteTemplateAndAttributesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreeTemplatesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/RemoveCategoryTreeTemplateSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/RemoveTemplateAndAttributesAfterCategoryTreeDeletionSubscriberSpec.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19650 GRF-829 : Fix Web API permissions are not taken into account for categories endpoints
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/DownloadCategoryMediaFileController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/CategoryAuthorization.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/CategoryAuthorizationEndToEnd.php
Labels: echoes/intent: feature

#19686 GRF-834: update category helper
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19651 PIM-10639 : Prevent users to change his password without providing its current password
  CHANGELOG.md
  make-file/user-management.mk
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
  src/Akeneo/UserManagement/Bundle/Resources/config/command_cli.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/command_handler.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Akeneo/UserManagement/back/Application/Command/UpdateUserCommand/UpdateUserCommand.php
  src/Akeneo/UserManagement/back/Application/Command/UpdateUserCommand/UpdateUserCommandHandler.php
  src/Akeneo/UserManagement/back/Application/Exception/UserNotFoundException.php
  src/Akeneo/UserManagement/back/Domain/PasswordCheckerInterface.php
  src/Akeneo/UserManagement/back/Infrastructure/PasswordChecker.php
  src/Akeneo/UserManagement/back/tests/Integration/Application/Command/UpdateUserCommand/UpdateUserCommandHandlerIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/PasswordCheckerIntegration.php
  tests/back/UserManagement/EndToEnd/Bundle/Controller/Rest/UserControllerEndToEnd.php
  tests/back/UserManagement/Helper/ControllerEndToEndTestCase.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19687 GROWTH-127: Implements div elements for login & pim cookie consent
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/app.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: butterfly

#19681 PIM-10967: Fix inconsistency on DQI completeness recommendation
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributes.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributesSpec.php
Labels: echoes/intent: maintenance

#19676 GRF-831 : Change back wording to textArea for rich text
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19690 GRF-810 : User is allowed to edit attribute
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19666 PIM-10949: Fix import duplicate variant products without identifier
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php
  tests/back/Pim/Enrichment/Integration/Product/Import/ImportProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
Labels: echoes/intent: maintenance, echoes/effort: M

#19604 PIM-10940 : Add command to remove orphan categories
  CHANGELOG.md
  src/Akeneo/Category/back/Domain/Query/PurgeOrphanCategories.php
  src/Akeneo/Category/back/Infrastructure/Cli/RemoveOrphanCategories/RemoveOrphanCategoriesCommand.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/PurgeOrphanCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cli.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/PurgeOrphanCategoriesSqlIntegration.php
  src/Akeneo/UserManagement/Bundle/Resources/config/command_cli.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/queries.yml
  src/Akeneo/UserManagement/back/Domain/Storage/AssignAllUsersToOneCategory.php
  src/Akeneo/UserManagement/back/Infrastructure/Cli/AssignAllUsersToOneCategoryTreeCommand.php
  src/Akeneo/UserManagement/back/Infrastructure/Storage/SqlAssignAllUsersToOneCategory.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Storage/SqlAssignAllUsersToOneCategoryIntegration.php
  tests/back/Pim/Enrichment/Integration/Command/Category/RemoveCategoriesOrphan/RemoveOrphanCategoriesIntegration.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19693 PIM-10958: Fix attribute option position after clicking on "done"
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/AttributeOptionTable.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/Edit.unit.tsx
Labels: echoes/intent: maintenance

#19699 CPM-1039: Create new table for completeness
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitProductCompletenessDbSchemaSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  upgrades/schema/Version_8_0_20230509160000_new_table_completeness.php
  upgrades/test_schema/Version_8_0_20230509160000_new_table_completeness_Integration.php
Labels: echoes/intent: feature

#19700 PIM-10976: Fix variant product counter on Product Model Edit Form for variant products without identifier
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php
  src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/CompleteVariantProducts.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/VariantProductRatioIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Query/CompleteVariantProductsSpec.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19707 PH-1021: Add ScheduledJobMessageNormalizer
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/MessengerBundle/tests/integration/JsonSerializerIntegration.php
  src/Akeneo/Tool/Component/BatchQueue/Normalizer/ScheduledJobMessageNormalizer.php
Labels: ucs, echoes/intent: maintenance

#19708 Fix standard that does not pass since fpm and httpd have been merged and catalog have been moved to EE
  std-build/install-required-files.sh
  std-build/package.json
Labels: echoes/intent: technical, echoes/effort: XS

#19658 PIM-10928: pim:update:check-requirements can create indexes which are unreachable from the PIM
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19710 PIM-10983: Error HTTP 500 when adding a custom app
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
  upgrades/schema/Version_8_0_20230511113912_fix_oro_access_tables_columns_length.php
  upgrades/test_schema/Version_8_0_20230511113912_fix_oro_access_tables_columns_length_Integration.php
Labels: echoes/intent: maintenance

#19717 PH-1028: :bug: Handle custom job config in watchdog
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/PurgeVersioningWatchdogIntegration.php
Labels: echoes/intent: maintenance

#19720 PIM-10980: Fix pagination update when applying filters on product association grid
  CHANGELOG.md
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19728 PH-1034: InstallStatusManager catches only TableNotFound exception
  src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
  tests/back/Platform/Integration/Installer/InstallStatusManagerIntegration.php
Labels: echoes/intent: maintenance

#19718 fix stateful UcsMiddleware injecting wrong tenant id in messages
  src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php
  src/Akeneo/Tool/Bundle/MessengerBundle/Resources/config/transport.yml
  tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
Labels: ucs

#19726 CPM-839: Add env parameter for Product Version retention
  config/services/pim_parameters.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
Labels: echoes/intent: technical

#19724 Pull up 7.0 into master
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Doctrine/Query/SqlGetPurgeableVersionListQueryIntegration.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19692 PIM-10972: change the way incomplete row are filled
  CHANGELOG.md
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php
Labels: contribution, echoes/intent: maintenance, echoes/effort: M

#19711 PIM-10977 make control on user type more strict during log in
  CHANGELOG.md
  src/Akeneo/UserManagement/Component/Model/User.php
  src/Akeneo/UserManagement/Component/Model/UserInterface.php
Labels: echoes/intent: maintenance

#19691 RAB-1396: Add PAUSING and PAUSED status
  front-packages/akeneo-design-system/src/components/SectionTitle/SectionTitle.tsx
  front-packages/akeneo-design-system/src/components/Tooltip/Tooltip.stories.mdx
  front-packages/akeneo-design-system/src/components/Tooltip/Tooltip.tsx
  front-packages/akeneo-design-system/src/components/Tooltip/Tooltip.unit.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Job/back/Domain/Model/Status.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/Progress.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/Progress.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/summary/SummaryTable.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/summary/SummaryTable.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/common/JobExecutionStatus.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/common/JobExecutionStatus.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionDetail/JobExecution.test.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionDetail/JobExecution.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionDetail/StepExecution.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobStatus.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/StepExecutionRowTracking.test.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/StepExecutionRowTracking.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/StepStatus.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/index.ts
  src/Akeneo/Tool/Component/Batch/Job/BatchStatus.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizerSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19704 CPM-1025: Handle ref entity nomenclature in PropertyProcessApplier
  components/identifier-generator/back/src/Application/Generate/Property/PropertyProcessApplier.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/PropertyProcessApplierSpec.php
Labels: echoes/intent: feature

#19701 GRF-821 : User can edit attribute options BACKEND
  src/Akeneo/Category/back/Application/Command/AddAttributeCommandHandler.php
  src/Akeneo/Category/back/Application/Command/UpdateAttributeCommand/UpdateAttributeCommand.php
  src/Akeneo/Category/back/Application/Command/UpdateAttributeCommand/UpdateAttributeCommandHandler.php
  src/Akeneo/Category/back/Application/Query/GetAttribute.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryTemplateAttributeSaver.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Exceptions/ViolationsException.php
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/AddAttributeController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateAttributeController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/UpdateAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Command/AddAttributeCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Unit/Application/Command/UpdateAttributeCommand/UpdateAttributeCommandHandlerTest.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19733 CPM-1058: Rename commands retrieving data to queries
  components/identifier-generator/back/src/Application/Get/GetGeneratorHandler.php
  components/identifier-generator/back/src/Application/Get/GetGeneratorQuery.php
  components/identifier-generator/back/src/Application/Get/GetGeneratorsHandler.php
  components/identifier-generator/back/src/Application/Get/GetGeneratorsQuery.php
  components/identifier-generator/back/src/Application/Get/GetNomenclatureHandler.php
  components/identifier-generator/back/src/Application/Get/GetNomenclatureQuery.php
  components/identifier-generator/back/src/Infrastructure/Controller/CreateIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Controller/GetNomenclatureController.php
  components/identifier-generator/back/src/Infrastructure/Controller/ListIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php
Labels: echoes/intent: feature

#19709 GRF-812: User can edit attribute options front-end
  make-file/category.mk
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateAttributeController.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/UpdateAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/hooks/useUpdateTemplateAttribute.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19695 PIM-10930: Fix validation of values in product uuid endpoints
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Labels: echoes/intent: maintenance, echoes/effort: XS

#19748 Fix database akeneo_pim does not exist when launching make database
  Makefile
Labels: echoes/intent: technical, echoes/effort: XS

#19729 RAB-1390: Add current state column on step execution table
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/StepExecution.orm.yml
  src/Akeneo/Tool/Component/Batch/Model/StepExecution.php
  upgrades/schema/Version_8_0_20230515140000_add_column_current_state_on_batch_step_execution.php
  upgrades/test_schema/Version_8_0_20230515140000_add_column_current_state_on_batch_step_execution_Integration.php
Labels: echoes/intent: feature, echoes/effort: S

#19703 CPM-1045: On product save, update/fill the new completeness table
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveCompletenesses.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlSaveCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenessesSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19745 Pim 10997 Update error message on role deletion
  CHANGELOG-6.0.md
  src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php
  tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
Labels: griffins, echoes/intent: maintenance

#19744 PIM-11000: Fallback on filePath when storage type is undefined
  CHANGELOG-7.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
Labels: echoes/intent: maintenance, echoes/effort: XS

#19761 [PULL-UP 7.0] PIM-10997 Update error message when trying to delete role with linked…
  CHANGELOG-7.0.md
  src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php
  tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
Labels: echoes/intent: maintenance

#19739 RAB-1387: Add pcntl as explicit dependency and forward SIGTERM to BatchCommand
  composer.json
  composer.lock
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/EventListener/PauseJobOnSigtermSubscriberSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19714 CPM-1046: Migration to fill with current completeness data
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20230512143522FillNewCompletenessTableZddMigration.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  tests/back/Pim/Enrichment/Integration/Product/V20230512143522FillNewCompletenessTableZddMigrationIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlSaveCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenessesSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19743 PIM-10966: Fix JS error on toggling tabs on an export profile editing page
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
Labels: echoes/intent: maintenance, echoes/effort: XS

#19768 PIM-1045-bis: fix number of queries to save completeness
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveCompletenesses.php
Labels: echoes/intent: feature, echoes/effort: S

#19756 RAB-1395: Register onTerminate only when an attribute is added to the aggregator
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AttributeRemovalSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
Labels: echoes/intent: feature, echoes/effort: XS

#19767 [PULL-UP master] PIM-10997 Update error message when trying to delete role with linked…
  CHANGELOG.md
  src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php
  tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
Labels: echoes/intent: maintenance

#19752 PIM-10978 : Fix category date update on labels changed (remove and add)
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnSave/SetUpdatedPropertyOnTranslationUpdateSubscriber.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Category/OnSave/SetUpdatedPropertyOnTranslationUpdateSubscriberSpec.php
Labels: echoes/intent: maintenance

#19773 Pullup 7.0 => master
  CHANGELOG-7.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
Labels: echoes/intent: maintenance, echoes/effort: XS

#19766 PIM-11003: Fix scrolling on Product edit form attributes
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Default.less
Labels: echoes/intent: maintenance

#19750 RAB-1392: Add class to handle paused job queue messages
  .env
  .env.behat
  .env.test
  .env.test_fake
  config/packages/behat/messenger.yml
  config/packages/dev/messenger.yml
  config/packages/prod/messenger.yml
  config/packages/test/messenger.yml
  src/Akeneo/Tool/Component/BatchQueue/Queue/PausedJobExecutionMessage.php
Labels: echoes/intent: feature, echoes/effort: XS

#19762 GRF: extract category code from enrich context
  src/Akeneo/Category/back/Infrastructure/Component/CategoryItemsCounterInterface.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Doctrine/ORM/Counter/CategoryItemsCounter.php
  src/Akeneo/Category/back/Infrastructure/Doctrine/ORM/Counter/CategoryItemsCounterRegistry.php
  src/Akeneo/Category/back/Infrastructure/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php
  src/Akeneo/Category/back/Infrastructure/Doctrine/ORM/Saver/CategorySaver.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/counters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/repositories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/savers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/serializers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/serializers_versioning.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/twig.yml
  src/Akeneo/Category/back/Infrastructure/Twig/CategoryExtension.php
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Doctrine/ORM/Saver/CategorySaverIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Doctrine/ORM/Repository/ExternalApi/CategoryRepositorySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Doctrine/ORM/Saver/CategorySaverSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Twig/CategoryExtensionSpec.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Counter/CategoryItemsCounterRegistryInterface.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Counter/CategoryProductsCounter.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/UpdateIndexesOnCategoryDeletion.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/category_counters.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/twig.yml
  tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ExternalApi/CategoryRepositoryApiResourceIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/InternalApi/CategoryRepositorySpec.php
Labels: griffins

#19781 OCT-262: Error on event API search subscription logs due tu bad json_decode exception
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Controller/Internal/SearchEventSubscriptionLogsAction.php
Labels: echoes/intent: technical

#19775 CPM-1041: Get Completenesses from new table
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompleteness.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/GetProductCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompletenessSpec.php
Labels: echoes/intent: feature, echoes/effort: M

#19777 RAB-1393: Add command to handle resume paused jobs
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/queries.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishPausedJobsToQueueCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
  src/Akeneo/Tool/Component/Batch/Query/GetPausedJobExecutionIdsInterface.php
  src/Akeneo/Tool/Component/Batch/Query/SqlGetPausedJobExecutionIds.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishPausedJobsToQueue.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishPausedJobsToQueueSpec.php
  tests/back/Tool/Integration/Batch/Query/SqlGetPausedJobExecutionIdsIntegration.php
Labels: echoes/intent: feature, echoes/effort: S

#19783 PIM-10982 : Fix flag emoji rendering on windows
  CHANGELOG.md
  front-packages/akeneo-design-system/.storybook/preview-head.html
  front-packages/akeneo-design-system/public/fonts/twemoji/LICENCE.txt
  front-packages/akeneo-design-system/public/fonts/twemoji/TwemojiCountryFlags.woff2
  front-packages/akeneo-design-system/src/components/Locale/Locale.stories.mdx
  front-packages/akeneo-design-system/src/components/Locale/Locale.tsx
  front-packages/akeneo-design-system/src/components/SwitcherButton/SwitcherButton.stories.mdx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Lato/LICENCE.txt
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Lato/Lato-Bold.ttf
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Lato/Lato-Light.ttf
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Lato/Lato-Regular.ttf
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Twemoji/LICENCE.txt
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/fonts/Twemoji/TwemojiCountryFlags.woff2
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/general.less
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19794 PIM-11013 : Fix edit user profile without password changes
  CHANGELOG.md
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Resources/config/command_handler.yml
  src/Akeneo/UserManagement/back/Application/Command/UpdateUserCommand/UpdateUserCommandHandler.php
  tests/back/UserManagement/EndToEnd/Bundle/Controller/Rest/UserControllerEndToEnd.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed
