Repository akeneo/pim-community-dev, pull requests merged in 2023-06, with the labels that each got.

#19799 RAB-1411: Forward SIGTERM across daemon and watchdog command
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
Labels: echoes/intent: feature, echoes/effort: S

#19796 RAB-1404: add reset pim acl & handle reset button display
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/acl.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Controller/ResetInstanceAction.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
Labels: echoes/intent: feature, echoes/effort: S

#19811 RAB-1436: remove useless command
  src/Akeneo/Tool/Bundle/BatchBundle/Command/MigrateJobExecutionWarningCountCommand.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Command/MigrateJobExecutionWarningCountCommandIntegration.php
Labels: echoes/intent: technical, echoes/effort: XS

#19759 SAAS-754-pim-ce Upgrade cloud-deployer
  .circleci/jobs/build_and_deploy.yml
Labels: echoes/intent: maintenance, echoes/effort: XS

#19810 PIM-11012 : Add helper if selected UI language is not sufficiently supported
  CHANGELOG.md
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/requirejs.yml
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/unsupported-ui-locale-warning-view.tsx
  src/Akeneo/UserManagement/Bundle/Resources/public/js/form/unsupported-ui-locale-warning.tsx
  src/Akeneo/UserManagement/Bundle/Resources/public/js/hooks/useUiLocales.ts
  src/Akeneo/UserManagement/Bundle/Resources/public/js/tools/apiFetch.ts
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19820 fix-ci-gcs
  .circleci/jobs/features/other.yml
  docker-compose.yml
Labels: echoes/intent: technical, echoes/effort: XS

#19800 RAB-1413: Pause and save state of attribute csv import
  src/Akeneo/Tool/Component/Batch/Item/PausableReaderInterface.php
  src/Akeneo/Tool/Component/Batch/Item/PausableWriterInterface.php
  src/Akeneo/Tool/Component/Batch/Job/JobStopper.php
  src/Akeneo/Tool/Component/Batch/Job/JobStopperInterface.php
  src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php
  src/Akeneo/Tool/Component/Batch/Step/ItemStep.php
  src/Akeneo/Tool/Component/Batch/spec/Item/FakeReader.php
  src/Akeneo/Tool/Component/Batch/spec/Item/FakeWriter.php
  src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php
  src/Akeneo/Tool/Component/Connector/Writer/Database/Writer.php
Labels: contribution, echoes/intent: feature

#19637 GROWTH-96: Implements div elements for cookie consent in FT
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/user-navigation.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
Labels: butterfly

#19740 CPM-1065: Update Attribute entity
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeRepository.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/Install/InitMainIdentifierSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Component/Repository/AttributeRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/SingleIdentifierAttributeValidator.php
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductViolationNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/SingleIdentifierAttributeValidatorSpec.php
  upgrades/test_schema/Version_8_0_20230412073849_set_main_attribute_column_Integration.php
Labels: echoes/intent: feature, echoes/effort: M

#19821 PIM-11025: :chart_with_upwards_trend: Enrich watchdog logs
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
Labels: ucs, echoes/intent: maintenance

#19797 GRF-830 reindex template attribute order after add/delete attribute
  src/Akeneo/Category/back/Application/Command/AddAttributeCommandHandler.php
  src/Akeneo/Category/back/Domain/Query/UpdateCategoryTemplateAttributesOrder.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/ReorderTemplateAttributesOnAttributeDeactivatedSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/DeactivateAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/AttributeCollectionSpec.php
Labels: griffins, echoes/intent: technical, griffins-risk-assessed

#19818 RAB-1414: paused import
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductAssociationWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductModelWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductWriter.php
  src/Akeneo/Pim/Structure/Component/Writer/Database/AttributeGroupWriter.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php
  src/Akeneo/UserManagement/Component/Connector/Writer/Database/RoleWithPermissionsWriter.php
Labels: contribution, echoes/intent: feature

#19815 CXP-1499: Add scroll bars on the target list and the source panel
  src/Akeneo/Connectivity/Connection/front/src/common/components/PageContent.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
Labels: echoes/intent: feature

#19823 PIM-11025: :bug: Fix akeneo_connectivity_connection_audit.step.update…
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/jobs.yml
Labels: echoes/intent: maintenance

#19814 PIM-11023 : Fix product search containing underscores
  CHANGELOG.md
  src/Oro/Bundle/PimFilterBundle/Filter/Product/LabelOrIdentifierFilter.php
  src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/LabelOrIdentifierFilterSpec.php
  src/Oro/Bundle/PimFilterBundle/spec/Filter/ProductValue/StringFilterSpec.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php
Labels: echoes/intent: maintenance

#19806 RAB-1394: Handle resume job
  src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
  src/Akeneo/Tool/Component/Batch/Job/BatchStatus.php
  src/Akeneo/Tool/Component/Batch/Job/Job.php
  src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php
  src/Akeneo/Tool/Component/Batch/spec/Job/BatchStatusSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19813 RAB-1438: A job with multiple steps is able to resume from the paused step
  src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Job/JobIntegration.php
  src/Akeneo/Tool/Component/Batch/Job/Job.php
Labels: echoes/intent: feature, echoes/effort: S

#19760 CPM-1070: Save product identifier values
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/DBAL/EventListener/SkipMultiValuedIndexDuringIntrospectionListener.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/CreateIdentifiersTableSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlUpdateIdentifierValuesQuery.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/IdentifierValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/UpdateIdentifierValuesQuery.php
  src/Akeneo/Pim/Enrichment/Component/Product/Value/IdentifierValue.php
  src/Akeneo/Pim/Enrichment/Component/Product/Value/IdentifierValueInterface.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/UpdateProductIdentifiersOnProductUpdateIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromUuidsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductSaverSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/MassEdit/ConvertToSimpleProductProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/RemoveParentSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ReadValueCollectionFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/IdentifierValueFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/AttributeOptionsExistValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/ReferenceDataOptionsExistValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/ScopableValuesValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
  upgrades/schema/Version_8_0_20230523094142_create_product_identifiers_table.php
  upgrades/test_schema/Version_8_0_20230523094142_create_product_identifiers_table_Integration.php
Labels: echoes/intent: feature, echoes/effort: S

#19822 GRF-850 : Fix empty label not replaced by [code]
  src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
Labels: echoes/intent: feature

#19835 GRF-817: Autosave of template attribute settings
  front-packages/shared/src/components/page/PageHeader.tsx
  front-packages/shared/src/components/page/PageHeader.unit.tsx
  front-packages/shared/src/components/page/header/AutoSaveStatus.tsx
  front-packages/shared/src/components/page/header/index.ts
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/providers/SaveStatusProvider.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/SaveStatusIndicator.tsx
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useSaveStatusContext.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19805 GRF-857 Display error badge on attribute in error and attributes tab
  src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.test.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19845 PH-1086: :ambulance: Improve job uniqueness check
  src/Akeneo/Platform/Bundle/ImportExportBundle/Repository/InternalApi/JobExecutionRepository.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
  tests/back/Platform/Integration/ImportExport/Repository/InternalApi/JobExecutionRepositoryIntegration.php
Labels: ucs, echoes/intent: feature, echoes/intent: technical

#19848 PH-1087: :loud_sound: Add tenant ID in log record context when possible
  src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
Labels: ucs, echoes/intent: feature, echoes/intent: technical

#19841 OCT-267: Removed sleep as rate limiting mecanism for Events API
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/commands.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/event_subscribers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventSubscribers/EventsApiRequestsLimitEventSubscriber.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/GetDelayUntilNextRequest.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/Command/SendBusinessEventToWebhooksEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/EventSubscribers/EventsApiRequestsLimitEventSubscriberSpec.php
Labels: echoes/intent: maintenance

#19808 PIM-11016: Improve the clean-removed-attributes command
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
Labels: chipmunks, echoes/intent: maintenance

#19825 PLGSM-44: Add segment-integration feature flag
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProvider.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/user-navigation.html
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
  tests/back/Platform/Specification/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProviderSpec.php
Labels: butterfly

#19833 GRF-858 : Frontend: Alert on page leave with unsaved changes
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/public/js/controller/CategoriesSettings.tsx
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/components/providers/CanLeavePageProvider.tsx
  src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx
  src/Akeneo/Category/front/src/feature/components/providers/index.ts
  src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/index.tsx
Labels: echoes/intent: feature

#19831 RAB-1416: Save current state when an export job is paused
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/writers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/writers.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/writers.yml
  src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/writers.yml
  src/Akeneo/Tool/Component/Buffer/JSONFileBuffer.php
  src/Akeneo/Tool/Component/Connector/Reader/Database/AbstractReader.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractFileWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Csv/Writer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/ExportedFileBackuper.php
  src/Akeneo/Tool/Component/Connector/Writer/File/WrittenFileInfo.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Xlsx/Writer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Yaml/Writer.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/Csv/WriterSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php
  src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml
  src/Akeneo/UserManagement/Component/Connector/Writer/File/AbstractUserWriter.php
  tests/back/Pim/Enrichment/Integration/Product/Export/Writer/YamlWriterIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
  tests/back/Tool/Integration/Connector/Writer/File/ExportedFileBackuperIntegration.php
  tests/back/Tool/Integration/Connector/Writer/File/dummy_export.csv
  tests/back/UserManagement/Specification/Component/Connector/Writer/File/CsvUserWriterSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Writer/File/XlsxUserWriterSpec.php
Labels: echoes/intent: feature, echoes/effort: M

#19839 RAB-1427: implements rewind state for yaml
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/MountFileOnResumeSubscriber.php
  src/Akeneo/Tool/Component/Batch/Item/StatefulInterface.php
  src/Akeneo/Tool/Component/Batch/Job/Job.php
  src/Akeneo/Tool/Component/Batch/Step/ItemStep.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php
Labels: contribution, echoes/intent: feature

#19863 PUM-11043: pullup 6.0 to 7.0
  CHANGELOG-6.0.md
Labels: echoes/intent: maintenance

#19855 PIM-11040: Sku is disabled according to the rights
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/creation/field.html
Labels: echoes/intent: maintenance

#19868 PIM-11045: Check whether the table exists before using it
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlUpdateIdentifierValuesQuery.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19804 PIM-11005: Skip invalid entities during compute_family_variant_structure_changes job
  src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeFamilyVariantStructureChangesTasklet.php
  tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeFamilyVariantStructureChangesTaskletSpec.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19836 RAB-1329: Validate no job running before resetting PIM
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCheckInstanceCanBeReset.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCheckInstanceCanBeReset.unit.ts
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Controller/CheckInstanceCanBeResetAction.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
  src/Akeneo/Platform/Installer/back/tests/Integration/Controller/CheckInstanceCanBeResetActionTest.php
  src/Akeneo/Platform/Installer/back/tests/Integration/ControllerIntegrationTestCase.php
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Platform/Job/back/ServiceApi/JobExecution/FindQueuedAndRunningJobExecution.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobExecution/FindQueuedAndRunningJobExecutionInterface.php
Labels: echoes/intent: feature, echoes/effort: S

#19872 PH-1106: immediatly acknowledge schedules job messages
  src/Akeneo/Tool/Bundle/BatchQueueBundle/EventListener/AckMessageEventListener.php
  src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/EventListener/AckMessageEventListenerSpec.php
Labels: ucs, echoes/intent: maintenance

#19879 GRF-844: change deactivate template naming
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: feature

#19871 PH-1104: :bug: Fix job_code empty in watchdog logs
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
Labels: bug, ucs, echoes/intent: feature, echoes/intent: maintenance

#19865 PIM-11043: pull-up 7.0 to master
  CHANGELOG-6.0.md
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/messages.pt_PT.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.pt_PT.yml
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_GB.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Platform/Bundle/NotificationBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fi_FI.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/translations/validators.pt_PT.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/messages.en_GB.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.pt_PT.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pt_PT.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.pt_PT.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/validators.pt_PT.yml
Labels: echoes/intent: maintenance

#19854 GRF-669 : Add 4 field columns (properties) to the user export job profile
  make-file/user-management.mk
  src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php
  src/Akeneo/UserManagement/Component/Normalizer/DateTimeNormalizer.php
  src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/DateTimeNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/Standard/UserNormalizerSpec.php
Labels: echoes/intent: feature

#19859 RAB-1407: Add main identifier in GetAttribute service api
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
  tests/back/Acceptance/Attribute/InMemoryGetAttributes.php
  tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php
Labels: echoes/intent: feature, echoes/effort: S

#19885 GRF-845: edit template properties form
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/providers/TemplateFormProvider.tsx
  src/Akeneo/Category/front/src/feature/components/reducers/templateFormReducer.test.ts
  src/Akeneo/Category/front/src/feature/components/reducers/templateFormReducer.ts
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeLabelTranslationInput.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeList.test.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeOptionRichTextCheckbox.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeSettings.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm/TemplateLabelTranslationInput.tsx
  src/Akeneo/Category/front/src/feature/components/templates/UnsavedChangeGuard.tsx
  src/Akeneo/Category/front/src/feature/components/templates/createTemplate.tsx
  src/Akeneo/Category/front/src/feature/components/templates/templateFormReducer.ts
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/channelHelper.test.ts
  src/Akeneo/Category/front/src/feature/helpers/treeHelper.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategoryTreeDeprecated.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategoryTreeList.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useCategoryTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCreateAttribute.ts
  src/Akeneo/Category/front/src/feature/hooks/useDragTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/hooks/useDropTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/legacy/helpers/permissionsHelper.test.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
  src/Akeneo/Category/front/src/feature/tools/apiFetch.test.ts
  src/Akeneo/Category/front/src/setupTests.js
  src/Akeneo/Category/front/src/tests/provideCategoryHelper.ts
  src/Akeneo/Category/front/src/tests/provideTreeNodeHelper.ts
  src/Akeneo/Category/front/tsconfig.json
Labels: griffins

#19861 PIM-11041: Fix null has attribute group code broke the pef
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
Labels: contribution, echoes/intent: maintenance, echoes/effort: M

#19809 PIM-10931: Add possibility to filter job execution to purge by status and job_instance_code
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Job/JobParameters/PurgeJobExecutions.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Job/PurgeJobExecutions.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
  src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php
  src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php
  src/Akeneo/Tool/Bundle/BatchBundle/Storage/DeleteJobExecutionLogs.php
  tests/back/Tool/Integration/Batch/Persistence/Sql/DeleteJobExecutionIntegration.php
  tests/back/Tool/Integration/Batch/Persistence/Sql/GetJobExecutionIdsIntegration.php
Labels: echoes/intent: maintenance, echoes/effort: M

#19893 PIM-11050: On "locale" DIV, missing the indication of the country
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/locale-switcher.html
Labels: echoes/intent: maintenance

#19900 CPM-1083: Use IdentifierValue in SetIdentifierSubscriber
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
Labels: echoes/intent: feature

#19911 PIM-11047: Be able to customize local storage root without breaking import/export
  CHANGELOG-7.0.md
  config/packages/behat/oneup_flysystem.yml
  config/packages/dev/oneup_flysystem.yml
  config/packages/prod/oneup_flysystem.yml
  config/packages/test/oneup_flysystem.yml
  config/services/pim_parameters.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/DownloadStep.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/step.yml
Labels: echoes/intent: maintenance, echoes/effort: S

#19918 GRF-874: add init template choice
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/InitializeTemplateChoice.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModel.tsx
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttributeOnTemplatePage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: griffins, echoes/intent: feature

#19904 GRF-841 User can create an empty category tree template BACKEND
  src/Akeneo/Category/back/Application/ActivateTemplate.php
  src/Akeneo/Category/back/Application/Command/CreateTemplate/CreateTemplateCommand.php
  src/Akeneo/Category/back/Application/Command/CreateTemplate/CreateTemplateCommandHandler.php
  src/Akeneo/Category/back/Domain/Exception/CategoryTreeNotFoundException.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Template.php
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CreateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/builders.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/template.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Validation/TemplateCodeShouldBeUnique.php
  src/Akeneo/Category/back/Infrastructure/Validation/TemplateCodeShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/UpdateCategoryControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Application/ActivateTemplateIntegration.php
  src/Akeneo/Category/back/tests/Integration/Application/Command/CreateTemplate/CreateTemplateCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeactivateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeactivateTemplateSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTemplateSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19913 PIM-11057: Fix ScalarValue::__toString does not cast wrapped boolean value correctly
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19914 GRF-843: Team can track the usage of the load predefined attributes action on an empty template
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/TrackUsageOfLoadPredefinedAttributesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/TrackUsageOfLoadPredefinedAttributesControllerEndToEnd.php
Labels: echoes/intent: feature

#19906 PIM-11039: Fix export with duplicated labels
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/TranslatedColumnPresenter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
  src/Akeneo/Tool/Component/Connector/Writer/File/SimpleColumnPresenter.php
  tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsWithLabelsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/TranslatedColumnPresenterSpec.php
Labels: echoes/intent: maintenance, echoes/effort: M

#19927 PIM-11063: Fix generated identifier validation
  CHANGELOG.md
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
Labels: echoes/intent: maintenance, echoes/effort: S

#19892 OCT-270: fix validation for the scope variable
  src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthorizationCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/RequestAppAuthorizationCommand.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: technical

#19915 PIM-11051: Add OnlySaasSandboxFeatureFlag
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasSandboxFeatureFlag.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19932 GRF-873: add load attribute set command
  src/Akeneo/Category/back/Application/Command/LoadAttributeSet/LoadAttributeSetCommand.php
  src/Akeneo/Category/back/Application/Command/LoadAttributeSet/LoadAttributeSetCommandHandler.php
  src/Akeneo/Category/back/Domain/AttributeSetFactory.php
  src/Akeneo/Category/back/Domain/Query/GetAttributeInMemory.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/LoadAttributeSetController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/LoadAttributeSetControllerEndToEnd.php
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/InitializeTemplateChoice.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx
Labels: griffins

#19934 GRF-841: User can create an empty category tree template FRONTEND
  src/Akeneo/Category/back/Application/Command/CreateTemplate/CreateTemplateCommand.php
  src/Akeneo/Category/back/Application/Command/CreateTemplate/CreateTemplateCommandHandler.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CreateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/templates/CreateTemplateModal.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCreateTemplate.ts
Labels: griffins, echoes/intent: feature

#19936 GRF-843: add tracking of template init
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/InitializeTemplateChoice.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx
  src/Akeneo/Category/front/src/feature/hooks/useTrackUsageOfLoadPredefinedAttributes.ts
Labels: echoes/intent: feature

#19943 PIM-11066: Fix Missing Values Adder for scopable + localizable + locale specific attributes
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
  src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
  tests/back/Common/Structure/Attribute/Builder.php
  tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductModelValuesSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductValuesSpec.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19826 PIM-11018: The App section displays the Permission screen on GE/CE PIM.
  CHANGELOG.md
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
Labels: echoes/intent: maintenance

#19953 GRF: small fixes on load predefined attributes
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/CreateTemplateModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm/EditTemplatePropertiesForm.tsx
Labels: echoes/intent: feature

#19944 PIM-10869: Change image upload error messages to give less information
  src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFile.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFileValidator.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/spec/Validator/Constraints/UploadedFileValidatorSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19949 CPM-1132: Remove no longer needed Doctrine DBAL listener
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/DBAL/EventListener/SkipMultiValuedIndexDuringIntrospectionListener.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
Labels: echoes/intent: feature, echoes/effort: XS

#19956 GRF-872: [Backport GRF-669] Add 4 field columns (properties) to the user export job profile
  CHANGELOG-7.0.md
  make-file/user-management.mk
  src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php
  src/Akeneo/UserManagement/Component/Normalizer/DateTimeNormalizer.php
  src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php
  src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
  tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/DateTimeNormalizerSpec.php
  tests/back/UserManagement/Specification/Component/Normalizer/Standard/UserNormalizerSpec.php
Labels: griffins, echoes/intent: feature

#19909 RAB-1415: Pause Jobs only when they are actually Pausable
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/test/jobs.yml
  src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/EventListener/PauseJobOnSigtermSubscriberIntegration.php
  src/Akeneo/Tool/Component/Batch/Job/Job.php
  src/Akeneo/Tool/Component/Batch/Job/PausableJobInterface.php
  src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
Labels: contribution, echoes/intent: feature

#19919 CPM-1084: Update ES Identifier filters to use main identifier attribute
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/CachedGetMainIdentifierAttributeCode.php
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetMainIdentifierAttributeCode.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetMainIdentifierAttributeCode.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ProductAndProductModelIdentifierFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
Labels: echoes/intent: feature, echoes/effort: L

#19921 RAB-1446: Fix Job and Step execution start time when a job resume
  src/Akeneo/Tool/Component/Batch/Job/Job.php
  src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php
  src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php
Labels: echoes/intent: feature, echoes/effort: XS

#19928 CPM-1100: Update queries with link to identifier product column
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEnrichment/GetProductIdentifierFromProductUuidQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEnrichment/GetProductIdentifierFromProductUuidQueryIntegration.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/FindNonExistingProductsQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetIdMappingFromProductIdsQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetUuidMappingQuery.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductLabels.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetExistingProductUuids.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetProductAssociationsByProductUuids.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetValuesAndPropertiesFromProductUuids.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductUuid.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductUuids.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodes.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetProductUuids.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
  tests/back/Integration/TestCase.php
  tests/back/Integration/catalog/technical_sql/200_products.sql
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
  tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/DateFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/DateTimeFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Integration/Product/ReadValueCollectionFactoryIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductUuidsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromUuidsIntegration.php
Labels: echoes/intent: feature

#19961 PIM-11008: (PIM-10960) Fix no violation raised when importing variant…
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19966 PIM-11077: Add missing supported image types
  src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/internal_api.yml
Labels: echoes/intent: maintenance, echoes/effort: XS

#19917 RAB-1440: Handle resume export when we already read every items
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
  src/Akeneo/Tool/Component/Connector/Reader/Database/AbstractReader.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Csv/Writer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Xlsx/Writer.php
  src/Akeneo/UserManagement/Component/Connector/Writer/File/AbstractUserWriter.php
Labels: echoes/intent: feature, echoes/effort: S

#19970 CPM-1112: Add doctrine migration to fill the new completeness table
  upgrades/.php_cd.php
  upgrades/schema/Version_8_0_20230628104642_fill_new_completeness_table.php
  upgrades/test_schema/Version_8_0_20230628104642_fill_new_completeness_table_Integration.php
Labels: echoes/intent: feature, echoes/effort: S

#19958 PIM-11062 Fix category filter behavior in product grid
  CHANGELOG.md
  front-packages/shared/src/components/CategoryTree/CategoryTrees.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridCategoryTreeController.php
  src/Akeneo/Pim/Enrichment/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCount.php
  src/Akeneo/Pim/Enrichment/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountHandler.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/TreeView.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/CategoryTree/CategoryTrees.unit.tsx
  tests/back/Pim/Enrichment/Specification/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountHandlerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountSpec.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19973 CPM-1140: Introduce interfaces for product grid queries
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRows.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductModelRowsFromCodesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductRowsFromIdentifiersInterface.php
Labels: echoes/effort: S

#19968 PIM-11008: Pull up 6.0 to 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19948 RAB-1456: DatabaseCommand should not rewrite pim_configuration table
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Doctrine/PimSchemaAssetFilter.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
  tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php
Labels: echoes/intent: feature, echoes/effort: S

#19903 CPM-1107: Remove legacy completeness code (read & write)
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnDelete/DeleteCompletenessSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/removers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetProductCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompleteness.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SwitchVariantProductCompletenessRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/CompletenessRemover.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  tests/back/Integration/catalog/technical_sql/200_products.sql
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php
  tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php
  tests/back/Pim/Enrichment/Integration/Fixture/CompletenessFilter.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlSaveCompletenessesIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenessesSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompletenessSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/SwitchVariantProductCompletenessRatioSpec.php
Labels: echoes/intent: feature

#19862 RAB-1429: Resume export job
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php
  src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php
  src/Akeneo/Tool/Component/Buffer/BufferFactory.php
  src/Akeneo/Tool/Component/Buffer/JSONFileBuffer.php
  src/Akeneo/Tool/Component/Connector/Reader/Database/AbstractReader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Csv/Writer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBuffer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/WrittenFileInfo.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Xlsx/Writer.php
  src/Akeneo/Tool/Component/Connector/Writer/File/Yaml/Writer.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/Database/ReaderSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/Csv/WriterSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php
  src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
  src/Akeneo/UserManagement/Component/Connector/Writer/File/AbstractUserWriter.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Reader/Database/UserRoleSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Reader/File/XlsxUserReaderSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Writer/File/CsvUserWriterSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Writer/File/XlsxUserWriterSpec.php
Labels: echoes/intent: feature, echoes/effort: XL

#19980 PIM-11008: pull up 7.0 to master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
Labels: echoes/intent: feature, echoes/intent: maintenance

#19952 PIM-11071: Fix potential divided by zero in completeness calculation
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
Labels: echoes/intent: maintenance, echoes/effort: S

#19946 GRF-855: User can reorder template attributes FRONTEND
  src/Akeneo/Category/back/Application/Command/ReorderTemplateAttributesCommand/ReorderTemplateAttributesCommand.php
  src/Akeneo/Category/back/Application/Command/ReorderTemplateAttributesCommand/ReorderTemplateAttributesCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Attribute/Attribute.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/ReorderTemplateAttributesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/ReorderTemplateAttributesControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSqlIntegration.php
  src/Akeneo/Category/back/tests/Unit/Domain/ValueObject/Attribute/AttributeCollectionTest.php
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeList.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx
  src/Akeneo/Category/front/src/feature/hooks/useReorderAttributes.ts
Labels: griffins, echoes/intent: feature

#19964 PIM-11075: fix import attribute option with numeric code
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Component/Updater/AttributeOptionUpdater.php
  tests/back/Pim/Structure/Specification/Component/Updater/AttributeOptionUpdaterSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19960 PIM-11067: fix display banner when user does not have system configur…
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/ConfigBundle/Controller/Rest/ConfigurationController.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19977 PIM-11072: Fix missing translation key
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
Labels: echoes/intent: maintenance

#19976 PIM-11073: Fix search with underscore on attribute grid
  CHANGELOG.md
  src/Oro/Bundle/FilterBundle/Filter/StringFilter.php
  src/Oro/Bundle/FilterBundle/spec/Filter/StringFilterSpec.php
  src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/StringFilter.php
Labels: echoes/intent: maintenance

#19986 GRF: add survey monkey link on enrich category
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Labels: griffins
