Repository akeneo/pim-community-dev, pull requests merged in 2023-10, with the labels that each got.

#20321 Pull-up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/translations/jsmessages.it_IT.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-label.js
Labels: echoes/intent: maintenance, echoes/effort: XS

#20313 PIM-11212: Fix error handling in mass associate bulk action
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/readers.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/MassEdit/AddProductValueProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReaderSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XL

#20329 PIM-11251: Fix option comparator when data is null
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionComparator.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionComparatorSpec.php
Labels: echoes/intent: maintenance, echoes/effort: M

#20331 RAB-1598: [7.0] Remove global settings tab from YML export profile
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
Labels: echoes/intent: feature, echoes/intent: technical, echoes/effort: XS
