Repository akeneo/pim-community-dev, pull requests merged in 2023-11, with the labels that each got.

#20334 PIM-11256: Filter values not bound to channel on datagrid
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
Labels: echoes/intent: maintenance, echoes/effort: M

#20338 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.fr_FR.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromUuidsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
Labels: echoes/intent: maintenance, echoes/effort: S

#20328 PIM-11163: Create command to verify attribute types in the database
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckAttributesCompatibilityWithSaasCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  tests/back/Platform/Integration/Installer/CheckAttributesCompatibilityWithSaasCommandIntegration.php
Labels: echoes/intent: technical, echoes/effort: XS

#20341 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Structure/Component/AttributeTypes.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckAttributesCompatibilityWithSaasCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
  tests/back/Platform/Integration/Installer/CheckAttributesCompatibilityWithSaasCommandIntegration.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#20343 [DSM] Add mixed capability to checkbox in TableRow component
  front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx
  front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
  front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.unit.tsx
Labels: design-system

#20342 PIM-11266: Fix value starting with "=<" causes error when exporting in Excel
  CHANGELOG-7.0.md
  src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
Labels: echoes/intent: maintenance, echoes/effort: S

#20345 PIM-11265: Fix mass delete action when using big grid filters
  CHANGELOG-7.0.md
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/mass-delete-action.js
Labels: echoes/intent: maintenance, echoes/effort: S

#20339 PIM-11269: Fix potential lost connection during 6.0 -> 7.0 migration
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php
  upgrades/schema/Version_7_0_20220429131804_execute_uuid_migration.php
Labels: echoes/intent: maintenance, echoes/effort: M

#20349 PIM-10903: Fix Doctrine warning related to Product and Group
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Model/Group.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#20351 PIM-10985: Mark skipped migrations as executed
  CHANGELOG-6.0.md
  upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
  upgrades/schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts.php
  upgrades/schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit.php
  upgrades/schema/Version_6_0_20210331105730_remove_datagrid_view_unique_label_constraint.php
  upgrades/schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts.php
  upgrades/schema/Version_6_0_20211119154203_add_is_stoppable_in_job_execution.php
  upgrades/schema/Version_6_0_20211122154203_add_step_count_in_job_execution.php
  upgrades/schema/Version_6_0_20211124154203_add_is_visible_in_job_execution.php
  upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php
  upgrades/schema/Version_6_0_20211129163800_add_index_on_is_visible_in_job_execution.php
  upgrades/schema/Version_6_0_20211130113100_add_index_to_improve_search_on_job_instance.php
  upgrades/schema/Version_6_0_20211207154203_add_is_trackable_in_step_execution.php
  upgrades/schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query.php
  upgrades/schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit.php
  upgrades/schema/Version_6_0_20220518130906_drop_table_akeneo_batch_job_execution_queue.php
  upgrades/schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables.php
  upgrades/schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution.php
  upgrades/schema/Version_6_0_20220524122443_oro_user_field_consecutive_authentication_failure_counter_is_not_nullable.php
  upgrades/schema/Version_6_0_20220524145600_add_updated_index_on_category.php
  upgrades/test_schema/ExecuteMigrationTrait.php
  upgrades/test_schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts_Integration.php
  upgrades/test_schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts_Integration.php
  upgrades/test_schema/Version_6_0_20211119154203_add_is_stoppable_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211122154203_add_step_count_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211124154203_add_is_visible_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211129163800_add_index_on_is_visible_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211130113100_add_index_to_improve_search_on_job_instance_Integration.php
  upgrades/test_schema/Version_6_0_20211207154203_add_is_trackable_in_step_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query_Integration.php
  upgrades/test_schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit_Integration.php
  upgrades/test_schema/Version_6_0_20220518130906_drop_table_akeneo_batch_job_execution_queue_Integration.php
  upgrades/test_schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables_Integration.php
  upgrades/test_schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20220524145600_add_updated_index_on_category_Integration.php
Labels: echoes/intent: maintenance

#20352 PIM-11289: Fix case-sensitive check in UniqueAxesCombinationSet
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
Labels: echoes/intent: maintenance

#20355 Rebase 6.0 7.0
  CHANGELOG-6.0.md
  upgrades/schema/Version_6_0_20210331105730_remove_datagrid_view_unique_label_constraint.php
  upgrades/schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts.php
  upgrades/schema/Version_6_0_20211119154203_add_is_stoppable_in_job_execution.php
  upgrades/schema/Version_6_0_20211122154203_add_step_count_in_job_execution.php
  upgrades/schema/Version_6_0_20211124154203_add_is_visible_in_job_execution.php
  upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php
  upgrades/schema/Version_6_0_20211129163800_add_index_on_is_visible_in_job_execution.php
  upgrades/schema/Version_6_0_20211130113100_add_index_to_improve_search_on_job_instance.php
  upgrades/schema/Version_6_0_20211207154203_add_is_trackable_in_step_execution.php
  upgrades/schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query.php
  upgrades/schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit.php
  upgrades/schema/Version_6_0_20220518130906_drop_table_akeneo_batch_job_execution_queue.php
  upgrades/schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables.php
  upgrades/schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution.php
  upgrades/schema/Version_6_0_20220524122443_oro_user_field_consecutive_authentication_failure_counter_is_not_nullable.php
  upgrades/schema/Version_6_0_20220524145600_add_updated_index_on_category.php
  upgrades/schema/Version_7_0_20220524134005_add_is_enabled_column_to_catalog.php
  upgrades/schema/Version_7_0_20220629142647_dqi_update_pk_on_product_score.php
  upgrades/schema/Version_7_0_20220808143128_add_value_collection_to_category.php
  upgrades/schema/Version_7_0_20220905141238_update_job_instance_parameter_user_to_notify.php
  upgrades/schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export.php
  upgrades/schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs.php
  upgrades/schema/Version_7_0_20221114112755_clean_family_codes_from_export_job_filters.php
  upgrades/schema/Version_7_0_20221121160755_clean_family_codes_from_export_job_filters.php
  upgrades/schema/Version_7_0_20221212160000_add_database_install_time.php
  upgrades/test_schema/ExecuteMigrationTrait.php
  upgrades/test_schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts_Integration.php
  upgrades/test_schema/Version_6_0_20211119154203_add_is_stoppable_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211122154203_add_step_count_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211124154203_add_is_visible_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211129163800_add_index_on_is_visible_in_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211130113100_add_index_to_improve_search_on_job_instance_Integration.php
  upgrades/test_schema/Version_6_0_20211207154203_add_is_trackable_in_step_execution_Integration.php
  upgrades/test_schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query_Integration.php
  upgrades/test_schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit_Integration.php
  upgrades/test_schema/Version_6_0_20220518130906_drop_table_akeneo_batch_job_execution_queue_Integration.php
  upgrades/test_schema/Version_6_0_20220518134914_set_not_null_fields_for_job_and_step_execution_tables_Integration.php
  upgrades/test_schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution_Integration.php
  upgrades/test_schema/Version_6_0_20220524145600_add_updated_index_on_category_Integration.php
  upgrades/test_schema/Version_7_0_20220905141238_update_job_instance_parameter_user_to_notify_Integration.php
  upgrades/test_schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export_Integration.php
  upgrades/test_schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs_Integration.php
  upgrades/test_schema/Version_7_0_20221114112755_clean_family_codes_from_export_job_filters_Integration.php
  upgrades/test_schema/Version_7_0_20221121160755_clean_family_codes_from_export_job_filters_Integration.php
Labels: echoes/intent: maintenance
