Repository akeneo/pim-community-dev, pull requests merged in 2023-07, with the labels that each got.

#19965 RAB-1463: fix iterator pointer on resume
  src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php
  src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
  src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductModelReaderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductReaderSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Reader/File/XlsxUserReaderSpec.php
Labels: contribution, echoes/intent: feature, echoes/effort: S

#19945 OCT-272: Fix broken link on app store link
  src/Akeneo/Connectivity/Connection/back/Application/Marketplace/MarketplaceUrlGenerator.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Marketplace/MarketplaceUrlGeneratorSpec.php
Labels: echoes/intent: maintenance

#19969 CPM-1138: Remove hardcoded queries with product identifier
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetAssociatedProductUuidsByProductFromDB.php
  tests/back/Pim/Enrichment/Integration/Product/Association/PreventDuplicateVariantAssociation.php
Labels: echoes/intent: feature, echoes/effort: S

#19795 Add dryRun on UpsertProductCommand
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
  src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
Labels: echoes/intent: feature

#19985 OCT-275: Fix flaky test SendBusinessEventToWebhooksEndToEnd
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/Command/SendBusinessEventToWebhooksEndToEnd.php
Labels: echoes/intent: maintenance

#19905 PIM-11035: modify the command to fit with UCS
  CHANGELOG.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/UpdateAuditData.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/Command/UpdateAuditDataCommandEndToEnd.php
Labels: echoes/intent: maintenance

#19753 CPM-1066 : Allow creating more than 1 identifier attribute
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotMainIdentifierOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/IdentifierAttributeCreationLimit.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/IdentifierAttributeCreationLimitValidator.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/SingleIdentifierAttribute.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/SingleIdentifierAttributeValidator.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ConstraintViolationNormalizerSpec.php
  tests/back/Pim/Structure/Integration/Attribute/ImportAttributesIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotIdentifierOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotMainIdentifierOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Validation/IdentifierIntegration.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/IdentifierAttributeCreationLimitValidatorSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/SingleIdentifierAttributeSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/SingleIdentifierAttributeValidatorSpec.php
  tests/legacy/features/pim/structure/attribute/delete_attribute.feature
  tests/legacy/features/pim/structure/attribute/edit_identifier_attribute.feature
Labels: echoes/intent: feature

#19954 PIM-11058 : Adapt user and role import to check administration privileges removal
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessor.php
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php
  src/Akeneo/UserManagement/back/Domain/Permissions/Query/EditRolePermissionsRoleQuery.php
  src/Akeneo/UserManagement/back/Domain/Permissions/Query/EditRolePermissionsUserQuery.php
  tests/back/UserManagement/EndToEnd/Bundle/Controller/Rest/UserControllerEndToEnd.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessorSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php
Labels: echoes/intent: maintenance

#19978 PIM-11011: Fix versioning on common attribute values update using no …
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Akeneo/Tool/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
Labels: echoes/intent: maintenance, echoes/effort: L

#19908 PIM-10676 : Prevent users in the PIM to remove all 'system' permissions
  CHANGELOG.md
  make-file/user-management.mk
  src/Akeneo/UserManagement/.php_cd.php
  src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
  src/Akeneo/UserManagement/Bundle/Controller/RoleController.php
  src/Akeneo/UserManagement/Bundle/Doctrine/ORM/Repository/RoleRepository.php
  src/Akeneo/UserManagement/Bundle/Form/Handler/AclRoleHandler.php
  src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/form.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
  src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
  src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessor.php
  src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php
  src/Akeneo/UserManagement/back/Domain/Permissions/MinimumEditRolePermission.php
  src/Akeneo/UserManagement/back/Domain/Permissions/Query/EditRolePermissionsRoleQuery.php
  src/Akeneo/UserManagement/back/Domain/Permissions/Query/EditRolePermissionsUserQuery.php
  src/Akeneo/UserManagement/back/tests/.php_cs.php
  src/Akeneo/UserManagement/back/tests/Integration/Domain/Permissions/EditRolePermissionsRoleQueryIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/Domain/Permissions/EditRolePermissionsUserQueryIntegration.php
  src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/PasswordCheckerIntegration.php
  tests/back/UserManagement/EndToEnd/Bundle/Controller/Rest/UserControllerEndToEnd.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
  tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessorSpec.php
  tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#20000 RAC-1302: Add test job declaration step to CI
  .circleci/jobs/features/other.yml
  .circleci/workflows/pull_request.yml
Labels: echoes/intent: maintenance, echoes/effort: XS

#19950 PIM-11070: [SLA] [Backport] PIM-10983 - Error HTTP 500 when adding a custom app
  CHANGELOG-6.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseLabelLengthQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseLabelLengthQueryIntegration.php
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
Labels: echoes/intent: maintenance, echoes/intent: technical

#19999 PIM-11088: Catch ElasticSearch exception
  front-packages/shared/src/components/Navigation/PimNavigation.tsx
  front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchKeyIndicators.ts
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/public/js/patch-fetcher.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardCompleteness.ts
Labels: echoes/intent: maintenance

#19996 RAB-1337: Save in db when resetting instance
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/VersionDataCollector.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Event/InstallerEvents.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Event/Subscriber/UpdateLastResetDateSubscriber.php
  src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Persistence/Sql/GetResetEvents.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Persistence/Sql/SaveResetEvent.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/subscribers.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Controller/ResetInstanceAction.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
  tests/back/Platform/Integration/Installer/Persistence/Sql/GetInstallDatetimeIntegration.php
  tests/back/Platform/Integration/Installer/Persistence/Sql/GetResetEventsIntegration.php
  tests/back/Platform/Integration/Installer/Persistence/Sql/SaveResetEventIntegration.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/VersionDataCollectorSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#20003 Pull-up 6.0 to 7.0
  .circleci/jobs/features/other.yml
  .circleci/workflows/pull_request.yml
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRows.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductModelRowsFromCodesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductRowsFromIdentifiersInterface.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#20001 PIM-11090: Add missing translations for Process Tracker
  CHANGELOG.md
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: maintenance, echoes/effort: XS

#20014 PIM-11095: Make image extension check case insensitive
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFileValidator.php
  src/Akeneo/Tool/Bundle/FileStorageBundle/spec/Validator/Constraints/UploadedFileValidatorSpec.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19992 RAB-1328: Storage cleanup job
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Installer/back/src/Application/ResetInstance/ResetInstanceHandler.php
  src/Akeneo/Platform/Installer/back/src/Domain/.gitkeep
  src/Akeneo/Platform/Installer/back/src/Domain/Service/FilesystemsPurgerInterface.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/FilesystemsPurger/FilesystemPurger.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/FilesystemsPurger/FilesystemsPurger.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Job/PurgeFilesystemsTasklet.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoInstallerExtension.php
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/services.yml
  src/Akeneo/Platform/Installer/back/tests/.php_cd.php
  src/Akeneo/Platform/Installer/back/tests/Acceptance/FakeServices/FakeFilesystemsPurger.php
  src/Akeneo/Platform/Installer/back/tests/Acceptance/Resources/config/fake_services.yml
  src/Akeneo/Platform/Installer/back/tests/Acceptance/UseCases/ResetInstance/ResetInstanceTest.php
  src/Akeneo/Platform/Installer/back/tests/Integration/FilesystemsPurger/FilesystemPurgeTest.php
  src/Akeneo/Platform/Installer/back/tests/Specification/Infrastructure/FilesystemsPurger/FilesystemsPurgerSpec.php
  src/Akeneo/Platform/Installer/back/tests/Specification/Infrastructure/Job/PurgeFilesystemsTaskletSpec.php
  src/Akeneo/Platform/Installer/back/tests/Specification/Infrastructure/UserConfigurationResetter/UserConfigurationResetterSpec.php
  upgrades/schema/Version_8_0_20230630161600_add_purge_filesystems_job_instance.php
  upgrades/test_schema/Version_8_0_20230630161600_add_purge_filesystems_job_instance_Integration.php
Labels: echoes/intent: feature

#19993 RAB-1452: Pause/Resume mass edit
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/FilteredProductAndProductModelReader.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php
Labels: echoes/intent: feature, echoes/effort: S

#20017 RAB-1420: Log error message when failing to push paused jobs to queue
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishPausedJobsToQueue.php
  src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishPausedJobsToQueueSpec.php
Labels: echoes/intent: feature, echoes/effort: XS

#20015 CPM-1075: Display main identifier value in GET and LIST product endpoints
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#19995 CPM-1133: Add tests on date update after main identifier update
  tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
Labels: echoes/intent: feature, echoes/effort: XS

#20016 Pull-up 7.0 to master
  .circleci/jobs/features/other.yml
  .circleci/workflows/pull_request.yml
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRows.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductModelRowsFromCodesInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FetchProductRowsFromUuidsInterface.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#19983 CPM-1067: Add endpoint to switch main identifier
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierCommand.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierHandler.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierValidator.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/SwitchMainIdentifierController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/handlers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SwitchMainIdentifierControllerEndToEnd.php
  tests/back/Pim/Structure/Integration/Attribute/SwitchMainIdentifierIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
Labels: echoes/intent: feature

#20030 PIM-11070: Pull-up 6.0 to 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseLabelLengthQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/persistence.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseLabelLengthQueryIntegration.php
  src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
Labels: echoes/intent: maintenance, echoes/intent: technical

#19929 RAB-1445: Add ZDDmigration in order to remove the old instant cols on mysql server in order to avoid having index corruption
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
  src/Akeneo/Tool/Bundle/StorageUtilsBundle/tests/integration/TableWithOldInstantColsCannotHaveNewColumnUntilUcsMigrationTest.php
  src/Akeneo/Tool/Component/StorageUtils/Migration/V20230622175500OptimizeTableWithInstantColsMigration.php
  upgrades/.php_cd.php
  upgrades/schema/Version_8_0_20230627173000_remove_instant_cols.php
  upgrades/test_schema/Version_8_0_20230627173000_remove_instant_cols_Integration.php
Labels: echoes/intent: technical, echoes/effort: M

#19832 CPM-1082: Update getIdentifier in AbstractProduct and deprecate setIdentifier
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Integration/Import/ImportProductsIntegration.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/IdentifierValueFactory.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/IdentifierFormatGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/LengthGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/UniqueIdentifierValueGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/UniqueValueGuesser.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/ProductContext.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AssociationUserIntentCollectionApplierSpec.php
  src/Oro/Bundle/PimDataGridBundle/Datasource/ProductDatasource.php
  src/Oro/Bundle/PimDataGridBundle/spec/Datasource/ProductDatasourceSpec.php
  tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
  tests/back/Acceptance/Attribute/InMemoryGetAttributes.php
  tests/back/Acceptance/Product/InMemoryProductRepository.php
  tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/LengthGuesserSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/UniqueValueGuesserSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
  tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature
Labels: echoes/intent: feature, echoes/effort: L

#19926 [on hold for CPM-1107] CPM-1042: Remove completeness table
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
  upgrades/schema/Version_8_0_20230720113636_drop_product_completeness_table.php
  upgrades/test_schema/Version_8_0_20230417092236_fix_completeness_table_auto_increment_Integration.php
  upgrades/test_schema/Version_8_0_20230720113636_drop_product_completeness_table_Integration.php
Labels: echoes/intent: feature

#20024 PIM-11083: [backport] CPM-653: do not sort on _id in ES cursors
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
  src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Elasticsearch/ElasticsearchProductUuidQueryFetcher.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactorySpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactorySpec.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#20067 PIM-11099: Fix regression on filtering products and product models on Identifier containing a dash character
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
Labels: bug, echoes/intent: maintenance

#20059 CPM-1153: Add disabled prop to Tile component
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-tiles-size-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.stories.mdx
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.tsx
  front-packages/akeneo-design-system/src/components/Tiles/Tiles.unit.tsx
  front-packages/akeneo-design-system/src/components/Tooltip/Tooltip.tsx
Labels: echoes/intent: feature

#20075 CPM-1161: Fix unicity validation for non-main identifier values
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductUniqueDataRepository.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductUniqueDataRepositoryInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/IdentifierFormatGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/UniqueIdentifierValueGuesser.php
  src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/UniqueValueGuesser.php
  tests/back/Acceptance/Catalog/Context/ProductCreation.php
  tests/back/Acceptance/Product/InMemoryProductUniqueDataRepository.php
  tests/back/Acceptance/Resources/config/pim/repositories.yml
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/UniqueValueGuesserSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueValueValidatorSpec.php
  tests/features/pim/enrichment/product/validation/identifiers.feature
Labels: echoes/intent: feature, echoes/effort: S

#20048 CPM-1152: Add Danger Zone in attributes edit
  src/Akeneo/Pim/Structure/Bundle/Resources/config/requirejs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/AttributeSetupApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/attribute-setup.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/models/Attribute.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/create.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/properties/localizable.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/properties/scopable.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/properties/type.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/properties/unique.js
Labels: echoes/intent: feature

#20053 CPM-1149: Add button to switch main identifier
  front-packages/shared/src/components/DeleteModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CanNotSwitchMainIdentifierException.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CanNotSwitchMainIndentifierWithPublishedProductException.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CommunityPublishedProductExists.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/PublishedProductExists.php
  src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierValidator.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/SwitchMainIdentifierController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/AttributeSetupApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/attribute-setup.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#20054 RAB-1518: Make pause and resume working with remote storage
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/JobExecutionController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/UploadStep.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/Local/LocalStorageClientProvider.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/step.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/StepExecutionArchivist.php
  src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/archiving.yml
  src/Akeneo/Tool/Bundle/ConnectorBundle/spec/EventListener/StepExecutionArchivistSpec.php
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractFilesystemArchiver.php
  src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
  src/Akeneo/Tool/Component/Connector/Archiver/ArchiverInterface.php
  src/Akeneo/Tool/Component/Connector/Archiver/FileReaderArchiver.php
  src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php
  src/Akeneo/Tool/Component/Connector/spec/Archiver/FileReaderArchiverSpec.php
  src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
Labels: echoes/intent: feature, echoes/effort: M

#20069 PIM-11101: Inconsistent behaviour on category label due to wrong upper/lower case
  CHANGELOG.md
  src/Akeneo/Category/back/Infrastructure/Component/Model/Category.php
  src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/CreateCategoryEndToEnd.php
Labels: griffins, echoes/intent: maintenance

#20082 CPM-1169: Add Translate with Components
  front-packages/shared/src/components/DeleteModal.tsx
  front-packages/shared/src/hooks/index.ts
  front-packages/shared/src/hooks/useTranslateWithComponents.tsx
  front-packages/shared/src/hooks/useTranslateWithComponents.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/AttributeSetupApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#20081 PIM-11103: Fix deletion of enriched category attribute when deleting attribute
  CHANGELOG.md
  src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAttributeAndEnrichedValues/CleanCategoryTemplateAttributeAndEnrichedValuesCommandHandler.php
  src/Akeneo/Category/back/Application/Query/GetDeactivatedAttribute.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDeactivatedCategoryTemplateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryTemplateAttributeAndEnrichedValues/CleanCategoryTemplateAttributeAndEnrichedValuesCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDeactivatedCategoryTemplateAttributeSqlIntegration.php
Labels: griffins, echoes/intent: maintenance

#19735 GRF-819: Remove feature flag: customize template
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/AddAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/DeactivateAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/ReorderTemplateAttributesControllerEndToEnd.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/TrackUsageOfLoadPredefinedAttributesControllerEndToEnd.php
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/AttributeList.tsx
Labels: griffins

#20050 CPM-1151: Add progress indicator and additional fields in attribute c…
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/CreateAttributeProgressIndicator.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/CreateAttributeModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/styles.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/CreateAttributeButtonApp.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/SelectAttributeType.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/edit-form.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
Labels: echoes/intent: feature

#20093 RAB-1541: Do not make the File required on LaunchJobInstanceCommand ServiceApi
  src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/LaunchJobInstanceHandler.php
  src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceCommand.php
Labels: echoes/intent: feature

#20049 PIM-11078: Double check file Mime Type before upload
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
  src/Akeneo/Tool/Component/FileStorage/spec/File/FileStorerSpec.php
Labels: echoes/intent: maintenance, echoes/effort: M

#20077 RAC-1247: Pluralize download file button label
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionDetail.test.tsx
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionDetail.tsx
  tests/legacy/features/pim/enrichment/product/import/import_products_and_download_imported_file.feature
  tests/legacy/features/platform/import/import.feature
Labels: echoes/intent: maintenance, echoes/effort: XS

#20109 CPM-1164: Add is main identifier information to attribute datagrid
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/attribute-type-cell.js
  src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#20089 CPM-1104: Use React for Choose component
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/ChooseApp.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/choose.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/choose.tsx
Labels: echoes/intent: feature

#20083 CPM-1165: Visualize main identifier in associations
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/UuidMapping.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associated-product-row.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Labels: echoes/intent: feature, echoes/effort: S

#20099 CPM-1080: Forbid deletion of main identifier (front)
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/hooks/__mocks__/useMainIdentifierCode.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/hooks/index.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/hooks/useGetIdentifierAttributesCount.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/hooks/useMainIdentifierCode.ts
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteAction.unit.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteModal.unit.tsx
  tests/legacy/features/pim/structure/attribute/delete_attribute.feature
Labels: echoes/intent: feature

#20123 PIM-11117: Pull-up from 6.0 to 7.0
  CHANGELOG-6.0.md
Labels: echoes/intent: maintenance

#20098 PIM-11106: Filter empty attribute option labels
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeOptionNormalizer.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/GetAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/Specification/Bundle/Form/Type/AttributeOptionTypeSpec.php
Labels: echoes/intent: maintenance
