Repository akeneo/pim-community-dev, pull requests merged in 2023-03, with the labels that each got.

#19312 GRF-771 : Update get categories SQL
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Labels: griffins, echoes/intent: feature

#19310 Fix PEF display for localizable and scopable values with wrong case
  CHANGELOG-6.0.md
  src/Akeneo/Channel/.php_cd.php
  src/Akeneo/Channel/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php
  src/Akeneo/Channel/Component/Query/PublicApi/GetCaseSensitiveChannelCodeInterface.php
  src/Akeneo/Channel/Component/Query/PublicApi/GetCaseSensitiveLocaleCodeInterface.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  tests/back/Channel/Specification/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
Labels: echoes/intent: maintenance

#19240 PIM-10855: Fix products and models with empty attribute values are counted by CountItemsWithAttributeValueAction
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/CountItemsWithAttributeValueAction.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductModelsWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsWithRemovedAttributeInterface.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx
  tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllProductIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductExistingAmongIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductNotSynchronisedBetweenEsAndMysqlIntegration.php
Labels: echoes/intent: maintenance

#19286 OCT-226: add a try catch to make silent exceptions
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Command/PurgeConnectionErrorsCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
Labels: echoes/intent: technical

#19193 CPM-962: Add simple selects to AddButtonProperty
  components/identifier-generator/front/src/feature/hooks/__mocks__/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetPropertyItems.test.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetAttributeByCode.ts
  components/identifier-generator/front/src/feature/hooks/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/hooks/useGetPropertyItems.ts
  components/identifier-generator/front/src/feature/models/attribute.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/itemsGroup.ts
  components/identifier-generator/front/src/feature/models/properties/propertyItem.ts
  components/identifier-generator/front/src/feature/models/structure.ts
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/AddPropertyButton.test.tsx
Labels: echoes/intent: feature

#19297 RAB-1265: Prevent remove & warn when cannot remove attributes
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AttributeRemovalSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotAFamilyVariantAxisOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotIdentifierOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotUsedAsChannelConversionUnitOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotUsedAsLabelOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Component/Attribute/Job/DeleteAttributesTasklet.php
  src/Akeneo/Pim/Structure/Component/Exception/AttributeRemovalException.php
  src/Akeneo/Pim/Structure/Component/Exception/CannotRemoveAttributeException.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotAFamilyVariantAxisOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotIdentifierOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotUsedAsChannelConversionUnitOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/Attribute/Query/CheckAttributeIsNotUsedAsLabelOnDeletionSubscriberIntegration.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/CheckAttributeOnDeletionSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Component/Attribute/Job/DeleteAttributesTaskletSpec.php
Labels: echoes/intent: feature

#19256 PIM-10860 - Fix display announcements
  CHANGELOG.md
  package.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Elasticsearch/CountVariantProducts.php
  src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Description.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProvider.php
  tests/back/Platform/Specification/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Elasticsearch/CountVariantProductsSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProviderSpec.php
  yarn.lock
Labels: griffins, echoes/intent: maintenance

#19307 RAB-1263: Create a dedicated controller for mass delete attributes instead of using enrichment one
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/attribute-mass-delete-action.ts
Labels: echoes/intent: feature

#19301 AST-453: Add DateInput component to the DSM
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-date-input-html-props-max-min-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-date-input-invalid-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-date-input-read-only-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-date-input-standard-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.tsx
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.unit.tsx
  front-packages/akeneo-design-system/src/components/Input/index.ts
Labels: design-system, salamander

#19324 GROWTH-45: Add FreeTrial front in eslintignore
  .eslintignore
Labels: butterfly

#19315 Pullup 7.0 => master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
  src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Controller/AjaxOptionController.php
  src/Akeneo/Platform/PimRequirements.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
  tests/back/Platform/Specification/Bundle/UIBundle/Controller/AjaxOptionControllerSpec.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#19320 CPM-981: Add custom message for deleted attributes
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/errors/AttributeNotFound.ts
  components/identifier-generator/front/src/feature/errors/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetAttributeByCode.ts
  components/identifier-generator/front/src/feature/tabs/conditions/SimpleOrMultiSelectLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleOrMultiSelectLine.test.tsx
Labels: echoes/intent: feature

#19050 CXP-1389: Constraint - required target
  components/catalogs/back/src/Application/Exception/ProductMappingRequiredSourceMissingException.php
  components/catalogs/back/src/Application/Mapping/ProductMapper.php
  components/catalogs/back/src/Application/Persistence/ProductMappingSchema/GetProductMappingSchemaQueryInterface.php
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/ProductMappingSchema/GetProductMappingSchemaQuery.php
  components/catalogs/back/src/Infrastructure/PqbFilters/PqbFiltersInterface.php
  components/catalogs/back/src/Infrastructure/PqbFilters/ProductMappingRequiredFilters.php
  components/catalogs/back/src/Infrastructure/PqbFilters/ProductSelectionCriteria.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.10.json
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-enum-of-number-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-enum-of-string-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-enum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-maxLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-maximum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-minLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-minimum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-pattern-value.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-required-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-missing-required-property.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-unsupported-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-unsupported-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-maxLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-maximum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-minLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-minimum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.10-with-wrong-type-for-pattern.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.10.json
  components/catalogs/back/tests/Unit/Infrastructure/PqbFilters/ProductMappingRequiredFiltersTest.php
  components/catalogs/back/tests/Unit/Infrastructure/PqbFilters/ProductSelectionCriteriaTest.php
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/TargetSourceAssociation.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
Labels: wip, echoes/intent: feature

#19331 CPM-986: Fix cache on get families
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
Labels: echoes/intent: feature

#19338 RAB-1264: Fix breakit and UX review
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotUsedAsLabelOnDeletionSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
Labels: echoes/intent: feature

#19329 RAB-1287: Move delete attribute groups error into a dedicated subscriber
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeGroupOtherCannotBeRemovedSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeGroupWithAttributeCannotBeRemovedSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Component/Exception/AttributeGroupOtherCannotBeRemoved.php
  src/Akeneo/Pim/Structure/Component/Exception/AttributeGroupWithAttributeCannotBeRemoved.php
  src/Akeneo/Pim/Structure/Component/Exception/UserFacingError.php
  tests/back/Pim/Structure/Integration/AttributeGroup/EventSubscriber/CheckAttributeGroupOtherCannotBeRemovedSubscriberIntegration.php
  tests/back/Pim/Structure/Integration/AttributeGroup/EventSubscriber/CheckAttributeGroupWithAttributeCannotBeRemovedSubscriberIntegration.php
Labels: echoes/intent: feature

#19313 PIM-10745: Fix history display for product's quantified association
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/VersioningController.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/localization/presenters.yml
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductIdentifier.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/VersionNormalizer.php
  src/Akeneo/Pim/Enrichment/Component/Product/Query/FindIdentifier.php
  src/Akeneo/Tool/Component/Localization/Presenter/ProductQuantifiedAssociationPresenter.php
  src/Akeneo/Tool/Component/Localization/spec/Presenter/ProductQuantifiedAssociationPresenterSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlFindProductIdentifierIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/VersionNormalizerSpec.php
Labels: echoes/intent: maintenance

#19290 PIM-10863: Fix import product without sku column
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
  src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductRepositoryInterface.php
  tests/back/Pim/Enrichment/Integration/Product/Import/ImportProductsIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
Labels: echoes/intent: maintenance

#19332 RAB-1358: Fixes after breakit on bulk delete attribute groups
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts
Labels: echoes/intent: feature

#19334 RAB-1286: Add mass delete attribute group job
  src/Akeneo/Pim/Structure/Bundle/Infrastructure/Job/AttributeGroup/DeleteAttributeGroupsTasklet.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/job_constraints.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/job_defaults.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
  upgrades/schema/Version_8_0_20230223170000_add_mass_delete_attribute_groups_job_instance.php
  upgrades/test_schema/Version_8_0_20230223170000_add_mass_delete_attribute_groups_job_instance_Integration.php
Labels: echoes/intent: feature

#18699 CPM-791: Be able to search by UUID in the searchbar
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/LabelOrIdentifierFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_product_picker.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/row.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/models/row.unit.ts
  tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/LabelOrIdentifierFilterSpec.php
  tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature
Labels: echoes/intent: feature

#19335 PIM-10874 : fix labels api type consistency
  CHANGELOG.md
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
Labels: echoes/intent: maintenance

#19357 CPM-970: Update get available conditions
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php
Labels: echoes/intent: feature

#19351 CPM-989: Disable the edit nomenclature button in read-only mode
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
Labels: echoes/intent: feature

#19339 CPM-971: Add CategoriesSelector
  components/identifier-generator/back/src/Infrastructure/Controller/GetCategoryLabelsController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetCategoryLabelsControllerEndToEnd.php
  components/identifier-generator/front/src/feature/components/CategoriesSelector.tsx
  components/identifier-generator/front/src/feature/components/CategoryTreeSwitcher.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/__tests__/CategoriesSelector.test.tsx
  components/identifier-generator/front/src/feature/components/__tests__/CategoryTreeSwitcher.test.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useCategoryLabels.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useCategoryTree.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useCategoryTrees.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useCategoryLabels.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useCategoryTree.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useCategoryTrees.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useCategoryLabels.ts
  components/identifier-generator/front/src/feature/hooks/useCategoryTree.ts
  components/identifier-generator/front/src/feature/hooks/useCategoryTrees.ts
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
  components/identifier-generator/front/src/feature/tests/test-utils.tsx
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-existing-value-and-labels-correctly-1-snap.png
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-inputs-tag-input-variation-on-invalid-values-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Dropdown/Header/Header.tsx
  front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.stories.mdx
  front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
  front-packages/akeneo-design-system/src/components/Tree/Tree.tsx
  front-packages/shared/src/components/CategoryTree/CategoryTrees.tsx
  front-packages/shared/src/components/CategoryTree/RecursiveCategoryTree.tsx
  front-packages/shared/src/components/CategoryTree/categoryParseResponse.ts
  front-packages/shared/src/components/CategoryTree/index.ts
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Category/GetCategoryTranslations.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/TreeAssociate.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/TreeView.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/category/Selector.tsx
Labels: echoes/intent: feature

#19363 CPM-990: Case insensitive UUID filter
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/UuidFilter.php
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/UuidFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/UuidFilterSpec.php
Labels: echoes/intent: feature

#19354 PIM-10878: Fix filtering products with identifiers would not display some product models
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
Labels: echoes/intent: maintenance

#19355 Fix box-sizing reset issue with the svg icons
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.tsx
Labels: design-system, salamander

#19370 CPM-985: Fix maximum width for IconCardGrid
  front-packages/akeneo-design-system/src/components/IconCard/IconCard.tsx
Labels: echoes/intent: feature

#19369 CPM-987: Fix scroll on nomenclature
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
Labels: echoes/intent: feature

#19353 RAB-1362: make attribute groups unselectable for prod
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
Labels: contribution, echoes/intent: feature

#19341 GRF-688: fix to handle http 403
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/DeactivateTemplateController.php
  src/Akeneo/Category/front/src/feature/hooks/useDeactivateTemplate.ts
  src/Akeneo/Category/front/src/feature/tools/apiFetch.test.ts
  src/Akeneo/Category/front/src/feature/tools/apiFetch.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19379 PIM-10877: Sequential edit is not working if grid is sorted by quality score
  CHANGELOG.md
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
Labels: echoes/intent: maintenance

#19392 CPM-1002: Fix SimpleSelectProperty normalize to not retrieve scope and locale if not needed
  components/identifier-generator/back/src/Domain/Model/Property/SimpleSelectProperty.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorWithSimpleSelectEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php
  components/identifier-generator/front/src/feature/hooks/useGetAttributeByCode.ts
Labels: echoes/intent: feature

#19390 CPM-960: Add GenerateSimpleSelectHandler
  components/identifier-generator/back/src/Application/Generate/Property/GenerateSimpleSelectHandler.php
  components/identifier-generator/back/src/Domain/Model/Property/SimpleSelectProperty.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateSimpleSelectHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php
Labels: echoes/intent: feature

#18882 PIM-10793: pim_api_access_token and pim_api_refresh_token tabels are never purged
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Command/DeleteExpiredApiTokens.php
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
  src/Akeneo/Tool/Bundle/ApiBundle/Doctrine/DBAL/DeleteExpiredAccessTokenQuery.php
  src/Akeneo/Tool/Bundle/ApiBundle/Doctrine/DBAL/DeleteExpiredRefreshTokenQuery.php
  src/Akeneo/Tool/Bundle/ApiBundle/Handler/DeleteExpiredTokensHandler.php
  src/Akeneo/Tool/Bundle/ApiBundle/Job/DeleteExpiredTokens.php
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/cli_commands.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/handlers.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/jobs.yml
  src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/queries.yml
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Doctrine/DBAL/DeleteExpiredAccessTokenQueryIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Doctrine/DBAL/DeleteExpiredRefreshTokenQueryIntegration.php
  src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Handler/DeleteExpiredTokensHandlerIntegration.php
  upgrades/schema/Version_8_0_20230124095459_add_scheduled_job_delete_expired_tokens.php
  upgrades/test_schema/Version_8_0_20230124095459_add_scheduled_job_delete_expired_tokens_Integration.php
Labels: echoes/intent: maintenance

#19314 RAC-1288: Handle exceptions triggering logs in MetricPresenter
  src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
Labels: contribution, echoes/intent: feature, echoes/intent: maintenance

#19402 OCT-204: removed weekly code quality dead config
  .circleci/jobs/features/connectivity.yml
  .circleci/workflows/squads/octopus/octopus_weekly_code_quality.yml
Labels: echoes/intent: technical

#19388 RAB-1365: Bug fix on mass delete attribute group
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
Labels: echoes/intent: feature

#19403 RAB-1365: Fix UI glitch
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
Labels: echoes/intent: feature

#19405 AST-527: Fix memoize callback issue with DateInput component
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.tsx
  front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.unit.tsx
Labels: design-system, salamander

#19410 PIM-10876: Revert cleanup migration from fix
  upgrades/schema/Version_8_0_20230308145000_set_empty_categories_labels_to_null.php
  upgrades/test_schema/Version_8_0_20230308145000_set_empty_categories_labels_to_null_Integration.php
Labels: griffins, echoes/intent: maintenance

#19358 RAB-1255: Add ACL for bulk remove attributes
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/acl.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  upgrades/schema/Version_8_0_20230308152730_disable_attributes_mass_delete_acl.php
  upgrades/test_schema/Version_8_0_20230308152730_disable_attributes_mass_delete_acl_Integration.php
Labels: echoes/intent: feature

#19364 RAB-1281: Add ACL for Bulk remove attribute groups
  src/Akeneo/Pim/Structure/Bundle/Infrastructure/Controller/MassDeleteAttributeGroupsController.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/acl.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  upgrades/schema/Version_8_0_20230308113214_disable_attribute_groups_mass_delete_acl.php
  upgrades/test_schema/Version_8_0_20230308113214_disable_attribute_groups_mass_delete_acl_Integration.php
Labels: echoes/intent: feature

#19350 CXP-1415: Add IS NOT EMPTY to CategoryFilter to use it on the ProductQueryBuilder
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/CategoryFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Filter/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/CategoryFilterSpec.php
Labels: echoes/intent: feature

#19414 CPM-1003: Fix CategoryQueryHandler::byCodes() type error
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/ServiceApi/InternalApiCategory.php
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/InternalApiCategoryIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19372 GRF-704: Refactor enriched values clean on categories for channel and locale
  src/Akeneo/Category/back/Application/Command/CleanCategoryEnrichedValuesByChannelOrLocale/CleanCategoryEnrichedValuesByChannelOrLocaleCommand.php
  src/Akeneo/Category/back/Application/Command/CleanCategoryEnrichedValuesByChannelOrLocale/CleanCategoryEnrichedValuesByChannelOrLocaleCommandHandler.php
  src/Akeneo/Category/back/Application/Enrichment/CategoryDataCleaner.php
  src/Akeneo/Category/back/Application/Enrichment/CleanCategoryDataLinkedToChannel.php
  src/Akeneo/Category/back/Application/Enrichment/Filter/ByChannelAndLocalesFilter.php
  src/Akeneo/Category/back/Application/Query/GetEnrichedCategoryValuesOrderedByCategoryCode.php
  src/Akeneo/Category/back/Application/Query/GetEnrichedValuesPerCategoryCode.php
  src/Akeneo/Category/back/Application/Storage/UpdateCategoryEnrichedValues.php
  src/Akeneo/Category/back/Domain/ValueObject/ValueCollection.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelChangeSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Job/CleanCategoriesEnrichedValuesTasklet.php
  src/Akeneo/Category/back/Infrastructure/Job/CleanCategoriesTemplateEnrichedValuesTasklet.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetEnrichedCategoryValuesOrderedByCategoryCodeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetEnrichedValuesPerCategoryCodeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/Update/UpdateCategoryEnrichedValuesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cleaners.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Category/back/tests/Integration/Application/ActivateTemplateIntegration.php
  src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryEnrichedValuesByChannelOrLocale/CleanCategoryEnrichedValuesByChannelOrLocaleCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Application/Enrichment/CleanCategoryDataLinkedToChannelIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetEnrichedValuesPerCategoryCodeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/Update/UpdateCategoryEnrichedValuesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Enrichment/Filter/ByChannelAndLocalesFilterSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelChangeSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryTemplateAndEnrichedValuesOnTemplateDeactivatedSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Job/CleanCategoriesEnrichedValuesTaskletSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Job/CleanCategoriesTemplateEnrichedValuesTaskletSpec.php
  src/Akeneo/Category/back/tests/Unit/Application/Command/DeactivateTemplateCommandHandlerTest.php
  src/Akeneo/Category/back/tests/Unit/Application/Enrichment/CategoryDataCleanerTest.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19296 PIM-10861: Fix calcuation of completeness channel ratio on Activity Dashboard
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/convertBackendDashboardCompletenessData.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/tests/front/unit/helpers/convertBackendDashboardCompletenessData.unit.ts
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php
Labels: echoes/intent: maintenance

#19326 GROWTH-10: Move FT features to serenity codebase
  .eslintignore
Labels: butterfly

#19298 PIM-10856: Prevent the creation of a useless PHP session when a new token is created in the API
  CHANGELOG.md
  src/Akeneo/UserManagement/Bundle/EventListener/LocaleSubscriber.php
  tests/back/UserManagement/Specification/Bundle/EventListener/LocaleSubscriberSpec.php
Labels: echoes/intent: maintenance

#19438 SP-490: add a service API to retrieve a list of families or a single Family
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetFamilies.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/Family.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/GetFamilies.php
  tests/back/Pim/Structure/Integration/Family/SqlGetFamilyIntegration.php
Labels: echoes/intent: feature

#19426 CPM-975: Move filter line and add Helper
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
Labels: echoes/intent: feature

#19420 GRF-774: Backend - add attribute text
  src/Akeneo/Category/back/Api/Command/Exceptions/ViolationsException.php
  src/Akeneo/Category/back/Application/Command/AddAttributeCommand.php
  src/Akeneo/Category/back/Application/Command/AddAttributeCommandHandler.php
  src/Akeneo/Category/back/Domain/Event/AttributeAddedEvent.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCode.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/AddAttributeController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/attribute_commands.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Validation/AttributeCodeShouldBeUniqueInTheTemplate.php
  src/Akeneo/Category/back/Infrastructure/Validation/AttributeCodeShouldBeUniqueInTheTemplateValidator.php
  src/Akeneo/Category/back/Infrastructure/Validation/LimitNumberOfAttributesInTheTemplate.php
  src/Akeneo/Category/back/Infrastructure/Validation/LimitNumberOfAttributesInTheTemplateValidator.php
  src/Akeneo/Category/back/tests/.php_cd.php
  src/Akeneo/Category/back/tests/EndToEnd/Helper/ControllerIntegrationTestCase.php
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/AddAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Specification/Application/Command/AddAttributeCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/AttributeCodeShouldBeUniqueInTheTemplateValidatorSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/LimitNumberOfAttributesInTheTemplateValidatorSpec.php
  src/Akeneo/Category/front/src/feature/models/ResponseStatus.ts
Labels: griffins, echoes/intent: feature

#19435 CPM-1004: Add tables and migration for simple select nomenclature
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  upgrades/schema/Version_8_0_20230315132124_create_identifier_generator_simple_select_nomenclature_tables.php
  upgrades/test_schema/Version_8_0_20230315132124_create_identifier_generator_simple_select_nomenclature_tables_Integration.php
Labels: echoes/intent: feature

#19348 CXP-1414: Constraint - string[] - enum
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.12.json
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-enum-of-array-string-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-enum-of-number-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-enum-of-string-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-enum-type-for-array.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-enum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-items-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-maxLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-maximum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-minLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-minimum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-pattern-value.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-required-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-missing-array-items-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-missing-array-items.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-missing-required-property.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-unsupported-array-items-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-unsupported-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-unsupported-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-items.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-maxLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-maximum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-minLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-minimum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.12/0.0.12-with-wrong-type-for-pattern.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.12.json
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/utils/createTargetFromProductMappingSchema.ts
  components/catalogs/front/src/components/ProductMapping/utils/createTargetFromProductMappingSchema.unit.ts
Labels: echoes/intent: feature

#19455 CPM-968: fix acceptance tests
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetCategoryInMemory.php
  tests/back/Acceptance/Resources/config/pim/repositories.yml
Labels: echoes/intent: feature

#19278 CXP-1374: Map measurement attributes (number)
  components/catalogs/back/rector.php
  components/catalogs/back/src/Application/Mapping/Measurement/MeasurementConverter.php
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromMetricAttributeValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Application/Persistence/Measurement/GetMeasurementsFamilyQueryInterface.php
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Persistence/Measurement/GetMeasurementsFamilyQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeMetricSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidMetricUnit.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidMetricUnitValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Acceptance/DatabaseContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/Measurement/MeasurementConverterTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromMetricAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Measurement/GetMeasurementsFamilyQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.ts
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectMeasurementUnitDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SourceParameters.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
  components/catalogs/front/src/components/ProductMapping/models/SourceParameter.d.ts
  components/catalogs/front/src/components/ProductMapping/models/SourceParameterErrors.d.ts
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.unit.ts
  components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementValueInput.tsx
  components/catalogs/front/src/hooks/useMeasurements.ts
  components/catalogs/front/src/hooks/useMeasurements.unit.ts
  components/catalogs/front/src/models/MeasurementUnit.d.ts
Labels: echoes/intent: feature

#19439 OCT-233: Added email_verified claim to JWT token
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateJsonWebToken.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateJsonWebTokenSpec.php
Labels: echoes/intent: technical

#19396 CPM-999: Apply complex filter with match
  components/identifier-generator/back/src/Application/Match/Condition/MatchCategoryHandler.php
  components/identifier-generator/back/src/Domain/Query/CategoriesHaveAtLeastOneChild.php
  components/identifier-generator/back/src/Infrastructure/AntiCorruptionLayer/CategoriesHaveAtLeastOneChild.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/anti_corruption_layers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Specification/Application/Match/Condition/MatchCategoryHandlerSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/front/src/feature/models/conditions/conditions.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateConditions.test.ts
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/CategoriesHaveAtLeastOneChild.php
  src/Akeneo/Category/back/ServiceApi/Query/CategoriesHaveAtLeastOneChild.php
  src/Akeneo/Pim/Enrichment/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  tests/back/Category/Integration/Query/CategoriesHaveAtLeastOneChildIntegration.php
Labels: echoes/intent: feature

#19287 CXP-1415: Map categories (string)
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Handler/GetMappedProductsHandler.php
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromCategoriesValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Application/Persistence/Category/GetProductCategoriesLabelsQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Category/GetProductCategoriesLabelsQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromCategoriesValueExtractorTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSourceTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SourceParameters.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts
  components/catalogs/front/src/hooks/useAttribute.ts
  components/catalogs/front/src/hooks/useAttribute.unit.ts
  components/catalogs/front/src/hooks/useSystemAttributes.ts
  components/catalogs/front/src/hooks/useSystemAttributes.unit.ts
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/CategoryFilter.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
  tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Filter/CategoryFilterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/CategoryFilterSpec.php
Labels: echoes/intent: feature

#19457 PIM-10897: Pull up from 6.0 to 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Channel/back/API/Query/GetCaseSensitiveChannelCodeInterface.php
  src/Akeneo/Channel/back/API/Query/GetCaseSensitiveLocaleCodeInterface.php
  src/Akeneo/Channel/back/Infrastructure/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php
  src/Akeneo/Channel/back/tests/.php_cd.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
  tests/back/Channel/Specification/Infrastructure/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php
  tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
Labels: echoes/intent: maintenance

#19446 CXP-1413: Map product family (string)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromFamilyValueExtractor.php
  components/catalogs/back/src/Application/Persistence/Family/GetFamilyLabelByCodeAndLocaleQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Family/GetFamilyLabelByCodeAndLocaleQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromFamilyValueExtractorTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Family/GetFamilyLabelByCodeAndLocaleQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySourceTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts
  components/catalogs/front/src/hooks/useSystemAttributes.ts
  components/catalogs/front/src/hooks/useSystemAttributes.unit.ts
Labels: echoes/intent: feature

#19365 CXP-1440: Display locale and channel in the source section
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSelection.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
Labels: echoes/intent: feature

#19417 GRF-775 create add template attribute modal
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCreateAttribute.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature

#19416 GRF-704: Template deactivation enriched values cleaning
  src/Akeneo/Category/back/Application/Command/CleanCategoryEnrichedValuesByChannelOrLocale/CleanCategoryEnrichedValuesByChannelOrLocaleCommandHandler.php
  src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAndEnrichedValues/CleanCategoryTemplateAndEnrichedValuesCommand.php
  src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAndEnrichedValues/CleanCategoryTemplateAndEnrichedValuesCommandHandler.php
  src/Akeneo/Category/back/Application/Enrichment/CategoryAttributeValuesCleaner.php
  src/Akeneo/Category/back/Application/Enrichment/Filter/ByTemplateAttributesUuidsFilter.php
  src/Akeneo/Category/back/Domain/Query/GetEnrichedValuesByTemplateUuid.php
  src/Akeneo/Category/back/Infrastructure/Job/CleanCategoriesTemplateEnrichedValuesTasklet.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetEnrichedValuesByTemplateUuidSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cleaners.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/jobs.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryEnrichedValuesByChannelOrLocale/CleanCategoryEnrichedValuesByChannelOrLocaleCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryEnrichedValuesByTemplateUuid/CleanCategoryTemplateAndEnrichedValuesCommandHandlerIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetEnrichedValuesByTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Enrichment/Filter/ByChannelAndLocalesFilterSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Job/CleanCategoriesTemplateEnrichedValuesTaskletSpec.php
  src/Akeneo/Category/back/tests/Unit/Application/Command/DeactivateTemplateCommandHandlerTest.php
  src/Akeneo/Category/back/tests/Unit/Application/Enrichment/CategoryAttributeValuesCleanerTest.php
  src/Akeneo/Category/back/tests/Unit/Application/Enrichment/CategoryDataCleanerTest.php
  src/Akeneo/Category/back/tests/Unit/Application/Filter/ByTemplateAttributesUuidsFilterTest.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19443 GRF-764 send add attribute's modal content and manage response
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.test.tsx
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.test.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useCreateAttribute.ts
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature

#18490 Merge fpm and php containers
  .circleci/config/commands.yml
  .circleci/jobs/build_and_deploy.yml
  .circleci/jobs/features/connectivity.yml
  .circleci/jobs/features/other.yml
  .circleci/run_behat.sh
  Dockerfile
  Makefile
  bin/benchmark_products_api.sh
  docker-compose.override-osx.yml
  docker-compose.yml
  docker/httpd.conf
  docker/supervisord.conf
Labels: to review

#19473 RAB-1360: Always display other in replacement attribute groups
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts
Labels: echoes/intent: feature

#19406 RAB-1300: Define a limit for attribute groups creation
  src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeGroupRepository.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attributegroup.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/validators.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AttributeGroupsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/buttons/AttributeGroupsCreateButton.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupRow.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/AttributeGroupsIndexProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupPermissions.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroups.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useFilteredAttributeGroups.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/buttons/AttributeGroupsCreateButton.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/AttributeGroupList.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/AttributeGroupRow.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupPermissions.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroups.unit.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupsIndexState.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/pages/AttributeGroupsIndex.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideAttributeGroupHelper.ts
  src/Akeneo/Pim/Structure/Component/Repository/AttributeGroupRepositoryInterface.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/AttributeGroups/MaxAttributeGroupCount.php
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/AttributeGroups/MaxAttributeGroupCountValidator.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/index.yml
  src/Akeneo/Tool/Component/Connector/Exception/InvalidItemFromViolationsException.php
  tests/back/Acceptance/AttributeGroup/InMemoryAttributeGroupRepository.php
  tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php
  tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/PartialUpdateAttributeGroupEndToEnd.php
  tests/back/Pim/Structure/Integration/AttributeGroup/ImportAttributeGroupIntegration.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/AttributeGroups/MaxAttributeGroupCountValidatorSpec.php
Labels: echoes/intent: feature

#19471 Grf 705 : Delete template + attributes & link to category tree
  src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAndEnrichedValues/CleanCategoryTemplateAndEnrichedValuesCommandHandler.php
  src/Akeneo/Category/back/Domain/Query/DeleteCategoryTreeTemplateByCategoryIdAndTemplateUuid.php
  src/Akeneo/Category/back/Domain/Query/DeleteCategoryTreeTemplateByTemplateUuid.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/RemoveCategoryTreeTemplateSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByCategoryIdAndTemplateUuidSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByTemplateUuidSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByCategoryIdAndTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteCategoryTreeTemplateByTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteTemplateAndAttributesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetEnrichedValuesByTemplateUuidSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/RemoveCategoryTreeTemplateSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/RemoveTemplateAndAttributesAfterCategoryTreeDeletionSubscriberSpec.php
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#18875 CXP-1358: Send notif when an attribute is removed and is used by catalog mapping
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingAttributesInProductMappingQueryInterface.php
  components/catalogs/back/src/Application/Service/DispatchAttributeRemovedEventInterface.php
  components/catalogs/back/src/Infrastructure/EventSubscriber/AttributeRemovalSubscriber.php
  components/catalogs/back/src/Infrastructure/Job/NotifyOnAttributeRemovalConstraint.php
  components/catalogs/back/src/Infrastructure/Job/NotifyOnAttributeRemovalTasklet.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingAttributesInProductMappingQuery.php
  components/catalogs/back/src/Infrastructure/Service/DispatchAttributeRemovedEvent.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/jobs.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/ServiceAPI/Events/AttributeRemovedEvent.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/NotifyOnAttributeRemovalConstraintTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingAttributesInProductMappingQueryTest.php
  src/Akeneo/Connectivity/Connection/back/Application/Apps/Notifier/AttributeRemovedNotifierInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/NotifyOnAttributeRemovalEventSubscriber.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Notifier/AttributeRemovedNotifier.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/event_subscribers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/NotifyOnAttributeRemovalEventSubscriberIntegration.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
  upgrades/schema/Version_8_0_20230111140000_add_notify_on_attribute_removal_job_instance.php
  upgrades/test_schema/Version_8_0_20230111140000_add_notify_on_attribute_removal_job_instance_Integration.php
Labels: echoes/intent: feature

#19500 PH-908: Use pim_configuration install data to check database installed
  src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/VersionDataCollector.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Exception/UnavailableCreationTimeException.php
  src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Persistence/Sql/GetInstallDatetime.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
  tests/back/Platform/Integration/Installer/InstallStatusManagerIntegration.php
  tests/back/Platform/Integration/Installer/Persistence/Sql/GetInstallDatetimeIntegration.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/VersionDataCollectorSpec.php
  tests/back/Platform/Specification/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManagerSpec.php
Labels: echoes/intent: feature

#19479 GRF-764 fix add attribute modal style and type options
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
Labels: echoes/intent: feature

#19482 GRF-790 : Migration: add column in template attribute table
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
  upgrades/schema/Version_8_0_20230323180900_add_column_is_deactivated_on_template_attribute.php
  upgrades/test_schema/Version_8_0_20230323180900_add_column_is_deactivated_on_template_attribute_Integration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19450 CPM-1010: [front] Error : The label for "en_US" must be filled
  components/identifier-generator/back/src/Application/Create/CreateGeneratorCommand.php
  components/identifier-generator/back/src/Application/Update/UpdateGeneratorCommand.php
  components/identifier-generator/back/src/Domain/Model/LabelCollection.php
  components/identifier-generator/back/src/Infrastructure/Controller/CreateIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldExistValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Create/CreateGeneratorCommandSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  components/identifier-generator/front/src/feature/components/LabelTranslations.tsx
  components/identifier-generator/front/src/feature/components/__tests__/LabelTranslations.test.tsx
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/validators/__tests__/validateLabelCollection.test.ts
  components/identifier-generator/front/src/feature/validators/validateLabelCollection.ts
Labels: echoes/intent: feature

#19497 RAB-1366: Select all attribute groups only selects filtered results
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupList.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature, echoes/effort: S

#19508 RAB-1367: Remove bulk delete attribute groups feature flag
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/feature_flags.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupList.tsx
Labels: echoes/intent: feature, echoes/effort: XS

#19518 GH-19430: Command shortcut cannot be a boolean
  src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedProductsCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php
Labels: bug

#19507 RAB-1322: Add a feature flag for reset pim feature
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyGrowthAndSerenitySandboxFeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
Labels: echoes/intent: feature

#19520 CPM-978: Prevent Dashlane from triggering on select inputs
  front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
Labels: echoes/intent: feature

#19519 PIM-10913: Fix attribute creation form when a label contains a question mark
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
Labels: echoes/intent: maintenance

#19463 CPM-1008: Be able to manage simple select nomenclature
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/hooks/useGetNomenclatureValues.ts
  components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts
  components/identifier-generator/front/src/feature/hooks/useNomenclatureDisplay.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/nomenclature.ts
  components/identifier-generator/front/src/feature/models/nomenclatureLineEditProps.ts
  components/identifier-generator/front/src/feature/models/properties/canUseNomenclatureProperty.ts
  components/identifier-generator/front/src/feature/models/properties/index.ts
  components/identifier-generator/front/src/feature/models/simpleSelect.ts
  components/identifier-generator/front/src/feature/tabs/structure/ProcessablePropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/FamilyPropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/SimpleSelectPropertyEdit.tsx
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeOption/SqlFindAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  tests/back/Pim/Structure/Integration/Query/InternalApi/AttributeOption/SqlFindAttributeOptionsIntegration.php
Labels: echoes/intent: feature

#19505 CPM-1009: Allow user to select nomenclature in the process list
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/hooks/useGetNomenclatureValues.ts
  components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts
  components/identifier-generator/front/src/feature/hooks/useNomenclatureDisplay.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/nomenclature.ts
  components/identifier-generator/front/src/feature/models/nomenclatureLineEditProps.ts
  components/identifier-generator/front/src/feature/models/properties/canUseNomenclatureProperty.ts
  components/identifier-generator/front/src/feature/models/properties/index.ts
  components/identifier-generator/front/src/feature/models/properties/simpleSelectProperty.ts
  components/identifier-generator/front/src/feature/models/simpleSelect.ts
  components/identifier-generator/front/src/feature/tabs/structure/ProcessablePropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/ProcessablePropertyEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/FamilyPropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/SimpleSelectPropertyEdit.tsx
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeOption/SqlFindAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  tests/back/Pim/Structure/Integration/Query/InternalApi/AttributeOption/SqlFindAttributeOptionsIntegration.php
Labels: echoes/intent: feature

#19481 GRF-789 : Delete attribute endpoint + command + command handler
  src/Akeneo/Category/back/Application/Command/DeactivateAttributeCommand.php
  src/Akeneo/Category/back/Application/Command/DeactivateAttributeCommandHandler.php
  src/Akeneo/Category/back/Domain/Query/DeactivateAttribute.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeUuid.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/DeactivateAttributeController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeactivateAttributeSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/EndToEnd/InternalApi/DeactivateAttributeControllerEndToEnd.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeactivateAttributeSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/Command/DeactivateAttributeCommandHandlerSpec.php
Labels: echoes/intent: feature

#19526 OCT-237: reverse wrong change in package.json
  components/catalogs/front/package.json
Labels: echoes/intent: maintenance

#19516 GRF-794: No template attributes
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttributeOnTemplatePage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19527 GRF: remove deactivate template feature flag
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, griffins-risk-assessed

#19529 GRF-788: Update Enriched Category helper message
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19514 PIM-10906: Use user timezone to display dates in history grid
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/datagrid/history.yml
  tests/legacy/features/pim/enrichment/reference-data/attribute/display_attribute_history.feature
Labels: echoes/intent: maintenance

#19525 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
Labels: echoes/intent: maintenance

#19535 CPM-1036: Fix pautophe review
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/front/src/feature/components/ScopeAndLocaleSelector.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/tabs/conditions/ImplicitSimpleSelectCondition.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/SimpleOrMultiSelectLine.tsx
Labels: echoes/intent: feature

#19540 PIM-10915: fix dynamic typing to cast to string
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/VersionNormalizer.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/VersionNormalizerSpec.php
Labels: echoes/intent: maintenance

#19509 CPM-1019: Add ref entities in GetAvailablePropertiesController
  components/identifier-generator/back/src/Infrastructure/Controller/GetAvailablePropertiesController.php
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailablePropertiesControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Helper/FeatureHelper.php
Labels: echoes/intent: feature

#19530 GRF-796: Frontend: Empty category attribute value list
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/templates/index.ts
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18972 CXP-1408: Adds feature flag to Catalogs [master]
  config/packages/akeneo_feature_flag.yml
  config/packages/dev/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/FakeFeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/AkeneoFeatureFlagExtension.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/Configuration.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
Labels: echoes/intent: feature
