Repository akeneo/pim-community-dev, pull requests merged in 2023-02, with the labels that each got.

#18601 CPM-842 : Erase the default number of digits for the auto number
  components/identifier-generator/front/src/feature/models/properties/autoNumber.ts
  components/identifier-generator/front/src/feature/tabs/structure/edit/AutoNumberEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/AutoNumberEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/AutoNumberPreview.tsx
  components/identifier-generator/front/src/feature/validators/__tests__/validateAutoNumber.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts
  components/identifier-generator/front/src/feature/validators/validateAutoNumber.ts
  components/identifier-generator/front/src/feature/validators/validateStructure.ts
Labels: echoes/intent: feature

#19011 GRF-700: Migration with new is_deactivated field on template table
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
  upgrades/schema/Version_8_0_20230131155436_add_column_is_deactivated_on_template.php
  upgrades/test_schema/Version_8_0_20230131155436_add_column_is_deactivated_on_template_Integration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18959 PIM-10808: Fix Error message on the family modification when an attribute is as required=0
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/FamilyRequirementsValidatorSpec.php
Labels: echoes/intent: maintenance

#18869 CXP-1372: Mapping - Accept an identifier as a source for a string attribute
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromIdentifierAttributeValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeIdentifierSource.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromIdentifierAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeIdentifierSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteSourceAttributes.ts
Labels: echoes/intent: feature

#18994 GRF-696: Fix Edit the Category label of a Category with the default label doesn't work
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19014 PIM-10802: Fix wysiwyg-field add link event
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Labels: echoes/intent: maintenance

#19018 PIM-10818: Backport PIM-10802 on 6.0
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Labels: echoes/intent: maintenance

#18951 PIM-10786 : Create error message when session expire
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: maintenance

#18983 CXP-1402: mapping - accept date as source for string-datetime target
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/StringDateTime/StringDateTimeFromDateAttributeValueExtractor.php
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeDateSource.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/StringDateTime/StringDateTimeFromDateAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeDateSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.4.json
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
Labels: echoes/intent: feature

#19017 CPM-938: update validator to be compatible with multi_select type
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveTypes.php
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveTypesValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValidValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/AttributeShouldHaveTypesValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Labels: echoes/intent: feature

#18929 CXP-1376: mapping - accept number as target with number source
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromNumberAttributeValueExtractor.php
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeNumberSource.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromNumberAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeNumberSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
Labels: echoes/intent: feature, echoes/intent: technical

#19019 RAB-1310: Add not ZDD migrations equivalent of ZDD migrations
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Security/ScopeMapperRegistryIntegration.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220516171405SetProductIdentifierNullableZddMigration.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/ZddMigration.php
  upgrades/.php_cd.php
  upgrades/schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns.php
  upgrades/schema/Version_7_0_20230201143500_set_product_identifier_nullable.php
  upgrades/test_schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns_Integration.php
  upgrades/test_schema/Version_7_0_20230201143500_set_product_identifier_nullable_Integration.php
Labels: echoes/intent: technical

#18858 GRF-671 : Create Category Version for Enriched Category
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Event/CategoryUpdatedEvent.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Domain/ValueObject/Version/CategoryVersion.php
  src/Akeneo/Category/back/Infrastructure/Builder/CategoryVersionBuilder.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/UpdateCategoryVersionSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/builders.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Builder/CategoryVersionBuilderIntegration.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
  src/Akeneo/Tool/Bundle/VersioningBundle/DependencyInjection/AkeneoVersioningExtension.php
  src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/service_api.yml
  src/Akeneo/Tool/Bundle/VersioningBundle/ServiceApi/VersionBuilder.php
  src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/ServiceApi/VersionBuilderIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19044 CXP-1431: Map number attributes (string)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
Labels: echoes/intent: feature

#18971 RAC-1287: Improve logging in MetricPresenter
  src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
Labels: echoes/intent: maintenance

#19060 Fix workerIdleMemoryLimit only work on jest 29, as we did not success to upgrade jest we used max_old_space_size
  components/identifier-generator/front/package.json
  front-packages/akeneo-design-system/package.json
  front-packages/measurement/package.json
  front-packages/shared/package.json
  src/Akeneo/Category/front/package.json
  src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/package.json
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/package.json
  src/Akeneo/Platform/Job/front/process-tracker/package.json
  src/Oro/Bundle/ConfigBundle/front/package.json
Labels: echoes/intent: technical, echoes/effort: XL

#18980 PIM-10796: Fix system-information endpoint with wrong answers
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml
  tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
Labels: echoes/intent: maintenance

#18957 PIM-10807 [PULL UP 7.0] : Create error message when session expire
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: maintenance

#18995 CPM-911: Add Family property and its edition
  components/identifier-generator/back/src/Domain/Model/Property/Process.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FamilyPropertySpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/ProcessSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyPropertyShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  components/identifier-generator/front/src/feature/components/OperatorSelector.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/models/conditions/operator.ts
  components/identifier-generator/front/src/feature/models/properties/abbreviationType.ts
  components/identifier-generator/front/src/feature/models/properties/familyProperty.ts
  components/identifier-generator/front/src/feature/models/properties/index.ts
  components/identifier-generator/front/src/feature/models/structure.ts
  components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__mocks__/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/FamilyLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/ImplicitConditionsList.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/SimpleSelectLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/ImplicitConditionsList.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/Preview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
  components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/FamilyPropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/FamilyPropertyEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/line/FamilyCodeLine.tsx
  components/identifier-generator/front/src/feature/tabs/structure/line/__tests__/FamilyCodeLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/line/index.ts
  components/identifier-generator/front/src/feature/tabs/structure/preview/FamilyCodePreview.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/__tests__/FamilyCodePreview.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/index.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateFamilyProperty.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts
  components/identifier-generator/front/src/feature/validators/validateFamilyProperty.ts
  components/identifier-generator/front/src/feature/validators/validateStructure.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/modal.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
Labels: echoes/intent: feature

#19004 CPM-934: Do not display attributes if user has no permissions to list attributes
  components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php
  components/identifier-generator/front/src/feature/tabs/conditions/SimpleSelectLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleSelectLine.test.tsx
  components/identifier-generator/front/src/setupTests.tsx
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#19070 GRF-719: Image attribute field accept any file type
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UploadController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/parameters.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19091 [Pullup master] PIM-10786: Create error message when session expire
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: maintenance, griffins-risk-assessed

#18966 GRF-300: As Julia, I want to delete a category tree with its template
  src/Akeneo/Category/back/Application/Query/DeleteTemplateAndAttributes.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/RemoveTemplateAndAttributesAfterCategoryTreeDeletionSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeleteTemplateAndAttributesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeleteTemplateAndAttributesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/RemoveTemplateAndAttributesAfterCategoryTreeDeletionSubscriberSpec.php
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
  upgrades/schema/Version_8_0_20230127150758_add_ondelete_cascade_on_category_template_attributes.php
  upgrades/test_schema/Version_7_0_20221017143357_add_category_template_table_Integration.php
  upgrades/test_schema/Version_8_0_20230127150758_add_ondelete_cascade_on_category_template_attributes_Integration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18928 GRF-623 : Clean category date on locale deactivation
  src/Akeneo/Category/back/Application/Enrichment/CleanCategoryDataLinkedToChannel.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelChangeSubscriber.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelDeletionSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Job/CleanCategoriesEnrichedValuesTasklet.php
  src/Akeneo/Category/back/Infrastructure/Job/CleanCategoryEnrichedValuesProvider.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/Integration/Application/Enrichment/CleanCategoryDataLinkedToChannelIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelChangeSubscriberSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Job/CleanCategoriesEnrichedValuesTaskletSpec.php
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  upgrades/schema/Version_8_0_20230104170600_add_clean_category_enriched_values_job_instance.php
  upgrades/test_schema/Version_8_0_20230104170600_add_clean_category_enriched_values_job_instance_Integration.php
Labels: wip, echoes/intent: feature, echoes/intent: maintenance

#19073 GRF-725 : Fix EC schema inconsistency between fresh
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19069 GRF-720: Does not display labels header if there are no labels
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19079 GRF-724: Fix attribute value to be clearable & remove persistence of null value
  src/Akeneo/Category/back/Api/Command/UserIntents/SetRichText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetText.php
  src/Akeneo/Category/back/Api/Command/UserIntents/SetTextArea.php
  src/Akeneo/Category/back/Api/Command/UserIntents/ValueUserIntent.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextAreaValue.php
  src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextValue.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidator.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextAreaValueSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextValueSpec.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19058 CXP-1424: Add the custom apps ACLs
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetOpenAppUrlAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/acl.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlActionSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetOpenAppUrlActionSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppActionSpec.php
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedTestAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppCard.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedTestAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
Labels: echoes/intent: feature

#19098 CPM-942: Add tables for family nomenclature
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  upgrades/schema/Version_8_0_20230131125133_create_identifier_generator_family_nomenclature_tables.php
  upgrades/test_schema/Version_8_0_20230131125133_create_identifier_generator_family_nomenclature_tables_Integration.php
Labels: echoes/intent: feature

#19095 CXP-1419 is custom app front
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/OpenAppButton.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCardDescription.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ErrorMonitoring/ConnectAppErrorMonitoring.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/OpenAppButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Settings/Authentication.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedTestAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-app.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/is-granted-on-catalog.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/is-granted-on-product.test.tsx
Labels: echoes/intent: feature

#19078 CXP-1421: Display credentials in the custom apps settings
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/GetCustomAppSecretAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/controllers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/routing.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/CustomApps/Controller/Internal/GetCustomAppSecretActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppSettings.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Settings/AuthenticationScopesList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Settings/ConnectedAppCredentials.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-custom-app-secret.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppCredentials.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx
Labels: echoes/intent: feature, echoes/intent: maintenance

#19012 CPM-944: Save nomenclatures
  components/identifier-generator/back/src/Application/Update/UpdateNomenclatureCommand.php
  components/identifier-generator/back/src/Application/Update/UpdateNomenclatureHandler.php
  components/identifier-generator/back/src/Domain/Model/NomenclatureDefinition.php
  components/identifier-generator/back/src/Domain/Repository/NomenclatureRepository.php
  components/identifier-generator/back/src/Infrastructure/Controller/UpdateNomenclatureController.php
  components/identifier-generator/back/src/Infrastructure/Repository/InMemoryNomenclatureRepository.php
  components/identifier-generator/back/src/Infrastructure/Repository/SqlNomenclatureRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_nomenclature_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Validation/UpdateNomenclatureCommandValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateFamilyNomenclatureContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateFamilyNomenclatureControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Domain/Model/NomenclatureDefinitionSpec.php
  components/identifier-generator/back/tests/behat.yml
  components/identifier-generator/back/tests/features/createFamilyNomenclature.feature
  components/identifier-generator/back/tests/features/updateFamilyNomenclature.feature
Labels: echoes/intent: feature

#19071 Grf 722 : Delete category modal doesn't display category code & the right context (tree vs category)
  src/Akeneo/Category/front/src/feature/components/datagrids/DeleteCategoryModal.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#19097 GRF-728 Update snapshot parent when the category is root
  src/Akeneo/Category/back/Domain/ValueObject/Version/CategoryVersion.php
  src/Akeneo/Category/back/Infrastructure/Builder/CategoryVersionBuilder.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Builder/CategoryVersionBuilderIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19007 Pim 10810: Optimize completeness saving
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
  tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
Labels: echoes/intent: maintenance

#19083 AST-493: Promote Unlock event through the login page on Serenity and Growth
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyGrowthAndSerenityFeatureFlag.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/AkeneoFeatureFlagExtension.php
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/twig.yml
  src/Akeneo/Platform/Bundle/FeatureFlagBundle/Twig/FeatureFlagExtension.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/illustrations/login/Unlock-Paris-2023-Product-Log-in.png
  src/Akeneo/UserManagement/Bundle/Resources/public/css/unlock-banner.css
  src/Akeneo/UserManagement/Bundle/Resources/views/Security/login.html.twig
  src/Akeneo/UserManagement/Bundle/Resources/views/Unlock/login-banner.html.twig
Labels: echoes/intent: feature, echoes/effort: S, salamander

#19118 Fix php-http/discovery version in order to avoid error about post-install script
  composer.json
  composer.lock
Labels: echoes/intent: technical

#19054 CPM-945: Add nomenclature screen
  components/identifier-generator/back/src/Infrastructure/Controller/GetFamiliesController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/NomenclatureLineEdit.tsx
  components/identifier-generator/front/src/feature/components/NomenclatureValuesDisplayFilter.tsx
  components/identifier-generator/front/src/feature/components/OperatorSelector.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/__mocks__/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/__mocks__/NomenclatureValuesDisplayFilter.tsx
  components/identifier-generator/front/src/feature/components/__mocks__/OperatorSelector.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureValuesDisplayFilter.test.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/hooks/useGetFamilyNomenclatureValues.ts
  components/identifier-generator/front/src/feature/hooks/useGetNomenclature.ts
  components/identifier-generator/front/src/feature/hooks/useNomenclatureDisplay.ts
  components/identifier-generator/front/src/feature/hooks/useSaveNomenclature.ts
  components/identifier-generator/front/src/feature/models/conditions/operator.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/nomenclature.ts
  components/identifier-generator/front/src/feature/models/nomenclatureFilter.ts
  components/identifier-generator/front/src/feature/models/nomenclatureLineEditProps.ts
  components/identifier-generator/front/src/feature/models/properties/abbreviationType.ts
  components/identifier-generator/front/src/feature/models/properties/familyProperty.ts
  components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/FamilyPropertyEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/FamilyPropertyEdit.test.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/__tests__/FamilyCodePreview.test.tsx
  components/identifier-generator/front/src/feature/validators/__tests__/validateFamilyProperty.test.ts
  components/identifier-generator/front/src/setupTests.tsx
  front-packages/akeneo-design-system/src/components/Pagination/Pagination.tsx
  front-packages/akeneo-design-system/src/components/Pagination/Pagination.unit.tsx
Labels: echoes/intent: feature

#19062 PIM-10806 Allow to delete product's attributes with type 'identifier' and ensure grey cross is displayed
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/manager/attribute-manager.js
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Labels: echoes/intent: maintenance, griffins-risk-assessed

#18775 GRF-637: Add twig function to show or hide HTML code in Twig template according to a feature flag
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/css/adblocker.css
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/img/akeneo-ico-free-trial.png
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/img/icon_close.svg
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/free-trial-ad-banner-fake.js
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/views/adblocker.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
Labels: griffins, echoes/intent: feature, echoes/intent: technical, griffins-risk-assessed

#19119 GRF-550 : Activate the Feature "Enriched Category"
  .env
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19136 GRF: fix feature branch
  src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php
  src/Akeneo/Category/back/tests/.php_cd.php
Labels: griffins, griffins-risk-assessed

#19111 CXP-1423: Adjust the developer mode (test apps) feature flag
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/CreateCustomAppAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/DeleteCustomAppAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/GetAllCustomAppsAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Persistence/GetAppQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/controllers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/persistence.yml
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/CustomApps/Controller/Internal/GetAllCustomAppsActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/Persistence/GetAppQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/CustomApps/Controller/Internal/CreateCustomAppActionSpec.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/Persistence/GetAppQuerySpec.php
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/DeveloperModeTag.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-app-developer-mode.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-developer-mode.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-test-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppsListPage.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/DeleteTestAppPromptPage.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/TestAppCreatePage.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-app-developer-mode.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-developer-mode.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-test-apps.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-test-apps.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/ConnectedAppsListPage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx
Labels: echoes/intent: feature

#19103 GRF-729: Fix error while displaying a category attributes for the first time
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19113 GRF-719: Change variable name to avoid confusion on EE side
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/parameters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/preview_generators.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19146 CXP-1424: fix acls
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetConnectedAppAction.php
  src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetConnectedAppActionSpec.php
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
Labels: echoes/intent: feature

#19130 RAB-1236: Create CheckStorage component & refactor tests
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/CheckStorageConnection.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/CheckStorageConnection.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/index.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/index.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/index.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/index.ts
  src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/summary/SummaryTable.tsx
Labels: echoes/intent: feature

#19148 RAB-1318: Backport major ticket in 7.0
  CHANGELOG-7.0.md
  front-packages/shared/src/components/TextField.tsx
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypter.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/normalizers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/job/common/edit/storage-form.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimitSpec.php
  tests/back/Pim/Structure/Specification/Component/Validator/Constraints/FamilyRequirementsValidatorSpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizerSpec.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#19147 GRF-736: Incorrect API return format when no enriched attribute values exist
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19150 PIM-10834: Fix regression on parent filter in LIST products endpoint
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
Labels: echoes/intent: maintenance

#19153 Revert "RAB-1124-divers: Add --workerIdleMemoryLimit=300MB"
  components/catalogs/front/jest.config.js
  front-packages/shared/jest.config.js
  src/Akeneo/Connectivity/Connection/front/jest.config.js
  src/Akeneo/Connectivity/Connection/workspaces/permission-form/jest.config.js
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/jest.config.json
Labels: echoes/intent: technical

#19141 CXP-1390: avoid 'any' in typescript
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
Labels: echoes/intent: feature

#19152 GRF-638: add helpcenter link
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19154 GRF-737: Deactivate template feature flag
  .env
  config/packages/akeneo_feature_flag.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19164 GRF-638: fix helper wording
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19133 PIM-10825: Improve message to the end user when remote storage does not work
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/UpdateJobExecutionStorageSummarySubscriber.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
Labels: echoes/intent: maintenance

#19161 CXP-1419 Create custom app
  src/Akeneo/Connectivity/Connection/back/Application/CustomApps/Command/CreateCustomAppCommand.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/Integration/CustomApps/Validation/CreateCustomAppCommandValidationIntegration.php
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppButton.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppCredentials.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/CreateTestAppForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-create-custom-app.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-create-test-app.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/CreateCustomAppPage.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/CustomApps.tsx
  src/Akeneo/Connectivity/Connection/front/src/model/Apps/custom-app-credentials.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppCredentials.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppForm.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-create-custom-app.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-create-test-app.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/CreateCustomAppPage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/test-utils.tsx
Labels: echoes/intent: feature

#19157 PIM-10824: Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
Labels: echoes/intent: maintenance

#19108 PIM-10823: Cannot import price and measurement with comma as decimal separator with value not saved as string in import file
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Value.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueSpec.php
Labels: echoes/intent: maintenance

#19156 DatabaseCommand should not write on output
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
Labels: tech-improvement

#19162 CXP-1420: Limit the number of custom apps (connected)
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppList.test.tsx
Labels: echoes/intent: feature

#19100 RAB-1260: Implement items count in backend
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/SqlCountAttributes.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Component/Query/InternalApi/CountAttributes.php
  src/Oro/Bundle/PimDataGridBundle/Adapter/ItemsCounter.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/adapters.yml
  src/Oro/Bundle/PimDataGridBundle/spec/Adapter/ItemsCounterSpec.php
  tests/back/Pim/Structure/Integration/Attribute/Query/SqlCountAttributesIntegration.php
Labels: echoes/intent: feature

#19120 PIM-10835: Fix command publish-job-to-queue does not work
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
Labels: echoes/intent: maintenance

#19163 CXP-1427: Apply search term to the custom apps section
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppCard.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-test-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-test-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
  src/Akeneo/Connectivity/Connection/front/src/model/app.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
Labels: echoes/intent: feature

#19166 PIM-10824: Pull up 7.0 into master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
  components/catalogs/front/jest.config.js
  front-packages/shared/jest.config.js
  src/Akeneo/Connectivity/Connection/front/jest.config.js
  src/Akeneo/Connectivity/Connection/workspaces/permission-form/jest.config.js
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
  src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/jest.config.json
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#19171 GRF-711: Template deactivation - Endpoint + CommandHandler + flag Template as deactivated
  make-file/category.mk
  src/Akeneo/Category/back/Application/Command/DeactivateTemplateCommand.php
  src/Akeneo/Category/back/Application/Command/DeactivateTemplateCommandHandler.php
  src/Akeneo/Category/back/Application/Query/DeactivateTemplate.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/DeactivateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/DeactivateTemplateSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/DeactivateTemplateSqlIntegration.php
  src/Akeneo/Category/back/tests/Unit/DeactivateTemplateCommandHandlerTest.php
  src/Akeneo/Category/back/tests/phpunit.xml.dist
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19167 GRF-727 : Get a list of category by their ids
  src/Akeneo/Category/back/Application/Registry/FindCategoryAdditionalProperties.php
  src/Akeneo/Category/back/Domain/Query/GetCategoryByIds.php
  src/Akeneo/Category/back/Domain/ValueObject/Version/CategoryVersion.php
  src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryByIdsSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryByIdsSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistrySpec.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18690 PH-430: Use Application::find() to run the command in CommandExecutor
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Tool/Component/Console/CommandExecutor.php
Labels: echoes/intent: feature

#19187 removed duplicated migration & test
  upgrades/schema/Version_7_0_20230104170600_add_clean_category_enriched_values_job_instance.php
  upgrades/test_schema/Version_7_0_20230104170600_add_clean_category_enriched_values_job_instance_Integration.php
Labels: griffins, griffins-risk-assessed

#18772 GRF-672: Adapt the Information component to fit its content height
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-information-fit-content-height-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Information/Information.stories.mdx
  front-packages/akeneo-design-system/src/components/Information/Information.tsx
Labels: design-system, griffins, echoes/intent: feature, griffins-risk-assessed

#18802 PH-609: Update Akeneo PIM CSP headers
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/ContentSecurityPolicy/MarketplaceContentSecurityPolicy.php
  src/Akeneo/Platform/Bundle/UIBundle/EventListener/ScriptNonceGenerator.php
  src/Akeneo/Platform/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProvider.php
  tests/back/Platform/EndToEnd/ContentSecurityHeadersEndToEnd.php
  tests/back/Platform/EndToEnd/WebTestCase.php
  tests/back/Platform/Specification/Bundle/UIBundle/Provider/ContentSecurityPolicy/AkeneoContentSecurityPolicyProviderSpec.php
  tests/back/Platform/Specification/Bundle/UIBundle/Provider/ContentSecurityPolicy/ContentSecurityPolicyProviderSpec.php
Labels: echoes/intent: feature

#19184 CXP-1418: front renaming
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCardDescription.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedCustomAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppCard.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-custom-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-custom-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-test-apps.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/OpenAppButton.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedCustomAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppCard.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-custom-apps.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-custom-apps.test.tsx
Labels: echoes/intent: feature

#19125 PIM-10778: Add limit to the number of options to display on the attribute option page
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19197 Revert "PH-430: Use Application::find() to run the command in Command…
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  src/Akeneo/Tool/Component/Console/CommandExecutor.php
Labels: echoes/intent: feature

#19186 CXP-1426: Limit the number of custom apps (created)
  src/Akeneo/Connectivity/Connection/back/Application/CustomApps/Command/CreateCustomAppCommand.php
  src/Akeneo/Connectivity/Connection/back/Application/CustomApps/Validation/IsCustomAppsNumberLimitReached.php
  src/Akeneo/Connectivity/Connection/back/Application/CustomApps/Validation/IsCustomAppsNumberLimitReachedValidator.php
  src/Akeneo/Connectivity/Connection/back/Domain/CustomApps/Persistence/IsCustomAppsNumberLimitReachedQueryInterface.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/IsCustomAppsNumberLimitReachedAction.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Persistence/IsCustomAppsNumberLimitReachedQuery.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Service/GetCustomAppsNumberLimit.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/controllers.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/persistence.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/routing.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/services.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/validators.yml
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
  src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/CustomApps/Controller/Internal/IsCustomAppsNumberLimitReachedActionEndToEnd.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/CustomApps/Persistence/IsCustomAppsNumberLimitReachedQueryIntegration.php
  src/Akeneo/Connectivity/Connection/back/tests/Integration/CustomApps/Validation/CreateCustomAppCommandValidationIntegration.php
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppButton.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppForm.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/RegenerateSecret/RegenerateSecretConfirm.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/RegenerateSecret/RegenerateSecretNewCredentials.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Section.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-create-custom-app.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-custom-apps-limit-reached.ts
  src/Akeneo/Connectivity/Connection/front/src/connect/pages/RegenerateSecretPage.tsx
  src/Akeneo/Connectivity/Connection/front/src/infrastructure/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-create-custom-app.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-custom-apps-limit-reached.test.ts
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/CreateCustomAppPage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/test-utils.tsx
Labels: echoes/intent: feature

#18925 Improve performance completeness table's UUID Migration
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCompletenessTable.php
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
  upgrades/test_schema/Version_7_0_20220429131804_execute_uuid_migration_Integration.php
Labels: echoes/intent: technical, echoes/effort: XL

#19092 CPM-881: Forbid auto number properties to be added twice
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
  components/identifier-generator/front/src/feature/tabs/structure/__tests__/AddPropertyButton.test.tsx
Labels: echoes/intent: feature

#19123 PIM-10826: Fix GET system-information endpoint with wrong answers
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php
  tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
Labels: echoes/intent: maintenance

#19176 RAB-1317: Fix difference between a fresh install and a migrated install 6.0 => 7.0
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php
  src/Akeneo/Tool/Component/Batch/Event/ErrorHandlerConfigurationListener.php
  src/Akeneo/Tool/Component/Connector/Encoder/CsvEncoder.php
  upgrades/schema/Version_7_0_20220404075823_add_uuid_columns.php
  upgrades/schema/Version_7_0_20220415090329_add_uuid_column_for_comment.php
  upgrades/schema/Version_7_0_20230213153500_remove_index_on_product_uuid.php
  upgrades/test_schema/Version_7_0_20230213153500_remove_index_on_product_uuid_Integration.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#19183 CPM-961: Add GetAvailableProperties endpoint
  components/identifier-generator/back/src/Infrastructure/Controller/GetAvailablePropertiesController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailablePropertiesControllerEndToEnd.php
Labels: echoes/intent: feature

#19175 PIM-10843: Rework query to avoid issue with group concat max lenght limit
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Association/Sql/SqlGetAssociationTypes.php
  tests/back/Pim/Structure/Integration/AssociationType/Query/SqlGetAssociationTypesIntegration.php
Labels: echoes/intent: maintenance

#18913 OCT-209: update tests
  components/catalogs/front/src/FakeCatalogEditContainer.tsx
  components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/utils/createTargetsFromProductMapping.ts
  components/catalogs/front/src/components/ProductMapping/utils/createTargetsFromProductMapping.unit.ts
  components/catalogs/front/src/components/ProductMapping/utils/sourceHasError.ts
  components/catalogs/front/src/components/ProductMapping/utils/sourceHasError.unit.ts
  components/catalogs/front/src/components/ProductSelection/ProductSelection.integration.tsx
Labels: echoes/intent: feature, echoes/intent: technical

#19201 Fix zdd migration
  src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php
Labels: griffins, griffins-risk-assessed

#19203 CXP-1418: Display an empty custom app section when no custom apps found
  src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppList.tsx
  src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppList.test.tsx
  src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
Labels: echoes/intent: feature

#19196 PIM-10828: Search bars don't take into account special characters
  CHANGELOG.md
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#19207 PIM-10844: Filter empty attribute option labels
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeOptionNormalizer.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/GetAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/Specification/Bundle/Form/Type/AttributeOptionTypeSpec.php
Labels: echoes/intent: maintenance

#19180 PIM-10831: Prevent association picker from sending too many requests
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/item-picker.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
Labels: echoes/intent: maintenance

#19213 PIM-10849: Fix sorting datagrid on completeness when the selected locale is not supported by the channel
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/CompletenessSorter.php
  tests/back/Pim/Enrichment/Integration/PQB/Sorter/CompletenessSorterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Sorter/Field/CompletenessSorterSpec.php
Labels: echoes/intent: maintenance

#19052 GRF-702: Update API query to ignore deleted template
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19066 GRF-703: Update save endpoint to ignore deleted template
  src/Akeneo/Category/back/Application/Query/IsTemplateDeactivated.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/SqlCategoryTreeTemplateSaver.php
  src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/IsTemplateDeactivatedSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/base.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/template.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTemplateAttributeSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/SqlCategoryTreeTemplateSaverIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/IsTemplateDeactivatedSqlIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19210 PIM-10852: Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php
  src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml
  tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
  tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
Labels: echoes/intent: maintenance

#19122 CXP-1377: Map multi-select attributes (string)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromMultiSelectAttributeValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeMultiSelectSource.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromMultiSelectAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeMultiSelectSourceTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
Labels: echoes/intent: feature

#19226 PIM-10857: Pull up 7.0 into master
  CHANGELOG-6.0.md
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php
  upgrades/schema/Version_7_0_20220404075823_add_uuid_columns.php
  upgrades/schema/Version_7_0_20220415090329_add_uuid_column_for_comment.php
  upgrades/schema/Version_7_0_20230213153500_remove_index_on_product_uuid.php
  upgrades/test_schema/Version_7_0_20230213153500_remove_index_on_product_uuid_Integration.php
Labels: echoes/intent: maintenance, echoes/intent: technical

#19029 CXP-1401 Map price attributes (number)
  components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromPriceCollectionAttributeValueExtractor.php
  components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php
  components/catalogs/back/src/Application/Persistence/Currency/GetChannelCurrenciesQueryInterface.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetChannelCurrenciesAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Currency/GetChannelCurrenciesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributePriceCollectionSource.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidCurrency.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidCurrencyValidator.php
  components/catalogs/back/tests/Acceptance/ApiContext.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromPriceCollectionAttributeValueExtractorTest.php
  components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelCurrenciesActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/GetChannelCurrenciesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AbstractAttributeSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributePriceCollectionSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.ts
  components/catalogs/front/src/components/ProductMapping/components/SelectChannelCurrenciesDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectCurrencyDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/hooks/useChannelCurrencies.ts
  components/catalogs/front/src/components/ProductMapping/hooks/useChannelCurrencies.unit.ts
  components/catalogs/front/src/components/ProductMapping/models/SourceParameter.d.ts
  components/catalogs/front/src/components/ProductMapping/models/SourceParameterErrors.d.ts
  components/catalogs/front/src/components/ProductValueFilters/components/FilterCurrencies.tsx
  components/catalogs/front/src/hooks/useCurrencies.ts
  components/catalogs/front/src/hooks/useCurrencies.unit.ts
Labels: echoes/intent: feature

#19235 PIM-10858: Fix password is set on sftp storage using private key
  CHANGELOG.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.ts
Labels: echoes/intent: maintenance

#19228 RAB-1353: Add script to check elasticsearch index have been created with Elasticsearch 7
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
  src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
Labels: echoes/intent: technical

#19244 GRF-752 increase default limit of usergroups fetched to quick fix
  src/Akeneo/UserManagement/back/ServiceApi/UserGroup/UserGroupQuery.php
Labels: griffins, griffins-risk-assessed

#19229 GRF-690: User can't edit template attribute values on deactivated template
  src/Akeneo/Category/back/Api/Command/Exceptions/ViolationsException.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validators.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplate.php
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidator.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidatorSpec.php
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/ResponseStatus.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19179 RAB-1284: Mass select attribute groups
  front-packages/shared/src/components/DeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
  front-packages/shared/src/components/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/AttributeGroup.interface.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AttributeGroupsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/AttributeGroupsIndexProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupsIndexState.unit.tsx
Labels: contribution, echoes/intent: feature

#19234 CPM-979: Fix design issues on nomenclature screen
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
  components/identifier-generator/front/src/feature/components/NomenclatureLineEdit.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
  components/identifier-generator/front/src/feature/hooks/useGetFamilyNomenclatureValues.ts
Labels: echoes/intent: feature

#19247 PIM-10853: Fix type checking in SaveFamilyVariantOnFamilyUpdate bulk action
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/legacy/features/pim/structure/family/mass_edit_families.feature
Labels: echoes/intent: maintenance

#19238 GRF-743: Link to Enriched Categories page
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19215 PIM-10829: Inconsistent behavior when importing label with 'wrong' locale case
  CHANGELOG.md
  src/Akeneo/Category/back/Infrastructure/Component/Model/Category.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Component/Model/CategorySpec.php
  src/Akeneo/Channel/back/Infrastructure/Component/Model/Channel.php
  src/Akeneo/Channel/back/tests/Specification/Infrastructure/Component/Model/ChannelSpec.php
  src/Akeneo/Pim/Enrichment/Component/Product/Model/Group.php
  src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/TranslationNormalizer.php
  src/Akeneo/Pim/Structure/Component/Model/AbstractAttribute.php
  src/Akeneo/Pim/Structure/Component/Model/AssociationType.php
  src/Akeneo/Pim/Structure/Component/Model/AttributeGroup.php
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  src/Akeneo/Pim/Structure/Component/Model/GroupType.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Model/GroupSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/TranslationNormalizerSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/AssociationTypeSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/AttributeGroupSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/AttributeSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
  tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
  tests/back/Pim/Structure/Specification/Component/Model/GroupTypeSpec.php
Labels: echoes/intent: maintenance

#19198 GRF: dockerize category micro-frontend
  make-file/category.mk
  src/Akeneo/Category/front/docker-compose.micro-frontend.yml
  src/Akeneo/Category/front/package.json
Labels: griffins, griffins-risk-assessed

#19190 PIM-10846: PIM installer does not drop database/schema
  Makefile
  bin/benchmark_products_api.sh
  src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
  std-build/Makefile
  tests/back/Pim/Enrichment/Integration/Product/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumnsIntegration.php
  upgrades/test_schema/Version_7_0_20220429131804_execute_uuid_migration_Integration.php
  upgrades/test_schema/Version_7_0_20220927080024_add_identifier_generator_table_Integration.php
  upgrades/test_schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns_Integration.php
Labels: echoes/intent: maintenance

#19259 GRF-701 : Update all queries to ignore deleted template
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreesSqlIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19249 GRF-710: deactivate template modal
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/DeactivateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
  src/Akeneo/Category/front/src/configuration/Page.tsx
  src/Akeneo/Category/front/src/feature/components/templates/DeactivateTemplateModal.tsx
  src/Akeneo/Category/front/src/feature/components/templates/TemplateOtherActions.tsx
  src/Akeneo/Category/front/src/feature/hooks/useDeactivateTemplate.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19237 GRF-745 : Fix by-default channel & locale selector and nav in the PIM (with PEF)
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19236 PIM-10840: Fix attribute update date on attribute options change above 10000 options
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/TimestampableAttributeSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
Labels: echoes/intent: maintenance

#19267 GRF-755: Missing check on empty value user intents
  src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidator.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidatorSpec.php
Labels: griffins, griffins-risk-assessed

#19269 GRF-755: Missing check on string label
  src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/LabelUserIntentFactorySpec.php
Labels: griffins, griffins-risk-assessed

#19271 GRF-755: Add check on undefined value
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
Labels: griffins, griffins-risk-assessed

#19277 GRF-760: export API enriched category media file
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/DownloadCategoryMediaFileController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/external_api/category.yml
  src/Akeneo/Category/back/tests/.php_cd.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19239 RAB-1294: [Front] Display number of attributes in the grid
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
Labels: contribution, echoes/intent: feature

#19223 Flex v7: update system requirements check
  src/Akeneo/Platform/PimRequirements.php
Labels: echoes/intent: technical, echoes/effort: S

#19257 PIM-10862: Fix attribute options fetch fails in Rule Engine cause of URI Too Long
  src/Akeneo/Platform/Bundle/UIBundle/Controller/AjaxOptionController.php
  tests/back/Platform/Specification/Bundle/UIBundle/Controller/AjaxOptionControllerSpec.php
Labels: echoes/intent: maintenance

#19253 GRF-692: Redirect to category trees page when user try to view a deactivated tempate
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
  src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#19280 PIM-10832: Fix compute completeness job
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
Labels: echoes/intent: maintenance

#19089 RAB-1272: redo attribute-group grid
  front-packages/shared/src/components/DeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
  front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
  front-packages/shared/src/components/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/public_api/queries.yml
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Model/AttributeGroupsActivation.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/AttributeGroup/GetAttributeGroupsActivationQuery.php
  src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/AttributeGroup/GetAttributeGroupsActivationQueryInterface.php
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/AttributeGroup.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/AttributeGroup/attributeGroupsFetcher.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/PublicApi/Query/AttributeGroup/GetAttributeGroupsActivationQueryIntegration.php
  src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/PublicApi/Model/AttributeGroupsActivationSpec.php
  src/Akeneo/Pim/Structure/.php_cd.php
  src/Akeneo/Pim/Structure/Bundle/Application/GetAttributeGroup/GetAttributeGroupHandler.php
  src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
  src/Akeneo/Pim/Structure/Bundle/Domain/Query/Sql/GetAttributeGroupsInterface.php
  src/Akeneo/Pim/Structure/Bundle/Infrastructure/Query/Sql/GetAttributeGroups.php
  src/Akeneo/Pim/Structure/Bundle/Infrastructure/controller/GetAttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/GetAttributeGroups.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/handler.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute_group.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AttributeGroupsApp.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/StatusBadge.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/AttributeGroupsIndexProvider.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/index.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useGetAttributeGroupLabel.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupsIndexState.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useGetAttributeGroupLabel.unit.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideAttributeGroupHelper.ts
  tests/back/Pim/Structure/Integration/AttributeGroup/Infrastructure/Query/Sql/GetAttributeGroupsIntegration.php
Labels: contribution, echoes/intent: feature

#19282 PIM-10868: Fix checkboxes on category trees
  CHANGELOG.md
  front-packages/shared/src/components/CategoryTree/CategoryTree.tsx
  front-packages/shared/src/components/CategoryTree/RecursiveCategoryTree.tsx
  src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/CategoryTree/RecursiveCategoryTree.unit.tsx
Labels: echoes/intent: maintenance

#19002 CXP-1393: Constraint - number - min/max
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.8.json
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-maxLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-maximum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-minLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-minimum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-pattern-value.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-unsupported-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-unsupported-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-maxLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-maximum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-minLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-minimum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.8-with-wrong-type-for-pattern.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.8.json
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#19010 CXP-1396: Constraint - string/number - enum
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.9.json
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-enum-of-number-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-enum-of-string-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-enum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-maxLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-maximum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-minLength-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-minimum-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-pattern-value.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-unsupported-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-unsupported-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-maxLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-maximum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-minLength.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-minimum.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.9-with-wrong-type-for-pattern.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.9.json
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
Labels: echoes/intent: feature

#19281 PIM-10820: Partially revert [PIM-10350] to fix case sensitivity on op…
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilter.php
  src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilter.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilterSpec.php
Labels: echoes/intent: maintenance

#19284 Pull up 6.0 => 7.0
  CHANGELOG-6.0.md
  src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
  src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/UIBundle/Controller/AjaxOptionController.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
  src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
  tests/back/Platform/Specification/Bundle/UIBundle/Controller/AjaxOptionControllerSpec.php
Labels: contribution, echoes/intent: maintenance, echoes/intent: technical

#19285 CXP-1439: 3 component split of Source Panel
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectChannelCurrenciesDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectCurrencyDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectLabelLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SourceParameters.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSectionTitle.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectLocaleDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSelection.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx
  components/catalogs/front/src/components/ProductMapping/models/Source.d.ts
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts
  components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.unit.ts
Labels: echoes/intent: feature

#19268 PIM-10865: Backport PIM-10606 on 6.0
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Component/Model/Family.php
  src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
Labels: echoes/intent: maintenance

#19279 RAB-1356: Backport SLA major ticket in 7.0
  CHANGELOG-7.0.md
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/CompletenessSorter.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Value.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/EventSubscriber/TimestampableAttributeSubscriber.php
  src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeOptionNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/UpdateJobExecutionStorageSummarySubscriber.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/item-picker.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
  src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
  src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
  src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
  tests/back/Pim/Enrichment/Integration/PQB/Sorter/CompletenessSorterIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Sorter/Field/CompletenessSorterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueSpec.php
  tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/GetAttributeOptionEndToEnd.php
  tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
  tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
  tests/back/Pim/Structure/Specification/Bundle/Form/Type/AttributeOptionTypeSpec.php
  tests/legacy/features/pim/structure/family/mass_edit_families.feature
Labels: echoes/intent: maintenance

#19304 Pull up 6.0 into 7.0
  CHANGELOG-6.0.md
Labels: echoes/intent: maintenance
