Repository akeneo/pim-community-dev, pull requests merged in 2023-01, with the labels that each got.

#18740 GRF-493 : EC permissions refacto
  src/Akeneo/Category/back/Application/Converter/StandardFormatToUserIntents.php
  src/Akeneo/Category/back/Application/Filter/CategoryEditAclFilter.php
  src/Akeneo/Category/back/Application/Registry/FindCategoryAdditionalProperties.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverProcessor.php
  src/Akeneo/Category/back/Application/Storage/Save/CategorySaverRegistry.php
  src/Akeneo/Category/back/Application/Storage/Save/SaveCategory.php
  src/Akeneo/Category/back/Application/Storage/Save/Saver/CategorySaver.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/UserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/Domain/UserIntent/UserIntentFactoryRegistry.php
  src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UserGroupController.php
  src/Akeneo/Category/back/Infrastructure/Converter/InternalApi/InternalApiToStd.php
  src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/converters.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/registry.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/user_group.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/save.yml
  src/Akeneo/Category/back/ServiceApi/Handler/CategoryAdditionalPropertiesFinder.php
  src/Akeneo/Category/back/tests/Integration/Application/Converter/StandardFormatToUserIntentsIntegration.php
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/CategorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/LabelUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/UserIntentFactoryRegistrySpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Converter/InternalApi/InternalApiToStdSpec.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistrySpec.php
  src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx
  src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.test.ts
  src/Akeneo/Category/front/src/feature/helpers/permissionsHelper.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/hooks/useFetchUserGroups.ts
  src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/CategoryPermission.ts
Labels: griffins, echoes/intent: feature

#18715 GRF-642 give users with category ACLs the new enriched category ACLs
  src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/migration.yml
  src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigrationIntegration.php
Labels: echoes/intent: feature

#18766 GRF-633 Add position option in API export for categories
  src/Akeneo/Category/back/Application/Query/GetCategoriesParametersBuilder.php
  src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php
  src/Akeneo/Category/back/Infrastructure/Handler/GetPositionHandler.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesParametersBuilderSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodes.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesParametersBuilderSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodesIntegration.php
  src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Handler/GetPositionHandlerSpec.php
Labels: griffins, echoes/intent: feature

#18684 GRF-644: Template label is no longer generated automatically during template creation
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php
  src/Akeneo/Category/back/Domain/Model/Classification/CategoryTreeTemplate.php
  src/Akeneo/Category/back/Domain/ValueObject/Template/TemplateCode.php
  src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CreateTemplateController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreeByCategoryTemplateSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php
  src/Akeneo/Category/back/tests/Integration/Application/ActivateTemplateIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/templates/createTemplate.tsx
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
Labels: griffins

#18730 GRF-546: Label can be of Type JSX.Element to be able to add Tag
  front-packages/akeneo-design-system/src/components/IconCard/IconCard.tsx
  front-packages/shared/src/components/Navigation/SubNavigation.tsx
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
Labels: griffins, echoes/intent: feature

#18769 GRF-626: Add discover Enriched categories information helper
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.test.tsx
  src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
  src/Akeneo/Category/front/src/feature/components/index.ts
  src/Akeneo/Category/front/src/feature/pages/CategoriesIndex.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
Labels: griffins, echoes/intent: feature

#18717 CPM-863: Be able to reorder conditions
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/FamilyLine.tsx
Labels: echoes/intent: feature

#18668 CPM-857: Add placeholder when there are no conditions
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx
  components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
Labels: echoes/intent: feature

#18812 CPM-902: Fix findValidationTooltip breaking behat tests
  tests/legacy/features/Context/Page/Base/ProductEditForm.php
Labels: echoes/intent: maintenance

#18810 Enriched Category : Fix CI
  src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigrationIntegration.php
  tests/legacy/features/Context/Page/Base/ProductEditForm.php
Labels: griffins, echoes/intent: feature

#18806 CPM-888: Add Query to get options and labels by search
  components/identifier-generator/back/src/Infrastructure/Controller/GetAttributeOptionsController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAttributeOptionsControllerEndToEnd.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeOption/FindAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeOption/SqlFindAttributeOptions.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  tests/back/Pim/Structure/Integration/Query/InternalApi/AttributeOption/SqlFindAttributeOptionsIntegration.php
  tests/back/Pim/Structure/Integration/Query/InternalApi/Family/DefaultSqlGetRequiredAttributesMasksIntegration.php
Labels: echoes/intent: feature

#18825 Preparing version 7.0.0
  CHANGELOG-7.0.md
Labels: echoes/intent: technical

#18815 Grf 630 : Fix of non-synchronised header translations when changing the locale in select
  src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Labels: echoes/intent: feature

#18831 CPM-892: Validate Simple Select
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/SimpleSelect.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Infrastructure/Controller/GetAttributeOptionsController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldExist.php
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldExistValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveType.php
  components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveTypeValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/ScopeAndLocaleShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/ScopeAndLocaleShouldBeValidValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectOptionCodesShouldExist.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectOptionCodesShouldExistValidator.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectShouldBeValidValidator.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAttributeOptionsControllerEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/AttributeShouldExistValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/AttributeShouldHaveTypeValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/ScopeAndLocaleShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/SimpleSelectOptionCodesShouldExistValidatorSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/SimpleSelectShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/InMemory/InMemoryFindFamilyCodes.php
Labels: echoes/intent: feature

#18816 CPM-902: Fix findvalidationtooltip breaking behat tests
  tests/legacy/features/Context/Page/Base/ProductEditForm.php
Labels: echoes/intent: maintenance

#18819 Pull-up 6.0 to 7.0
  .circleci/jobs/build_and_deploy.yml
  CHANGELOG-6.0.md
  src/Akeneo/Channel/back/Infrastructure/Component/Query/PublicApi/FindActivatedCurrenciesInterface.php
  src/Akeneo/Channel/back/Infrastructure/Doctrine/Query/FindActivatedCurrencies.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness_mask_generators.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/Compiler/ContentTypeNegotiatorPass.php
  tests/back/Acceptance/Channel/InMemoryFindActivatedCurrencies.php
  tests/back/Acceptance/Resources/config/pim/queries.yml
  tests/back/Acceptance/spec/Channel/InMemoryFindActivatedCurrenciesSpec.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php
  tests/back/Pim/Enrichment/Integration/Storage/Sql/FindActivatedCurrenciesIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
  tests/legacy/features/Context/Page/Base/ProductEditForm.php
Labels: echoes/intent: technical

#18845 Fix compiler pass broken due to FOSRestBundle upgrade
  src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/Compiler/ContentTypeNegotiatorPass.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#18804 RAB-1239: CI workflow for 7.0
  .circleci/jobs/build_and_deploy.yml
  .circleci/workflows/editions/community.yml
  .circleci/workflows/pull_request.yml
  .circleci/workflows/squads/octopus/octopus_deploy_pull_request.yml
  .circleci/workflows/squads/octopus/octopus_weekly_code_quality.yml
Labels: echoes/intent: technical

#18808 GRF-652: Fix Image resolution and size when previewing uploaded image in Category Edit Form
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/file/preview/fullscreen-preview.tsx
  src/Akeneo/Category/front/src/feature/components/file/preview/media-preview.tsx
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18561 OCT-176: Product Mapping : on save, validate product mapping with product mapping schema requirements
  components/catalogs/back/.php_cd.php
  components/catalogs/back/src/Application/Handler/GetProductIdentifiersHandler.php
  components/catalogs/back/src/Domain/Catalog.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogErrorsAction.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/UpdateCatalogAction.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMapping.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductSelectionCriteria.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductSelectionCriteriaValidator.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductValueFilters.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductValueFiltersValidator.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php
  components/catalogs/back/src/Infrastructure/Validation/IsCatalogValid.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchema.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchema.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedCurrencyValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsValidChannelValidator.php
  components/catalogs/back/src/ServiceAPI/Command/UpdateProductMappingSchemaCommand.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributeActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogErrorsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/UpdateCatalogActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogProductMappingTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogProductSelectionCriteriaTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogProductValueFiltersTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/IsCatalogValidTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMappingSchemaValidatorTest.php
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/findFirstError.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.ts
  components/catalogs/front/src/components/CatalogEdit/utils/getTabsValidationStatus.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductMappingSourceErrors.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductSelectionCriteriaErrors.unit.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.ts
  components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.unit.ts
Labels: echoes/intent: technical

#18820 OCT-203: refactor ProductSchemaValidatorTest
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogProductMappingTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMappingSchemaValidatorTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.1-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.1-with-unsupported-type-number.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.2-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.2-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.2-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.2-with-unsupported-type-number.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.1.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.2.json
Labels: echoes/intent: technical

#18866 OCT-207: limit catalogs coverage to unit & inte, not perfs
  components/catalogs/Makefile
Labels: echoes/intent: technical

#18837 CPM 894 : Create Controller to get the available Conditions
  components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
  components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php
  src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetGroupedAttributes.php
Labels: echoes/intent: feature

#18854 PIM-10787: Do not run the remove completeness job when there is no need
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
Labels: echoes/intent: maintenance

#18792 CPM-898: Add validation on delimiter value
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts
  components/identifier-generator/front/src/feature/validators/__tests__/validateFreeText.test.ts
  components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
  components/identifier-generator/front/src/feature/validators/validateFreeText.ts
Labels: echoes/intent: feature

#18800 GRF-629 : Add channel translation for template attribute field creation
  src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextAreaFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/buildTextFieldAttribute.tsx
  src/Akeneo/Category/front/src/feature/components/attributes/index.ts
  src/Akeneo/Category/front/src/feature/components/attributes/types.ts
  src/Akeneo/Category/front/src/feature/helpers/channelHelper.test.ts
  src/Akeneo/Category/front/src/feature/helpers/channelHelper.ts
  src/Akeneo/Category/front/src/feature/helpers/index.ts
  src/Akeneo/Category/front/src/tests/provideChannelHelper.ts
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18856 CXP-1287: JSON Meta Schema V0.0.3
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.3.json
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.3-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.3-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.3-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.3-with-unsupported-type-array.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.3.json
Labels: echoes/intent: feature

#18872 RAB-1266: Introduce a new param for VersionProvider
  config/services/services.yml
  src/Akeneo/Platform/Bundle/PimVersionBundle/Resources/config/services.yml
Labels: echoes/intent: technical

#18857 CPM-916: Add migration for target
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
  components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php
  upgrades/schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators.php
  upgrades/test_schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators_Integration.php
Labels: echoes/intent: technical

#18880 GRF-672 backport feature branch
  front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-information-fit-content-height-correctly-1-snap.png
  front-packages/akeneo-design-system/src/components/Information/Information.stories.mdx
  front-packages/akeneo-design-system/src/components/Information/Information.tsx
Labels: griffins, griffins-risk-assessed

#18879 Fix version of ramsey/uuid
  .circleci/detect_structure_changes.sh
  .circleci/jobs/build_and_deploy.yml
  .circleci/workflows/pull_request.yml
  composer.json
  composer.lock
Labels: echoes/intent: maintenance, echoes/effort: XS

#18635 RAB-1124: Update monolog/monolog
  composer.json
  composer.lock
  src/Akeneo/Tool/Bundle/BatchBundle/Monolog/Handler/BatchLogHandler.php
  src/Akeneo/Tool/Component/Batch/Event/ErrorHandlerConfigurationListener.php
Labels: echoes/intent: technical

#18828 CPM-889: Add SimpleSelectOptionsSelector for Simple Select filter
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/SimpleSelectOptionsSelector.tsx
  components/identifier-generator/front/src/feature/components/__tests__/SimpleSelectOptionsSelector.test.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetSelectOptions.test.tsx
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts
  components/identifier-generator/front/src/feature/models/option.ts
Labels: echoes/intent: feature

#18867 GRF-339: Apply category permissions on children after saving
  src/Akeneo/Category/back/Api/Event/CategoryEditedEvent.php
  src/Akeneo/Category/back/Application/Query/GetCategoryChildrenIds.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryChildrenIdsSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryChildrenIdsSqlIntegration.php
Labels: griffins, echoes/intent: feature, griffins-risk-assessed

#18722 CXP-1357 : Disable Catalogs when Channels associated with mapping are…
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingChannelsInMappingQueryInterface.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnChannelRemovalTasklet.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsInMappingQuery.php
  components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnChannelRemovalTaskletTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsInMappingQueryTest.php
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
Labels: echoes/intent: feature

#18861 CPM-832: Create migration to initialize Identifier Generator ACLs
  upgrades/schema/Version_7_0_20230110161438_initialize_identifier_generator_acl.php
  upgrades/test_schema/Version_7_0_20230110161438_initialize_identifier_generator_acl_Integration.php
Labels: echoes/intent: feature

#18747 CXP-1356: GetProductMappedHandler : Catch exception from PQB like in GetProductsHandler
  components/catalogs/back/src/Application/Handler/GetMappedProductsHandler.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
Labels: echoes/intent: feature, echoes/intent: technical

#18905 RAB-1273: Refactor attribute group index
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/AttributeGroup.interface.ts
  src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
  src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
  src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/GetAttributeGroups.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute_group.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
Labels: echoes/intent: feature

#18713 CXP-1355: Disable Catalogs when Locales are removed
  components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQueryInterface.php
  components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTasklet.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQuery.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationConstraintTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTaskletTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQueryTest.php
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Labels: echoes/intent: feature

#18781 OCT-189 : Show message in parameters section of mapping configuration
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/FakePIM.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
Labels: echoes/intent: technical

#18753 OCT-200: updated error payload for consitency
  components/catalogs/back/src/Infrastructure/Controller/Public/GetMappedProductsAction.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php
Labels: echoes/intent: technical

#18752 OCT-199 Add catalog disable event on error for GetProduct endpoint
  .circleci/config/commands.yml
  components/catalogs/back/src/Application/Handler/GetProductHandler.php
  components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php
Labels: echoes/intent: technical

#18793 OCT-188 : AttributeMapping: Error is shown one more time after correction.
  components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogErrors.ts
Labels: echoes/intent: feature, echoes/intent: technical

#18914 CPM-895: Call backend for Add Condition Button
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/components/__tests__/SimpleSelectOptionsSelector.test.tsx
  components/identifier-generator/front/src/feature/hooks/__mocks__/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetConditionItems.test.tsx
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetFamilies.test.tsx
  components/identifier-generator/front/src/feature/hooks/index.ts
  components/identifier-generator/front/src/feature/hooks/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
  components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts
  components/identifier-generator/front/src/feature/tabs/conditions/AddConditionButton.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/AddConditionButton.test.tsx
  src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetGroupedAttributes.php
Labels: echoes/intent: feature

#18917 RAB-1254: Init mass action
  src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeRepository.php
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Datasource/AttributeDatasource.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
Labels: echoes/intent: feature

#18798 OCT-196 : Fix the width of catalog header to display the save button …
  src/Akeneo/Connectivity/Connection/front/src/common/components/PageHeader.tsx
Labels: echoes/intent: maintenance

#18915 Feature enriched categories merge master
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetProductCompletenesses.php
Labels: echoes/intent: maintenance

#18751 OCT-139: [CE] remove justinrainbow/json-schema in composer.json
  composer.json
  composer.lock
Labels: echoes/intent: technical

#18782 OCT-202: add placeholder on the source selector in mapping
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/components/SelectAttributeDropdown.tsx
Labels: echoes/intent: technical

#18744 RAB-1138: Do not display the additional storage in CE
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
Labels: echoes/intent: feature

#18892 CXP-1375: Refactor useInfiniteAttribute to useInfiniteSourceAttribute
  components/catalogs/back/src/Application/Exception/NoCompatibleAttributeTypeFoundException.php
  components/catalogs/back/src/Application/Service/TargetTypeConverter.php
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatAction.php
  components/catalogs/back/src/Infrastructure/Persistence/Attribute/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.4.json
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductMappingSchemaValidator.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Persistence/Attribute/SearchAttributesQueryTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-format-for-wrong-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-invalid-uuid-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-missing-target-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-missing-uuid.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-unsupported-format.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/invalid/0.0.4-with-unsupported-type.json
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.4.json
  components/catalogs/back/tests/Unit/Service/TargetTypeConverterTest.php
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/SelectSourceAttributeDropdown.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteSourceAttributes.ts
  components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteSourceAttributes.unit.ts
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeCriterionFactories.ts
  components/catalogs/front/src/components/ProductSelection/hooks/useInfiniteAttributeCriterionFactories.unit.ts
Labels: echoes/intent: feature

#18460 [wait until 15/12/22] CPM-817: Add subscriber to fill prefixes
  components/identifier-generator/back/src/API/Query/UpdateIdentifierPrefixesQuery.php
  components/identifier-generator/back/src/Domain/Model/ProductIdentifier.php
  components/identifier-generator/back/src/Infrastructure/Query/SqlUpdateIdentifierPrefixesQuery.php
  components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/cli_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml
  components/identifier-generator/back/src/Infrastructure/ZddMigrations/V20221205153905FillIdentifierPrefixesZddMigration.php
  components/identifier-generator/back/tests/.php_cd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Query/SqlUpdateIdentifierPrefixesQueryEndToEnd.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Integration/ZddMigrations/V20221205153905FillIdentifierPrefixesZddMigrationIntegration.php
  components/identifier-generator/back/tests/Specification/Domain/Model/ProductIdentifierSpec.php
  src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml
  tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductSaverSpec.php
Labels: echoes/intent: feature, echoes/intent: maintenance

#18898 PIM-10779: Lowercase on get attribute group code for dqi activation
  CHANGELOG.md
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
Labels: griffins, echoes/intent: maintenance, griffins-risk-assessed

#18840 PIM-10789: Do not return and show encrypted password
  CHANGELOG.md
  front-packages/shared/src/components/TextField.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypter.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/normalizers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/job/common/edit/storage-form.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizerSpec.php
Labels: echoes/intent: maintenance

#18770 PIM-10759: Tailored exports fail after the deletion of a category tree
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/RemoveCategoryFilterInJobInstanceSubscriber.php
Labels: contribution, echoes/intent: maintenance

#18692 RAB-785: Add possibility to check if we are in a context of initialization
  config/packages/akeneo_feature_flag.yml
  config/services/behat/services.yml
  config/services/test/test_services.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Application/DownloadFileFromStorage/DownloadFileFromStorageHandler.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Application/TransferFilesToStorage/TransferFilesToStorageHandler.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Hydrator/LocalStorageHydrator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/DownloadStep.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/Storage/None/NoneStorageValidator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/StorageValidator.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/handlers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
  src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
  tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
  tests/back/Integration/catalog/technical/jobs.yml
  tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/ValidateStorageTest.php
  tests/back/Platform/Acceptance/ImportExport/UseCases/DownloadFileFromLocalStorageTest.php
  tests/back/Platform/Acceptance/ImportExport/UseCases/DownloadFileFromManualStorageTest.php
  tests/back/Platform/Acceptance/ImportExport/UseCases/TransferFilesToLocalStorageTest.php
  tests/back/Platform/EndToEnd/ImportExport/InternalApi/GenerateZipArchiveEndToEnd.php
  tests/back/Platform/Integration/Analytics/Query/IsDemoCatalogIntegration.php
  tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
  tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php
  tests/legacy/features/Behat/Context/JobContext.php
  tests/legacy/features/Context/catalog/apparel/jobs.yml
  tests/legacy/features/Context/catalog/catalog_modeling/jobs.yml
  tests/legacy/features/Context/catalog/footwear/jobs.yml
Labels: echoes/intent: feature

#18745 OCT-198: fix GuzzleWebhookClient
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
Labels: echoes/intent: maintenance

#18842 RAB-1253: Add attribute mass delete (front + dummy job)
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/job_constraints.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/job_defaults.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
  src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Pim/Structure/Component/Attribute/Job/DeleteAttributesTasklet.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
  src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
  src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
  src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  src/Oro/Bundle/PimDataGridBundle/Adapter/ItemsCounter.php
  src/Oro/Bundle/PimDataGridBundle/Adapter/OroToPimGridFilterAdapter.php
  src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
  src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/attribute-mass-delete-action.js
Labels: echoes/intent: feature

#18834 GRF-674: Add filter on empty value when export categories
  src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php
  src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
Labels: griffins, griffins-risk-assessed

#18910 GRF-682 : Connect front to service to get child categories count
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Event/CategoryCreatedEvent.php
  src/Akeneo/Category/back/Domain/Event/CategoryEditedEvent.php
  src/Akeneo/Category/back/Domain/Event/CategoryUpdatedEvent.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category.yml
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/DeleteCategoryModal.tsx
  src/Akeneo/Category/front/src/feature/components/tree/CategoryTree.tsx
  src/Akeneo/Category/front/src/feature/components/tree/Node.tsx
  src/Akeneo/Category/front/src/feature/helpers/treeHelper.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useCountCategoryChildren.ts
  src/Akeneo/Category/front/src/feature/hooks/useDeleteCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useDragTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/hooks/useDropTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/Tree.ts
  src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/tests/provideTreeNodeHelper.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#18777 GRF-637: Move Free Trial adblocker detection into CE
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/css/adblocker.css
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/img/akeneo-ico-free-trial.png
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/img/icon_close.svg
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/free-trial-ad-banner-fake.js
  src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/views/adblocker.html.twig
  src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
Labels: griffins, echoes/intent: feature, echoes/intent: technical, griffins-risk-assessed

#18912 PIM-10791: Fix product and product model completeness compute on fami…
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
Labels: echoes/intent: maintenance

#18903 GRF-643 clean category data after channel deletion
  src/Akeneo/Category/back/Application/Enrichment/CleanCategoryDataLinkedToChannel.php
  src/Akeneo/Category/back/Application/Query/GetEnrichedCategoryValuesOrderedByCategoryCode.php
  src/Akeneo/Category/back/Application/Storage/UpdateCategoryEnrichedValues.php
  src/Akeneo/Category/back/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelDeletionSubscriber.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetEnrichedCategoryValuesOrderedByCategoryCodeSql.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/Update/UpdateCategoryEnrichedValuesSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/cleaners.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
  src/Akeneo/Category/back/tests/Integration/Application/Enrichment/CleanCategoryDataLinkedToChannelIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetEnrichedCategoryValuesOrderedByCategoryCodeSqlIntegration.php
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/Update/UpdateCategoryEnrichedValuesSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Infrastructure/EventSubscriber/CleanCategoryDataAfterChannelDeletionSubscriberSpec.php
Labels: echoes/intent: feature

#18933 GRF-676: Category Tree linked to 100+ products notification changed from INFO to ERROR
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
Labels: griffins, griffins-risk-assessed

#18700 PIM-10768: Fix update list status_code response
  CHANGELOG.md
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
Labels: echoes/intent: maintenance

#18765 PIM-10784: Fix API error 500 when filtering for identifier with null …
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimit.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimitSpec.php
Labels: echoes/intent: maintenance

#18776 PIM-10785: Fix case-insensitive patch product model
  CHANGELOG.md
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
Labels: echoes/intent: maintenance

#18956 CPM-900 + CPM-919 + CPM-903 + CPM-872 + CPM-906 = CPM-4500
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
  components/identifier-generator/front/src/feature/components/Styled.tsx
  components/identifier-generator/front/src/feature/tabs/structure/DelimiterEdit.tsx
  components/identifier-generator/front/src/feature/tabs/structure/line/FreeTextLine.tsx
  components/identifier-generator/front/src/feature/tabs/structure/preview/AutoNumberPreview.tsx
Labels: echoes/intent: feature

#18876 CPM-917: Fix product indexation command with "--diff" option
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysql.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysqlIntegration.php
Labels: echoes/intent: maintenance

#18918 PIM-10794: Fix error message on search attributes for product and pro…
  CHANGELOG-6.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
  src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
Labels: echoes/intent: maintenance

#18937 CPM-907 : Allow create/update with Family Generation
  components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
  components/identifier-generator/back/src/Domain/Model/Property/FamilyProperty.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Model/Property/Process.php
  components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyPropertyShouldBeValid.php
  components/identifier-generator/back/src/Infrastructure/Validation/FamilyPropertyShouldBeValidValidator.php
  components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FamilyPropertySpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/ProcessSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyPropertyShouldBeValidValidatorSpec.php
  components/identifier-generator/back/tests/features/createIdentifierGenerator.feature
  components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#18868 Grf 677 : Add warning before category deletion
  src/Akeneo/Category/back/Application/Query/GetCategoryChildrenIds.php
  src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
  src/Akeneo/Category/back/Domain/Event/CategoryCreatedEvent.php
  src/Akeneo/Category/back/Domain/Event/CategoryEditedEvent.php
  src/Akeneo/Category/back/Domain/Event/CategoryUpdatedEvent.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CategoryController.php
  src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php
  src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryChildrenIdsSql.php
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
  src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category.yml
  src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryChildrenIdsSqlIntegration.php
  src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
  src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
  src/Akeneo/Category/front/src/feature/components/datagrids/DeleteCategoryModal.tsx
  src/Akeneo/Category/front/src/feature/components/tree/CategoryTree.tsx
  src/Akeneo/Category/front/src/feature/components/tree/Node.tsx
  src/Akeneo/Category/front/src/feature/helpers/treeHelper.test.ts
  src/Akeneo/Category/front/src/feature/hooks/useCountCategoryChildren.ts
  src/Akeneo/Category/front/src/feature/hooks/useDeleteCategory.ts
  src/Akeneo/Category/front/src/feature/hooks/useDragTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/hooks/useDropTreeNode.test.tsx
  src/Akeneo/Category/front/src/feature/models/Category.ts
  src/Akeneo/Category/front/src/feature/models/Tree.ts
  src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
  src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
  src/Akeneo/Category/front/src/tests/provideTreeNodeHelper.ts
  src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Labels: echoes/intent: feature

#18823 CPM-874: Fix case where table column code is an int
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetTableValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetTableValueSpec.php
Labels: echoes/intent: feature

#18955 CPM-908: Add handler to generate family codes
  components/identifier-generator/back/src/Application/Exception/UnableToTruncateException.php
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierCommand.php
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GenerateAutoNumberHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GenerateFamilyHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GenerateFreeTextHandler.php
  components/identifier-generator/back/src/Application/Generate/Property/GeneratePropertyHandlerInterface.php
  components/identifier-generator/back/src/Domain/Model/Property/Process.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateAutoNumberHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFamilyHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFreeTextHandlerSpec.php
Labels: echoes/intent: feature

#18992 Feature enriched categories merge master
  CHANGELOG.md
  front-packages/shared/src/components/TextField.tsx
  src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
  src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/RemoveCategoryFilterInJobInstanceSubscriber.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
  src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysql.php
  src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimit.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
  src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetTableValue.php
  src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetTableValueSpec.php
  src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypter.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizer.php
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/normalizers.yml
  src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/job/common/edit/storage-form.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
  src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
  src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
  src/Akeneo/Tool/Bundle/BatchBundle/Remover/JobInstanceRemover.php
  src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
  src/Akeneo/Tool/Bundle/BatchBundle/spec/Remover/JobInstanceRemoverSpec.php
  tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysqlIntegration.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimitSpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
  tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizerSpec.php
Labels: echoes/intent: feature, echoes/intent: maintenance

#18993 CPM-915: Add text transformation
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/front/src/feature/components/LocaleSelector.tsx
  components/identifier-generator/front/src/feature/components/ScopeSelector.tsx
  components/identifier-generator/front/src/feature/components/TextTransformationSelector.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useGetIdentifierGenerators.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetSelectOptions.test.tsx
  components/identifier-generator/front/src/feature/hooks/useCreateIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/hooks/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/models/identifierGenerator.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/text-transformation.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/FamilyLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/GeneralPropertiesTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleSelectLine.test.tsx
  components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts
Labels: echoes/intent: feature

#18981 CPM-914: Upper and lower cases
  components/identifier-generator/back/src/Application/Generate/GenerateIdentifierHandler.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php
  components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php
  components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php
  components/identifier-generator/front/src/feature/components/LocaleSelector.tsx
  components/identifier-generator/front/src/feature/components/ScopeSelector.tsx
  components/identifier-generator/front/src/feature/components/TextTransformationSelector.tsx
  components/identifier-generator/front/src/feature/components/index.ts
  components/identifier-generator/front/src/feature/hooks/__mocks__/useGetIdentifierGenerators.ts
  components/identifier-generator/front/src/feature/hooks/__tests__/useGetSelectOptions.test.tsx
  components/identifier-generator/front/src/feature/hooks/useCreateIdentifierGenerator.ts
  components/identifier-generator/front/src/feature/hooks/useGetConditionItems.ts
  components/identifier-generator/front/src/feature/models/identifierGenerator.ts
  components/identifier-generator/front/src/feature/models/index.ts
  components/identifier-generator/front/src/feature/models/text-transformation.ts
  components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__mocks__/CreateGeneratorModal.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
  components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
  components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/FamilyLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/__tests__/GeneralPropertiesTab.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx
  components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleSelectLine.test.tsx
  components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts
Labels: echoes/intent: feature

#19001 CPM-935: Merge migrations
  components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
  upgrades/schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators.php
  upgrades/schema/Version_8_0_20230126094541_add_options_for_identifier_generator.php
  upgrades/test_schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators_Integration.php
  upgrades/test_schema/Version_8_0_20230126094541_add_options_for_identifier_generator_Integration.php
Labels: echoes/intent: feature

#18795 CPM-866: update wording
  components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/identifier-generator/front/src/feature/pages/ListPage.tsx
Labels: echoes/intent: feature, echoes/intent: maintenance

#18974 CXP-1408: Adds feature flag to Catalogs [7.0]
  .circleci/jobs/install_front_dependencies.yml
  components/catalogs/back/.php_cd.php
  components/catalogs/back/rector.php
  components/catalogs/back/src/Application/Persistence/Channel/GetChannelQueryInterface.php
  components/catalogs/back/src/Infrastructure/Persistence/Attribute/SearchAttributesQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsWithFilteredValuesQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Channel/GetChannelsByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Channel/GetChannelsQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Family/GetFamiliesByCodeQuery.php
  components/catalogs/back/src/Infrastructure/Persistence/Family/SearchFamilyQuery.php
  components/catalogs/back/src/Infrastructure/Security/CatalogScopeMapper.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing.yml
  components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
  components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidMeasurementValidator.php
  components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionContainsScopeAndLocaleValidator.php
  components/catalogs/back/tests/Acceptance/AuthenticationContext.php
  components/catalogs/back/tests/Integration/Fakes/TimestampableSubscriber.php
  components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateProductMappingSchemaActionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AbstractAttributeSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/SystemSource/UuidSourceTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/AbstractSystemCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/CompletenessCriterionTest.php
  components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/SystemCriterion/EnabledCriterionTest.php
  components/catalogs/back/tests/Integration/IntegrationTestCase.php
  components/catalogs/back/tests/Unit/Infrastructure/Security/CatalogScopeMapperTest.php
  config/packages/akeneo_feature_flag.yml
Labels: echoes/intent: feature

#18950 CXP-1387: add requirements section
  components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
  components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
  components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
  components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx
  components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
  components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
  components/catalogs/front/src/components/ProductMapping/models/ProductMappingSchema.d.ts
  components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
Labels: echoes/intent: feature

#18968 CPM-909: Add implicit conditions
  components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
  components/identifier-generator/back/src/Domain/Model/Condition/EmptyIdentifier.php
  components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
  components/identifier-generator/back/src/Domain/Model/ProductProjection.php
  components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
  components/identifier-generator/back/src/Domain/Model/Property/FamilyProperty.php
  components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
  components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
  components/identifier-generator/back/src/Domain/Model/Structure.php
  components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
  components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateAutoNumberHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFamilyHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFreeTextHandlerSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EmptyIdentifierSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EnabledSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/FamilySpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Condition/SimpleSelectSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/Property/FamilyPropertySpec.php
  components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
  components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
Labels: echoes/intent: feature
