Repository akeneo/pim-community-dev, pull requests merged in 2024-03, with the labels that each got.

#20400 PIM-11388: Backport PIM-10832 into 7.0
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/.php_cd.php
  src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
  src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeCompletenessOfProductsFamilyTasklet.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
Labels: echoes/intent: maintenance, echoes/effort: M

#20409 PIM-11405: Fix permission on created files on local storage
  CHANGELOG-7.0.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/Local/LocalStorageClientProvider.php
Labels: echoes/intent: feature, echoes/intent: maintenance, echoes/intent: technical

#20411 PIM-11407 [backport] Fix Family sorting on product grid
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/FamilySorter.php
  tests/back/Pim/Enrichment/Integration/PQB/Sorter/FamilySorterIntegration.php
  tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Sorter/Field/FamilySorterSpec.php
Labels: echoes/intent: maintenance

#20417 PIM-11405: Permissions should be 655 and 755
  CHANGELOG-7.0.md
  src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/Local/LocalStorageClientProvider.php
Labels: echoes/intent: maintenance, echoes/effort: XS

#20418 [backport PIM-11406] PIM-11418: Fix API Product Model endpoint when trying to update family with wrong case
  CHANGELOG-7.0.md
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ExternalApi/ProductModelUpdater.php
  src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
  tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ExternalApi/ProductModelUpdaterSpec.php
  tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductModelUpdaterSpec.php
Labels: echoes/intent: maintenance, echoes/effort: S
